### ISSUE TITLE
Question: Restify client, ECONNRESET and agent

### ISSUE THREAD

**Issue by ygrenzinger** [restify/node-restify#1001]
Hello,

This is not an "issue" because there is a clear solution but I want to discuss it with you because maybe it's an information to improve Restify.

I use JsonClient to request a webservice. However with agent = true the webservices kill the connection abruptly after some timeout.

It sends this error:

> Error: read ECONNRESET
>     at exports._errnoException (util.js:874:11)
>     at TCP.onread (net.js:544:26)

Which bubbles up to node process and the only way to "catch" it is to put a 
process.on('error', function(err) { ... });

The myClient.on('error' ...) does nothing but it seems normal because if I have understood correctly the restify code this sort of errors should be returned by the callback.

The only "clean" solution so far is to set agent = false for the client.

Is it really working as intended or am i missing something ?

PS: I have tried to use glitter but it seems there is not enough people to answer :(

**Comment by DonutEspresso** [comment]
Thanks for the report! I don't have a good answer for you, so I'll have to go do some digging and get back to you. If I had to guess, it sounds like the underlying system is throwing an error, so the whole thing comes crashing down.

**Comment by serv** [comment]
@ygrenzinger, which node version and restify are you using currently? 
We have the same problem with our app that uses node 0.10.21 and restify 2.8.5.

**Comment by ygrenzinger** [comment]
Node 4.x and restify 4.x

**Comment by 72apps** [comment]
Same issue here.  Node 5.x and Restify 4.x.

**Comment by sleetish** [comment]
Found this on: https://github.com/restify/node-restify/issues/485
#######BEGIN######
gfpacheco commented on Jan 30, 2014
I solved it:
By default NodeJS uses agents to keep the TCP connection open, so you can reuse it.
The problem is that if the server is closed, or it closes your connection for whatever reason you get the ECONNRESET error.

To close the connection every time you just need to set agent: false in your client creation:

var client = restify.createJsonClient({
    url: "http://localhost:5653",
    version: '*',
    agent: false
});
It worked for me, I hope it helps you too.
#######END#######

Hope this helps others.

Also, gfpacheco, wherever you are... you rock.

**Comment by retrohacker** [comment]
Hey all,

It would be helpful to the community if we could get (as small and concise as possible) repro case, ideally all within the same node.js process, that replicates this problem. As it stands, a passerby wanting to jump into this would have to invest a non-negligible amount of time attempting to create the problem with fresh code before they could begin working on a solution.

Once we get a clear rerpo case, I'll run it and remove the `Unconfirmed` tag, replacing it with `Help Wanted` :heart:

**Comment by retrohacker** [comment]
Closing this issue as stale for now. Happy to re-open it if we can get a repro case :smile:

**Comment by ygrenzinger** [comment]
No problem. Actually I don't think I could reproduce it.
