### ISSUE TITLE
Need audit logger to ignore certain route

### ISSUE THREAD

**Issue by leitsubomi** [restify/node-restify#1002]
This is an use case for health check route. We don't want this to keep pumping into log.  Need a configuration to ignore certain route

**Comment by micahr** [comment]
Do you mind moving this issue to the [plugins](https://github.com/restify/plugins/issues) repo?

**Comment by maxnachlinger** [comment]
Here's how I solved that issue, hope it helps: https://github.com/maxnachlinger/restify4-utils/blob/master/lib/bunyanAuditLogger.js#L90

**Comment by retrohacker** [comment]
Hey @leitsubomi,

This can be solved by specifying your own [bunyan serializers](https://github.com/trentm/node-bunyan#serializers). I hope this helps! If not, we can re-open and discuss some more :heart:
