### ISSUE TITLE
Release 4.0.4

### ISSUE THREAD

**Issue by behcet-li** [restify/node-restify#1005]
Currently with latest 4.0.3 release (latest on npm), restify enters a hanging state in several conditions related to content negation and formatters but those issues were addressed in PR's 9a2721f0bf0f2fc6c2fdef6f9eb8895d78aabd3e 75f9a6913b0b8402f663c371f3ad304f6f21d271 etc, but nothing was released since those were merged. There are a couple outstanding fixes in 4.x branch. 

Can you please release 4.0.4 with the latest PR's ?

Thanks.

**Comment by DonutEspresso** [comment]
Sure, we can probably do that. @micahr @yunong any objections? I suspect this might be the last 4.x release we do unless any breaking issues come up.

**Comment by yunong** [comment]
Seems like a sane thing to do.

**Comment by micahr** [comment]
:+1:

**Comment by DonutEspresso** [comment]
4.0.4 released.
