### ISSUE TITLE
getLogger - Does it exist?

### ISSUE THREAD

**Issue by AlecTaylor** [restify/node-restify#1011]
I `grep`d this repo, but could only find it in `docs/index.restdown`.

Would like to use it, but am getting this error:
> req.getLogger is not a function

Posted here also: http://stackoverflow.com/questions/35333233/restify-req-getlogger-is-not-a-function

**Comment by lukealbao** [comment]
You're right, it was removed in 097cad0. That answer from HeadCode is the way to do it. Submitting a PR now...
