### ISSUE TITLE
Documentation: Mounting and unmounting routes dynamically and repercussions of each.

### ISSUE THREAD

**Issue by lgomez** [restify/node-restify#1014]
Hi,

This is not a bug report but a request for documentation (I'm happy to add the docs PR once I understand this better).

Like some before me, I'm trying to dynamically mount and unmount route handlers. I've gone through the code but I'm confused about what each action touches on. 

Some context...
* Here https://github.com/restify/node-restify/blob/5.x/lib/server.js#L424 I see how the http methods (get, put, del, etc) are registered with the server where the handler takes the route options explicitly.
* Stepping into that here https://github.com/restify/node-restify/blob/5.x/lib/server.js#L501 I see how the remaining arguments to the route handler are added to the chain.
* In router.mount here: https://github.com/restify/node-restify/blob/5.x/lib/router.js#L242 I see how a route is mounted onto the router.
* We can also see how a route can be removed here: https://github.com/restify/node-restify/blob/5.x/lib/server.js#L591which itself calls on router.mount here: https://github.com/restify/node-restify/blob/5.x/lib/router.js#L320

Where I'm getting lost is within those methods and I'm failing to understand the following:

1. Where are the connections between route name and handler stored?
2. Why do I see a handful of `null` members in server.chain when I log it out?
3. When unmounting a route through server.rm, is the registered handler function (or the chain of functions?) also removed completely (I'm concerned about memory leaks/footprint when doing a large number of dynamic un/mounts)?
4. Would I be correct in assuming I'm better off passing an explicit name to my dynamically added routes to ensure I can track them for possible subsequent removal?

Thank you!

**Comment by micahr** [comment]
I'll try to answer your questions to help point you in the right direction:

1. Route name is used for looking up the set of handlers that are used when running through the route. Put another way, the route name is the key for the chain of functions that are executed for each route.
2. Likely the nulls are coming from the fact that the handlers don't have function names (they are anonymous functions)
3. Yes, all references to the handler functions of a specific route are removed when the route is `rm`ed. If another handler is still referring to the same function, then it won't be garbage collected.
4. Yes, naming a route is better for referencing it. However, if there is a name collision, a randomly generated one is created and will be used, so be sure to name them uniquely. 

Hope that helps!

**Comment by lgomez** [comment]
@micahr Thank you. That is very helpful.

The only handlers I have defined are a few of the included plugins and a few `.pre`s. Perhaps the `.pre` calls are injecting those null values in my chain. I'll look into that a bit more.

My dynamic route handler functions do come from a source that is already enforcing unique names so it should be fine. Thank you.
