### ISSUE TITLE
What's the correct way of making a content type synonymous with other

### ISSUE THREAD

**Issue by McOmghall** [restify/node-restify#1015]
I'm receiving at my server `Accept: application/hal+json` requests that are responded with an `HTTP 406` status code by default. I believe this should not be the case as `application/hal+json` resources are valid `application/json` resources as well. How should I configure restify to handle these requests like if they were `json` only but responding with the correct `content-type`?

**Comment by DonutEspresso** [comment]
Are you using the `acceptParser()` plugin? If so, you'll want to add a formatter for `application/hal+json` type, otherwise restify will reject requests for any missing formatters:

```js
var server = restify.createServer({
  formatters: {
    'application/hal+json': restify.formatters['application/json; q=0.4']
  }
});
```

The default q value should be 0.4 for JSON. You can log restify.formatters to get a list of the built in formatters.

**Comment by McOmghall** [comment]
That's great, thank you.

**Comment by AndrewAskins** [comment]
Hey, is there a way to extend this functionality to the bodyParser as well? I'm using content-type 'application/vnd.api+json' which is valid json, and I have my formatters defined, but restify is still defaulting to application/octet-stream for my request body. And I'd really prefer not to have to write my own parser for valid json.

**Comment by DonutEspresso** [comment]
Hi @AndrewAskins, unfortunately that isn't supported at the moment. If you'd like, please file an issue over at the restify-plugins repo and we can prioritize the work. Thank you!
