### ISSUE TITLE
Support for multiple response header values broken

### ISSUE THREAD

**Issue by BryanDonovan** [restify/node-restify#1017]
While debugging some other issues I noticed this: https://github.com/restify/node-restify/pull/702, and tried it out, but it doesn't really work (it only works for the `link` headers apparently).  I'm not really sure when someone would want to do this intentionally, but this:

``` javascript
 res.header('content-type', 'text/plain');
 res.header('content-type', 'application/json');
```

... throws an error:

```
TypeError: type.split is not a function
```

This is because line 128 in response.js (https://github.com/restify/node-restify/blob/5.x/lib/response.js#L128) uses `'-1'` (a string) instead of `-1` (a number), which means any string or array will pass that `else if` check:

``` javascript
    } else if (type.indexOf(';') !== '-1') {
        type = type.split(';')[0];
    }
```

So when `type` is an array, such as when two content-type headers have been added, it tries to call `split` on the array, which is not a function.

Changing the check to `-1` fixes that issue, but then other things begin to fail.  Here's a failing unit test for server.test.js:

``` javascript
test('sending multiple response content-type header values', function (t) {
    SERVER.get('/', function (req, res, next) {
        res.header('content-type', 'application/json');
        res.header('content-type', '*/*');
        res.send(200, 'root');
    });

    CLIENT.get('/', function (err, _, res) {
        t.equal(res.statusCode, 200);
        t.equal(res.headers['content-type'].split(',').length, 2);
        t.end();
    });
});
```

**Comment by DonutEspresso** [comment]
Thanks for the report! This is something we fixed in #986 for the upcoming 5.x release, but it hasn't yet been published. There's a subset of headers which don't allow for multiple values, and content-type was one of them.

**Comment by BryanDonovan** [comment]
Cool, thanks for the update!

**Comment by retrohacker** [comment]
Thanks for your patience while we worked on shipping 5.x!

This should be resolved now. If not, feel free to comment on this issue and we will re-open it :heart:
