### ISSUE TITLE
Simple authentication example?

### ISSUE THREAD

**Issue by panosru** [restify/node-restify#102]
Hello, could you provide a simple authentication example?

For instance I have set the server like this:

``` js
// Create server instance
var server = module.exports = restify.createServer({
    name : 'test-api'
  , version : '0.0.1-dev'
});

// Middlewares
server.use(restify.acceptParser(server.acceptable));
server.use(restify.authorizationParser());
server.use(restify.dateParser());
server.use(restify.queryParser({ mapParams : false }));
server.use(restify.urlEncodedBodyParser());
server.use(restify.bodyParser({ mapParams : false }));
server.use(restify.throttle({
    burst : 100
  , rate : 50
  , ip : true
  , overrides : {

    }
}));
```

and client like this:

``` js
var client = restify.createJsonClient({
    url: 'http://localhost:3003'
  , versions : '0.0.1-dev'
});
client.basicAuth('panosru', '123123');
```

Then on server I can get my username with `req.username`, and I can see that in `req.authorization` I have those info:

``` js
authorization: 
   { scheme: 'Basic',
     credentials: 'cGFub3NydToxMjMxMjM=',
     basic: { username: 'panosru', password: '123123' } }
```

but how I should apply the authentication mechanism?

Thanks in advance! :)

**Comment by mike-aungsan** [comment]
Can anyone show me example how to use passport with restify? I don't have any error but I don't see cookie is set by passport.

**Comment by tapmodo** [comment]
I wanted to make a "basic auth" middleware to password-protect some static content. The above documentation got me part way there, but it didn't work from a browser, which needs a certain header to request authentication from a user. Since restify errors do not respect headers set with `res.header()` I had to manually send the 401 error, and importantly I had to call `next()` with a value of `false`.

Here's the working middleware I came up with:

```javascript
var basicAuth = function(req, res, next){                                       
  res.header('WWW-Authenticate','Basic realm="API Docs"');            
                                                                                
  if (                                                                          
    !req.authorization ||                                                       
    !req.authorization.basic ||                                                 
    !req.authorization.basic.password                                           
  ){                                                                            
    res.send(401);                                                              
    return next(false);                                                         
  }                                                                             
                                                                                
  checkUserPassword(req.authorization.basic.password, function(err,data){        
    if (err || !data){                                                          
      res.send(401);                                                            
      return next(false);                                                       
    }                                                                           
    else return next();                                                         
  });                                                                           
};
```

Then, to use this middleware, it can be inserted on a specific route:

    server.get('/docs/', basicAuth, routes.displayDocumentation);

Or it can be "used" ahead of all routes that need basic authentication:

    server.use(basicAuth);

Your milage may vary, but hopefully this is helpful to someone. The simplified middleware code doesn't provide the `checkUserPassword()` function, doesn't check the username at all, and isn't concerned with specific error-handling. Adjust to taste.

**Comment by micahr** [comment]
Thank you for the example @tapmodo. The need for `next(false)` makes sense, as that is used as a [signal](https://github.com/restify/node-restify/blob/5.x/lib/server.js#L886-L888) to the server that the response is done being processed.

Can you clarify what you mean by:

> restify errors do not respect headers

Were you not able to send the `WWW-Authenticate` header to the client as part of the 401 response? If so, then we should look into that to make sure that it is sent. Could you also try: `res.setHeader` and see if that has a similar result?

**Comment by tapmodo** [comment]
To clarify, it appears that this code:
```
res.header('WWW-Authenticate','Basic realm="API Docs"');
return next(new restify.NotAuthorizedError());
```
...does not pass the header. That's not a big problem, but I did need to work around it.

**Comment by micahr** [comment]
It's definitely a surprise when it isn't sent. I'm wondering if using [`res.setHeader`](https://nodejs.org/api/http.html#http_response_setheader_name_value) directly will behave any differently.

**Comment by lgomez** [comment]
Just added this: https://github.com/restify/node-restify/issues/1099. Thought it could help someone. Cheers.

**Comment by anubhavsrivastava** [comment]
Can anyone please explain what is realm here and what are standard values? is it custom to application?
