### ISSUE TITLE
restify.CORS violates JavaScript naming conventions

### ISSUE THREAD

**Issue by EvgenyOrekhov** [restify/node-restify#1021]
restify.CORS is not a constructor, so its name should not start with an uppercase letter.
I suggest renaming restify.CORS to restify.cors.

**Comment by EvgenyOrekhov** [comment]
Here is a restify.CORS usage example from restify API guide that produces a warning in ESLint:
![restify.CORS ESLint warning](https://cloud.githubusercontent.com/assets/8045060/13349926/cfd81f50-dc8d-11e5-883e-3bd12a6856cf.png)

**Comment by DonutEspresso** [comment]
Thanks for the report! This is being addressed by a CORS refactor [over here](https://github.com/restify/plugins/pull/10).

**Comment by retrohacker** [comment]
Hey @EvgenyOrekhov! The cors module has found a new home and now includes the PR @DonutEspresso was referring to :heart:

https://github.com/TabDigital/restify-cors-middleware/
