### ISSUE TITLE
Make it more clear in docs that an event name is emitted sans 'Error' postfix

### ISSUE THREAD

**Issue by paulwalker** [restify/node-restify#1023]

**Comment by pkyeck** [comment]
(how) can I circumvent this behavior?
because right now I have things like

```javascript
    MyCustomValidation // minus the Error postfix
```

but still built-in things like

```javascript
    NotFoundError
```

**Comment by pkyeck** [comment]
ah sorry, just realized that this was because I was using a mix of `restify.errors` and `restify-errors`.

**Comment by DonutEspresso** [comment]
We're going to release 5.x soon - this should normalize the behavior and return you error names sans 'Error' postfix everywhere.

**Comment by retrohacker** [comment]
Hey @paulwalker and @pkyeck, this appears to be resolved in the 5.x branch :smile:

I'm closing this as resolved for now, but if I'm missing a nuance please comment and I'd be happy to re-open and discuss!
