### ISSUE TITLE
Add option to disable restify's uncaughtException handler

### ISSUE THREAD

**Issue by twhiteman** [restify/node-restify#1024]
I would like to be able to disable (turn off) restify's handling for uncaught exceptions.

This is so the node server when used with --abort-on-uncaught-exception will core dump (as currently restify will handle the exception, report and error to that request and then continue on processing).

**Comment by micahr** [comment]
That's a great idea, Todd. Do you mind creating a PR with a test or two?

**Comment by twhiteman** [comment]
Right (forgot to mention that), yes, I will be working on the PR for this.

**Comment by yunong** [comment]
@twhiteman Thanks for doing this. I would prefer that the default behavior is to disable domains, and make it opt-in, instead of opt out.

**Comment by twhiteman** [comment]
The patch is complete, added a test - any thoughts for this, thanks.
https://github.com/restify/node-restify/pull/1028

**Comment by yunong** [comment]
@twhiteman looks like style checks are failing. Would you mind fixing?
