### ISSUE TITLE
`server.url` is wrong

### ISSUE THREAD

**Issue by serv** [restify/node-restify#1029]
`server.url` is giving back a bad value right now.

To repro,

1. Try running https://github.com/restify/node-restify/blob/01ec72d9eb30ba07067c58c97f414885a7702cac/examples/jsonp/jsonp.js in your machine.
2. See the server log write:
`ready on http://[::]:8080`

Possible cause

I think there's something wrong with node 4.x's http module's `address()` function.
https://github.com/restify/node-restify/blob/v4.0.4/lib/server.js#L343
This is returning `{ port: 1337, family: 'IPv6', address: '::' }`.

My test environment 
- node 4.2.4
- restify 4.0.4

**Comment by micahr** [comment]
If you are using IPv6 then the equivalent to `localhost` or `127.0.0.1` is `::`. I think that should be correct. You can try disabling IPv6 on your machine and see if it changes, but that shorthand is valid.

**Comment by micahr** [comment]
@serv did my comment resolve your issue?

**Comment by serv** [comment]
@micahr Yes. Your explanation makes sense.

**Comment by McGern** [comment]
Hi,

Sorry to reopen an old ticket, but I am having the same issue, but on the production server (azure) server.url is returning http://undefined:undefined.

req.headers.host is returning the correct url, but I don't know how to get a request with hooking into "use" or something else like that.

Thanks,
Jarrod

**Comment by DonutEspresso** [comment]
Hi @McGern, can you open a new ticket? I believe the original issue here is different from what you are experiencing.

**Comment by markau** [comment]
The answer to @McGern's issue seems to be to explicity set a PORT value in Application Settings. Then you should see a similar message to what you see locally: `restify listening to http://[::]:3978` instead of `restify listening to http://undefined:undefined`. I'm guessing this is an issue with Azure node config not picking up the port environment variable?
