### ISSUE TITLE
Error when run with --'use-strict' mode

### ISSUE THREAD

**Issue by takaaptech** [restify/node-restify#1030]
Hi, I am running restify example in node version 5.0.0 and with --use-strict flag. How can i fix this error?
Thank so much!

macbooks-MacBook-Pro-2:restify macbook$ node --'use-strict' main.js 
/Users/macbook/nodejs/restify/node_modules/assert-plus/assert.js:41
                stackFunc = stackFunc || _assert.caller;
                                                ^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at _assert (/Users/macbook/nodejs/restify/node_modules/assert-plus/assert.js:41:49)

**Comment by micahr** [comment]
This looks like a problem with the assert-plus module. Do you mind filing an [issue](https://github.com/mcavage/node-assert-plus/issues) with them?

**Comment by takaaptech** [comment]
OK, https://github.com/mcavage/node-assert-plus/issues/23

**Comment by micahr** [comment]
Thanks. I'll close this issue.

**Comment by plurry** [comment]
It's fixed in the current version of `assert-plus` but Restify is still using an older version.

**Comment by DonutEspresso** [comment]
Looks like 5.x has been updated, but 4.x is on an older version. We can rev it and release a new version.

**Comment by plurry** [comment]
4.x uses `arguments.callee` itself in a couple places. This is also fixed in 5.x.

**Comment by retrohacker** [comment]
Closing this as fixed in 5.x+

**Comment by retrohacker** [comment]
If this is not the case, please comment on this issue and we can re-open :heart:
