### ISSUE TITLE
cross  domain

### ISSUE THREAD

**Issue by Suhsmitha19** [restify/node-restify#1033]
How to make a cross domain call in get function?

My server script is:

server.get("/lookup", function(req, res, next) {
      console.log("in lookup");
      res.header("Access-Control-Allow-Origin: *");
      res.header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
      res.header("Access-Control-Allow-Headers", "X-Requested-With");
      res.send("RESPONSE");
}

My client side is:
  var xmlhttp = new XMLHttpRequest();
  var url = "http:localhost:3000/lookup";
xmlhttp.onreadystatechange = function(resp) {
    console.log("in resp");
    console.log(xmlhttp.responseText);
}
   
  xmlhttp.open("GET", url, true);
  xmlhttp.setRequestHeader("Access-Control-Allow-Origin", "*");
  xmlhttp.send();
  });

My status i s0 and I have no response text. Can you help me sort this?

**Comment by DonutEspresso** [comment]
Hello, if you are on 4.x release please check out the CORS plugin. http://restify.com/#bundled-plugins
