### ISSUE TITLE
Run multitple apps on the same port

### ISSUE THREAD

**Issue by junerockwell** [restify/node-restify#1035]
Please add a feature to run multiple node/restify apps on the same port that's essentially similar to Express's `.use()` (it enables running multiple node apps on the same port)

For example:
You have your apps saved in this path:

```
/var/www/app1
/var/www/app2
/var/www/app3
```

each having similar routes like this:

```
app.get('/', func...);
app.get('/about', func...);
app.post('/foo', func...);
app.post('/bar', func...);
```

and easily access them as different apps from -

```
localhost/app1
localhost/app2
localhost/app3
```

In Express, it's done like this:

```
app
   .use('/app1', require('./app1/index').app)
   .use('/app2', require('./app2/index').app)
   .listen(8080);
```

More details on this SO question's answer:
http://stackoverflow.com/questions/11225983/running-multiple-node-express-apps-on-same-port

**Suggestion:** _maybe make a plugin for restify to add this feature_

**Comment by serv** [comment]
What would be a good use case for this?

**Comment by junerockwell** [comment]
@serv I was given a virtual server with one domain name that looks like this `api.something.com` running on one port (for example, `8000`). I made a mobile app with a REST API using Restify and I'm keeping it alive with PM2. I have been tasked to make another mobile app and I've made its own REST API. And, because there seems to be no way, according to the person who made the server for me, to run multiple ports because `api.something.com` already points to port `8000`, I need to be able to do this `api.something.com/app1` and `api.someting.com/app2`. I've tried making a sample in ExpressJS and I do not need to use more than 1 port because I `exports.app = app = express()` at the end of both app1/index.js and app2/index.js. 

I don't want to restart the first Node REST API app along with the second Node REST API app. Additionally, since Restify have done the heavy lifting for me with plugins such as `.acceptParser()`, `authorizationParser()` along with many other features, I'd rather not remake these apps in Express which will just be time consuming. So to have a feature like Express' `app.use()`, it'd be really helpful. Most importantly, I don't need to include a view engine for Restify. In fact, I don't even render web pages for these REST API's.

**Comment by DonutEspresso** [comment]
I like this use case. I would love to explore this after we cut 5.x. I think there's value in decoupling the router from the server, if only for better separation of concerns. Might even be able to reuse existing router modules from elsewhere.
