### ISSUE TITLE
Remove defaultResponseHeaders from documentation

### ISSUE THREAD

**Issue by crapthings** [restify/node-restify#1040]
```
 restify.defaultResponseHeaders = function(data) {
  this.header('Server', 'helloworld');
 this.charset('utf-8')
};
```

**Comment by DonutEspresso** [comment]
It appears the docs are outdated. @yunong do you know what happened to this option? Removed in favor of a universal handler?

**Comment by crapthings** [comment]
okay cool

but what is new method to define default headers ?

by use pre ?

**Comment by DonutEspresso** [comment]
Yep, you can use either `server.pre()` or `server.use()` to accomplish the same thing. `pre()` will fire before routing occurs, which may or may not be desirable for your use case.

**Comment by DonutEspresso** [comment]
Hi @crapthings, closing this issue since it looks like we're good. Feel free to file a new issue if you have other problems.

**Comment by DonutEspresso** [comment]
Actually, I'm going to keep this open as a bug against the documentation.
