### ISSUE TITLE
Option to pretty print JSON responses

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1042]
When sending back JSON or a JavaScript object it would be awesome to have an option to pretty print the JSON.

**Comment by DonutEspresso** [comment]
This is possible by implementing your own JSON formatter: 

```js
var server = restify.createServer({
    formatters: {
        'application/json; charset=utf-8': function(req, res, body, cb) {
            return cb(null, JSON.stringify(body, null, '\t'));
        }
    }
});
```

Give it a try and let us know if that works for you.

**Comment by nodesocket** [comment]
Thanks that worked. Would it be worth a convenience option you pass into `createServer()`?

Something like:

```
{
    prettyJSON: true
}
```

**Comment by DonutEspresso** [comment]
Since it's pretty easy to implement custom formatters, this is an option we'll probably want to avoid to keep the core small and lean. Always open to revisit at a later date though if other use cases come up!
