### ISSUE TITLE
Disable DTrace option

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1051]
Is it possible to disable DTrace support? Would disabling result in any improved performance or decreased memory usage?

Would also be great if `npm install restify` by default did not install DTrace as a dependency. It is large and takes a bit of time.

Perhaps have DTrace support something you have to opt-into?

**Comment by micahr** [comment]
Part of the draw of using Restify is the ability to use Dtrace for introspection into the live running app. If you are not wanting that capability during development or production, feel free to run: `npm install restify --no--optional` to not pick up Dtrace support.

**Comment by nodesocket** [comment]
Didn't know about `--no-optional` that is perfect. Is there a way specify that flag in a `package.json` though?

```
 "dependencies": {
    "restify": "4.0.4"
  }
```

**Comment by DonutEspresso** [comment]
Unfortunately I don't know of a way to specify that via package.json. There seems to be an issue over at npm/npm#679 talking about ways to do this when using shrinkwrap, but AFAICT there's no straightforward way.
