### ISSUE TITLE
new restify.BadRequestError() missing restCode property

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1052]
The default 404 error handler with JSON returns the following body:

```
{
    "message": "/foo does not exist",
    "statusCode": 404,
    "body": {
        "code": "ResourceNotFound",
        "message": "/foo does not exist"
    },
    "restCode": "ResourceNotFound"
}
```

However, manually triggering a 400 with:

```javascript
return next(new restify.BadRequestError('400 bad request message here'));
```

Returns the following JSON body:

```
{
    "message": "400 bad request message here",
    "statusCode": 400,
    "body": {
        "code": "BadRequestError",
        "message": "400 bad request message here"
    }
}
```

Notice it is missing the `restCode` property. Should be added to maintain consistency.

**Comment by nodesocket** [comment]
Any update on this?

**Comment by DonutEspresso** [comment]
Apologies for the delay - I have been on vacation and mostly disconnected. Is this on the 5.x branch?

**Comment by nodesocket** [comment]
Thanks for the reply, running restify `4.0.4`. I switched to using `restify-errors` so the payload is different now.

```
"{\"code\":\"BadRequest\",\"message\":\"Unable to retrieve quote for ticker symbol \\\"\\\"\"}"
```

**Comment by DonutEspresso** [comment]
Cool. I'm happy to add `restCode` to restify-errors serialization, that should be pretty straightforward. Do you have a custom JSON formatter? The default JSON formatter will always return the .body property of the error object as the payload, so I'm not sure how you are getting all the properties of the error exposed as part of the payload.

**Comment by DonutEspresso** [comment]
Would you mind filing an issue over at restify-errors?

**Comment by DonutEspresso** [comment]
Apologies, just noticed you already opened an issue there. Let's continue the conversation in the other thread.
