### ISSUE TITLE
Remove references to dead IRC channel

### ISSUE THREAD

**Issue by fidian** [restify/node-restify#1055]
I've been trying to hang out in IRC in order to contact the developers.  My goal was to discuss Proxy Protocol and get feedback on pull request #1046 this entire week.  There were no replies.  In fact, while I was there, I was unable to observe any other messages beyond the probes I was sending to the room.

I do understand that people come and go, but I suspect that trying patiently for a week is a solid amount of effort, beyond what you would expect most of your users to attempt.  I propose taking off the bit about joining IRC from restify.com and from the README.md in the project.

As support, here is a two-day chat log.

![screenshot from 2016-04-01 07-53-19](https://cloud.githubusercontent.com/assets/428348/14207305/d4dbf5d2-f7de-11e5-8148-4ccd21df095a.png)

**Comment by DonutEspresso** [comment]
Apologies for the delayed reply. I've been on vacation and mostly disconnected. 

Thanks for the feedback! Unfortunately all the maintainers have full day jobs, so the IRC channel has not been an effective way for us provide support. What you've suggested is something we've been considering some time, this is probably just another nail in the coffin.

**Comment by fidian** [comment]
Please keep in mind that I would *greatly* prefer this idea to be rejected and instead see a more active user group in the IRC channel.  However, either the docs or the developers' behavior should change so the website doesn't imply this false sense of support.

**Comment by fidian** [comment]
Is the IRC channel still dead?  Does the documentation still say that people can find answers there?

**Comment by retrohacker** [comment]
Hey @fidian,

I'm not sure anything has changed, but I'm :+1: on removing the IRC channel for reasons beyond maintainer activity. Back-channeling discussions around the project on any medium fragments the project's history. Would like to see problems, feature discussions, etc. happening in a place that can at least be linked to from GitHub.

**Comment by yunong** [comment]
@retrohacker works for me -- feel free to file a PR to that effect.
