### ISSUE TITLE
On the website restify.com updated documentation?

### ISSUE THREAD

**Issue by KostyaTretyak** [restify/node-restify#1058]
From restify.com:

> Note this documentation refers to the 2.x version(s) of restify

But now the actual 4.x versions. So restify.com placed relevant documentation or not?

**Comment by serv** [comment]
From my experience, restify API hasn't changed very much, so it should be still very much relevant.
We recently moved from v2.9.0 to 4.0.4 without changing very much other than formatter. Go ahead and use the doc with the latest version. You should be fine.

**Comment by Jokero** [comment]
restify has very bad documentation. A lot of things not documented at all. So it's better to look code than to read the documentation

**Comment by DonutEspresso** [comment]
Thanks for the feedback folks - we have a documentation revamp in the works. Keep your eyes peeled!

**Comment by dwightgunning** [comment]
I'm new to Restify so was reading the docs and I found a very small error. Forked the repo and then found that the source MD behind the docs was fixed in a commit from last May.

Seems like the latest docs should be rebuilt and deployed to restify.com?

**Comment by KostyaTretyak** [comment]
@dwightgunning, the project maintained extremely slow and [not very professional](https://github.com/restify/node-restify/pull/1264) (forgive me, but it is).

**Comment by dwightgunning** [comment]
@KostyaTretyak - Doesn't seem all that bad to me. Perhaps the active contributors / more folks haven't got their watching/notifications tuned in to closed issues and PRs.

@DonutEspresso - are you able to confirm the restify.com website is behind the latest docs, and how we can help fix that up?

**Comment by DonutEspresso** [comment]
The documentation is up to date for 4.x (the 2.x blurb is actually out of date). If you do see any issues, please file issues. While response may be slow at times, we'll get through the backlog eventually. 

@KostyaTretyak all of the current maintainers have full time jobs and families - so for us, this project is something we do primarily in our free time. We try our best so response may be slow at times. We are always happy to take help where we can get it. :)
