### ISSUE TITLE
Getting Unexpected token o 

### ISSUE THREAD

**Issue by fr-kshibata** [restify/node-restify#1060]
In restify.createJsonClient 
It was showing uncaughtexception and then I removed the server.on('uncaughtexception');
I got 
`InternalError: Unexpected token o`

```
				console.log(typeof poster); //string
				poster = JSON.parse(poster);
				console.log(typeof poster); //object

				client.post('/test', poster, function (err, req, res, obj) {
					if (err) callback(err, null);
					else {
						console.log(obj);
					}
				});
```

using restify 4.0.4

**Comment by micahr** [comment]
What is the string content of `poster`? Likely there is a JSON parse error when parsing the content.

**Comment by fr-kshibata** [comment]
The content of poster(string) is 

```
{
	"server": "server1",
	"message": {
		"resize": {
			"x": 1000,
			"y": 1000
		},
		"padding": {
			"x": 184,
			"y": 184,
			"color": "#000"
		},
		"remote": {
			"path": null
		}
	}

}
```

**Comment by DonutEspresso** [comment]
Can you post the snippet of code that initializes your server?
