### ISSUE TITLE
Middleware for specific route

### ISSUE THREAD

**Issue by augustovictor** [restify/node-restify#1063]
How to build a middleware for a specific route like in express?

Should I use promises?

I want to do something like this:

```
var mid = function(req, res, next) {
  models.Team.find({
      where: {
        id: req.params.id
      }
    }).then(team => {
      if (team) {
        req.team = team;
        return next();
      } else {
        res.send(404, 'Team not found');
      }
    }).catch(err => {
      send(500, err);
    });
};
  
  
// -----------------------------------------------
  
var getById = function(req, res, next) {
  mid(req, res, next);
  res.send(req.team);
  return next();
};
```

**Comment by micahr** [comment]
If `getById` is your specific route, you'll want to add your handler as part of a chain when you mount your route:

```javascript
server.get('/foo/:id', [mid, getById]);
```

This ensures that your `mid` middleware runs to completion before it calls the next handler (in this case `getById`).

**Comment by augustovictor** [comment]
What about the middleware function?
Is that the right way to retrieve data from database?
Is there any way to send an error from the middleware? If so, should I do it?


Thanks a lot for your fast reply.

**Comment by micahr** [comment]
The way you retrieve data from your database is not something I can help with too much, as that is very specific to your application. The way you are doing it seems fine from the sense of catching any errors and sending a 500 error to the client.

**Comment by DonutEspresso** [comment]
@augustovictor Looks like we're good here, let us know if you have other questions.
