### ISSUE TITLE
EventEmitter deprecation message - spdy

### ISSUE THREAD

**Issue by Jovaage** [restify/node-restify#1067]
The version of spdy used in restify. are making calls to `process.EventEmitter`.  
This has since been deprecated, I believe in nodejs v6, and it's now logged in the console.  
Could the dependency be updated to a later version of spdy?

**Comment by danielfigueiredo** [comment]
Yeah, I also started getting this error when updated to nodejs v6.0.0
```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x20a8f96c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x2c69edaa7a4] (this=0x33d394e94751 <an Object with map 0x30a94d28491>#1#,module=0x449e1063679 <a Module with map 0x30a94d29301>#2#,filename=0x449e1063581 <String[117]: /Path/To?my?project/.../DTraceProviderBindings.node>)
  .....
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: node::DTraceProbe::Initialize(v8::Local<v8::Object>)
 3: node::DTraceProvider::Initialize(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 8: 0x2c69ec0961b
 9: 0x2c69edaa7a4
(node:3841) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
```

**Comment by DonutEspresso** [comment]
Hello, thanks for the report. To help quickly debug, which combination of restify/spdy is causing the deprecation warning?

**Comment by danielfigueiredo** [comment]
I'm not using spdy and I also get the error. My server is a regular rest API that works with json payload and upload images.
You can easily reproduce the error by installing Nodejs version:
```
daniel@Daniels-MacBook-Pro-2> node --version
v6.0.0
```
and running the following script:

```
'use strict';

const restify = require('restify');
const server = restify.createServer({
  name: 'Test resitfy with nodejs 6'
});
server.listen(3050, () => {
  console.log('server started');
});
```

**Comment by DonutEspresso** [comment]
I dug into it some more, looks we've updated spdy on 5.x already and are looking to cut a release imminently. Once it's released I'll update the issue here.

**Comment by lgomez** [comment]
Is there a ballpark release date for 5.x?

**Comment by DonutEspresso** [comment]
Looking to have it cut in the next week or two. Certainly before end of the month!

**Comment by bobvanluijt** [comment]
This is working for me :-)
https://github.com/restify/node-restify/pull/1105

**Comment by DonutEspresso** [comment]
Quick update: restify@4.1.0 was just released for this who really need this now now. 

5.x forthcoming.

**Comment by danielfigueiredo** [comment]
I still have the same issue even after updating to restify 4.1.0.
Same scenario same thing I posted above ^

Does anyone have any idea?

**Comment by fedorkleber** [comment]
I also still have the same issue, even with restify 4.1.0 installed. Any ideas? @danielfigueiredo did you find a fix?

`DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.`

**Comment by brahiansoto** [comment]
It works! Thanks @DonutEspresso
