### ISSUE TITLE
serveStatic does not serve default file as fallback

### ISSUE THREAD

**Issue by thedillonb** [restify/node-restify#1076]
The documentation describes the default parameter as operating as such:

`You can also provide a default parameter such as index.html for any directory that lacks a direct file match.`

I would assume, from this description, that upon failure to direct file match, a default file will be served. However, the code suggests something completely different:

```
 function serveNormal(file, req, res, next) {
        fs.stat(file, function (err, stats) {
            if (!err && stats.isDirectory() && opts.default) {
                // Serve an index.html page or similar
                file = path.join(file, opts.default);
                fs.stat(file, function (dirErr, dirStats) {
```

This would only attempt to serve the default file if the original request mapped to a directory. All other failures to "direct file match" just end up as BadRequests. This would seem to make having a fallback file impossible.

**Comment by JoeDoyle23** [comment]
I ran into this as well and just created this PR: restify/plugins#31

**Comment by retrohacker** [comment]
closing this in favor of #535 :heart:

**Comment by wasa4587** [comment]
I have to do this
