### ISSUE TITLE
createServer() name and version properties not taking effect

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1078]
I'm setting `name` and `version` when calling `restify.createServer()` but not seeing these props take effect.

```
let server = restify.createServer({
    name: 'my-restify-server',
    version: '1.2.3',
    formatters: {
        'application/json': function(req, res, body, callback) {
            return callback(null, JSON.stringify(body, null, 4));
        }
    }
});
```

````
curl -i http://127.0.0.1:9090
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Date: Sat, 07 May 2016 20:56:44 GMT
Transfer-Encoding: chunked

{}
````

Notice the `Server` header is not being set to `my-restify-server` and the route should return 404, because it should be `http://127.0.0.1:9090/1.2.3/`.

**Comment by nodesocket** [comment]
Bump. I'm I just doing something stupid?

**Comment by DonutEspresso** [comment]
Hi - it looks like the docs are out of date. Neither of these options are currently working. You can probably add them by simply adding a universal handler:

```js
server.use(function(req, res, next) {
   res.header('name', name);
   res.header('version', version);
});
```

**Comment by nodesocket** [comment]
@DonutEspresso I see. Were they removed, or never implemented?

Specifically the version property is super useful to prefix every route.

    version: 'v1'

Which would make all routes:

    /v1/...

**Comment by DonutEspresso** [comment]
Honestly I don't know, some of the documentation has been there before I started working on restify. :)

FWIW, as far as I can tell from the original docs, I think the intention of these attributes were to set default headers for your routes, in the absence of an explicit version. This is different from the prefix functionality you're after, which sounds similar to #1035.

**Comment by nodesocket** [comment]
I think the currently documentation is very misleading then:

     version	String|Array	A default version to set for all routes

I read that to mean it prepends that value to the beginning of every route.

**Comment by nodesocket** [comment]
Also, the **README.md** uses `name` and `version` in the example. If indeed these properties are not supported and do nothing we should update README.md.

```
var server = restify.createServer({
  name: 'myapp',
  version: '1.0.0'
});
```

**Comment by DonutEspresso** [comment]
Yes, the README needs some TLC, which is one of the next big things on the roadmap. We're happy to take PRs in the meantime. As far as versioning is concerned, restify uses the `Accept-Version` header to handle version negotiation.

**Comment by DonutEspresso** [comment]
Server header is now passed down as part of recent fix. We'll update the docs.

**Comment by nodesocket** [comment]
@DonutEspresso I'm still not seeing the `Server: name` and version working. Here is my usage:

```javascript
restify.createServer({
        name: 'my-awesome-package',
        version: '1.0.0',
        formatters: {
            'application/json': function(req, res, body, callback) {
                return callback(null, JSON.stringify(body, null, 4));
            }
        }
});
```

**Comment by DonutEspresso** [comment]
This is the 5.x branch was is not yet released. We may release a RC sometime this week or early next week which will have these available.
