### ISSUE TITLE
Allow the request id header to be configured

### ISSUE THREAD

**Issue by micahr** [restify/node-restify#1086]
Instead of assuming `request-id` or `x-request-id` as the headers for an incoming request id, allow the header to be configured via a property.

**Comment by DonutEspresso** [comment]
Seems reasonable to add this as an option when creating the server.

**Comment by nodesocket** [comment]
I was actually trying to figure this out. Does restify automatically add a response header `Request-Id`? I'm not seeing it.

**Comment by DonutEspresso** [comment]
Currently restify uses the incoming request's `request-id` or `x-request-id` as the value returned by the `req.id()` method. If you want to set the request id as a response header, you can do it via a `use()` handler.

**Comment by nodesocket** [comment]
Gotcha, so there is no way to have restify automatically add a `request-id` to the response?

**Comment by micahr** [comment]
Try this:

```javascript
const restify = require('restify');
const server = restify.createServer({});

function requestIdMiddleware(req, res, next) {
   res.setHeader('req_id', req._id);
   return next();
}
server.use(requestIdMiddleware);

```

**Comment by mogsie** [comment]
When restify is running behind anything amazon, amazon will have created request IDs that they use to track things, e.g. `X-Amz-Request-Id`.  Varnish does the same, by default `X-Varnish: 123123`. Making it possible to configure which incoming HTTP headers denote my request ID would be a good idea, I think.

**Comment by nodesocket** [comment]
I guess I don't see the point passing along a client request-id. Isn't this usually an id generated server side that is returned in the response?

If we just pass along the client request-id back to the response, users can put whatever they want and it will output back.

**Comment by nodesocket** [comment]
@mogsie you can do the following right?

```javascript
const restify = require('restify');
const server = restify.createServer({});

function requestIdMiddleware(req, res, next) {
   const amzRequestId = req.get('X-Amz-Request-Id') || null;

   if(amzRequestId) {
        res.setHeader('Request-Id', amzRequestId);
   }

   return next();
}
server.use(requestIdMiddleware);
```

**Comment by DonutEspresso** [comment]
Allowing the request id to be configured also means the request logger, the audit logger, and various other plugins in the restify ecosystem will use that same request id everywhere. It's great if you're using the request id to track the request through various subsystems.

**Comment by mogsie** [comment]
First of all, thanks for the quick feedback!

@nodesocket I don't think I made myself entirely clear. I am not saying _clients_ should provide a request ID; I am suggesting that a front end load balancer often has the same concept of tagging requests.  CDNs like Amazon CloudFront, Akamai (`X-Akamai-Request-ID`), load balancers like Amazon Elastic Loadbalancer, caches like Varnish Cache (`X-Varnish`) all have this concept.  Amazon's API Gateway, the list goes on.  These are the trusted sources that can generate various forms of Request IDs, and forward them using some or other header.

I think it's common to have something in front of the restify process, already tracking the request.

This worked, but it feels hackish, and depends on implementation details:

```
const restify = require('restify');
const server = restify.createServer({});

function requestIdMiddleware(req, res, next) {
   const amzRequestId = req.header('X-Amz-Request-Id') || null;
   if(amzRequestId) {
      req._id = amzRequestId;
   }
   return next();
}

function executeRequest(req,res, next) {
   res.end("The request ID was " + req.id());
}
server.use(requestIdMiddleware);
server.get(/(.*)/, executeRequest);
server.listen(1337);
```

`curl -H "X-Amz-Request-Id: xyzzy" http://localhost:1337` yields `The request ID was xyzzy`.

Simply a setter, perhaps with "set if unset" semantics would be enough.

**Comment by serv** [comment]
What do you think about attaching req_id to outgoing requests created by clients?
I will copy over the explanation for this feature from https://github.com/restify/node-restify/issues/1101.

```
We know that all the incoming request to restify server has a req_id.
Restify server may make subsequent requests to other services using the restify client.
Can we add an ability to attach this req_id to subsequent requests' header created by restify clients?
```

**Comment by mogsie** [comment]
I'm a bit unsure how you would know which req_id to add to an outbound request, if any.  An incoming request might make a db lookup to, say, mongodb, and when it returns I might make another HTTP request to another thing, in the mogodb callback.  How would you (could you) automatically set the restlet client req_id? I would imagine that I as the user of restify and restify-client would have to do _some_ housekeeping to make that connection. Documentation and an indication of how one _ought_ to accomplish this would be useful.

I looked at b2419e975 and it seems to solve #1086 admirably :-)

**Comment by DonutEspresso** [comment]
@serv @mogsie feel free to continue the discussion over in the other thread. 

In short, I don't think there's anything magical restify can do to automatically attach id's to upstream requests. It'd be no different if you were using request or superagent or the raw http client - some glue must exist to get the current id off the incoming request and attach it as an outbound header.
