### ISSUE TITLE
Question: add an ability to attach req_id to a header of requests created by restify clients

### ISSUE THREAD

**Issue by serv** [restify/node-restify#1101]
I know this is a bit mouthful, but the title describes the feature request. 
We know that all the incoming request to restify server has a `req_id`.
Restify server may make subsequent requests to other services using the restify client.
Can we add an ability to attach this req_id to subsequent requests' header created by restify clients?

This is useful when you want to debug some production issues with downstream services you have control over.
Say, one of your client says that there's been some problem with a request calling /xyz endpoint to your restify API. And you are asked to find out what's happening.
You can take the req_id created from the request calling /xyz and take it to your downstream services team and ask them to look up some logs with req_id as header value. And help yourself during the debugging process.

**Comment by DonutEspresso** [comment]
Thanks for the suggestion - I think this feature request is captured in #1086. The idea being that restify will automatically use whatever request id header you've specified. Can you take a look and see if that's meets your needs?

**Comment by serv** [comment]
@DonutEspresso I don't think that issue is exactly what I am looking for, although it's quite similar. I'll suggest this issue as a part of requirement we might want to consider for #1086

**Comment by DonutEspresso** [comment]
If you're making requests to upstream services, that would be configured at the client level, rather than the server right? I don't think restify-clients currently supports headers on a per request basis if that's what you're looking for. 

If I'm not misunderstanding, can you please open an issue for this over at the [restify-clients](https://github.com/restify/clients) repo? Thanks!

**Comment by mogsie** [comment]
I was under the (mistaken) impression that this (forwarding the req_id to "back-end" services) was more or less out-of-the-box behaviour of restify, but I see that it isn't.  I guess how to do it should be documented and explained how to do. I think that would be enough.  And I agree that it makes more sense in the restify-clients project.

**Comment by DonutEspresso** [comment]
Definitely something we can add to the docs.
