### ISSUE TITLE
Website is incorrect about bundled plugins

### ISSUE THREAD

**Issue by fidian** [restify/node-restify#1112]
Restify is not bundled with any of the listed plugins except for CORS.  The website's examples can not work.

http://restify.com/#bundled-plugins

**Comment by DonutEspresso** [comment]
Yup, brand new docs coming when 5.x goes out the door.

Docs reflect the current state of 4.x

**Comment by fidian** [comment]
I'm glad to know there are updated docs coming.  Why is the version in NPM not matching the documentation?

**Comment by DonutEspresso** [comment]
The latest on npm is version 4.1.0 - it contains both the bundled plugins as well as the clients.

**Comment by fidian** [comment]
Aha, I have found my problem.  I forked my repository off of yours and my `package.json` file is pointing at the proxywrap branch of my repository.  This is because I require Proxy Protocol-wrapped TCP connections and because my pull request (see #1046) is not gathering much attention.

This issue is bogus, I am closing it.  Sorry for troubling you and thanks for being responsive!
