### ISSUE TITLE
A weird char at the end of the response string

### ISSUE THREAD

**Issue by leijing7** [restify/node-restify#1116]
![pic](http://7xnfkz.com1.z0.glb.clouddn.com/Screen%20Shot%202016-05-31%20at%206.59.29%20AM.png)

How can I get rid of the % at the end of the response string?

The server side code is exactly the same as the provided example code.

**Comment by micahr** [comment]
If you are using ZSH, it could be a result of that shell: http://stackoverflow.com/questions/29497038/why-does-a-curl-request-return-a-percent-sign-with-every-request-in-zsh

I don't believe this is an issue with Restify, as the Restify framework does not return percentage signs in responses.

**Comment by DonutEspresso** [comment]
You should configure your PROMPT_SP, this is specific to ZSH and not restify related.
