### ISSUE TITLE
Hanging on unsent response?

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#1127]
As of #1104, the semantics of the server 'after' have changed a bit. After is now fired only when both of the following are true:
- a response has been sent (or terminated by client)
- reached the end of the handler chain

This creates a new scenario where it's possible to reach the end of the handler chain and have never sent a response, meaning after is never fired, and the audit log never kicks in. I'm not sure if we can do anything here - technically user could be flushing a ridiculously large file and it's just taking a while. Current code is to wait for the res 'finish' event, which may be the best we can do. Thoughts?

**Comment by retrohacker** [comment]
Closing this as stale.
