### ISSUE TITLE
Return instance created previously

### ISSUE THREAD

**Issue by danieldms** [restify/node-restify#1133]
I don't know if it's correct, but in other parts of my system he don't returns the instance created previously.

Main.js
var restify = require('restify');
var server = restify.createServer(opts);

second.js
var restify = require('restify');
var server = restify.createServer(opts); // New Server
console.log(server);

If you observe the second.js, it's created a new server and don't returns a instance of the server created previously.

i know that is possible create this in nodejs. i would like know if has other form to make. Thanks for attention.

**Comment by DonutEspresso** [comment]
Hello - not sure this is a restify problem. You should just export your server, and other files can import that same object if you need access to the server objec.t
