### ISSUE TITLE
100% CPU consumption with restify 4.0.4 after x hours caused by restify.throttle

### ISSUE THREAD

**Issue by awenger** [restify/node-restify#1137]
We had a problematic service that is based on restify 4.0.4. Approx. every 30 hours the cpu usage jumped (in a few seconds) to 50% and a few minutes later to 100% (and stayed there till the service was restarted). This service is utilizing the cluster module (2 workers, 2 cores). We were able to verify that the two jumps were related to the 2 workers starting to consume all the available cpu time. Also the times the cpu consumption jumped wasn't correlated with the amount of requests restify was processing. 

After several unsuccessful attempts to pin point the cause for this problem I found the following commit (Sadly they don't use any kind of Changelog?): https://github.com/isaacs/node-lru-cache/commit/f95bf1f72744c7dc323f27b35331512aebdfa9ca

We are using `restify.throttle` in different parts of this service. So I added a differnt `tokensTable: new TokenTable()` implementation. This version is exactly the same that is used by restify, hewever this one is based on the latest version of `lru-cache`. With this single change the service is now running stable for more than a week.

I know that there is now the new 5.x.y version of restify (That already utilizes the new version of `lru-cache`). However, because of the severity of this problem and the work required to fix it, I think this could be worth backporting into a 4.0.5 version.

**Comment by micahr** [comment]
Restify 4.1.1 has been released with an update to LRU Cache.

**Comment by awenger** [comment]
Thanks a lot for the updated version. We'll check it out.
