### ISSUE TITLE
How to use SO_REUSEPORT with restify

### ISSUE THREAD

**Issue by dlsniper** [restify/node-restify#1138]
Hello,

Thank you for this library.
How can one configure SO_REUSEPORT with it?
Thank you.

**Comment by yunong** [comment]
A simple google search reveals: https://github.com/nodejs/node/issues/2604#issuecomment-135960433

**Comment by dlsniper** [comment]
The simple Google search did not reveal how to make the JS part work after that, thus the simple question. I've moved on from this since then so it can remain closed. Thanks.

**Comment by OmgImAlexis** [comment]
@yunong that doesn't help.
