### ISSUE TITLE
Create middleware for all routes using POST method

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1141]
Is it possible to create a middleware function that is called only for routes using `POST` method?

**Comment by micahr** [comment]
It is not possible to create a middleware and add it via `server.use` and have it only applied to POSTs. You can however, add a middleware via `server.use` and unless the request method is a POST you call next.

```javascript
server.use((req, res, next) => {
    if (!req.method === 'POST') { 
        return next();
    }
    // add your POST only logic here
});
```
