### ISSUE TITLE
Remove header Content-MD5

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1142]
Is there a way to disable or remove the header `Content-MD5: mZFLkyvTelC5g8XnyQrpOw==`? Don't want it exposed.

**Comment by micahr** [comment]
Yes, you can call: `res.removeHeader('Content-MD5')` and that will drop it for any requests you don't want it exposed for. If you want it to happen for all requests, just create a middleware that removes it and register it with `server.use`.

**Comment by nodesocket** [comment]
Humm, can't get the header removed.

```
rest.pre((req, res, next) => {
    res.removeHeader('Content-MD5');
    return next();
});
```

**Comment by nodesocket** [comment]
Any update? I love restify, but there is a pattern of small things not working like the should out of the box.

**Comment by DonutEspresso** [comment]
If you are using CORS fullResponse header, it automatically sets the the Content-MD5 header. You'd probably want to have a handler in your chain that comes after the CORS plugin that removes that header.

**Comment by nodesocket** [comment]
I am adding a handler after all the middleware.

Here is the basically the entire setup I am using:

```javascript
function Server(config) {
    this.config = config;

    this.rest = restify.createServer({
        formatters: {
            'application/json': (req, res, body, callback) => {
                // manipulate error response object
                if(body.body && body.body.code) {
                    body.code = body.body.code;
                }

                if(body.body) { delete body.body; }
                if(body.restCode) { delete body.restCode; }

                // pretty print JSON
                return callback(null, JSON.stringify(body, null, 4));
            }
        }
    });

    this.rest.use(restify.fullResponse());
    this.rest.pre(restify.pre.userAgentConnection());

    this.rest.pre((req, res, next) => {
        res.header('Server', 'Node.js ' + nodeVersion);
        res.header('Charge-Control-Version', pkg.version);
        res.cache('no-cache, no-store');
        return next();
    });

    this.rest.use((req, res, next) => {
        res.header('Request-Id', 'static-request-id');
        return next();
    });

    this.rest.use(restify.CORS({
        origins: [this.config.jsURL],
        credentials: true
    }));
    this.rest.use(restify.acceptParser(this.rest.acceptable));
    this.rest.use(restify.authorizationParser());
    this.rest.use(restify.bodyParser({
        maxBodySize: 1048576, // 1MB
        mapParams: true
    }));
    this.rest.use(restify.gzipResponse());

    this.rest.use((req, res, next) => {
        res.removeHeader('Content-MD5');
        return next();
    });

    this.rest.on('after', restify.auditLogger({
        log: bunyan.createLogger({
            name: pkg.name,
            stream: process.stdout
        }),
        body: true
    }));
}
```

**Comment by DonutEspresso** [comment]
Ah, sorry, it looks like fullResponse plugin attaches headers to the response using the 'header' event, which is emitted before restify writes out the headers:

https://github.com/restify/node-restify/blob/4.x/lib/plugins/full_response.js#L103

I'd recommend doing something similar in your custom handler, to listen to the 'header' event and remove the header you want. Just make sure you register it after the fullResponse plugin, as listeners are registered in order:
https://nodejs.org/api/events.html#events_asynchronous_vs_synchronous

**Comment by nodesocket** [comment]
> custom handler, to listen to the 'header' event and remove the header you want

Can you give an example of this? Thanks for the hand holding.

**Comment by DonutEspresso** [comment]
Sure:

```js
server.use(restify.fullResponse());
server.use(function removeHeaders(req, res, next) {
  res.on('header', function() {
    // this event will get fired when you call res.send sometime later. fullResponse will fire first, since it listens to the same 'header' event 
    res.removeHeader('Content-MD5');
  });
  return next();
});

// your other handlers
```

**Comment by nodesocket** [comment]
Perfect thanks.
