### ISSUE TITLE
Can't use RegExp in routing (v. 4.0.3)

### ISSUE THREAD

**Issue by GatoPresto** [restify/node-restify#1146]
Hi!
I have problem with RegExp in routing. I'm trying to create assets:
```
this.server = restify.createServer();

this.server.use(restify.acceptParser(this.server.acceptable));
this.server.use(restify.queryParser({ mapParams: false }));
this.server.use(restify.bodyParser({
    maxBodySize: 0,
    mapParams: false,
    overrideParams: false
}));

this.server.get(/\/assets\/?.*/, restify.serveStatic({
    'directory': './management/assets'
}));
```
And I caught a bug. I can't use RegExp in my route.
![Image of Yaktocat](https://sc-cdn.scaleengine.net/i/b6339874dbfc293c4cee4e35317547f62.png)

I tried several restify versions: 2.6.0, 4.0.3, 4.1.1 and saw same problem.

On Ubuntu 16.04
Node 0.12.3 (NW.js 0.12.3)
Restify 4.0.3

**UPD:**
I tried to use new NW.js 0.15.4 with latest node 6.2.2. I see the same problem, but I see no error in the console.

**Comment by GatoPresto** [comment]
is it the same problem?
https://github.com/restify/node-restify/issues/632

**Comment by GatoPresto** [comment]
What's going on?
![screenshot](https://sc-cdn.scaleengine.net/i/1de4125c2637f2fb52df6721a13cefab.png)

**Comment by DonutEspresso** [comment]
Hi, I can't reproduce this in regular node. Using your snippet I have no issues starting the server using restify 4.1.0:

```js
var restify = require('restify');
var server = restify.createServer();

server.get(/\/assets\/?.*/, restify.serveStatic({
    'directory': './management/assets'
}));

server.listen(3000, function() {
	console.warn('listening');
});
```

I'd suggesting asking for help with the NW.js folks - this is not a use case we currently support.

**Comment by GatoPresto** [comment]
Maybe it's issue in NW.js
Thanks for feedback
