### ISSUE TITLE
GatewayTimeoutError handler not working.

### ISSUE THREAD

**Issue by jaoxico** [restify/node-restify#1149]
Iḿ trying to handle GatewayTimeoutError event but this code:

`server.on('GatewayTimeoutError', function(req, res, route, err) {
    console.log('GatewayTimeoutError');
    console.log(err);
    // boom! this event has been fired.
});`

It never gets fired. Is there a way to do that?

**Comment by micahr** [comment]
I believe the event you are looking for is just `GatewayTimeout` as the `Error` gets stripped from the event: https://github.com/restify/node-restify/blob/5.x/lib/server.js#L191

**Comment by DonutEspresso** [comment]
Closing - let us know if you're still seeing issues.
