### ISSUE TITLE
restify.client handling of paths with spaces 

### ISSUE THREAD

**Issue by timoxley** [restify/node-restify#115]
If you accidentally use the client to request a path with spaces in it, everything hangs.

Doesn't reach the route, but it also doesn't return a status code to the client either. Just dead.

What do you think best approach here would be? 

Some kind of url encoding like " " to "%20" etc? throw error? 500? 403? 404?

https://github.com/timoxley/node-restify/blob/path-with-spaces/test/client.test.js#L76

**Comment by deepakshrma** [comment]
Use nodejs __querysrting__ module
```js
console.log("?"+querystring.stringify({a:'ds d', b:"sdsd"}));
```
Good handles all possible checks.
