### ISSUE TITLE
OPTIONS requests for CORS getting rejected

### ISSUE THREAD

**Issue by Reubend** [restify/node-restify#1150]
I'm trying to add CORS to my Restify server, but the preflight requests sent to me server are being rejected with a `403` error. Here's the code I'm using, which doesn't seem to help.
```
server.use(restify.fullResponse());
server.use(restify.CORS({
    origins: ['*'],
    headers: [
        "authorization",
        "withcredentials",
        "x-requested-with",
        "x-forwarded-for",
        "x-real-ip",
        "x-customheader",
        "user-agent",
        "keep-alive",
        "host",
        "accept",
        "connection",
        "upgrade",
        "content-type",
        "dnt",
        "if-modified-since",
        "cache-control"
    ]
}));
server.opts(/\.*/, function (req, res, next) {
    res.header("Access-Control-Allow-Credentials", true);
    res.header("Access-Control-Allow-Headers", restify.CORS.ALLOW_HEADERS.join(", "));
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    res.header("Access-Control-Allow-Origin", req.headers.origin);
    res.header("Access-Control-Max-Age", 0);
    res.header("Content-type", "text/plain charset=UTF-8");
    res.header("Content-length", 0);
    
    response.send(204);
    return next();
});
```

Does anyone know how to get around this? Perhaps my handling code is incorrect, or there might be a bug in the CORS plugin.

**Comment by nodesocket** [comment]
You've gotten farther than me. When I enable `fullResponse()` basically none of the properties I set in the CORS plugin take effect. Just always returns `Access-Control-Allow-Origin: *`. See my issue for further details: https://github.com/restify/node-restify/issues/1151

**Comment by nodesocket** [comment]
Also, as I understand the entire point of the CORPS plugin is that you don't have to set:

```
res.header("Access-Control-Allow-Credentials", true);
res.header("Access-Control-Allow-Headers", restify.CORS.ALLOW_HEADERS.join(", "));
res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
res.header("Access-Control-Allow-Origin", req.headers.origin);
```

In the route definition. However, I am not seeing the CORS plugin working as expected.

**Comment by Reubend** [comment]
Good to hear it's not just me that's struggling with this! The reason I set those headers manually is that since the plugin didn't respond properly to the preflight requests, I wanted to override that behavior with my own. However, neither the plugin's default nor my custom function seem to work.

**Comment by Reubend** [comment]
I'm trying everything that I can think of, and I'll let you know if I find any solutions :)

**Comment by nodesocket** [comment]
Ok I got something working, but note this is very custom and hacky, so your mileage may vary.

````javascript
    rest.use(restify.fullResponse());

    rest.use((req, res, next) => {
        res.on('header', () => {
            if(req.method !== 'OPTIONS') {
                res.removeHeader('Access-Control-Allow-Headers');
            }

            res.removeHeader('Access-Control-Expose-Headers');
        });
        return next();
    });

    // use() instead of pre() since we only want the
    // these headers modified for successful requests
    rest.use((req, res, next) => {
        res.header('Access-Control-Max-Age', 300);
        return next();
    });
}

Then in your routes you need to specify an explicit route for options handling and set the `Access-Control-Allow-Headers` manually:

```javascript
// OPTIONS handler for /
api.rest.opts('/', (req, res, next) => {
    res.header('Access-Control-Allow-Headers', 'Accept, Content-Type, X-Requested-With');
    res.send(200);
    next();
});
```

**Comment by Reubend** [comment]
@nodesocket That code didn't work for me, but I really appreciate the help nevertheless!

**Comment by Reubend** [comment]
Interesting... what finally worked for me was to call `server.use(restify.CORS())` *before* I called `server.listen()` 

Hope this helps anyone else who runs into issues!

**Comment by micahr** [comment]
Glad it's working for you. We have CORS on our list of items to improve in the future, but would appreciate help if others have ideas.
