### ISSUE TITLE
DTrace-Provider issue on El Capitan

### ISSUE THREAD

**Issue by remcinerney** [restify/node-restify#1161]
Hi,
I'm getting issues installing Restify on El Capitan... I've found some threads looking at the issue with Yosemite but nothing after that...

The issue:

$ npm install --save restify
> dtrace-provider@0.6.0 install /Users/[OMMITTED]/node_modules/restify/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
restify@4.1.1 node_modules/restify
├── assert-plus@0.1.5
├── tunnel-agent@0.4.3
├── escape-regexp-component@1.0.2
├── keep-alive-agent@0.0.1
├── negotiator@0.6.1
├── mime@1.3.4
├── formidable@1.0.17
├── node-uuid@1.4.7
├── qs@3.1.0
├── once@1.3.3 (wrappy@1.0.2)
├── semver@4.3.6
├── backoff@2.5.0 (precond@0.2.3)
├── http-signature@0.11.0 (ctype@0.5.3, asn1@0.1.11)
├── verror@1.6.1 (core-util-is@1.0.2, extsprintf@1.2.0)
├── vasync@1.6.3 (verror@1.6.0)
├── csv@0.4.6 (csv-generate@0.0.6, stream-transform@0.1.1, csv-stringify@0.0.8, csv-parse@1.1.7)
├── lru-cache@4.0.1 (pseudomap@1.0.2, yallist@2.0.0)
├── dtrace-provider@0.6.0 (nan@2.4.0)
├── bunyan@1.8.1 (safe-json-stringify@1.0.3, mv@2.1.1, moment@2.14.1)
└── spdy@3.3.4 (http-deceiver@1.2.7, handle-thing@1.2.4, select-hose@2.0.0, debug@2.2.0, spdy-transport@2.0.11)

and then...
$ node app.js
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

Node: 4.4.7
npm: 2.15.8
restify: 4.1.1

Any help would be great,
Thanks

**Comment by micahr** [comment]
dtrace is optional.

You can install with: `npm install --save restify --no-optional` and that will ignore dtrace.

**Comment by remcinerney** [comment]
Ok thanks. That's now installing / running without error.
