### ISSUE TITLE
Get custom header inserted via middleware from route

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1163]
If I have a middleware that automatically inserts a response header like:

```
rest.use((req, res, next) => {
    res.header('App-Id', uuid.v4());
    return next();
});
````

How do I fetch this value `App-Id` from a route?

````
rest.post('/', (req, res, next) => {
    //how do I get App-Id?
}
````

**Comment by micahr** [comment]
You can use: `res.getHeader('App-Id')` in your route.

**Comment by micahr** [comment]
Did that solve your problem @nodesocket?

**Comment by nodesocket** [comment]
All good, actually went a different route and generate the `App-Id` in the route instead of middleware. Thanks.
