### ISSUE TITLE
Redirect to a next route given a new path

### ISSUE THREAD

**Issue by Gywem** [restify/node-restify#1166]
Hello everyone,

I would want to create a handler that is executed prior a route is checked if it exists (using `pre`), then that handler could run the next function to a concrete route just in case it does not match with anyone.

I would want to achieve something like below:

``` javascript
const formatHandler = (req, res, next) => {
  if (/\.xml$/.test(req.url)) {
    res.setHeader('content-type', 'application/xml');
    return next(req.url.replace('.xml', ''));
  }
  next();
};
```

So a route like `/foos.xml` will be detected, marked its content-type and then redirected to `/foos` route.

Is that possible with Restify?

**Comment by micahr** [comment]
What you described should work as long as it is run as a `pre` handler. It will modify the incoming request url, which will in turn be used for routing to the appropriate route. One slight deviation from your question, is that it won't be a *redirect*, instead it will just be an internal route to `/foos`.

**Comment by Gywem** [comment]
It is not working for me, I am getting an internal error

```
<?xml version="1.0" encoding="UTF-8"?>
<xml>
    <message></message>
    <statusCode>500</statusCode>
    <body>
        <code>InternalError</code>
        <message></message>
    </body>
    <restCode>InternalError</restCode>
</xml>
```
I guess it is because the detail you posed, about this being an internal route and not a _redirect_. Is there a way to cancel the flow of the initial route?

**Comment by micahr** [comment]
Do you mind posting the definition of the route you are registering as `/foo`?

**Comment by Gywem** [comment]
Sure. This is just a test, trying to prove the idea.

The `/foos` route is defined as follows:

``` javascript
  // List
  server.get('/foos', (req, res, next) => {
    res.send(200);
    return next();
  });
```

I want to add that there are other routes defined as `/foos` but they are create, update and delete ends.

I am using `restify.pre.sanitizePath` and `restify.queryParser` middleware.

**Comment by micahr** [comment]
One thing you might be missing is that `req.url` will contain any query parameters. So if you are passing along additional parameters your regex in the `formatHandler` function you included won't evaluate to true. A better approach would be to parse out the url:

```javascript
const url = require('url');

function hasXmlExtension(req) {
  return /\.xml$/.test(url.parse(req.url).pathname)
}
```

**Comment by Gywem** [comment]
That is true. But I am still getting the 500 error, and I am requesting plain routes.

**Comment by micahr** [comment]
Do you mind posting the log showing the error you are getting?

**Comment by Gywem** [comment]
Sorry, how do I provide you more information about logs?

**Comment by Gywem** [comment]
ok, I have solved at least with the simple example.

I was not providing a name to the route, I was thinking if you don't do it, it gets the path as the name, and when you redirect using `next` it search for the `path` instead. Is not a way just to redirect to a concrete route path instead of a route name?

**Comment by DonutEspresso** [comment]
A 302 is definitely the easiest way to do it. Internal redirects are frequently fraught issues, it's something we'd like to take a closer look at in 6.x.
