### ISSUE TITLE
Expose csv-parse options in body parser

### ISSUE THREAD

**Issue by paolochiodi** [restify/node-restify#1167]
I'd like to be able to set some of the options of the csv parser used internally by csv-parse, especially  `relax_column_count`.

I know that I can override some of the default options with request headers, but not everything is exposed and not everything should be left to the client to decide

**Comment by micahr** [comment]
Do you mind moving this issue to: [restify/plugins](https://github.com/restify/plugins) so we can address it there? What you are asking seems pretty reasonable.

**Comment by paolochiodi** [comment]
Sure, I'll do
