### ISSUE TITLE
Prototype null for req.query

### ISSUE THREAD

**Issue by suhas-karanth** [restify/node-restify#1168]
The `__proto__` key for the query object populated by the queryParser plugin is null and hence calls to `hasOwnProperty` fail. I tested parsing query string with latest version of [qs](https://www.npmjs.com/package/qs) but it seemed to work fine.

PS: I wanted to attach screenshots but wasn't able to upload.

**Comment by suhas-karanth** [comment]
Attached screenshots. 
![restify_params_obj](https://cloud.githubusercontent.com/assets/7699414/17829072/520bbb4c-66bf-11e6-9018-0180b6e18c7f.png)
![restify_query_obj](https://cloud.githubusercontent.com/assets/7699414/17829073/520f8808-66bf-11e6-8930-511c0f3380dd.png)

**Comment by suhas-karanth** [comment]
I took out the code for query parser and am running it with the updated `qs` module. That solved the issue. But will there be any other problems that might occur due to the major version upgrade(3.1.0 -> 6.2.1)

**Comment by DonutEspresso** [comment]
Hello - plugins have been moved out into their own [repo](https://github.com/restify/plugins), and ongoing development will continue there. The queryParser plugin there is using a newer version of qs - please check it out. If this is still a problem please file an issue in that repo. Note that you can use restify-plugins with the currently 4.x release.

**Comment by suhas-babyoye** [comment]
Okay thanks. I'll switch over to the plugins repo.

**Comment by suhas-karanth** [comment]
Okay thanks. I'll switch over to the plugins repo.
