### ISSUE TITLE
Sample required to set etag

### ISSUE THREAD

**Issue by fvisticot** [restify/node-restify#1170]
I need to set etag in all my GET request.
I can not find a sample setting this etag and how to compute etag value from body response.
In fact, I can not find a way to access body response and after use an etag computing package to set the value

**Comment by DonutEspresso** [comment]
Hi @fvisticot, there is an example in #482, I believe you were in that thread already. You'd simply set the etag header like so:

```
res.setHeader('ETag', etag);
```

Computing the etag is up to you. Whether you want to do a MD5 hash or something else is completely up to you.

**Comment by fvisticot** [comment]
Hello,
My pb is in fact to compute etag from response body
With Restify I don’t know how to access response body to compte etag value from this body

Fred

**Comment by yunong** [comment]
We can add this to the documentation backlog

**Comment by fvisticot** [comment]
Tx,
Waiting to this documentation, can you please provide me a solution ?

Regards,

Fred

**Comment by ticatagdev** [comment]
Waiting for documentation update. can someone please give me sample code to access response body to compute etag ?

**Comment by retrohacker** [comment]
Hey @ticatagdev, we documented etag properly here: https://github.com/restify/node-restify/pull/1313/files

You probably aren't looking for the response body, more than likely you will want to read the resource you are planning to send across the network from disk and compute its sha512 sum (or something similar) to generate an etag. This can let you determine if you need to send the response over the wire early in the request lifecycle.

Closing this now as the documentation has been merged, please comment if you still need help :heart:
