### ISSUE TITLE
Removing a single versioned route breaks routing for all versions

### ISSUE THREAD

**Issue by jquatier** [restify/node-restify#1171]
It looks like currently when you remove a single version of a route at runtime, the `reverse` mapping that the router class maintains internally gets removed, even though there may be other versions of that API with the same source path. This appears to be a problem with the reverse mapping itself, it assumes there will only be a single route per source path and method and doesn't take route versioning into account.

https://github.com/restify/node-restify/blob/5.x/lib/router.js#L352

Example project:

```javascript
const restify = require('restify');

var server = restify.createServer();
const routeOne = server.get({ path: '/hello/:name', version: '1.0.0'}, (req, res, next) => {
  res.send('hello ' + req.params.name);
  next();
});

const routeTwo = server.get({ path: '/hello/:name', version: '2.0.0'}, (req, res, next) => {
  res.send('hello 2.0 ' + req.params.name);
  next();
});

const routeThree = server.get({ path: '/hello/:name', version: '3.0.0'}, (req, res, next) => {
  res.send('hello 3.0 ' + req.params.name);
  next();
});

server.rm(routeThree); // remove the 3rd version, maintain the others.

server.listen(9111, function() {
  console.log('%s listening at %s', server.name, server.url);
});

```

If you run this application and then try to hit /hello/something, you'll get a stack trace because the reverse mapping is now undefined after the route was removed:

```
/node_modules/restify/lib/router.js:524
        res.methods = reverse.slice();
                             ^
TypeError: Cannot read property 'slice' of undefined
    at Router.find (/node_modules/restify/lib/router.js:524:30)
```

Anyway, this basically prevents users from removing versioned routes at runtime because the routing breaks after the first version is removed. You can't remove more than 1 either because the `unmount` method also results in a undefined reference for the same reverse mapping.

**Comment by micahr** [comment]
That indeed does look like a bug. Instead of wholesale removing any route with the same name / route the version should be checked and only the appropriate version should be removed. I think this points out further deficiencies in how routes are stored in that unique routes aren't created for each version just each verb and path.
