### ISSUE TITLE
InvalidArgument and MissingParameter---is 409 correct?

### ISSUE THREAD

**Issue by domenic** [restify/node-restify#118]
This is kind of an OCD thing to worry about, so feel free to close, especially since changing this could have back-compat concerns.

`restify.InvalidArgumentError` and `restify.MissingParameterError` map to status code 409, which is defined as

> The request could not be completed due to **a conflict with the current state of the resource**. This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request. The response body SHOULD include enough information for the user to recognize the source of the conflict. Ideally, the response entity would include enough information for the user or user agent to fix the problem; however, that might not be possible and is not required.
> 
> **Conflicts are most likely to occur in response to a PUT request. For example, if versioning were being used and the entity being PUT included changes to a resource which conflict with those made by an earlier (third-party) request, the server might use the 409 response to indicate that it can't complete the request.** In this case, the response entity would likely contain a list of the differences between the two versions in a format defined by the response Content-Type.

(emphasis added). This doesn't seem like a good match for "invalid argument" or "missing parameter". Indeed 409 usually seems to be used in REST APIs for the PUT conflict scenario described, more specifically with the ETag as the version.

Rather, I'd think 403 Forbidden:

> The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated. If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead.

And if not that, 400 Bad Request:

> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

Notably `restify.InvalidContentError` already uses 400, and seems to be in the same class as InvalidArgument and `MissingParameter`.

---

Thoughts? Again, this is a pretty minor detail. But if you agree, I'd happily submit a pull request.

**Comment by shaunc** [comment]
422 -- +1... exactly what a conflict is for 409 seems unclear, but whatever it means, it should be possible to have an invalid argument without a conflict.
