### ISSUE TITLE
Binding an Object to "this" in a router handler function

### ISSUE THREAD

**Issue by jcald1** [restify/node-restify#1181]
I set up a Restify route using the following code. I created a pseudoclass, instantiated the object and used that as the handler for a route. I want the object itself to be bound to "this" in the "ping" function so I have access to variables set in the constructor.

```
    var Handler1 = function(config) {
      this.config = config
       if (!(this instanceof Handler1 )) {
        return new Handler1 (config);
       }
       ...
    }
    HttpHandlers.prototype.ping= function(req, res, next) {
            //"this" doesn't point to the handler1 object.
            return next();
     }
...
    var myhandler1= new Handler();
    app.get("/ping", myhandler1.ping, handler2);
    handler1.ping.bind(myhandler1)
```

**Comment by micahr** [comment]
I would suggest trying:

```javascript
app.get('/ping', myhandler1.ping.bind(myhandler1), handler2);
```

The issue is that when you perform your binding now it is returning the bound function, but nothing is using it.
