### ISSUE TITLE
How to update restify to 5.x.x via npm?

### ISSUE THREAD

**Issue by namirsab** [restify/node-restify#1182]
Well, the title is enough. I'm sorry for asking here but i've tried through the irc channel and via twitter and nobody answered :_)

**Comment by Pritoj** [comment]
`npm update restify` should work right?

**Comment by namirsab** [comment]
But the latest version is not 5.0.0. I've changed the title, sorry for the confusion

**Comment by micahr** [comment]
5.x hasn't been released or published yet. You can pull in Master from this repo: `npm install git@github.com:restify/node-restify.git#master` but I wouldn't recommend that until it's released.
