### ISSUE TITLE
Adding multiple router handlers

### ISSUE THREAD

**Issue by jcald1** [restify/node-restify#1183]
I'm trying to add multiple router handlers like so:

```
var handlers = []
for (var i = 0; i < config.length; i++) {
   var func = = function(req, res, next) {
                                  ....
            };
   handlers.push(func);
}
app.get(oneRouteConfig.context, handlers);
```

However, only the last handler is executed.  I tried to add them as two separate parameters instead of an array, and I had the same result.  I also tried using the new keyword and had the same results.  I can only seem to get multiple handlers to execute when I actually write out the different handlers manually.

**Comment by micahr** [comment]
Try the following:

```javascript
app.get.apply(app, handlers)
```

The http method based route registration function takes a variable amount of functions to run, but not an array of functions. So calling `apply` will fix that.

**Comment by jcald1** [comment]
I ended up just manually adding them, but I suggest updating the API documentation is apply() is the preferred way to dynamically anonymous functions multiple times, or functions instantiated with new.

**Comment by yunong** [comment]
We'll add this to the documentation backlog for the next release.
