### ISSUE TITLE
Add the unbundled plugins ref to the doc

### ISSUE THREAD

**Issue by theGlenn** [restify/node-restify#1185]
Apparently all plugins have been moved into a different bundle at [https://github.com/restify/](url) but this is specified nowhere in the documentation. 

Would be nice to add it because when people do `npm install restify`they got the last (supposedly stable) version but without the plugins and stuff like `server.use(restify.queryParser())` doesn't work see #1184.

**Comment by DonutEspresso** [comment]
Hello - the latest 5.x beta went out untagged accidentally. We've seen rectified the situation - apologies for the noise! The docs are still applicable for 4.x, but if you are interested in the beta I'd check out the [migration guide](https://github.com/restify/node-restify/blob/5.x/4TO5GUIDE.md).
