### ISSUE TITLE
Restify Breaks swagger-node

### ISSUE THREAD

**Issue by revnode** [restify/node-restify#1186]
When restify is used with swagger-node, the validation middleware for swagger breaks.

https://github.com/swagger-api/swagger-node/issues/313#issuecomment-150846472

In version 4.1.1 of restify, in /lib/response.js on line 329 if we change

self.write(self._data);

to

self.end(self._data);

the error is resolved.

With the way the code is now, the empty self.end overwrites the self.write and the data is never sent.

**Comment by DonutEspresso** [comment]
Asking for more info over at swagger-api/swagger-node#313

**Comment by revnode** [comment]
Yup, I responded there.
