### ISSUE TITLE
return next(err) doesn't halt processing

### ISSUE THREAD

**Issue by jcald1** [restify/node-restify#1189]
I have a router handler that calls another function.  In that second function I call "return next(new Error("test"));".  The error is sent back to the browser, but the code keeps executing further down in the first function, the handler.

**Comment by DonutEspresso** [comment]
Hello, can you post an example snippet demonstrating the behavior?

**Comment by gswalden** [comment]
```js
function first(req, res, next) {
  second(req, res, next);
  console.log('This still executes, as expected');
}

function second(req, res, next) {
  return next(new Error('test'));
}
```
I believe that is what is being described, and does not constitute a real issue, just a misunderstanding of the application.

**Comment by jcald1** [comment]
gswalden, correct, I was missing the return statement in first().
