### ISSUE TITLE
Receiving image as binary body

### ISSUE THREAD

**Issue by splacentino** [restify/node-restify#1200]
Hi.

I would like to receive a binary file (picture) in my POST/ route.

I am trying to use cUrl and Postman without any success to get the received file in the `body` of `request` object.

How can I do ?

**Comment by DonutEspresso** [comment]
You could use form post:

```
$ curl -X POST -F image=@./image.jpg localhost:3000/image
```

Files uploaded via forms is available on `req.files`.
