### ISSUE TITLE
HttpErrors Codes Changed & Not Reflected In Documentation

### ISSUE THREAD

**Issue by NeilCresswell** [restify/node-restify#1206]
The built-in list of HttpErrors at http://restify.com/#error-handling includes:
- 412 PreconditionFailedError
- 413 RequestEntityTooLargeError
- 414 RequesturiTooLargeError
- 415 UnsupportedMediaTypeError

In the past I had code in a long-standing app that I believe tested against **RequestEntityTooLargeError** OK, since I was testing some upload file sizes when the code was written, but I noticed today that is now failing in some logs. Took a brief look at `restify.errors` and found that **RequestEntityTooLargeError** doesn't appear to be present. Instead, I found the following:
- PreconditionFailedError
- PayloadTooLargeError (different)
- UriTooLongError (different)
- UnsupportedMediaTypeError

Might be a good idea to possibly support the old codes too to match the documentation, or if not, at least to update the documentation to match the code base?

**Comment by DonutEspresso** [comment]
Hello, thank you for the report. Is there any chance you recently updated to Node4+? The error codes are automatically generated from the core http module's status codes, and there was a breaking change between 0.x and 4. You can test it yourself by switching between node versions and running this snippet:

```
var http = require('http');
console.log(http.STATUS_CODES);
```

I agree that the documentation can be updated, however, to note this breaking change; I suspect many may be unaware.

**Comment by yunong** [comment]
@DonutEspresso would you mind updating the docs to reflect this?
