### ISSUE TITLE
Strange behavior declaring route with and without parameters in path

### ISSUE THREAD

**Issue by vellotis** [restify/node-restify#1213]
I have run into a strange behavior of Restify that has given me an headache.

Node: 6.2.2
Restify: 4.2.0

My restify code
```js
var restify = require('restify');
var server = restify.createServer();

server.get('/hello', function(req, res, next) {
  setTimeout(function() {
    res.send(200);
    next();
  }, 1000);
});

server.get('/hello/:time', function(req, res, next) {
  setTimeout(function() {
    res.send(200);
    return next();
  }, req.params.time);
});

server.listen(8100, function() {
  return console.log('%s listening at %s', server.name, server.url);
});
```
My JS for browser:
```js
var req = function (url) {
  var xhr = new XMLHttpRequest;  
  xhr.open('GET', url, true);
  xhr.setRequestHeader('Accept', 'application/json');
  xhr.withCredentials = true;
  xhr.onload  = function() { console.log('DONE - ' + url) };  
  xhr.send(null);
};

// /hello
req('http://api.kliendikaardid.ee:8100/hello');
req('http://api.kliendikaardid.ee:8100/hello');
req('http://api.kliendikaardid.ee:8100/hello');
req('http://api.kliendikaardid.ee:8100/hello');
req('http://api.kliendikaardid.ee:8100/hello');
// /hello/:time
req('http://api.kliendikaardid.ee:8100/hello/1000');
req('http://api.kliendikaardid.ee:8100/hello/2000');
req('http://api.kliendikaardid.ee:8100/hello/3000');
req('http://api.kliendikaardid.ee:8100/hello/4000');
req('http://api.kliendikaardid.ee:8100/hello/5000');
```
Responding in chrome:
[![Capture2.png](http://s17.postimg.org/bvw77c4n3/Capture2.png)](http://postimg.org/image/typ9yk0hn/)

Like you can see that parallel requests to `/hello` are handled sequentially.
And parallel requests to `/hello/:time` are handled concurrently.

**Comment by vellotis** [comment]
Seems to be not a Restify issue. The same procedure done in Firefox results:
[![Capture3.png](http://s16.postimg.org/zfokbiwv9/Capture3.png)](http://postimg.org/image/uh11wzt29/)

Closing

**Comment by DonutEspresso** [comment]
Hello - were you able to root cause this? Is this due to the way browsers schedule requests?

**Comment by vellotis** [comment]
@DonutEspresso Yep. Chrome performs sequentially requests that are made at the same time to the same URL. Different URL's are resolved parallel.
