### ISSUE TITLE
Route using regex path not setting params capture group

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1215]
`path: '/quotes/([a-zA-Z\-]+$)',` and sending `/quotes/aapl` results in `req.params` being set to an empty object. Shouldn't there be an element in `req.params` with the result of the capture group `aapl`?

**Comment by DonutEspresso** [comment]
`req.params` should be an array in this scenario. Is that not the case?

**Comment by nodesocket** [comment]
@DonutEspresso I am seeing an empty object returned.

Here are my settings for `bodyParser`:

````javascript
restify.use(restify.bodyParser({
    maxBodySize: 1048576,
    mapParams: true
}));
````

**Comment by DonutEspresso** [comment]
If you're passing in `path` as a string it won't register as a regexp route. You'll have to pass in a `new RegExp()` or a regex literal.

**Comment by nodesocket** [comment]
@DonutEspresso I am retarded. Of course I need a regex literal. Thanks and sorry for wasting your time.
