### ISSUE TITLE
Set default formatter

### ISSUE THREAD

**Issue by nerdpad** [restify/node-restify#1224]
Hi,

Is it possible to have one formatter that can handle any accept type that is not defined.

For Example:

```javascript
restify.createServer({
  formatters: {
    'application/json': () => {},
    // All other requests that come in are handled by this, instead of throwing error
    'application/every-thing-else': () => {}
  }
});
```

**Comment by DonutEspresso** [comment]
If the content-type can't be negotiated, it should fall back on application/octet-stream. You could use that as your default formatter for all unknown/dynamic types.

**Comment by DonutEspresso** [comment]
I believe you can also define a '*/*' formatter.

**Comment by NerdPad** [comment]
@DonutEspresso I will try your suggestion.
