### ISSUE TITLE
File Upload returns 405

### ISSUE THREAD

**Issue by geraldchecka** [restify/node-restify#1230]
Hi,
I've been trying to do a FileUpload using bodyparser with some defaults. It returns me a 405 despite having the method registered at compile time.

> Front-end code

    $(document).ready(function() {
      document
        .getElementById('fileinput')
        .addEventListener('change', function() {
          for (var i = 0; i<this.files.length; i++) {
            var file =  this.files[i];
            console.group("File "+i);
            console.log("name : " + file.name);
            console.log("size : " + file.size);
            console.log("type : " + file.type);
            console.log("date : " + file.lastModified);
            console.groupEnd();
          }
          // console.log(this.files[0]);
          uploadFile(this.files[0])
        }, false);

      function uploadFile(file) {
        var url = '/uploadMyFile';
        var xhr = new XMLHttpRequest();
        var fd = new FormData();
        xhr.open("POST", url, true);
        //xhr.setRequestHeader("Content-type", "multipart/form-data");
        xhr.onreadystatechange = function() {
            if (xhr.readyState == 4 && xhr.status == 200) {
                // Every thing ok, file uploaded
                console.log(xhr.responseText); // handle response.
            }
        };
        fd.append("upload_file", file);
        xhr.send(fd);
      }
    });`

> Restify code

```
var rs = require('restify');
var orchestrators = require('./orchestrators');
var db = require('./lib/database');
var config = require('./config/application.json');

// Server setup
var server = rs.createServer({
  name: "componentRepo",
  version: "1.0.0"
});
server.use(rs.acceptParser(server.acceptable));
server.use(rs.queryParser());
server.use(rs.bodyParser({
  // keepExtensions: true,
  // multiples: true,
  // hash: 'sha1',
  // uploadDir: config.resourceDIR,
  // overrideParams: false,
  // mapFiles: true,
  // mapParams: true
  maxBodySize: 2000,
  mapParams: true,
  mapFiles: false,
  overrideParams: false,
  multipartHandler: function(part) {
      part.on('data', function(data) {
        debugger;
        console.log("hello world");
        /* do something with the multipart data */
      });
  },
  multipartFileHandler: function(part) {
      part.on('data', function(data) {
        debugger;
        console.log("hello world");
        /* do something with the multipart file data */
      });
  },
  keepExtensions: false,
  uploadDir: './temp',
  multiples: true,
  hash: 'sha1'
}));

// CORS
server.use(rs.CORS());

server.on('MethodNotAllowed', function (request, response, cb) {
  console.log(request);
  console.log(response);
});

// Bootstrapping APIs
for(var orch in orchestrators) {
  var items = orchestrators[orch];
  for(var item in items) {
    var apis = items[item];
    for(var api in apis) {
      server[item](api, apis[api]);
    }
  }
}

// Initiate SQL connection
var connObj = db.connect();

server.listen(8080, function () {
  console.log('%s listening at http://localhost:8080', server.name);
});
```

> Handling Methods here

```
var services = require('../providers');

var API = {
  get: {},
  post: {
    '/uploadMyFile': uploadMyFile
  }
};

function uploadMyFile(req, res, next) {
  console.log(req.params);
  services
    .componentService
    .uploadFile(req.params)
    .then(function(response) {
      res.send(response);
    })
    .catch(function(error) {
      res.send(error);
    });
}
module.exports = API;
```

I'm not completely familiar with handling FileUpload in Restify though. Any help is appreciated.

Here is the screenshot from a test webpage.
![file_upload_test_and_components_orchestrator_js_ _componentrepo_2_and_componentrepo_2_ _node_middleware_middleware_js_ _122x31](https://cloud.githubusercontent.com/assets/5643210/20331150/84ce6328-abc9-11e6-854b-71c9fcd51e74.jpg)

**Comment by DonutEspresso** [comment]
I'm not sure what your `providers` file is, but you need to register a `server.post('/uploadMyFile', ...` somewhere or restify will not know where to route the request.

**Comment by geraldchecka** [comment]
@DonutEspresso  The providers file will contain some operations/logic to run whenever that API endpoint hits.

Server Configuration
```
var rs = require('restify');
var orchestrators = require('./orchestrators');

var server = rs.createServer({
  name: "componentRepo",
  version: "1.0.0"
});

for(var orch in orchestrators) {
  var items = orchestrators[orch];
  for(var item in items) {
    var apis = items[item];
    for(var api in apis) {
      server[item](api, apis[api]);
    }
  }
}
```
This is how I load all my API endpoints at the time of creating a server.

**Comment by DonutEspresso** [comment]
What's in the content of `orchestrators`? If you just hard code a `server.post('/uploadMyFile', ...`, does that work?

**Comment by yunong** [comment]
Closing, feel free to re-open if this is still an issue.
