### ISSUE TITLE
serveStatic – always redirect /directory to /directory/

### ISSUE THREAD

**Issue by ickata** [restify/node-restify#1232]
I have the following static server:

```
server.get( /^\/?^((?!api).)*$/, restify.serveStatic({
   directory   : 'www/',
   default     : 'index.html'
}) );
```

In the `www` directory I have sub-directories, each having `index.html`. The server always returns that index no matter how I enter the url: `http://localhost/subdirectory` (without end slash) or `http://localhost/subdirectory/` (with end slash). 

The problem is that my resources (scripts, css) are not loaded when I enter the first url. My paths are relative to the directory, and I want to keep them relative. Somehow the browser considers "subdirectory" as a file rather than directory, and this mess things up.

Any suggestions how to configure the static server to make sure that there is always slash at the end?

**Comment by oakfire** [comment]
Fortunately I only have one subdirectory , so I solve it by  `res.redirect`:
```
server.get('/docs', (req, res, next) => {
    res.redirect('/docs/', next);
});
```

**Comment by ickata** [comment]
Thanks for the idea. Fortunately I have only one level of sub-directories, and this did it:

```
server.get( /^\/[a-z]+$/, function ( req, res, next ) {
   res.redirect( req.url + '/', next );
});
```
