### ISSUE TITLE
Validating HMAC signature

### ISSUE THREAD

**Issue by bomb-on** [restify/node-restify#1252]
Hi!
I started to play around with Restify after a long pause with JS-development in general, so it might be that I'm missing something trivial here...
I have a client written in Python which is including HMAC-SHA256 signature in every request:

    # pseudo-code
    h = hmac.new(bytes(API_SECRET, 'utf-8'), b'', sha256)
    h.update(TIMESTAMP)
    h.update(request.body or b'')  # include request body for POST and empty string for GET requests
    signature = h.hexdigest()

On Python server, validation works fine for GET and POST requests (with correct credentials, of course), but trying out to validate POST with Restify every time results in different SHA256 string after trying to re-create the signature and therefore with 401 responses. However, requesting GET with the same body validates fine and results in 200.

The server code I am running looks like this:

```
var restify = require('restify');
var crypto = require('crypto');
var bufferEq = require('buffer-equal-constant-time');
var _ = require('lodash');

var fakeDb = {
    "Security": {
        "UseAuth": true,
        "UseACL": true,
        "AllowAnonymous": false,
        "Users": [
            {
                "name": "testuser",
                "role": "admin",
                "user": "testuser",
                "key": "xxwMXEqOGiY2TssVZ9hvOB4x6EVW3RW75hjAKEai4UBlxG0ts8Js8dsWOzDvAVq4"
            }
        ]
    }
}


var server = restify.createServer();
server.use(restify.acceptParser(server.acceptable));
server.use(restify.dateParser());
server.use(restify.queryParser());
server.use(restify.jsonp());
server.use(restify.gzipResponse());
server.use(restify.bodyParser());
server.use(restify.throttle({
    burst: 100,
    rate: 50,
    ip: true,
    overrides: {
        '192.168.1.1': {
            rate: 0,        // unlimited
            burst: 0
        }
    }
}));
server.use(restify.conditionalRequest());


server.use(function authenticate(req, res, next) {
    console.log('checking auth...');

    var dbUser = _.filter(fakeDb.Security.Users, {user: user}).pop();

    var user = req.headers.authorization.split(':')[0];
    var key = req.headers.authorization.split(':')[1];
    console.log(key);

    console.log(req.body);
    var checkSignature = crypto.createHmac('sha256', dbUser.key)
        .update(req.headers.timestamp)
        .update(JSON.stringify(req.body))  // PROBLEMATIC LINE (use req.body with GET requests)
        .digest('hex');

    console.log(checkSignature);
    if (!bufferEq(Buffer.from(checkSignature), Buffer.from(key))) {
        return next(new restify.UnauthorizedError('Authorization error.'));
    }

    return next();
});


function respond(req, res, next) {
    res.send('hello!');
    next();
}

server.get('/', respond);
server.post('/', respond);

server.listen(8080, function() {
    console.log('%s listening at %s', server.name, server.url);
});
```

Now, in the line marked as 'problematic' if I use `req.body` for GET requests this works fine because `req.body` is a JSON-formatted string. But if I send a POST request, `req.body` ends up as an object and so I tried to use `JSON.stringify(req.body)`. In this case, my validation always fails.

How should I handle request body in POST requests in order to re-create HMAC-SHA256 signature properly?

**Comment by DonutEspresso** [comment]
You should have access to the raw request body via `req.rawBody`. It could well be that the incoming string has been stringified differently (or using different formatting options). Give that a try and let us know if that works.

**Comment by bomb-on** [comment]
Well, I didn't have `rawBody` in my request for some reason, so I ended up constructing it "manually" like this:

```
server.use(function doTheBody(req, res, next) {
    req.body = '';
    req.on('data', function(data) {
        req.body += data;
    });
    req.on('end', function(data) {
        next();
    });
});
```

After that I could access `request.rawBody` in my `authenticate` function.
