### ISSUE TITLE
Restify support   multipart/form-data ??!!

### ISSUE THREAD

**Issue by tonyleen** [restify/node-restify#1253]

**Comment by tonyleen** [comment]
when i upload files(Content-Type:multipart/form-data), error occured
{
  "code": "BadRequestError",
  "message": "bad content-type header, no multipart boundary"
}

**Comment by DonutEspresso** [comment]
Hello, can you please share your server code and how you are making the request?

**Comment by yunong** [comment]
Closing for now. Feel free to reopen if you want to give us more context.

**Comment by tonyleen** [comment]
Sorry, i use a wrong 'content-type', it's my mistake.
