### ISSUE TITLE
Error starting restify server

### ISSUE THREAD

**Issue by albertoortiz** [restify/node-restify#1259]
node -v 7.3.0
npm -v 3.10.10
ARMv6-compatible
GNU/Linux 2.6.32

error: uncaughtException: The super constructor to "inherits" must not be null or undefined
file=/node_modules/spdy/lib/spdy.js, function=, line=20, method=null, native=false], stack=[TypeError: The super constructor to "inherits" must not be null or undefined,     at Object.exports.inherits (util.js:961:11),     at Object.<anonymous> (/node_modules/spdy/lib/spdy/connection.js:86:6),     at Module._compile (module.js:571:32),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3),     at Module.require (module.js:498:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/node_modules/spdy/lib/spdy.js:20:19)]

**Comment by kazmiekr** [comment]
What version of restify are you running? I think upgrading to  >= 4.1 should solve that problem. It did for me.  Looks like they had to bump the version of `spdy`

**Comment by albertoortiz** [comment]
thanks
