### ISSUE TITLE
Domain context lost on response from remote server

### ISSUE THREAD

**Issue by adami** [restify/node-restify#1260]
i'm using the domain already created by restify, per request, to store my own session data (i.e. process.domain.data = data).
i do that when starting to handle an incoming request, and later call (through http) a remote server. on the callback of the request to the remote server, i expect to still have the same context, but it is not always the case - sometimes it's OK, sometimes i find data belonging to a domain i used a few minutes ago, sometimes i keep getting the same 'old' domain data a few times.

since i'm using domains directly on another node (not using restify) and see no such problems there - is anyone aware of this issue or has any suggestions why this may happen?

**Comment by yunong** [comment]
It's not within the scope of the restify API for you to re-use the domain it creates. I would suggest creating your own domain. Also domains will be deprecated in the upcoming 5.x release.
