### ISSUE TITLE
Beta: async formatters incompatible with error handlers

### ISSUE THREAD

**Issue by cecchi** [restify/node-restify#1269]
When using async formatters in 5.x, it's required to provide a callback to `res.send`, but Restify internally calls `res.send` in a handful of places without a callback. For example, when using a global `restifyError` handler the following line causes an AssertionError any time that handler is triggered:

https://github.com/restify/node-restify/blob/5.x/lib/server.js#L948

I imagine the other cases where Restify uses `res.send` internally have the same issue.

Using 5.0.0-beta-2

**Comment by DonutEspresso** [comment]
Hi, can you take a look at this:
https://github.com/restify/node-restify/blob/5.x/4TO5GUIDE.md#sync-vs-async-formatters

I think that should resolve your problem - once 5.x goes live we'll definitely be very clear about these breaking changes up front.

**Comment by cecchi** [comment]
@DonutEspresso, I may be misinterpreting the documentation, but it's my understanding that the breaking change is that if I want to use an async formatter in 5.x I need to ensure I provide a callback any time I call `res.send`. Restify itself, however, does not follow this rule and blindly calls `res.send` without knowing whether all formatters are sync or not.

Perhaps an example of a valid async formatter would be useful? Using 5.0.0-beta-4.0, the following formatter throws an error after the response is sent, and the callback is not invoked (nothing is logged to the console):

```js
const restify = require('restify');

const server = restify.createServer({
    'formatters' : {
        'application/json' : function format(req, res, body, cb) {
            setTimeout(() => {
                cb(null, JSON.stringify(body));
            }, 1000);
        }
    }
});

server.get('/', function(req, res, next) {
    res.json({'hello' : 'world'}, function() {
        console.log('Response sent.');
        next();
    });
});

server.listen(4000);
```

**Comment by DonutEspresso** [comment]
Yes! That is definitely an issue, and why we are still in beta. :)  There are a number of places in core code (as you noticed) where async formatters are not yet first class.

**Comment by retrohacker** [comment]
Closing this in favor of #1347
