### ISSUE TITLE
Alter clock skew on restify.authorizationParser

### ISSUE THREAD

**Issue by RSpicer** [restify/node-restify#1270]
The current default clock skew on the authorizationParser() is 300s. However, I've found absolutely no way to alter or remove that clock skew, and I'm desperate for a solution. is this a tweak that's possible? If not, could it be added somehow?

**Comment by DonutEspresso** [comment]
Hello, are you talking about the date parser? That's the only plugin I see that has a harcoded value of 300. You should be able to pass in the clockskew as a parameter:

`server.use(date({myClockSkew}));`

**Comment by RSpicer** [comment]
Nope, talking about the authorizationParser. One of the errors I get running the parser is the following:

{ code: 'InvalidHeader',
  message: 'Authorization header invalid: clock skew of 313.587s was greater than 300s' }

Some of the code on this server I'm working on predates me, so I may be missing something... but I don't think so. No mention of the date parser (I looked in to that, as I saw what you saw) and the error is directly correlated to when we call the authorization parser.

**Comment by DonutEspresso** [comment]
I found it - the default is coming from [http-signature](https://github.com/joyent/node-http-signature). You should be able to override by passing an object option to the plugin that then passes that to http-signature:

https://github.com/restify/plugins/blob/master/lib/plugins/authorization.js#L133

**Comment by retrohacker** [comment]
This appears to have been resolved, closing.
