### ISSUE TITLE
In chain of handlers, not intercepted errors (from second handler and more)

### ISSUE THREAD

**Issue by KostyaTretyak** [restify/node-restify#1271]
If we [here](https://github.com/restify/plugins/blob/573513f9c871a2ededd25758072f5f8f3356b684/test/context.test.js#L89-L91) insert this:

```js
throw new Error('some error!');
```

error handler not intercepted this error, test will be pass.

Note that before the test handler has [this](https://github.com/restify/plugins/blob/573513f9c871a2ededd25758072f5f8f3356b684/test/context.test.js#L27-L30).

**Comment by KostyaTretyak** [comment]
Now I see that if we commented [first handler](https://github.com/restify/plugins/blob/573513f9c871a2ededd25758072f5f8f3356b684/test/context.test.js#L27-L30), all works as expected.

**Comment by DonutEspresso** [comment]
Hello, thanks for catching this. This is being addressed over in restify/plugins#88
