### ISSUE TITLE
server.url "undefined" on production server

### ISSUE THREAD

**Issue by McGern** [restify/node-restify#1274]
Hi,

My local server is returning http://[::] for server.url (I think because it was explained in a different issue that this is to do with IPv6), but on my production server (azure) server.url is returning http://undefined:undefined.

req.headers.host is returning the correct url, but I don't know how to get a request without hooking into "use" or something else like that. I am currently using a clunky method that gets the host on every request.

The reason that I want to know the host header is that I am using restify to also serve up static files to a chat bot (also using restify for the bot api endpoint) and it needs the full path to the files on it's own server.

Thanks,
Jarrod

**Comment by DonutEspresso** [comment]
Hello, what does `server.address()` give you?

`server.url` is a think wrapper over the core http server's `address()` method. That would help point us in the right direction.

**Comment by retrohacker** [comment]
Hey @McGern!

Thank you for taking the time to open this issue. It looks like additional information was requested back in February and we haven't received a response. I'm going to close this issue as stale for now but, if you are still having the problem, please read our new shiny [ISSUE_TEMPLATE.md](https://raw.githubusercontent.com/restify/node-restify/5.x/.github/ISSUE_TEMPLATE.md) and provide an update using the appropriate template so we can better help :heart: we would be happy to re-open this issue and help you debug this problem!
