### ISSUE TITLE
restify.serveStatic() doesn't work.

### ISSUE THREAD

**Issue by briannovillo** [restify/node-restify#1275]
Hi, I was trying to expose static files using restify.serveStatic() and I noticed that the serveStatic function only works in version 2.6.1, if it is changed in the package.json to another it will be seen that it does not work. I am doing something wrong?

I have created a repo on Github with my test project so that you can help me.

https://github.com/briannovillo/restify-serve-static-files-bug

Thank you in advance for your attention to this matter.

**Comment by joe-oli** [comment]
your url is http://localhost:8081/files/index.html 
restify is thus looking for a file /static/files/index.html , which you dont have available.
instead you put your file in /static/index.html, which is not going to work.

**Comment by briannovillo** [comment]
Hi @joe-oli, thanks for your response, but if you see the file app.js you will see that here is a regexp in server.get() to match all "files/*" patterns to a "static" folder.

app.js
```
var restify = require('restify');

var server = restify.createServer();

server.get(/\/files\/?.*/, restify.serveStatic({
    directory: './static'
}));

server.listen(8081, function () {
    console.log("App online on port: " + 8081);
});
```

**Comment by joe-oli** [comment]
Hey @briannillo here is an example of how restify works. (Refer to docs, don't assume anything).

 If you type any of the following url's in your browser
  localhost/files/index.html
  localhost/files/whatever/mary-popings.html
  localhost/files/anything-you-want/anything.html
  
  they will match the regex you have written, and thus all 3 will be handled by that particular route.
  
  Now that route says:
  prepend 'static' and look for corresponding files on your hard disk
  
Thus respectively, it will go looking for files in:
/static/files/index.html
/static/files/whatever/mary-popings.html
/static/files/anything-you-want/anything.html
 
Do you have files in the above locations??? Did you say no? Then how do you expect restify to find them :-)
 Hope this helps.
