### ISSUE TITLE
Website docs isn't up to date with NPM latest (4.3.0)

### ISSUE THREAD

**Issue by dwightgunning** [restify/node-restify#1279]
The restify.com website docs contains a small mistake. The mistake has been fixed in the [4.x branch](https://github.com/restify/node-restify/blob/4.x/docs/index.restdown) so it would seem it just hasn't ever been deployed to the site.

The small mistake I'm referring to is the section on Versioned Route. The response to the first example request is not `hello: mark` but rather `{"hello":"mark"}` as the subsequent paragraph on the website correctly describes. Not a big deal but since the website/docs don't explicitly reference a version, I was wondering whether there are other areas they're out of date.

I think the quick fix is probably for somebody responsible for the website to re-deploy from 4.x branch?

The mistake is also resolved in the 5.x-docs branch so if there's a release imminent then this can probably closed as a wont-fix.

PS - I initially mentioned this in a comment on #1058 and the advice was to raise an issue. I understand this is really trivial for long-time users but for people new to the project it creates some unnecessary friction.

**Comment by texaco** [comment]
I think it is alredy fixed.
I can see in http://restify.com/docs/home/ how the first response is 
```
$ curl -s localhost:8080/hello/mark
{"hello":"mark"}
```
