### ISSUE TITLE
node-uuid is deprecated

### ISSUE THREAD

**Issue by piorek** [restify/node-restify#1283]
While doing npm install im getting deprecation message

> npm WARN deprecated node-uuid@1.4.7: use uuid module instead

**Comment by fmauNeko** [comment]
Duplicate of #1233, already fixed in the 5.x branch.

**Comment by piorek** [comment]
So you are not planning to do it in 4.x?

**Comment by retrohacker** [comment]
This has been backported to both the 4.x and 5.x branches. Marking this as resolved for now :heart:

**Comment by piorek** [comment]
@retrohacker Thanks!
