### ISSUE TITLE
Website not up to date?

### ISSUE THREAD

**Issue by a0viedo** [restify/node-restify#1286]
I was reading http://restify.com/#response-api but couldn't find `res.headers`. In master [it's listed](https://github.com/restify/node-restify/blob/5.x/docs/pages/components/response.md) and the order slightly differs.

**Comment by DonutEspresso** [comment]
Hello, master is currently on the 5.x public beta branch, when it goes live we will update the docs to reflect the new version. 

You are right, It looks like `res.headers()` is not currently documented in the 4.x docs.
