### ISSUE TITLE
Restify server hangs for unsupported HTTP methods

### ISSUE THREAD

**Issue by meeque** [restify/node-restify#1287]
Restify server hangs indefinitely (until a general request timeout occurs, or, the client closes the connection) whenever a client requests an unsupported HTTP method. Consider the following curl commands:

    curl -X GET -D - http://localhost:8080/foo
    curl -X NI -D - http://localhost:8080/foo

The first one uses the legitimate GET method. If no routes are configured, Restify will respond with a 403 status. In contrast, the second one uses a bogus NI method, and Restify will let the request hang.

I tested that with a 4.3 Restify from NPM. To reproduce, you can use a minimal Restify Server instance, like the one attached.

For comparison, a vanilla node http server with similar setup will reply with an empty response immediately. See the other attachment, and the same curl commands as above.

**Comment by meeque** [comment]
Sorry, Github does not seem to like .js attachments, so I'll post the test code inline.

Minimal Restify Server:

    const restify = require('restify');
    restify.createServer().listen(8080, '127.0.0.1');

Minimal node http server:

    const http = require('http');
    const server = http.createServer((req, res) => {res.statusCode = 200; res.end();});
    server.listen(8080, '127.0.0.1');

**Comment by meeque** [comment]
Btw, it's not like the whole Restify server is hanging. It's just the requests that use bogus HTTP methods. 

I still wonder if this might be abused for DoS attacks. Closing the connection right away (like the node http server does) seems more secure. Responding with a 405 would be even better from a UX perspective.

**Comment by DonutEspresso** [comment]
Thank you for the report! It looks like in this case a bad http verb triggers a `clientError` event on the server. It is proxied through from the underlying http server in this case: 

```
server.on('clientError', function(err) { ... });

// err => { Error: Parse Error
       at Error (native) bytesParsed: 1, code: 'HPE_INVALID_METHOD' }
```

(from https://nodejs.org/api/http.html#http_event_clienterror)

It appears the proxying of the event itself (i.e., attaching a listener to clientError) prevents the underlying server from destroying the socke. If you listen to the `clientError` event in minimal server and do nothing, the socket remains open like it does with restify. 

That means It's up to the application owner right now to define the behavior upon receiving such a request, though I believe there is an argument here for a sane default. I'm not familiar with what errors get surfaced through the `clientError` event, but I think it's wholly reasonable to handle HPE_INVALID_METHOD and respond accordingly, in addition to threading that through to audit logs. 

cc @yunong @rajatkumar

**Comment by meeque** [comment]
Thanks for confirming! I had a quick glance at the source-code myself, but I wasn't able to get to the bottom of it. I had noticed though that not even a pre-handler would be invoked in case of unsupported HTTP methods. Your explanation seems to be in line with that observation:)

**Comment by meeque** [comment]
As suggested by @DonutEspresso, I added an appropriate error handler to my own application:

```
server.on(
            'clientError',
            (err, socket) =>
            {
                try
                {
                    if (err)
                    {
                        var status = 400;
                        var message = 'Unexpected error while receiving client\'s HTTP request.';

                        if (err.code === 'HPE_INVALID_METHOD')
                        {
                            status = 405;
                            message = 'Unsupported HTTP request method.';
                        }
                        var statusText = http.STATUS_CODES[status];
                        if (!statusText)
                        {
                            status = 500;
                            statusText = http.STATUS_CODES[status];
                            message = 'Internal server error while handling an error in the client\'s HTTP request.';
                        }
                        const errorEntity = JSON.stringify(createErrorEntity(err, status, message));
                        const contentLength = errorEntity.length;
                        // XXX what about multi-byte characters?

                        var response = 'HTTP/1.1 ' + status + ' ' + statusText + '\r\n';
                        response += 'Content-Type: application/json\r\n';
                        response += 'Content-Length: ' + contentLength + '\r\n';
                        // TODO add properly formatted date header
                        // response += 'Date: ' + '\r\n';
                        response += '\r\n';
                        response += errorEntity;

                        socket.write(
                                response,
                                'UTF-8',
                                () => socket.end()
                                );
                    }
                }
                catch (fatalErr)
                {
                    socket.end();
                }
            });
```

Works pretty well for the particular case, and my integration tests pass now. However, i assume there are much more HTTP parsing errors and connection problems that should be handled in a similar manner.

As you can see the code is rather cumbersome, as there is no response object available in the handler, and all headers have to be written manually. 

Feel free to adapt the code for restify!

**Comment by DonutEspresso** [comment]
Found this relevant issue in node core: https://github.com/nodejs/node/issues/7126

@meeque were you using node6+? The linked issue above seems to suggest that node4 cannot handle this gracefully.

**Comment by retrohacker** [comment]
@meeque it appears the proposed solution was to upgrade to Node v6. If this didn't solve your problem, please comment and we can revisit :heart:

Closing this as solved for now!
