### ISSUE TITLE
Where to find the release notes?

### ISSUE THREAD

**Issue by ShaharyarAhmed** [restify/node-restify#1289]
I am using version **4.1.1**. But now latest stable version is **4.3.0** so I was looking to read the release notes of that version but couldn't find them anywhere.

**Comment by DonutEspresso** [comment]
Hello - sorry about that. Master is 5.x, so all the 4.x release changelogs are on the 4.x branch here:
https://github.com/restify/node-restify/blob/4.x/CHANGES.md

**Comment by ShaharyarAhmed** [comment]
Thanks. Wouldn't it be better if you add notes when you make a release? It will be a lot easier for people looking for notes.

**Comment by DonutEspresso** [comment]
Hello, the missing changelogs from 4.x have been migrated to 5.x, so they are now available in the main branch. That should help ease the discoverability a bit. Thanks for the feedback!
