### ISSUE TITLE
.use() vs .pre()

### ISSUE THREAD

**Issue by jayesbe** [restify/node-restify#1291]
Starting off with Restify and setting up a very simple example. 

At the moment trying to use the bodyParser to fetch the rawBody. I have...

```
server.pre(plugins.bodyParser());
server.pre((req, res, next) => {
  console.log('1', req.rawBody);
  return next();
});

```

and 

```
server.use(plugins.bodyParser());
server.use((req, res, next) => {
  console.log('2', req.rawBody);
  return next();
});

```

I noticed that I get this

1 foo=1&bar=2

I'm trying to understand..  why is the use not even called ? 

I should mention.. that I don't have any routes defined at the moment.

**Comment by jayesbe** [comment]
ok so it seems that not only does 'use' require a route.. it requires a **matching** route.

If a route does NOT match a request.. the 'use' chain is not executed.

**Comment by DonutEspresso** [comment]
Thanks for the report, glad you got it sorted. You are spot on, `pre` is for any/all requests that the server receives, prior to any routing.
