### ISSUE TITLE
{"code":"InternalError","message":"Undefined token u"}, what does this mean?

### ISSUE THREAD

**Issue by locohost** [restify/node-restify#1299]
I'm using Angular2 for the client code. I have the Restify API on DigitalOcean MongoDb VM behind Nginx for SSL. GET works fine, POST does not. Can you see what I'm doing wrong in caps below?

Here is my full server code...

![restify api server](https://cloud.githubusercontent.com/assets/132458/24609857/55e0a1dc-184a-11e7-9311-983318161aca.PNG)

Here is my Player POST route...

![restify api post player](https://cloud.githubusercontent.com/assets/132458/24609876/6d05b10e-184a-11e7-9cd2-137b0abd1ab1.PNG)

Here is my Angular service addPlayer method...

![restify client addplayer](https://cloud.githubusercontent.com/assets/132458/24609901/86880a5a-184a-11e7-86fe-11e9d120dc20.PNG)

And finally here, is the Chrome/Postman app console output...

![cors_error_postman_console](https://cloud.githubusercontent.com/assets/132458/24609919/9ca151ac-184a-11e7-98c2-74b44366e1ea.PNG)

Thank you, thank you, thank you, thank you for any help. I've stalled completely on this error.

**Comment by DonutEspresso** [comment]
`Unexpected token u` looks like an error resulting from syntax errors. I suspect your `JSON.parse(req.params.player)` statement might be the culprit. I'd take a look at your server logs if you can, they should show you a stack trace along with what's happening when your server returns a 500.

**Comment by locohost** [comment]
Thank you for the reply. And your suspicion is right. I was JSON.parse'ing a non-string. It was already JSON.
