### ISSUE TITLE
Redirect functionality not implemented on Response class/object.

### ISSUE THREAD

**Issue by andrewstec** [restify/node-restify#1300]
The redirect functionality is listed on the API documentation on the Response object, but it is not actually implemented.

The redirect functionality is useful to implement as part of OAuth authentication with Passport. 

There is evidence of others having the same issue here: https://coderwall.com/p/arjzog/make-passport-work-with-restify-by-fixing-redirect-functionality-with-this-snippet

Thanks!

**Comment by trentm** [comment]
@andrewstec It seems to me it is implemented here: https://github.com/restify/node-restify/blob/4.x/lib/response.js#L270

Can you provide a code example showing it not working?

**Comment by andrewstec** [comment]
@trentm 

Thanks for checking. My mistake. 

After investigating this problem further, it turns out that typings for the TypeScript res.redirect method was not implemented. The compiler didn't pick it up. 

I'll contact the maker of the TypeScript and see if he would like to put it in there with a pull request.

Cheers.
