### ISSUE TITLE
problem shutting down restify server

### ISSUE THREAD

**Issue by AndrewKovalenko** [restify/node-restify#1303]
I try to shut down restify server on ctrl-c, and after I call `close` method - server keeps running.
Also, callback to a close method gets never called. 

```
const { createServer } = require('restify');
...
const httpServer = createServer();
...
const serverShutDown = () => {
  webSocketServer.stop();
  console.log(info('Try to shutdown HTTP server...'));

  httpServer.close(()=>{
    console.log(success('HTTP server is successfully shutdown.'));
  });

  watchMocksSubject && watchMocksSubject.dispose();
}

process.on('SIGINT', serverShutDown);

//catches uncaught exceptions
process.on('uncaughtException', (errorMessage)=>{
  console.log(error(errorMessage));
  serverShutDown();
});
```

**Comment by DonutEspresso** [comment]
restify's close method delegates to node core's [http.Server's close](https://nodejs.org/api/net.html#net_server_close_callback) method. `close` only keeps the server from accepting new connections, but it doesn't close existing connections. Any active connections or will keep the server up and running until they complete. 

If you want to force close existing client connections (which may or may not be a good idea depending on your use case) you can use something like [server-destroy](https://github.com/isaacs/server-destroy).
