### ISSUE TITLE
Q: Hide request/response data logged by auditLogger in 'after' event  

### ISSUE THREAD

**Issue by dublx** [restify/node-restify#1306]
Hi, 
I have a question, I'll explain the use case first: I want to log req & res bodies but I only want to do it for some HTTP methods or some routes (eg, dont need to log OPTIONS requests, or dont need to log my load balancer health checks), but, most importantly, I want to control what req/res data is logged, so I can remove personal identifiable data that the API handles.

Is there a way to decide (per request) whether to log the body in 'after' event, and hide request/response data that is logged? ... or maybe this should be done via bunyan if that is possible at all?

Thanks in advance!
Luis

**Comment by retrohacker** [comment]
Hey @dublx,

In v5 of the restify API, you can specify your own bunyan logger when creating a server via [`opts.log`](https://github.com/restify/node-restify/blob/5.x/lib/index.js#L32)

The default bunyan instance (used when you don't specify `opts.log`) uses the [these serializers](https://github.com/restify/node-restify/blob/5.x/lib/bunyan_helper.js#L203-L209)

You should be able to [specify your own serializers](https://github.com/trentm/node-bunyan#serializers) for these properties to intercept the `req` and `res` objects and do your scrubbing.

With this API, I could see a pretty nifty plugin for middleware-based log transformations being built in userland, i.e. a simple interface for regex matching on `req`/`res` properties to invoke middleware log transformations on specific routes. Essentially you could build a "restify-like" interface for scrubbing bunyan logs. This theoretical plugin would simply be passed into the `createServer` constructor as `opts.log`.

Anyways, it looks like restify exposes enough of an interface through bunyan to accomplish what you are trying to do, and there is certainly a lot of potential for community contribution in userland here! Hope this helps!

**Comment by dublx** [comment]
Great, thanks, ill give it a try.
