### ISSUE TITLE
Restify server not completing SYN-ACK sequence on Windows 10

### ISSUE THREAD

**Issue by vgriffin** [restify/node-restify#1307]
I'm running Windows 10 and want my REST server to be available across a network. For development, I've been testing with the client and server on the same machine, with No-IP redirects to allow external access through a redirect on my router. I've got appropriate permissions through Windows Firewall. My client-server interaction works fine if I configure the client to request access using the localhost access. It does not connect if I configure the client to use the No-IP address. I can do other things using the same No-IP address, pointing to other applications on my local machine.

LOTS of analysis, including Wireshark logging, showed my local machine receiving a SYN request without sending back a SYN-ACK response.

I have not tested access to another machine running on the same network.

The connection code is buried deeper than I could easily chase through to figure out what's happening. I tried creating a server that just uses the most current version of Express, without restify code. That code does connect, using either the local or No-IP address. I'm converting my application to not use restify for the server because I need to get it to work asap.

**Comment by retrohacker** [comment]
Hey @vgriffin,

Thank you for taking the time to dive so deeply into this bug, and for providing such a detailed report. We don't have a clear repro case (though it may be as simple as trying to host a service on a Windows machine?) and I personally don't have a Widows machine to test this on.

I'm marking this as `Unconfirmed` until one of the maintainers is able to reproduce this bug, and flagging it with `Help Wanted` with the hope that a community member with a Windows machine will be able to reproduce this and create a PR :heart:

**Comment by vgriffin** [comment]
You should probably be able to reproduce it by hosting something as a
restify server on a Windows 10 machine and connecting to it from another
network (or from something that pretends to be another network). You can
validate the client/server by running both sides on the same Windows 10
machine, which should work. As I noted, I didn't test the issue with
different machines on the same network. Wireshark really helped!

It could well be something you're calling to handle your connection process
instead of something actually in your code, probably some native code.
