### ISSUE TITLE
Unicode characters corrupted by serveStatic

### ISSUE THREAD

**Issue by NatalieWolfe** [restify/node-restify#1312]
Given a file with higher-order unicode characters embedded in it, `restify.serveStatic` will corrupt them when serving the file. Here is a very simple app that demonstrates this issue:

```js
var restify = require('restify')

var server = restify.createServer()
server.get('/', restify.serveStatic({
  directory: './',
  default: 'index.html'
}))
server.listen(8080)
```

```html
<!DOCTYPE html>
<html>
  <head>
    <title>µJ</title>
  </head>
  <body>
  </body>
</html>
```

OS: Mac OS 10.11, Node:6 docker container on Ubuntu 14.04.
Node: 4.8.0, 6.10.2, 6.0.0
Restify: 4.3.0

I've also attached this application demoing the issue, just `npm install && npm start` and then hit localhost:8080. When serving the same file with express there is no corruption (see localhost:8088 in the example app). Note that this happens regardless of express' inclusion, it is just there to demonstrate that the source file is not itself corrupted.

Here is a gif showing the corruption as demoed by the example app. Note that 8080 (restify) has a corrupted page title while 8088 (express) does not.
![unicode-corruption](https://cloud.githubusercontent.com/assets/466761/25242310/03a88cd8-25ae-11e7-9d86-28c3d7655423.gif)

[restify-example.tar.gz](https://github.com/restify/node-restify/files/944552/restify-example.tar.gz)

**Comment by NatalieWolfe** [comment]
Hmm... interestingly if I add `charSet: 'utf-8` to the serveStatic options this clears up, but I know this was not a problem at the beginning of the year when I last worked on this project. I'll see if I can narrow down the change to a specific version of `restify` or `mime`.

**Comment by retrohacker** [comment]
Hey @NatalieWolfe,

Thanks for pointing this out! Let us know if you track this down. For now, it looks like there is a clear solution which is to specify `charSet`. Closing this as resolved for now :heart:
