### ISSUE TITLE
server.url defaults to 169.254.0.1:0000

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1316]
Would it be cleaner to `return undefined`?

**Comment by yunong** [comment]
I believe this is a reserved IP address known as the "automatic private IP". It's used when the server is unable to get a DHCP address, which seems relevant if the server currently has no IP address. It makes sense for this use case.

**Comment by retrohacker** [comment]
Ah, roger that. Have never heard of this before.

This is probably a bike shed so I'll go ahead and close this issue. Going to document what I'm thinking in-case we need to revisit this in the future. (Someone may find their way here via google)

It sounds like `server.address` not returning a value means that the server hasn't bound to a port/address yet. Link local addresses appear to be designed to allow for services on the same link to find each other even if DHCP isn't working. In our case, it sounds like nothing will be able to discover our service since it isn't actually bound to anything, so assigning this address could be a bit misleading. Furthermore, it looks like these addresses aren't randomly self-assigned, they are picked from a pool and then checked across the local link for collisions to ensure it is unique. `undefined` would indicate that this service isn't reachable by any url, where as the 169.254.X.X address indicates it will be available to other devices on that local link.

Reference: https://en.wikipedia.org/wiki/Link-local_address#IPv4 (and the linked RFC)
