### ISSUE TITLE
sysdig support

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1323]
`dtrace` is wickedly cool, but support for the Linux kernel is lacking

The best available `dtrace` implementation for the Linux kernel can be found [here](https://github.com/dtrace4linux/linux) but I've had varying mileage so far using it, and it isn't packaged for any distribution I've seen. Solaris is relatively uncommon and, while BSD(like) systems are becoming more common in userland thanks to OSx, most people aren't shipping on BSD in production. Gnu/Linux (and Windows) contain most of the market share for servers on the internet ([source](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Public_servers_on_the_Internet)).

Outside of the raw popularity argument, Docker is becoming a pretty common building block for teams to get Node.js applications into production. Docker relies on the Linux kernel. It isn't uncommon for teams to do their local testing (and even development) in a Docker environment.

For what we are using `dtrace` for in the restify library, we could easily add `sysdig` [tracers](https://github.com/draios/sysdig/wiki/Tracers) support. The advantage of `sysdig` is that we won't need to add any dependencies, we just write tracers directly to `/dev/null`. A bonus is that `sysdig` has first class Docker support.

Alternatively, we could break both `dtrace` and `sysdig` out into plugins or userland modules and accept a `trace` option much like a `log` option. This would allow users to plug-in their own tracing logic, and would remove the native dtrace dependency. Making this a module would still allow restify to boast both `dtrace` and `strace` support!

**Comment by terencechow** [comment]
Is there any work or planned work for this ? As you said, the majority of ppl are probably running linux / docker linux in production so a major benefit of restify (i.e. dtrace) isnt available to those that would like it.

**Comment by retrohacker** [comment]
Nope, nothing planned or in progress. Though if you believe it is valuable and would be willing to implement (:heart:) I would be happy to talk though some designs with you :smile:

That being said, dtrace is actually a small part of the overall value of restify. We see more value from the bunyan logging for introspection.

**Comment by terencechow** [comment]
If you describe what you have in mind here maybe I can take a look at if when I have some free time, although I haven't really looked through the restify code base so I can't guarantee anything. At the least if you describe it here, if I don't pick it up, maybe someone else will be able to pick it up.

**Comment by retrohacker** [comment]
What I was thinking of was providing an API that allowed the user to pass in their own tracer. We would pull the existing dtrace implementation out into a module that could be required in and then create a module for sysdig that does the same.
