### ISSUE TITLE
Can Restify Work with Firebase auth?

### ISSUE THREAD

**Issue by MichelDiz** [restify/node-restify#1325]
Hi there!

I'm learning about Restify, Node, React, RN - Can we do that? integrate Firebase auth with Restify Easily?

My goal is to make an API where my users authenticate through an application in React Native. Meaning, my RN APP will consume the Node API data but in an authenticated way. In my React Native APP It will register users with Firebase auth and then it would give access to the Node API.

So, thanks! Best Regards.

**Comment by retrohacker** [comment]
Hey @MichelDiz,

I'm not sure I fully understand the question, but it sounds like you are wanting to make requests from a Node.js process (in this case, using restify, but that should be irrelevant) to the firebase API.

This is more a question for the Firebase team than the restify team, as it is regarding their API. Restify just provides routing, your clients can connect to your server and then your server runs any arbitrary logic that you code into it. If that logic contains API calls to firebase, than your restify server will work with firebase.

I would start here for working with firebase in Node.js, but again, this isn't my area of expertise. Firebase is a product, it would be worth reaching out to their support team: https://firebase.google.com/docs/admin/setup

**Comment by retrohacker** [comment]
Good luck on your project! It sound interesting :smile:

**Comment by MichelDiz** [comment]
Nice! Thanks man!
