### ISSUE TITLE
Update restify 4.x semver dependency to 5.x

### ISSUE THREAD

**Issue by bigZ-again** [restify/node-restify#1339]
# Feature Request
Update semver dependency to 5.x in restify 4.x.

## Use Case
In my project(use webpack), there are two library that depend semver. One is imap, another is  restify. But semver version conflict.
![image](https://cloud.githubusercontent.com/assets/15630922/25782665/c83b8844-3381-11e7-9237-c9b85bd09260.png)
![image](https://cloud.githubusercontent.com/assets/15630922/25782652/afc2884e-3381-11e7-8414-0ef2e9fb7d59.png)

## Call Stack
![image](https://cloud.githubusercontent.com/assets/15630922/25782788/bf155194-3383-11e7-9053-4536ec2c80aa.png)

![image](https://cloud.githubusercontent.com/assets/15630922/25782795/ded2293a-3383-11e7-9f78-b9f71907a137.png)
![image](https://cloud.githubusercontent.com/assets/15630922/25782804/faa982f2-3383-11e7-8dd6-95a4c4ab4c3e.png)
![image](https://cloud.githubusercontent.com/assets/15630922/25782816/18b9b85c-3384-11e7-9f9d-43ccc4c563ab.png)
![image](https://cloud.githubusercontent.com/assets/15630922/25782824/2ef4fa14-3384-11e7-947b-2c0f5869037b.png)

## Are you willing and able to implement this?
no

**Comment by bigZ-again** [comment]
After I comment all imap code(include `require(imap)`), the problem still exists.
And i find [Semver version conflict when using webpack #391](https://github.com/nomiddlename/log4js-node/issues/391) for reference.

**Comment by retrohacker** [comment]
Hey @bigZ-again,

I'm happy to help with this, and we def need to keep our packages up-to-date so will take a pass at this here soon.

I have a quick question that is related to your bug (but doesn't really prevent us from moving forward with the fix!). I'm not intimately familiar with webpack, but in Node.js land you should be able to use two separate versions of the same module in the same codebase without a problem. The main exception to this is when a module attempts to make itself a "singleton" like [the bitcore team does](https://github.com/bitpay/bitcore-lib/blob/master/index.js#L6-L16), but I don't believe the semver module does this.

Does webpack introduce a constraint on the modules forcing them to be globally unique?

The root of my question is that I don't understand why semver v4 and semver v5 can't live happily alongside one another in a webpack bundle, when this isn't a problem for Node.js and browserify.

I'm also interested in why restify is going into a webpack bundle ^_^

**Comment by retrohacker** [comment]
Taking a look at our deps, restify v5 is already using the latest version of semver.

v4 can use an update, but will be superseded by v5. I'm not up-to-speed on how releases are currently cut, so this may take a bit longer on my end. Will let you know when this is fixed!

**Comment by bigZ-again** [comment]
I must update my report. It should not be version conflict, because i have remove any other code, the problem still exist. And...

#### webpack bundle
Please refer mentioned previously. ( Semver version conflict when using webpack 391 & WEBPACK_AMD_DEFINE_FACTORY)
> the problem is caused because node-notifier uses semver version 4.1.0 and this appears to cause webpack to think it is an amd module and this causes webpack to insert the WEBPACK_AMD_DEFINE_FACTORY code. 

#### Why webpack? 
My project need access email, but there any solution that send IMAP from browser, so i need a special proxy, package IMAP + restify into Electron is my solution.

Thanks

**Comment by retrohacker** [comment]
Closing this as stale as we have shipped multiple major version releases since 4.x

If this is still a problem for users, please comment and we can revisit :heart:
