### ISSUE TITLE
Content from serveStatic corrupted by browser cache

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1340]
Migrated from: https://github.com/restify/plugins/issues/11

Are you still having this problem @jocull?

**Comment by jocull** [comment]
@retrohacker Sorry, the project that was previously having this issue was killed off awhile ago and I don't have an easy way to reproduce it now. It's probably safe to close unless someone else raises the issue again. Thanks for following up anyways! ❤️

**Comment by retrohacker** [comment]
Thanks for the follow up :smile:
