### ISSUE TITLE
Place throttle limits in response header

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1344]
Migrated from https://github.com/restify/plugins/issues/80

**Comment by eps1lon** [comment]
I did some work implementing this (which was pretty straight forward).

On which branch do you accept pull requests?

**Comment by retrohacker** [comment]
Hey @eps1lon,

Thanks for doing this :heart:! PRs should be opened against the latest major release, and backported if necessary. Currently, that is 5.x :smile:

**Comment by retrohacker** [comment]
Merged in https://github.com/restify/node-restify/pull/1453
