### ISSUE TITLE
Server constructor mutates global state

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1348]
- [ X ] Used appropriate template for the issue type
- [ X ] Searched both open and closed issues for duplicates of this issue
- [ X ] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version

5.x

## Node.js Version

All

## Expected behaviour

Constructor should only effect the object being instantiated

## Actual behaviour

Constructor effects all future server objects

## Cause

https://github.com/restify/node-restify/blob/5.x/lib/server.js#L306-L311

Since `PROXY_EVENTS` are shared between every instance of a restify server, and `upgrade` is added but never removed, all future instances of `Server` will have the `upgrade` event proxied.

## Are you willing and able to fix this?

Yes. It seems the  fix should be to make `PROXY_EVENTS` local.

**Comment by DonutEspresso** [comment]
Nice catch, code certainly reads like this is the case.

**Comment by DonutEspresso** [comment]
Fixed by #1661
