### ISSUE TITLE
Use deep copy instead of shallow copy

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1349]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request

We are currently creating a shallow copy of options objects passed into restify. It seems we are trying to protect against configuration values being changed after they are validated. In this case, it would be best to create a deep copy using a module such as [clone](https://www.npmjs.com/package/clone).

## Use Case

Fully protects against, what appears to be, the original intention of the code.

## Are you willing and able to implement this?

Yes :tada:

**Comment by retrohacker** [comment]
This would essentially revert https://github.com/restify/node-restify/pull/316

It looks like the original case for avoiding deep clones was to not copy the prototype. A deep clone appeared to effect the bunyan logger. Will take a closer look.

**Comment by DonutEspresso** [comment]
Ah, yes, I think deep clone won't work for any options that are not POJOs

**Comment by retrohacker** [comment]
Closing as it doesn't work for anything that isn't a POJO
