### ISSUE TITLE
Why do we support nested arrays of handlers?

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1350]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Question

https://github.com/restify/node-restify/blob/5.x/lib/server.js#L63-L99

The logic here appears to be adding a lot of complexity to support what appears to be a strange feature. I can't seem to find it documented anywhere, but it looks like you can pass in nested arrays of handlers and restify will unwind them for you. Do we know why this exists, and how common it is to use?

## Example API

```js
server.get('/', [ [ (req, res, next) => next(), [ (req, res, next) => next() ] ] ])
```

**Comment by DonutEspresso** [comment]
I don't have context on this - @yunong?

**Comment by retrohacker** [comment]
I've observed this used in the wild.

When constructing a route handler, modules may want to return an array of routes to register.
