### ISSUE TITLE
Reformat output

### ISSUE THREAD

**Issue by angelathewebdev** [restify/node-restify#1357]
I would like to reformat the output of the response as we wish to implement a different output structure. Which event is a suitable choice?

Currently, I'm rewriting error outputs by catching the `uncaughtException`, `InternalServer`, and `error` event. However, this seems rather inefficient (and because there is no catch-all event to handle errors in the next clause, I need to enumerate all of the event which is a bit tedious as well).

In addition, I have no idea how to obtain the output of handlers at the end of the handler chain (after running it through services and such), then format it.

Any input would be appreciated.

**Comment by retrohacker** [comment]
Hey @angelathewebdev,

Have you looked into using a custom formatter? The documentation around these could be much better, but you can see an example of how to use them here: http://restify.com/#content-negotiation

**Comment by angelathewebdev** [comment]
Thanks, I'll take a look into it.
