### ISSUE TITLE
 Does is possible listen unix sockets?

### ISSUE THREAD

**Issue by jvanz** [restify/node-restify#1361]
Hi guys,

A doubt... Does is possible listen unix sockets?

Thanks!

**Comment by retrohacker** [comment]
Hey @jvanz,

At the current point, I don't believe so. `this.server` is instantiated to be an instance of a plain old `http`/`https`/`spdy` server.

https://github.com/restify/node-restify/blob/5.x/lib/server.js#L281-L304

It doesn't appear that the code base affords a way to pass in your own object for `this.server`, so we are pretty much bound to how restify instantiates the server object. Allowing this to be passed in would be interesting though! We could convert this to a feature request if you would be interested in tackling it.

Closing this for now :smile: let me know if I missed something!

**Comment by retrohacker** [comment]
@friedemannsommer is correct :blush:

**Comment by jvanz** [comment]
Thanks guy, I'll do that!
