### ISSUE TITLE
Custom port on response redirect is ignored and take default port to 80

### ISSUE THREAD

**Issue by aguilarcarlos** [restify/node-restify#1362]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version
5.x and 4.x
## Node.js Version
v6.10.3
## Expected behaviour

According to the documentation [Response API](http://restify.com/#response-api), the method redirect accepts a explicit port in object passed as options. Here is the example in the documentation that I was following:
```
res.redirect({
  hostname: 'www.foo.com',
  pathname: '/bar',
  port: 80,                 // defaults to 80
  secure: true,             // sets https
  permanent: true,
  query: {
    a: 1
  }
}, next);  // => redirects to 301 https://www.foo.com/bar?a=1
```
User should be redirected to the hostname with custom port.
```
res.redirect({
  hostname: 'www.foo.com',
  pathname: '/bar',
  port: 3000,                 // defaults to 80
  secure: false,             // sets https
  permanent: true,
  query: {
    a: 1
  }
}, next); 
```
The above code should redirect to:
`http://www.foo.com:3000/bar?a=1`

## Actual behaviour
The above code take port 80 as default ignoring the opts.port:
`http://www.foo.com/bar?a=1`

## Repro case
To reproduce it use the following configuration:
```
res.redirect({
  hostname: 'www.foo.com',
  pathname: '/bar',
  port: 3000,
  secure: false,
  permanent: true,
  query: {
    a: 1
  }
}, next); 
```

## Cause

Even though this feature is included in the documentation, is not implemented in the code for that reason this is being ignored all the time.

## Are you willing and able to fix this?

Yes, I will create the proper PR for 4.x and 5.x to be reviewed.

**Comment by retrohacker** [comment]
Hey @aguilarcarlos!

Thank you for taking the time to open such a thorough bug report, and for including a PR against both branches with accompanying tests! This is fantastic work :heart:

Apologies for the delay in responding to this, I have been out of office for the past 2 weeks. Going to merge now :-)

**Comment by retrohacker** [comment]
Merged :smile:
