### ISSUE TITLE
node restify req.files undefined with header

### ISSUE THREAD

**Issue by vctt94** [restify/node-restify#1373]
when I define no header, my method works just fine:

```
uploadImage(req, res, next) {
    console.log(req.files)
    const {image} = req.files;
    imageBucketService.sendUploadToGCS(image).then(url=>{
      return controller.returnResponseSuccess(res,url)
    })
  }

```
But when I use headers, like 
 content-type: application/x-www-form-urlencoded

it does not work

**Comment by retrohacker** [comment]
Hi @vctt94,

I don't fully understand the problem you are encountering. Could you use the template that was provided when you opened your issue?

A clear and concise repro case that includes _only_ the code necessary to expose the bug would help us a lot. This example should stand alone and be able to be run with `node index.js`. Currently, your example has quite a bit of logic that is not relevant to restify and is missing the creation of the server and how you are registering the handler to it. We also don't know how you are setting the headers, it would help if you could provide the request either via a simple command like `curl` or through the repro case itself.

I'm going to close this for now until we have more context.
