### ISSUE TITLE
Minor Issue on Website sidebar 

### ISSUE THREAD

**Issue by melen** [restify/node-restify#1375]
# Bug Report

## Restify Version 
Website Issue http://restify.com/#request-api

## Expected behaviour

Clicking on Request API Highlights Request on the sidebar

## Actual behaviour

Highlights Response API instead

### Notes
Clicking Response Highlights DTrace, and DTrace stays on DTrace. Just a minor UI thing

**Comment by retrohacker** [comment]
Hey @melen!

Thanks for taking the time to open this issue :heart:

We are in the process of shipping a new doc site. It should come shortly after we unblock the 5.x release (hopefully soon :crossed_fingers:) so stay tuned :smile:
