### ISSUE TITLE
restify 5.0.0 bodyParser() not work

### ISSUE THREAD

**Issue by pangff** [restify/node-restify#1394]
# Bug Report

I make a post request  to restify server 5.0.0 . but cannot get body params in req.params

## Restify Version

- restify 5.0.0
- node v8.0.0

## Expected behaviour

with code blow:

> const restify = require('restify');
> const server = restify.createServer({
>     name: 'video-monitor-service',
>     version: '1.0.0'
> });
> server.use(restify.plugins.acceptParser(server.acceptable));
> server.use(restify.plugins.queryParser());
> server.use(restify.plugins.bodyParser());
> 
> server.post('/scene/video/report', function(req, res, next){
>     console.log(req.params)
> });
> 
> server.listen(3600, function() {
>     console.log('%s listening at %s', server.name, server.url);
> });

and make curl post request as blow:

> curl -X POST --data "data=xxx" http://localhost:3600/scene/video/report

I Expected get

> {data:xxx}

## Actual behaviour

I get req.parms an empty obj

> {}

something wrong with my code? and is a bug with restify 5.0.0

**Comment by wooiliang** [comment]
+1 It happens to me as well.

**Comment by igalep** [comment]
+1 , got the same error 
went back to 4.3.0

**Comment by jgliner** [comment]
Looks like it's been deprecated...
https://github.com/restify/node-restify/blob/5.x/4TO5GUIDE.md

They should draw more attention to this in their README.md. 5.0.0 breaks quite a few things.

**Comment by wooiliang** [comment]
It works, thank you @jgliner !
```
server.use(restify.plugins.queryParser({
    mapParams: true
}));
server.use(restify.plugins.bodyParser({
    mapParams: true
}));
```

**Comment by pangff** [comment]
It works, thank you @jgliner !

**Comment by kaiservonarctic** [comment]
That's all it took. Thanks @jgliner!!

**Comment by rsathishr** [comment]
![d0542c9ec210204c7c0126b614d01335c06f3ba345d1cb7f64 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/23234643/30475753-86ab35d6-9a25-11e7-9e2e-456cc3a6f2af.jpg)

Change the NODE-PATH

**Comment by rsathishr** [comment]
![image](https://user-images.githubusercontent.com/23234643/30475805-ac91ca08-9a25-11e7-88bb-3543f0142697.png)

**Comment by kozo002** [comment]
@jgliner thanks. you save my time
