### ISSUE TITLE
5.0.0 undocumented change: opts.event (string) is required

### ISSUE THREAD

**Issue by eddieajau** [restify/node-restify#1395]
* Restify Version: 5.0.0
* Node.js Version: 6.5.0

Just doing a migration to 5.x and came across this error. I'm just wondering if it needs to be listed in the migration guide? If so, could you sketch out quickly the difference between 'pre', 'routed', or 'after' and I'll be happy to make a PR to add it.

**Comment by retrohacker** [comment]
Hey @eddieajau,

We appreciate you being so active on the issues! We knew there would be some rough edges around the 5.0 release, and we really appreciate you helping us document them.

I actually don't have an answer for the question you are asking (I'm still pretty new to the restify codebase). I'll need to dive down into the codebase at some point to give a definitive answer. That being said, the JSDoc declarations in the codebase are pretty good. Doing a search for `prototype.pre` etc. may be enough to get the answers you are looking for :smile: Also, the new doc site may have some good stuff: https://restify.github.io/

I'm OOO for the 4th of July holiday. When I get back I'll try to spend a day catching up on issues. If there are enough hours in the day I'll get you the info you need :heart:

**Comment by DonutEspresso** [comment]
@yunong would you be able to shed some light on this?

**Comment by retrohacker** [comment]
Closed by #1518
