### ISSUE TITLE
Help with file upload

### ISSUE THREAD

**Issue by eddieajau** [restify/node-restify#1403]
Has anyone had any experience getting Restify to work with Multer to upload files? I'm totally stuck trying to get it to work. Thanks in advance.

Edit: Let me explain what I'm trying to do first. I have an existing ExpressJS microservice written by someone else. I am progressively migrating such services to Restify. It cobbled together a few bits and pieces to get it to "just work". The legacy service uploads files to AWS S3 using Multer atm. 

Now, Restify uses Formibable so the alternative question had anyone had any experience using that for uploading large files to S3?

**Comment by eddieajau** [comment]
Hrm, have to test this out but I suspect it would be to graft [this example](https://github.com/tsuz/node-formidable/blob/master/example/aws-s3.js) into the `multipartFileHandler` option, correct?

**Comment by souravdasslg** [comment]
I have made it work with multiparty. 
While you are working with file , make sure you use this
restify.createServer().use(restify.urlEncodedBodyParser())

**Comment by retrohacker** [comment]
Hey @eddieajau,

This is a bit outside of my domain knowledge in the project (I use restify for server->server RPC). I hope @souravdasslg's comment helped! Thank you for chiming in and helping @souravdasslg :heart:

Closing this as resolved for now. If this is still giving you problems, please comment and we can re-open and revisit.
