### ISSUE TITLE
restify serialize the restify-errors incorrectly

### ISSUE THREAD

**Issue by bbeyes** [restify/node-restify#1410]
# Bug Report

## Restify Version

5.0.0

## Node.js Version

6.10.0

## Expected behaviour

`{"code":"Conflict","message":"I just don't like you"}`

## Actual behaviour

`{"jse_shortmsg":"I just don't like you","jse_info":{},"message":"I just don't like you","body":{"code":"Conflict","message":"I just don't like you"},"restCode":"Conflict"}`

## Repro case

```js
var errs = require('restify-errors');

server.get('/', function(req, res, next) {
  return next(new errs.ConflictError("I just don't like you"));
});
```

## Cause

???????

## Are you willing and able to fix this?

> "Yes" or, if "no", what can current contributors do to help you create a PR?
> If this issue is unique, as the checklist you completed above suggests, then
> you are one of the few people who have encountered this bug in the wild.
> While contributors will often help work on issues out of the kindness of
> their hearts, its important to remember that you are the largest stakeholder
> in seeing this bug resolved as you are the one experiencing it. Kindness
> and contributions are what make Free Software go round, help pay it forward!

**Comment by retrohacker** [comment]
Hey @bbeyes!

Thank you for opening this issue and for providing a reproduction case :heart: I've marked this bug as 'unconfirmed' until a maintainer is able to reproduce the error.

**Comment by retrohacker** [comment]
Also, I've updated this issue to follow our template. Not all of the information was provided.

**Comment by DonutEspresso** [comment]
Hi @bbeyes, I was unable to repro this using the following:

```js
const restify = require('restify');
const errs = require('restify-errors');
const server = restify.createServer({ name: 'foo' });

server.get('/', function(req, res, next) {
  return next(new errs.ConflictError("I just don't like you"));
});

server.listen(3000);
```

```sh
$ curl localhost:3000
{"code":"Conflict","message":"I just don't like you"}
```

Could you verify if this works for you?

**Comment by bbeyes** [comment]
@DonutEspresso, thanks.  Using your case under **restify@5.0.0** + **restify-errors@3.1.0**, I got this:
```
$ curl localhost:3000
{"jse_shortmsg":"I just don't like you","jse_info":{},"message":"I just don't like you","body":{"code":"ConflictError","message":"I just don't like you"}}
```

But it works under **restify@5.0.0** + **restify-errors@4.3.0**.
