### ISSUE TITLE
restify.com should serve restify.github.io

### ISSUE THREAD

**Issue by hugodahl** [restify/node-restify#1412]
I was working through some of the sample code from [http://restify.com][], and after a while, some things didn't quite line up. It turns out that the docs on that site are out of date for the current version of Restify, but rather, the 2.0 version (per the page).

The [gh-pages][] branch of the [node-restify][] project should more than likely either:
* redirect to [restify.github.io][] (clean and simple, but perhaps "wastes" the domain)
* be kept in sync with the [restify.github.io][] project (sounds like begging for problems)
* obsoleted and serve the restify.com site from the same [restify.github.io][] project as the `github.io` page
* Call out that the restify.com site covers an older version, with a link to the current documentation page for the current version.

[gh-pages]: https://github.com/restify/node-restify/tree/gh-pages
[restify.github.io]: https://restify.github.io

**Comment by retrohacker** [comment]
Yes, restify.github.io is the official source of truth for the current release (5.x) of Node.js

I still need to migrate the restify.com domain over but I don't actually know who owns that? (cc:// @yunong @DonutEspresso @rajatkumar @micahr et. al?)

**Comment by yunong** [comment]
I think this can be closed now since restify.com has been migrated. 🎉

**Comment by hugodahl** [comment]
Awesome, and looking Spiffy!
