### ISSUE TITLE
Add "secureOptions" option to the Restify server creation

### ISSUE THREAD

**Issue by marc0l92** [restify/node-restify#1415]
# Feature Request

## Use Case

"secureOptions" is an _https_ library option that allows to specify some extra TLS configurations like block old version of the ssl protocol in order to increase the server security.

## Example API

The Node.js _https_ library allows several options during the server creation:
https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

These option are the one used by tls.createServer and tls.createSecureContext:
https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener
https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

This is the description of the new option that i ask you to add:

> secureOptions <number> Optionally affect the OpenSSL protocol behavior, which is not usually necessary. This should be used carefully if at all! Value is a numeric bitmask of the SSL_OP_* options from OpenSSL Options.

## Are you willing and able to implement this?

This new feature can be implemented adding this single line to the file lib/server.js at the line 282:

`secureOptions: options.secureOptions,`

**Comment by retrohacker** [comment]
Hey @marc0l92,

This sounds good to me! Submit a PR? I don't believe this needs a test, since we are passing through to the Node.js implementation.

@yunong @DonutEspresso @rajatkumar: in the spirit of forward compatibility, what are your thoughts on changing this line to be:

```
this.server = https.createServer(options)
```

**Comment by DonutEspresso** [comment]
That seems reasonable to me, though I might suggest something like removing the intersection of known restify related options and passing only the remaining options. I don't feel strongly to fight for it if nobody else cares, but I'm generally a fan of exposing and passing only relevant items to a particular API.

**Comment by hekike** [comment]
It's already implemented
