### ISSUE TITLE
Undocumented bodyParser options

### ISSUE THREAD

**Issue by simonepri** [restify/node-restify#1423]
- [ ] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

The `bodyParser` plugin has some options available that aren't documented.
https://github.com/restify/node-restify/blob/5.x/docs/api/plugins.md#bodyparser

This is the list:
```
// bodyParser
requestBodyOnGet: false

// jsonParser
reviver: false

// multipartParser (from formidable)
maxFieldsSize: 2 * 1024 * 1024
```

**Comment by hekike** [comment]
Thanks, closed by: https://github.com/restify/node-restify/pull/1469/files
