### ISSUE TITLE
Add examples of audit logs

### ISSUE THREAD

**Issue by simonepri** [restify/node-restify#1424]
- [ ] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

It's quite difficult to find detailed informations about the req and res object.
Maybe we can add some examples of values that users may be interested to log.

Eg:
```
server.on('after', (req, res, route, err) => {
  server.on('after', (req, res, route, err) => {
  const ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
  const date = req.date();
  const method = req.method.toUpperCase();
  const path = req.url;
  const httpv = req.httpVersion;
  const status = res.statusCode;
  const reqLen = Buffer.byteLength(JSON.stringify(req.body) || '');
  const resLen = Buffer.byteLength(JSON.stringify(res._body) || '');
  const ms = Math.floor(new Date() - req.date);

  console.log(ip, '['+date+']', method, path, httpv, status, '['+reqLen, '-', 'resLen+']', ms);
  //=> ::ffff:127.0.0.1 [2017-07-29T00:00:00.000Z] POST /users/auth HTTP/1.1 200 [52 - 724] 321
});
```

What do you think about that?

**Comment by retrohacker** [comment]
This looks awesome! Would be super handy to either put at the top of the [Request API](http://restify.com/docs/request-api/) page or to create a dedicate Examples document. Thank you for all of your help on the repo @simonepri!

`req.log` can be used to log via bunyan/pino instead of constructing your own `console.log` statements :smile:

**Comment by simonepri** [comment]
@retrohacker this is far from perfection. For instance will fail if req.body or res._body cause JSON.stringify to throw an error.

But the idea behind this example is that most of us really don't know witch information are really useful for logging purposes in production envs.

I hope we will be able to collect lots of suggestions from users!

**Comment by retrohacker** [comment]
Is this a deficiency in our JSDoc definitions for `Request`? Would it be worth enumerating the properties here: https://github.com/restify/node-restify/blob/5.x/lib/request.js#L1

What do type systems do today? I.E. typescript?

**Comment by simonepri** [comment]
This is a proposal of list of interesting things that we can document about request/response objects that users may need to access. Please comment if you have more!

## Request
- [ ] IP
_IP from where the request comes._
- [ ] Date
_Timestamp of when the socket for the client has been opened._
- [ ] Path and Method
_What resource the user asked for._
- [ ] Download time
_Time elapsed from the opening of the socket to the moment that datas are ready to be processed._
- [ ] Size of data received
_How much bandwidth we have consumed to receive that request. We may want to consider_
- [ ]

**Comment by simonepri** [comment]
This is a proposal of list of interesting things that we can document about request/response objects that users may need to access. Please comment if you have suggestions!
I will try to implement some of them in the following comments and then mark it as done on that list.

## Request
- [ ] Headers
- [ ] Body
- [ ] IP
_IP from where the request comes._
- [ ] Path and Method
_What resource the user asked for._
- [ ] Download time
_Time elapsed from the opening of the socket until the moment that datas are ready to be processed._
- [ ] Size of data received
_How much bandwidth we have consumed to receive that request. Sizes that we may be interested in:_
  * Byte of the URL
  * Byte of the headers
  * Byte of the body
  * Sum of all of them
Please let me know if are there any other data that is sent with an HTTP request that I've not took in consideration.
- [ ] Protocol and http version

## Response
- [ ] Headers
- [ ] Body
- [ ] Middleware time
_Time spent into middlewares:_
  * Before enter in our route
  * After our route is endend
- [ ] Route processing time
_Time spent in the user route logic._
- [ ] Size of data sent
_Same as request but for the response_
- [ ] Upload time
_Time elapsed from the end of processing until the closure of the socket. (For keep-alive connections until all datas are been sent)_
- [ ] Response time
_Time elapsed from the opening of the socket to his closure._

**Comment by simonepri** [comment]
### Request - Headers
Documented here:
http://restify.com/docs/request-api/#headerkey-defaultvalue

### Response - Headers
Documented here: 
http://restify.com/docs/response-api/#headerkey--value

**Comment by hekike** [comment]
@simonepri now we a little bit more example: https://github.com/restify/node-restify/blob/bde189cc025a904f330fa0df8ddd24189ebc4bf4/docs/_api/plugins.md#auditlogger
