### ISSUE TITLE
Passing data to a redirect

### ISSUE THREAD

**Issue by drekka** [restify/node-restify#143]
I'm trying to figure out how to pass data through a redirect. Is there an in memory data store I can use ie. session) ?

**Comment by marcellodesales** [comment]
Looking for the same... Sucks that there's no pointers provided... @mcavage

**Comment by fr-kshibata** [comment]
@drekka this might be outside of restify scope but you can pass context using either query, param or body
lets say for example you have `res.redirect('/test?a=test',next)`
you can access that in the next as 
`console.log(req.query.a) //test` 

also there is param and body
