### ISSUE TITLE
Use JSDoc for generating docs

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1430]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request

We have some pretty awesome JSDoc blocks in our code base, it would be nice if these were used to generate our API documentation.

## Use Case

> Why do you want this?

Remove duplication from our documentation and improve consistency when documenting our API

## Example API

> This should include code snippets and documentation for the proposed feature

`make prepush` should trigger compiling the JSDoc blocks into markdown files with jekyll headers.

## Are you willing and able to implement this?

> "Yes" or, if "no", what can current contributors do to help you create a PR?

Yes
-->

**Comment by retrohacker** [comment]
Hey @hekike :smile:

I saw you were working on some of our examples and docs today. Thought I ping you on this before you felt the pain :stuck_out_tongue: 

Currently we document everything in a minimum of 2 places in 2 different ways, at least one markdown file and a JSDoc. It would be super slick if our JSDoc specs would generate the files we need for our doc site, but I haven't had a chance to tackle that yet. Would be happy to partner on it if you would find it handy :smile:

**Comment by hekike** [comment]
Hi @retrohacker,

yes, sure! It's a good idea.
I'm going to look around for solutions that could fit for our need.
I'll ping you when I found something.

**Comment by hekike** [comment]
@retrohacker I opened a WIP PR with a proposal:
https://github.com/restify/node-restify/pull/1495

Actually, it requires tons of work to move examples to JSDoc.

Please let me know what do you think.

**Comment by hekike** [comment]
@retrohacker please update https://github.com/restify/restify.github.io
I've no permission to do that, from now all of the docs are auto-generated from JSDoc :)
