### ISSUE TITLE
Add express style parameter regular expression handling

### ISSUE THREAD

**Issue by stevehipwell** [restify/node-restify#1433]
# Feature Request

Adding *Express* style parameter regular expression handling, such as `/test/:id([a-f\d]{24})` and `/test/:num(\d+)`, to *Restify* would make working with paramaters in _Restify_ a much nicer experience.  In addition it would enable _Restify_ to handle the shared middleware scenarios that it cannot currently support due to parameters being unnamed and an array when regular expressions are used.

## Use Case

A nested scenario.

```typescript
const idMiddleware = (req, res, next) => {
  const obj = service.getObjById(req.params.id);
});

const numMiddleware = (req, res, next) => {
  const obj = service.getObjByNum(req.params.num);
});

server.get("/test:id([a-f\d]{24})", idMiddleware);
server.get("/test:num(\d+)", numMiddleware);

server.get("/parent:parentId/test:id([a-f\d]{24})", idMiddleware);
server.get("/parent:parentId/test:num(\d+)", numMiddleware);
```

A custom middleware scenario.

```typescript
function getMiddleware(parmasPath, objPath) {
  return (req, res, next) => {
    const obj = service.getObjById(req.params[paramsPath]);
    const value = obj[objPath];
  });
}

server.get("/test:id([a-f\d]{24})", getMiddleware("id", "id"));
server.get("/test:num(\d+)", getMiddleware("num", "numericId"));
```

## Example API

You can use regular expressions to validate parameters by including the regular expression in brackets after the parameter name. The pattern `/test:id(\d+)` will match the url **/test/8** and `res.params.id` will be **8**; however the url **/test/hello** will not match.

## Are you willing and able to implement this?

I'm willing to help implement this if I can be pointed in the right direction.

**Comment by retrohacker** [comment]
Yes! This would be amazing :heart:

We have a feature request asking for this here https://github.com/restify/node-restify/issues/1292

I believe the current proposal is to use `path-to-regexp`

**Comment by stevehipwell** [comment]
@retrohacker - Is there some developer documentation?

**Comment by hekike** [comment]
Restify 7.x router is wildcard based, please see migration guide.
