### ISSUE TITLE
resify latest version update 5.0.1 from 4.3.1 is causing proble

### ISSUE THREAD

**Issue by nnarender** [restify/node-restify#1434]
{ Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.writeHead [as _writeHead] (_http_server.js:180:21)
    at ServerResponse.writeHead [as writeHead]

**Comment by retrohacker** [comment]
Hey @nnarender,

I recently changed the way we send headers, but not in a way that should have affected this. Could you provide a few things to help us track this down:

1) A clean and concise repro case
2) The version of Node.js you are using

If you want to try tracking down the problem, headers should only be flushed on [this line](https://github.com/restify/node-restify/blob/5.x/lib/response.js#L337) from my understanding. Adding a `console.log` statement above line 337 may help you track down what is going on.

**Comment by nnarender** [comment]
Node version i am using v6.11.0

**Comment by nnarender** [comment]
@retrohacker

**Comment by nnarender** [comment]
**Install the module with:    npm install restify-plugins*** 

**and below you can find the code for latest restify version 5.0.1**

***var restifyBodyParser = require('restify-plugins').bodyParser,
    restifyAcceptParser = require('restify-plugins').acceptParser,
    restifyQueryParser = require('restify-plugins').queryParser,
    restifyFullResponse = require('restify-plugins').fullResponse;



var server = restify.createServer({

    name: 'xxxxxx(your choice)',
    version: 'xxxxx(your own version)'
});

server.use(restifyAcceptParser(httpServer.acceptable));
server.use(require('restify-plugins').authorizationParser());
server.use(require('restify-plugins').queryParser());
server.use(require('restify-plugins').bodyParser());
server.use(auth.basicAuth);

server.use(restifyQueryParser({ mapParams: true }));
server.use(restifyFullResponse()); ***

**Comment by retrohacker** [comment]
`require('restify-plugins')` has been deprecated. Have you tried with `restify.plugins`

**Comment by retrohacker** [comment]
https://github.com/restify/plugins/issues/108 just finished this, should help moving forward :smile:

**Comment by retrohacker** [comment]
> the above code solved my issue

Just to clarify, your issue has been resolved?

**Comment by nnarender** [comment]
Yeah issue has been resolved
