### ISSUE TITLE
Merge 5.x down to master

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#1448]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request

Not really a feature, but we should merge 5.x down to master now that 5.x is the mainline. master is probably super out of date - I'm not sure it even has 4.x latest...!

**Comment by kwhitley** [comment]
Second this request, along with an NPM publish (afterwards) - I've got people waiting very eagerly for the fixes merged into 5.x this week!

Cheers all!

**Comment by retrohacker** [comment]
As opposed to merging, I'm just going to point master to the head of the 5.x branch and leave the current head dangling. 5.x is the desired state, master doesn't have anything we need from my understanding.

**Comment by retrohacker** [comment]
Will ship ASAP @kwhitley sorry for the delay.

Ideally CI/CD will automate this in the near future removing humans from the loop :wink:

**Comment by kwhitley** [comment]
Sounds good @retrohacker - totally understand re. CI/CD!  It's the holy grail we chase, but I'm not there yet either :)

**Comment by kwhitley** [comment]
@retrohacker - I notice the package.json reflects an older version (5.0.1) in the 5.x branch  - just a heads up before trying to publish something to NPM!

**Comment by retrohacker** [comment]
Done :smile:

@kwhitley 5.2.0 should have the changes you need :heart:

**Comment by kwhitley** [comment]
@retrohacker Thanks so much! 🍾 ✌️ 🍾  My restify folks will be stoked, as well as everyone else!  All tests pass and node support continues on to 8 without breaking restify! :)


Thanks to all involved for sure!
