### ISSUE TITLE
restify digital meetup

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1450]
Hey all!

A few people have asked to get the maintainers together so we can align on project goals.

So I propose....

### :tada: The first restify meetup :tada:

Anyone who wants to participate is welcome to join!

We can do this any way we want on any time line that works with the community. Some ideas to kick off the conversation:

1. Setup a temporary Slack/IRC/etc we can all join
2. Hangouts on Air
3. Mage summing circle

Whatever we choose to do, I want to make sure it is recorded/documented so we can share it back with the community here for those who can't join and I want to make sure it is as inclusive as possible. I.E. meeting in person is off the table because it will significantly limit the number of people who can attend, unless we go with the summoning circle, then we just need to make sure we can get people back home safely.

We can try to do this in the next couple weeks if that gives everyone enough time. Look forward to meeting with everyone! :heart:

**Comment by retrohacker** [comment]
// CC: @DonutEspresso @gergelyke @hetul @jclulow @mcavage @micahr @montmanu @rajatkumar @sean3z @trentm @yunong

**Comment by sean3z** [comment]
w00t! Let's make it happen! 🎉

**Comment by jclulow** [comment]
Let's not use Slack.

**Comment by simonepri** [comment]
❤️ reaction to this comment to say that you are willing to participate.

**Comment by DonutEspresso** [comment]
Love the idea. Would prefer a hangout or similar a/v, maybe it's just me but discussing nuanced/complex topics over chat with a large group of folks seems inefficient.
