### ISSUE TITLE
plugins.pre.sanitizePath removes slashes from GET variables also

### ISSUE THREAD

**Issue by ed-g** [restify/node-restify#1455]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version

5.2.0

## Node.js Version

6.11.1

## Expected behaviour

I would hope that slashes are deduplicated in the path portion of the URI but that GET variables would not be modified.

## Actual behaviour

Slashes in GET variables get eaten.

## Repro case

```javascript
var fetch   = require('node-fetch');
var restify = require('restify');

var server = restify.createServer({
  name: 'sanitize-url-repro',
});

server.use(restify.plugins.queryParser({ mapParams: true }))
server.pre(restify.plugins.pre.sanitizePath())

server.get('/path/to/echo', function (req, res, next) { 
    res.send( req.params.foo );
})

server.listen ( 8080, 'localhost');

fetch("http://localhost:8080//path/to////////echo?foo=bar")
.then( (res) => (res.text()) ) 
.then( function (text) {
    console.log('text should be "bar":')
    console.log(text)
})
.then(() => fetch("http://localhost:8080//path/to////////echo?foo=b////ar"))
.then( (res) => (res.text()) ) 
.then( function (text) {
    console.log('text should be "b////ar" with four slashes:')
    console.log(text)
})
```

## Cause

https://github.com/restify/node-restify/blob/6d83fb3ef84fbddca11238d0f9047ecf57904d0d/lib/plugins/pre/prePath.js#L15

I think that strip() should simply copy the variables portion of the URI after the path.

## Are you willing and able to fix this?

I'm willing to fix, but I'm not too familiar with edge cases in URI handling.

**Comment by retrohacker** [comment]
Hey @ed-g,

Thank you for taking the time to open this bug report and for using our template :heart:

I definitely agree with you, stripping slashes from variables is surprising.

It looks like we should be parsing the request doing something like `require('url').parse(req.url)` to break it into it's components before stripping the pathname of duplicate slashes.

I'm :+1: on a PR :smile:

**Comment by DonutEspresso** [comment]
Thanks for the report! I think we reviewed this exact issue over in #1262. While surprising this does conform to the RFC. I would recommend having your issuing client(s) encode their query parameters.

**Comment by ed-g** [comment]
@DonutEspresso that all makes sense.

In the mean time I've created this work around, maybe others will find it useful:

```javascript
const url_library = require('url');
function sanitizePathButNotQueryString (req, res, next) {
    let parsed  = url_library.parse(req.url)
    req.url = parsed.pathname.replace(/\/+/g, '/') + parsed.search
    next()
}
```
