### ISSUE TITLE
Restify Error handler and Content-Type: (text or html) broken

### ISSUE THREAD

**Issue by NathanaelA** [restify/node-restify#1456]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report
If you add a static server, and you attempt to get a resource that doesn't exist; it throws a `ResourceNotFound` error, if you attempt in your `ResourceNotFound` error handler to use `res.setHeader('Content-Type', 'text/html');`  Chrome will show it as a bad response of 0 bytes. 

## Restify Version
5.0.1

## Node.js Version
v6.9.4

## Expected behaviour
My goal is on a StaticServer ResourceNotFound to serve a HTML page; the current error handler you can add a function toJSON to override the results and return a string; however when you do so; it encapsulates the result in a quote (") string (the default of the json content type).   So the next step in getting this plan working is to return the proper ContentType.  When you attempt to return plain/text or text/html, it fails weirdly.  The partial data returned is discarded according to wget; and the header is application/octet-stream.    Chrome throws a invalid response and the debug tools show 0k returned, and no return headers (so it is like the entire packet is corrupt).

## Actual behaviour

Browser throws a browser error about invalid response.

## Repro case

```
const restify = require('restify');
let server = restify.createServer();
server.use(restify.plugins.acceptParser(server.acceptable));
server.use(restify.plugins.bodyParser({mapParams: false}));
server.use(restify.plugins.authorizationParser());
server.use(restify.plugins.queryParser());

let serveData = restify.plugins.serveStatic({
	directory: '../static',
	default: 'index.html',
	maxAge: 1
});
server.get(/\/static\/.*/, serveData);
server.on('ResourceNotFound', errorRedirect);

function errorRedirect(req, res, error, next) {
    res.setHeader('Content-Type', 'text/html');
    error.statusCode = 404;
    error.toJSON = function customToJSON() {
        return "<html>I'm <b>html</b> data</html>";
    };
    next();
}
```

## Cause

Setting the header seems to cause the wrong data path to be ran is my assumption.   Attempting to debug; it does show the .toJSON being called and content-length and data being put on the wire.  But continuing to debug gets really confusing after that point.   I suspect the data is getting put on the wire twice once from the normal path and once in the error handling path causing the length and content-type to get messed up.

## Are you willing and able to fix this?

Not sure; time is extremely limited right now.

**Comment by DonutEspresso** [comment]
Hi @NathanaelA, thank you for the bug report! It seems some of our server documentation has gone mysteriously missing, including the documentation about formatters.

For each type of content-type you want to send, you'll have to add a formatter. Formatters are how restify knows how to format specific content-types. This would resolve the application/octet-stream issue you are seeing:

```js
let server = restify.createServer({
    formatters: {
        'text/html': function(req, res, body) {
            // body is whatever was passed to res.send() - in the case of html, it usually is already an 
            // html string. In the case of errors, like your 404, you will get a NotFoundError here. you can
            // choose to implement a toString() on your error object, and this formatter function would
            // send back the html. you could alternatively check if body here is an error and do the 
            // appropriate thing as well. 
            return body.toString();
        }
    }
});

server.on('NotFound', errorRedirect);
function errorRedirect(req, res, error, next) {
    res.setHeader('Content-Type', 'text/html');
    error.statusCode = 404;
    error.toString = function customToJSON() {
        return "<html>I'm <b>html</b> data</html>";
    };
    // this error object is what will be passed to your formatter
    next();
}
```

This has brought up a few gaps in the documentation - will look to address these soon!

**Comment by NathanaelA** [comment]
Thank you that solved my issue!

**Comment by anotherhale** [comment]
Has this been addressed in the Docs?  I could not find it - even with a google search. I just started to look through Issues to see if someone else had reported and came across this Issue.
This did resolve my issue and it would be good if it was documented.
