### ISSUE TITLE
Passing variables to next handler

### ISSUE THREAD

**Issue by BryceJech-OSUF** [restify/node-restify#1457]
## Question
What is the best practice for passing variables to the next handler(s)?

In Express, best practice is to attach variables for the next handler as properties on the res.locals object where they are "scoped to the request, and therefore available only to the view(s) rendered during that request / response cycle (if any)"

[Express res.locals](http://expressjs.com/en/api.html#res.locals)

It doesn't seem as though restify creates this object on the response; so I'm wondering if there is some other restify specific best practice or if I should just create an empty object on res.locals earlier on in my server setup or do something entirely different altogether such as adding my own props to the response object directly.

Thanks!

**Comment by BryceJech-OSUF** [comment]
To elaborate, what I'm looking to achieve is something like this:

```js

function validateToken(req, res, next){
    // do token validation
    if(success){
        res.locals.token = token;
        return next();
    }
    else{
        res.send(401);
        return next(false);
    }
}

function validateUser(group){
    // group is a string containing the name of an Active Directory group
    // Need to grab the guid off the token and use that to identify user

    return function(req, res, next){
        if(!res.locals.token){
            res.send(401);
            return next(false);
        }
        let guid = res.locals.token.guid;

        memberOf(guid, group)
            .then((isMemberOf) => {
                if(isMemberOf){
                    return next();
                }
                else{
                    res.send(401);
                    return next(false);
                }
            })
            .catch((err) => {
                res.send(500);
                return next(false);
            });
    }
}

// This way I can apply these handlers depending on whether I need
// authentication or authentication + authorization

// Authentication only
server.post('/route1', [validateToken, routeHandler]);

// Authentication + Authorization
server.post('/route2', [validateToken, validateUser('adminGroup'), routeHandler]);

```

**Comment by DonutEspresso** [comment]
Hi @BryceJech-OSUF, we are actively working on the [documentation](http://restify.com/docs/plugins-api/) to make this easier to discover, but there is a plugin called `plugins.context()` that helps you with this:

```js
server.use(restify.plugins.context());

server.get('/', [
  function one(req, res, next) {
    req.set('foo', 'bar');
    return next();
  },
  function two(req, res, next) {
    res.send(req.get('foo')); // => 'bar'
    return next();
  }
]);
```

The context plugin will store any value you give it in a closure specific to that request. If you try to set an existing key, it will stomp over the existing value.

**Comment by BryceJech-OSUF** [comment]
@DonutEspresso thanks for the info! Do you know what version of restify this appears in? I'm using 5.0.1 and `restify.plugins.context` is undefined. I do see a context method on `restify.plugins.pre`, not sure if related tho.

**Comment by DonutEspresso** [comment]
Oops, yes, the context plugin can be found on `restify.plugins.pre.context()`. 👍

**Comment by BryceJech-OSUF** [comment]
Excellent. Thanks @DonutEspresso, I appreciate it!

**Comment by DonutEspresso** [comment]
No problem! Closing for now - please let us know if you run into other issues.
