### ISSUE TITLE
restify documentation headings are perhaps a touch oversized

### ISSUE THREAD

**Issue by jclulow** [restify/node-restify#1458]
The documentation on `restify.com`, e.g., http://restify.com/docs/server-api/, appears to have been styled with headings that are _very_ large.

![large](https://user-images.githubusercontent.com/304070/29591307-dc0da5c6-8752-11e7-86ba-ba40dd6c720b.png)

The headings should really be much closer to the size of the prose.  For an example of something that would probably be better, see the Node documentation [on Streams](https://nodejs.org/dist/v0.12.15/docs/api/stream.html).

**Comment by hekike** [comment]
I guess it's fixed now.
