### ISSUE TITLE
restify documentation appears to be missing HTTP verb methods

### ISSUE THREAD

**Issue by jclulow** [restify/node-restify#1459]
I was reading the Restify server documentation, i.e., http://restify.com/docs/server-api/, and it seems that the route handler mounting methods (e.g., `.get()`, `.post()`, etc) are completely missing from the server API documentation.  They are covered to some extent in the _Getting Started_ section, but appear to be absent entirely from the reference portion of the documentation.

**Comment by hekike** [comment]
Fixed by JSDoc based docs generation.
