### ISSUE TITLE
avoid duplicate stack-traces in log output when log level is "trace" 

### ISSUE THREAD

**Issue by iamjochem** [restify/node-restify#1493]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request (sort of)

TBH I don't think this is a Feature Request nor is it really a Bug, mostly it is an observation of an annoyance my collegues and I face when debugging/developing (in the context of using/setting bunyan's log level to "trace")

When restify handles an error and log-level is "trace" the stack-trace of every error is logged at least twice, due to the log.trace() statements in the following files:

- `restify/lib/server.js` at or around **line 836**
- `restify/lib/response.js` at or around **line 302**

When one uses the "audit" plugin the complete stack-trace of each error is output another time.

## Use Case

> Why do you want this?

During debugging/development sessions using log-level trace is often warranted (aside: in our case we use bunyan everywhere and `restify` is merely a single component that consumes our instance) 

I'd like to avoid the duplicate stack-traces so that it is less painful to grok what is being output to the console (or any other output stream bunyan might be configured with)

## Are you willing and able to implement this?

Yes, if you can help decide the how & the what!

I think a discussion is needed as to whether it is even smart to change the behaviour,
additionally I am observing the behavior in v4 (I have no experience with v5 ... it is quite possible that the issue is not relevant anymore).

My first suggestion would be remove the error object from the `log.trace()` data in `server.js` and let only the `log.trace()` call in `response.js` include it.

I'm not sure how to tackle the duplicate stack-trace output generated by the audit plugin - in order to do that there would seem to be a requirement that the log.trace() logic in various places would need to be aware of the fact that the audit plugin is active ... something which feels rather "dirty".

Maybe the best & simplest solution would be to simply not include the error in any `log.trace()` calls? some of the `log.trace()` calls already include info about the Error type in the generated message (maybe that is enough for trace logging?) e.g.:

 ```js
    log.trace({err: arg, errName: errName}, 'next(err=%s)', (arg.name || 'Error'));
``` 

I'd love to hear your opinion on this!

**Comment by DonutEspresso** [comment]
Hey @iamjochem, thanks for the report! I feel your pain - there is a not so dissimilar ergonomics problem with the request capture stream as well, where log records can get duplicated, and it gets even messier when trace is on. 

I am generally in agreement with your proposal - get rid of the trace call in `server.js` but leave the one in `response.js`. With the audit log its a little less clear, as it's a completely different component. One option might be to wrap the audit log invocation:

```js
const auditLoggerPlugin = restify.plugins.auditLogger({
    log: log.child({
        component: 'audit'
    })
});

server.on('after', function(req, res, route, err) {
    if (req.log.level() === 10) {
        auditLoggerPlugin();
    }
});
```

However, I wouldn't recommend doing this for production, where you likely want the audit logger to always be in place. Another option might be to use bunyan to filter out any audit logs with an `err` field:
```sh
$ node myProcess.js | bunyan -c "(this.audit === true && this.err) === false"
```

Understandably, none of these are great options - but bunyan does give you some facilities to easily strip out things based on message or otherwise - and that might allow you to easily craft some fine grained filters to remove the specific things that are causing additional noise. Let me know if that gives you some ideas!

**Comment by iamjochem** [comment]
hi @DonutEspresso,
 
thanks for your feedback. do you recommend I make a little PR for the changes to the relevant "trace log" calls?

with regard to the auditLogger - I agree with you that it's not clear at all (and my feeling is that it is probably best not to try doing anything [clever] with it). your first option wont work for me because I actually want to see the `response` log ... and I agree that messing around with it is not really desirable due to the risk of inadvertently turning it off in production.

with regard to the second option, this is definitely powerful and allows endless filtering. but herein lies a number of "problems" for me:

1. it's unwieldy and + the last thing you want during development and you are debugging errors is to stop and figure out a "tricky" set of command line args for filtering console output ... it breaks the flow somewhat (I can't get the options/parameters into muscle-memory so I find myself having to RTFM everytime).
2. one could have the such filters in place by default, but I feel like that is a bad idea because of the risk of structurally filtering out items that might be important.

there is also the complication of the `debug` module ... *lots* of modules use it (I use it in our own code too) ... having the `debug` module's output interlaced with bunyan output is not particularly  

actually I really like the `debug` module, the output is simple and [generally] consise (also the colors really help with grokking console output). I like it so much so that I am using it as a custom output stream for `bunyan` (that is activated automatically based on a combination of my app's config and the existence of `process.env.DEBUG`, when this "debug-stream" is not active my app automatically defaults (in "dev" enviroments) to bunyan's standard STDOUT behaviour. in this way it is possible to have everything as `debug` output during development with the ability to switch to raw bunyan log output in combination with the full power/capabilities of the `bunyan` cli when you need to it. (I should point out that our primary/real output stream is a custom stream that publishes log messages to rabbitmq).

Below is a gist (I thought you might possibly be interested) containing the various parts I use implement this, It includes a mechanism for skipping the duplicate output of Error log-data - it solves my day-to-day pain with console logging:

https://gist.github.com/iamjochem/3d272f916ff227e1a8e4793483b55275

and just 'because' here is a gist for the custom rabbitmq stream we use (aside: I wonder is there an official "extra/custom streams" repo that something like this might live in?)?:

https://gist.github.com/iamjochem/c6d74c4ed916acab56973d7b8f0a0697
