### ISSUE TITLE
Fix in documentation: getQuery plugin

### ISSUE THREAD

**Issue by alwinkpc** [restify/node-restify#1502]
# Bug Report

## Restify Version
5.2.0

## Node.js Version
npm info using npm@5.3.0
npm info using node@v8.4.0

## Expected behaviour
[Documentation](http://restify.com/docs/request-api#getquery) of getQuery plugin says:

    // incoming request is /foo?a=1
    server.use(restify.plugins.queryParser());
    req.getQuery();
    // => { a: 1 }

## Actual behaviour
Reading the code I found that the plugin actually saves __getQuery()__ to __req__ object. So, the example should be:

    // incoming request is /foo?a=1
    server.use(restify.plugins.queryParser());
    req.query;     // => { a: 1 }

## Cause
    /node_modules/restify/lib/plugins/query.js

    line 31: req.query = qs.parse(req.getQuery(), opts);

**Comment by retrohacker** [comment]
Thanks for reporting this @alwinkpc ! :heart:

**Comment by DonutEspresso** [comment]
Merged
