### ISSUE TITLE
Remove package-lock.json from git

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1524]
# Question

Do we need to be committing our `package-lock.json` file? It is in a very broken state right now (incorrect package version, has resolved urls to private registries, etc.). I know we need it for `nsp`, but does that require it be tracked in git?

# References

#1510 #1477 #1492 #1482 #1475

**Comment by hekike** [comment]
No, I think we don't need it.

**Comment by DonutEspresso** [comment]
Shall we just add a .gitignore for this file?

**Comment by yunong** [comment]
I'm with Alex, shame on npm for illicitly adding package.lock to your first commit that doesn't have it.
