### ISSUE TITLE
SEO: Site template needs to replace default text with Restify project info

### ISSUE THREAD

**Issue by nwhitmont** [restify/node-restify#1541]
Alert!

**Problem:**
Site template contains *default text* that shows up as project description in search results.

**Solution:**
Replace default text with Restify project description.

**Screenshot:**
![restify google search](https://user-images.githubusercontent.com/3075047/32024088-30e77b8e-b990-11e7-9d85-2c82bde64ef3.png)

**Comment by retrohacker** [comment]
Heh good catch @nwhitmont, thanks!
