### ISSUE TITLE
Access to old documentation website?

### ISSUE THREAD

**Issue by bitsoflogic** [restify/node-restify#1543]
# Feature Request

Is there a way to access the old docs still?    I saw the DNS was moved over on #1393

## Use Case

I've been trying to get used to the new docs, but it's been very difficult to find what the info I'm looking for.  I'd like to have access to the old docs to try to understand where the breakdown is.

## Are you willing and able to implement this?

If it isn't online anymore, I'd be happy to throw it up on localhost or publicly if the source code for it is still available.

**Comment by retrohacker** [comment]
Hey @bitsoflogic,

I'm actually not sure :disappointed: maybe @yunong could chime in on where the old doc site lived and how it was generated?

As for the new site, do you have any feedback? What info are you trying to find?

**Comment by scippio** [comment]
I really need old docs... please help.

**Comment by DonutEspresso** [comment]
The old docs could be found in this repo by going back in the commit history - but if you want the UI an easier way might be to just hit up wayback machine:

https://web.archive.org/web/20170226234515/http://restify.com/
