### ISSUE TITLE
Server crashing after throwing obscure error

### ISSUE THREAD

**Issue by mellogarrett** [restify/node-restify#1556]
# Bug Report
Server runs fine for a bit, then crashes after throwing this error:
<img width="917" alt="screen shot 2017-11-04 at 11 01 44 am" src="https://user-images.githubusercontent.com/9908831/32406499-fc8af8b2-c14f-11e7-9d47-4ffeccbdd6dd.png">

## Restify Version
4.3.0
## Node.js Version
8+
## Expected behaviour
For the server not to crash

**Comment by retrohacker** [comment]
Hey @mellogarrett,

Thank you for taking the time to open an issue. A few questions so we can try and help you out:

1. Could you provide the output of `npm ls`? Seems like there is something weird with `verror`... That method _should_ exist, it looks like it has been there for [~2 years])(https://github.com/mcavage/node-assert-plus/blame/master/assert.js#L19) :thinking:
2. Does this still happen on the latest release of restify? The version you are using is v4.x which uses the old `/lib/errors`, most of that has been re-factored and moved to [restify-errors](http://github.com/restify/errors)
3. Do you have a repro case that I can run locally? Does this happen on any restify server you start or is there something specific you are doing when you see this happen?
