### ISSUE TITLE
able to disable server name

### ISSUE THREAD

**Issue by jimmywarting** [restify/node-restify#1563]
I want to remove the server header response but omitting it will result in a default header: restify
```js
const server = restify.createServer({
    name: false
});
```

**Comment by DonutEspresso** [comment]
You should be able to remove response headers via `res.removeHeader()`. Does that work for you?

**Comment by pkyeck** [comment]
worked for me (version ^6.3.4), thanks.

**Comment by DonutEspresso** [comment]
Closing as we didn't hear back from @jimmywarting - let us know if that worked for you!
