### ISSUE TITLE
Close/aborted requests should log as http 444

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#1565]
- [X] Used appropriate template for the issue type
- [X] Searched both open and closed issues for duplicates of this issue
- [X] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

When a request is closed by the client or aborted, restify doesn't change the default status code which is 200. This trickles through the audit log as well as the metrics plugin. Technically a response was never written, but if you are looking at aggregate metrics this can be quite misleading. 

## Restify Version

All

## Node.js Version

All

## Expected behaviour

I would expect an http 444 for `req.on('close')`. This seems applicable for `req.on('abort')` as well, but open to other status codes.

## Actual behaviour

Restify leaves the default status code of 200. 

## Repro case

```
const restify = require('restify');
const log = require('bunyan').createLogger({ name: 'foo '});
const server = restify.createServer({
    name: 'foo'
});

server.on('after', restify.plugins.auditLogger({
    server: server, // this ensures `audit` event is called
    event: 'after',
    log: log.child({
        component: 'audit'
    })
}));

server.get('/', function(req, res, next) {
    setTimeout(function() {
        return next();
    }, 3000);
});

server.listen(3000);
```

Start the process, then curl and ctrl-c the request. Wait for timeout to expire. See 200 in the audit logs. 

## Cause

These event listeners should probably set the status code as appropriate:
https://github.com/restify/node-restify/blob/master/lib/server.js#L1012

**Comment by hekike** [comment]
I think we can close this.
