### ISSUE TITLE
req.time() documentation

### ISSUE THREAD

**Issue by chemdrew** [restify/node-restify#1574]
- [x ] Used appropriate template for the issue type
- [x ] Searched both open and closed issues for duplicates of this issue
- [x ] Title adequately and _concisely_ reflects the feature or the bug

in docs Request.time() is described as being returned as a number, but is actually a tuple array of [seconds, nanoseconds]

in server.js line 1214
`req._time = process.hrtime();`

**Comment by hekike** [comment]
@chemdrew thanks for reporting this!
It's a bug caused by a previous PR (https://github.com/restify/node-restify/pull/1507).

**Comment by hekike** [comment]
Closed due to: https://github.com/restify/node-restify/pull/1576
Thanks for reporting this!
