### ISSUE TITLE
not matching on multiple routes

### ISSUE THREAD

**Issue by terencechow** [restify/node-restify#1587]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

I am using `swagger-restify-mw` which registers swagger in `swagger-node-runner` with the below code.

```
server.get('.*', someHandler)
```

I want to add a route specific middleware to `/some-route`
so I do:

server.get('/some-route', routeSpecificMiddleware)

when I hit `/some-route` this routeSpecificMiddleware catches the route regardless of whether I call `next()`. However I really want to allow this route to go to the 'next' handler that it catches which is the `server.get('.*')` <-- this is where swagger route handler gets called.

Is there a way to do this? 

## Restify Version
6.3.2
## Node.js Version
6.11.4
## Expected behaviour
I expect the get /some-route handler to be called and the later '.*' route to catch as well.

## Actual behaviour
only the /some-route handler is called

## Repro case
fairly simple, just create a server that has
```
server.get('/some-route', function(req, res,next) {
    console.log('hit some route')
    next()
})

server.get('.*', function(req,res,next){
    console.log('hit .* route')
})
```

curl to /some-route and it console logs `hit some route`, but never `hit .* route`

## Are you willing and able to fix this?

I can try to help but i've tried looking in the restify code base and it is fairly large. I anticipate the routing to be fairly complex as well....

**Comment by sfaizanh** [comment]
Hi @terencechow, you can do like this, hope it helps

```js
const restify = require('restify');

const server = restify.createServer({
    name: 'Test',
    versions: ['1.0.0', '2.0.0']
});

const beforMethod = (req, res, next) => {
    console.log('---------------------');
    if (['/route1', '/route2', '/route5'].indexOf(req.getRoute().path.toLowerCase()) > -1) {
        console.log('Before');
    }
    return next();
}

server.use(beforMethod);

const afterMethod = (req, res, next) => {
    console.log('After');
    next();
}

// Routes

server.get('/route1', (req, res, next) => {
    res.send(200);
    next();
});

server.get('/route2', (req, res, next) => {
    res.send(200);
    next();
});

server.get('/route3', (req, res, next) => {
    res.send(200);
    next();
}, afterMethod);

server.get('/route4', (req, res, next) => {
    res.send(200);
    next();
}, afterMethod);


server.get('/route5', (req, res, next) => {
    res.send(200);
    next();
}, afterMethod);


server.listen(2000, () => {
    console.log('OK GO');
});
```

**Comment by retrohacker** [comment]
Thank you for helping @sfaizanh :heart:

Closing this as resolved! If you are still experiencing problems @terencechow, let us know and we can re-open this.
