### ISSUE TITLE
Any plans to support promises?

### ISSUE THREAD

**Issue by StarpTech** [restify/node-restify#1588]
## Restify Version
Any

# Feature Request

## Use Case
Node.Js is increasingly developing but promises and async / await are the new standard to deal with asynchrony without a performance loss.

## Are you willing and able to fix this?
Yes

> Why do you want this?

In order to be compatible with the latest standard and be an example for "The future of Node.js REST development"

**Comment by retrohacker** [comment]
Hey @StarpTech,

Thank you for taking the time to open this issue.

Promises have some outstanding issues making them unsuitable for server side rest frameworks. While they are certainly the future, and will more than likely eventually have some sort of support in this library, there are currently no plans or timelines for treating them as first class constructs.

The most thorough conversation around including promises can be found here: https://github.com/restify/node-restify/issues/1304

There are several other cases where proposals have been made for including promises and we have concluded they aren't mature enough yet for our use case. Once we see progress on the issues listed in the thread above, I would be happy to take a pass at compiling a list of the outstanding issues preventing promises from being integrated into this code base.

**Comment by StarpTech** [comment]
Hi @retrohacker thank you, that's reasonable.

**Comment by leodutra** [comment]
Cls suffers with native promise btw. It's a horrid thing to discover in the
middle of a project.

Em 6 de fev de 2018 7:26 AM, "Dustin Deus" <notifications@github.com>
escreveu:

**Comment by joeytwiddle** [comment]
We wanted to use promises in our middleware and our route handlers, so we wrote two wrappers than can convert a promise-returning handler into a restify-compatible handler.

Example:
```js
server.get(
  { path: '/users/_self', version: VERSION },
  middleware(authUserMiddleware),
  controller(getUserSelf)
);

async function authUserMiddleware(req) {
  const user = await authHelper.findUserFromToken(req.headers['x-auth-token']);
  if (!user) throw Error("No user found!");
});

function getUserSelf() {
  return Promise.resolve({
    name: 'Example User',
    color: 'green'
  });
}
```

You can get the two wrappers here:

https://gist.github.com/joeytwiddle/a3a038d88b9a689bddbfe7eab1b459af
