### ISSUE TITLE
remove lodash dep

### ISSUE THREAD

**Issue by jimmywarting** [restify/node-restify#1592]
You are only using 2 functions from lodash (forOwn & forEach) which can easily be replaced with  builtin functions such as `Object.entries, Object.keys or Object.values` and `array.forEach`

**Comment by DonutEspresso** [comment]
It looks like some of the code has changed enough that the original examples aren't all applicable anymore. I think we should be able to achieve most of what we need through use of `Array.map`, plain old `for in`, and `typeof` checks. It's not as ideal for restify code, but if we can save pulling in all of lodash that might would be a win for folks. 

Here's what I found:
```sh
$ ag '_\.'
plugins/conditionalHandler.js
75:    if (!_.isArray(candidates)) {
83:        if (_.isArray(candidate.handler)) {
94:        if (_.isString(candidate.version)) {
97:        if (_.isString(candidate.contentType)) {
163:            if (_.isUndefined(maxVersionIndex)) {

router.js
213:    return _.mapValues(routes, function mapValues(route, routeName) {

server.js
659:        var routes = _.map(routeInfo, function mapValues(route) {
750:    _.forEach(this.router.getRoutes(), function forEach(route, routeName) {
1046:    if (_.isString(err)) {
1244:        if (_.isNumber(err.statusCode)) {
```

**Comment by jimmywarting** [comment]
Could follow Nodes LTS schedule?
4.x has reached its End-of-Life support...

https://github.com/nodejs/Release

That means minimum node version = 6.x
