### ISSUE TITLE
Formatter signature change missing from documentation

### ISSUE THREAD

**Issue by nineohnine** [restify/node-restify#1594]
Sorry this does not follow the issue template.  This is a documentation bug / missing detail.  Previously in Restify 4 the signature for response formatters was:

``` function (req, res, body, callback) { ... }```

It looks like in Restify 5 / 6 it as removed the need for the callback in favor of just returning the formatted body.  I could not find this documented anywhere.  Apologies if I missed this.  I think it would be a helpful addition.  Thanks.

**Comment by retrohacker** [comment]
Yes, we removed support for async formatters, they introduced edge cases and complexity that made them unsuitable for production use.

You are right, it doesn't look like we document our formatters very well: http://restify.com/docs/server-api/#createserver
