### ISSUE TITLE
Server RM can't remove Route with Regexp path

### ISSUE THREAD

**Issue by valerionarcisi** [restify/node-restify#1606]
# Bug Report

## Restify Version 
6.3.4
## Node.js Version 
8.9.1

## Expected behaviour

When i register a route with Regexp path and than i should be remove this route by server with rm method i don't want type string mandatory, but expect  also Regexp is available.

## Actual behaviour

When i try to remove a route with Regex by server i have an error: 'path must be a string'

## Repro case

TEST:
  const { mounts: routes } = SERVER.router;
  Object.keys(routes).forEach((route) => SERVER.rm(route));
It is a Jest afterEach.

Error if route is a Regex.

## Cause

at Router.findByPath (node_modules/restify/lib/router.js:608:12)
      at Router.unmount (node_modules/restify/lib/router.js:351:15)
      at Server.rm (node_modules/restify/lib/server.js:604:25)

**Comment by hekike** [comment]
Restify v7.x doesn't support RegExp path, please migrate to wildcards:
https://github.com/restify/node-restify/blob/master/docs/guides/6to7guide.md#different-regexp-usage-in-router-path-and-wildcards

You can remove wildcard paths via the API.
