### ISSUE TITLE
uploading file issue - maxFileSize exceeded, received 2098372 bytes of file data

### ISSUE THREAD

**Issue by NShahri** [restify/node-restify#1620]
- [ ] Used appropriate template for the issue type
- [ ] Searched both open and closed issues for duplicates of this issue
- [ ] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

Can not upload file which has more than 2098372 bytes 

## Restify Version

6.3.4

## Node.js Version

8.9.3

## Expected behaviour

Be able to config max file size

## Actual behaviour

Can not configure maxFileSize

## Repro case

```javascript
router.post(
        {name: RouteNames.fileNew, path: '/file'},
        restify.plugins.bodyParser({maxFileSize: config.,axFileSize}),
       filePostHandler);
```

```json
{"stack":"BadRequestError: maxFileSize exceeded, received 2098372 bytes of file data\n    at parse (/Users/nimas/dev-personal/power.js2/node_modules/restify/lib/plugins/multipartBodyParser.js:88:29)\n    at IncomingForm.<anonymous> (/Users/nimas/dev-personal/power.js2/node_modules/formidable/lib/incoming_form.js:104:9)\n    at emitOne (events.js:116:13)\n    at IncomingForm.emit (events.js:211:7)\n    at IncomingForm._error (/Users/nimas/dev-personal/power.js2/node_modules/formidable/lib/incoming_form.js:298:8)\n    at Stream.<anonymous> (/Users/nimas/dev-personal/power.js2/node_modules/formidable/lib/incoming_form.js:222:12)\n    at emitOne (events.js:116:13)\n    at Stream.emit (events.js:211:7)\n    at MultipartParser.parser.onPartData (/Users/nimas/dev-personal/power.js2/node_modules/formidable/lib/incoming_form.js:387:14)\n    at callback (/Users/nimas/dev-personal/power.js2/node_modules/formidable/lib/multipart_parser.js:102:31)"}
```

## Cause

There is an option `maxFileSize` in formidable which blocks uploading files which are more than 2.0MB. 

https://github.com/felixge/node-formidable/commit/b81d1c71cd3774419571c360db4312c965a57a13

Restify does not allow to set this option when uses formidable.

## Are you willing and able to fix this?

YES
https://github.com/restify/node-restify/pull/1621

Adding `maxFileSize` documentation to `formidable`:
https://github.com/felixge/node-formidable/pull/464

**Comment by DonutEspresso** [comment]
Fixed by #1621
