### ISSUE TITLE
how do mount an override method to HTML input hidden

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [restify/node-restify#1625]
Hello
I'm working with a middleware to map put/delete methods, the code and this
```javascript
  // methodOverride
  server.pre((req, res, next) => {
    req.query().split('&').forEach((key) => {
      const params = key.split('=')

      if(params[0] === '_method') {
        req.method = params[1]
      }
    })
    return next()
  })

  // html
  form(action="/password_changed?_method=PUT", method="POST")
```
But I'd like to catch the _method parameter of the form, something like
```javascript
form(action="/password_changed", method="POST")
  input(type="hidden", name="_method", value="PUT")
```
I looked at the documentation and solved the code, but found nothing to help me. Is it possible to do that?

**Comment by DonutEspresso** [comment]
Hi - I don't think we can help with the HTML side of your code here, but at least on the server side you may be better served by installing your routes against all the verbs you want to support for that particular request.

**Comment by carvalhoviniciusluiz** [comment]
ok thanks
