### ISSUE TITLE
Documentation regarding regex paths is out of date

### ISSUE THREAD

**Issue by thisandagain** [restify/node-restify#1644]
# Bug Report

## Restify Version
`7.1.0`

## Node.js Version
`8.11.1`

## Expected behaviour
Restify should recognize regex literals when defining a path as per documentation:

> You can also pass in a RegExp object and access the capture group with req.params (which will not be interpreted in any way):
```js
server.get(/^\/([a-zA-Z0-9_\.~-]+)\/(.*)/, function(req, res, next) {
  console.log(req.params[0]);
  console.log(req.params[1]);
  res.send(200);
  return next();
});
```

## Actual behaviour
```
[Redacted]/node_modules/assert-plus/assert.js:22
    throw new assert.AssertionError({
    ^

AssertionError [ERR_ASSERTION]: path (string) is required
    at RouterRegistryRadix.add ([Redacted]/node_modules/restify/lib/routerRegistryRadix.js:39:12)
    at Router.mount ([Redacted]/node_modules/restify/lib/router.js:167:20)
    at Server.serverMethod [as get] ([Redacted]/node_modules/restify/lib/server.js:1476:33)
    at Object.<anonymous> ([Redacted]/test.js:4:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

## Repro case
```js
const restify = require('restify');

const server = restify.createServer();
server.get(/^\/([a-zA-Z0-9_\.~-]+)\/(.*)/, function(req, res, next) {
  console.log(req.params[0]);
  console.log(req.params[1]);
  res.send(200);
  return next();
});
server.listen(8000);
```

## Cause

I believe this may be the intended behavior as per changes in [this commit](https://github.com/restify/node-restify/commit/82832771826321480e5e524db258668f62b689c2#diff-504fd89f344be1e9c4b583f3ebd7428a) and documented [here](https://github.com/restify/node-restify/blob/master/docs/guides/6to7guide.md#different-regexp-usage-in-router-path-and-wildcards).

## Are you willing and able to fix this?

Yes, but I have the following questions:
- Was breaking the example case intentional?
- If so: given what the example in the existing documentation is trying to show does it seem reasonable to replace it with this example from the "6 to 7" migration guide?

```js
server.get('/example/at/:hour(^\\d{2})h:minute(^\\d{2})m', (req, res, next) => {
  // req.params => { hour: 12, minute: 15 }
}))
```

**Comment by hekike** [comment]
Restify doesn't support raw RegExp anymore just wildcards as you found it in the 6to7 guide: http://restify.com/docs/6to7/

So you right,  documentation should be updated.
PR would be more than welcomed, thanks!

**Comment by ariden83** [comment]
Hello,  restitfy router RouterRegistryRadix don't accept  regex in route.path because of : 

`assert.string(route.path, 'path');` in router.js 

then, why can you test if path.name is a regex in server.js > serverMethodFactory function ?

`if (opts instanceof RegExp || typeof opts === 'string') {
            opts = {
                path: opts
            };
        }`

?

We can surcharge default router, which router could you recommend that will accept regex?

**Comment by hekike** [comment]
You are right, `RegExp` types are not supported but RegExp params in a string path is supported.
So this path should work: `server.get('GET', '/example/:file(^\\d+).png', () => {}))`
For more examples see: https://github.com/delvedor/find-my-way#supported-path-formats

Doc issues are addressed in this PR: https://github.com/restify/node-restify/pull/1679

Thanks for reporting!

**Comment by therightstuff** [comment]
Well, this sucks. We were relying on regex support to use restify on iisnode with virtual directories that cannot be predetermined - I'm very disappointed that we now have to find another solution entirely.

**Comment by AhmedAyman0** [comment]
We were using `	server.get(
		/^\/?.*/,
		restify.plugins.serveStatic({
			directory: __dirname + "/public",
			default: "index.html",
		})
	);`

but after upgrading we couldn't serve our static files any more , Is there a replacement?
