### ISSUE TITLE
Node v10 support

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#1665]
It looks like something changed between v10.1.0 and v10.2.0 that caused tests to start failing. Given v10 isn't LTS this isn't super high priority yet.

The 10.2.0 changelog is here:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.2.0

Unclear at the moment if this is due to a way we are using undocumented APIs, or something in core changing.

**Comment by hekike** [comment]
Fixed by: https://github.com/restify/node-restify/pull/1672
