### ISSUE TITLE
Unclear documentation about Server config

### ISSUE THREAD

**Issue by Junkern** [restify/node-restify#1666]
The docs on http://restify.com/docs/server-api/ are not consistent. 

There is one section for `createServer` and one section for `Server`. Both are describe to `create a server`, but their documentation states different options. E.g. for `Server` there is a `noWriteContinue` which is not present for `createServer`.

Also `options.httpsServerOptions`
> Any options accepted by node-https Server. If provided the following restify server options will be ignored: spdy, ca, certificate, key, passphrase, rejectUnauthorized, requestCert and ciphers; however these can all be specified on httpsServerOptions. 

So can I also pass these httpsServerOptions directly to the restify server? If so, that should be documented as `options`

Moreover, according to the docs you still can pass an regexp to e.g. `.get()`. `Server~methodOpts` is listed as accepting `Regexp`.

**Comment by pkyeck** [comment]
also found this:

> Versioned Routes
[...] You can default the versions on routes by passing in a version field at server creation time. [...]

But this is not mentioned in the docs - neither here (http://restify.com/docs/server-api/#createserver) nor here (http://restify.com/docs/server-api/#server).

Is this still possible? Or was this removed at some point?

**Comment by DonutEspresso** [comment]
@Junkern thanks for filing this - `createServer` and `Server` should be identical for all intents and purposes. We started doing automatic API generation at some point so this could be a result of new auto generated stuff clashing with existing API docs. cc @hekike 

@pkyeck it seems the versioned routing also seems to be missing from the verb APIs, which is where they live now: http://restify.com/docs/6to7/

We definitely need to add those back in..

**Comment by hekike** [comment]
I created a PR to fix this: https://github.com/restify/node-restify/pull/1678

**Comment by hekike** [comment]
Closed by https://github.com/restify/node-restify/pull/1678
