### ISSUE TITLE
not an issue, more of a 'how to' - maxParamLength for find-my-way router

### ISSUE THREAD

**Issue by keba** [restify/node-restify#1677]
# Information/How-To Report

## Restify Version
7.2.1

## Node.js Version
8.10.0

## Expected behaviour
Not limited to 100 characters when using a `:paramName` style object in a route

## Actual behaviour
Limited to 100 characters when using a `:paramName` object in a route

## Repro case

If passing a url encoded string of more than 100 characters, by default restify will give a NotFound error.

## Cause
find-my-way has a default limit of 100 characters as a maximum for the innards of a parameter used as part of a route.

More information on https://github.com/delvedor/find-my-way/blob/master/README.md - search for `maxParamLength`

## Are you willing and able to fix this?

Fixed by specifying `maxParamLength` in createServer options.

This doesn't feel obvious/explicit, but does work with no other code changes needed due to the way that `restify.createServer({maxParamLength: 500})` sends its options to Router which sends its options to RouterRegistryRadix which sends the options to find-my-way.

Example code on how to specify find-my-way maxParamLength successfully:

```
const server = restify.createServer({
    name: 'example',
    version: '0.0.1',
    maxParamLength: 500
});

```

This probably works for other find-my-way options. I've not needed other options thus far so haven't tested this.

Now when calling a route with a stupidly long string, the stupidly long string is now only limited to 500 characters rather than 100 characters. Yes, my testing covers stupidly long strings just in case somebody tries using them, and I'd set my validator to 128 characters...

Note: This was not a limitation in restify before version 7. Only found due to upgrading and having a bunch of 'max length' integration tests fail with 404 NotFound instead of my usual validation error messages.

As I'm unsure if the above was intended behaviour, I've not updated the documentation, as I wouldn't want others to propagate unintentional options in their applications if there should be a better way to 'fix' this limitation.

## Recommendation

The main 'version 6 to 7' page could do with a note for this if intentional or an implementation and wording for if its fixed in a clearer way. (https://github.com/restify/node-restify/blob/v7.2.1/docs/guides/6to7guide.md or whichever version is relevant at the time of a PR)

**Comment by DigaoParceiro** [comment]
I'm using restify@8.4.0 and there's no param maxParamLength in createServer(options), so, my solution was:
I went to node_modules\find-my-way\index.js and I replaced this line:

`this.maxParamLength = opts.maxParamLength || 100`
to
`this.maxParamLength = opts.maxParamLength || 200`

Is there a better solution?
