### ISSUE TITLE
Receiving statusCode 444 after upgrading to Node 10

### ISSUE THREAD

**Issue by bureson** [restify/node-restify#1682]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

After upgrading to Node v10, our responses return statusCode 444. We came across this issue already a couple of weeks ago and decided to ignore it as Node v10 was not yet a LTS version, but now Docker started supporting this version and we need to resolve this issue. On previous versions of Node we don't have such an issue. I'm quite helpless and have no idea where should I start looking. I will welcome any suggestions for further investigation. Lower I'm attaching source of how we create the server.

## Restify Version

7.2.0

## Node.js Version

10.4.0

## Expected behaviour

Return statusCode 200

## Actual behaviour

Returns statusCode 444

## Repro case

```
const server = restify.createServer();
server.use(restify.plugins.bodyParser({
  keepExtensions: true,
  mapFiles: true
}));
server.use(restify.plugins.queryParser());
```

## Cause

Unknown.

## Are you willing and able to fix this?

Willing yes, able no.

**Comment by hekike** [comment]
Hi, you should use latest (7.2.1) version of restify, that's where we addressed this issue.

**Comment by bureson** [comment]
Thank you for your reply! It fixed the issue.
