### ISSUE TITLE
serving static files & browser history with React front end

### ISSUE THREAD

**Issue by frankjar** [restify/node-restify#1696]
- [X] Used appropriate template for the issue type
- [X] Searched both open and closed issues for duplicates of this issue
- [X] Title adequately and _concisely_ reflects the feature or the bug

#
Restify v6.3.2

# serving static files & browser history with React front end

I have developped an app with create react app and i want to deploy it. React is used for the front end and Restify publish API that is consumed by the front end.

**The app uses browser history and when i refresh the page Restify return JSON object saying that the route is unknown**.

To solve this problem, the Create-react-app documentation explains how to do it well with the Express server :

```
const express = require('express');
const path = require('path');
const app = express();

app.use(express.static(path.join(__dirname, 'build')));

app.get('/*', function (req, res) {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});
```

Here is the doc  :
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

## Use Case

As mentionned in the create-react-app doc, i use restify to serve static front end React app :
```
server.get(
  /\/(.*)?.*/,
  restify.plugins.serveStatic({
    directory: "./static",
    default: "index.html"
  })
);
```

It's all right with Express but not with Restify.  With Express, we must use a middleware first to server static files and next we have to redirect routes to the "index.html" front end app.
With Restify, i have just only used the serveStatic plugin, but it's not enough.

So, if you have an idea to solve that... it would be fabulous ! 
thx

**Comment by jackfiallos** [comment]
Hi there

Just a doubt, why you want to handle static files using restify, was this library was created to handle api request/responses .. in that case, you could use [http-server](https://github.com/indexzero/http-server). Actually, as a good practice you should keep separated your static server from your api server

**Comment by frankjar** [comment]
hi,
in fact i duplicate the logic used by Express & React do develop SPA app and Rest API. May be this philosophy is not the good one for Restify ?


This code seems to work , but it's more a "tip" than a real good solution :
`
server.get(
  /\/static\/(.*)?.*/,
  restify.plugins.serveStatic({
    directory: "./static",
    default: "index.html"
  })
);

const fs = require("fs");
server.get(/\/(.*)?.*/, function(req, res, next) {
  fs.readFile("./static/index.html", "utf8", function(err, file) {
    if (err) {
      res.send(500);
      return next();
    }

    res.sendRaw(200, file);
    res.end();
    next();
  });
});
`
The plugin is used to serve all the files into the subdirectory "static" and all other routes go to the index.hml file; this file is send to the browser by reading it from hard disk.
