### ISSUE TITLE
Retrieve res.body within middleware

### ISSUE THREAD

**Issue by MartinMuzatko** [restify/node-restify#1703]
# Feature Request

## Use Case

It would be nice to be able - like in express - to modify or use the response body.

## Example API

within middleware function: `res.body`

## Are you willing and able to implement this?

I am not really familiar with the node internals for requests/responses. But I don't know why the response is not passed to the middleware. Point me into the correct direction and I'll happily implement it.

**Comment by unsol** [comment]
Hi Martin.

Maybe use `res.write` to build a response, then `res.end` to flush it at the end of your routing? Either that, or I think you're stuck sending from middleware, which probably isn't a great idea.
