### ISSUE TITLE
Why i can't get Response prototype?

### ISSUE THREAD

**Issue by maxzhou0** [restify/node-restify#1707]
# Bug Report

## Restify Version
Latest

## Node.js Version
Latest

## Expected behaviour
I want to access the Response prototype and add some methods

> This section details what you expected restify to do based on the code that you wrote

## Actual behaviour

return undefined

## Repro case

```
let {Response} = require('restify')
console.log(Response)
```

**Comment by ekristen** [comment]
Response isn't exported.
https://github.com/restify/node-restify/blob/master/lib/index.js#L108-L113
