### ISSUE TITLE
Feature: Support trustProxy Setting

### ISSUE THREAD

**Issue by ekristen** [restify/node-restify#1712]
A good majority of the time (I have zero stats to back up this statement, lol) restify is deployed behind proxies. Especially now with containers and kubernetes and the like they all use proxies to manage traffic.

Restify doesn't understand or trust proxy related headers which leads to rather useless logs, especially when it pertains to audit logs. Perhaps not useless but remote addresses are valuable pieces of information. Take for example if someone wants to allow a particular route accessed if the remote address falls within a specific CIDR.

Many assumptions are made in and throughout the plugins (including throttle, audit, and bunyan) that assume `req.connection.remoteAddress` is the real IP, when in fact it could be one or more proxies.

I would like to suggest Restify allows for a server option called `trustProxy` that when enabled uses a library like `request-ip` that uses different headers to attempt to determine the real remote address and expose it using a function on `req` called `ip`, similar to `id`. 

Then in all plugins within Restify, instead of calling `req.connection.remoteAddress`, `req.ip()` can be called instead. 

I'm more than happy to submit the PR, but I wanted to get general feedback first, before spending time on the implementation.

**Comment by history007** [comment]
Resurrection this issue. It would be nice if restify will have this feature, for example to create secure cookie. Because behind nginx (which contains SSL) we couldn't set and get secure cookies.

**Comment by masterwaffle** [comment]
+1

**Comment by shryder** [comment]
+1
