### ISSUE TITLE
dyld: _usdt_create_provider - program abort on macOS 10.14.1

### ISSUE THREAD

**Issue by onionyst** [restify/node-restify#1724]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version

7.2.3

## Node.js Version

11.2.0

## Expected behaviour

> When I run `npm run dev` using RESTify, it should start the engine successfully. 

## Actual behaviour

> I get the following output and the application quits. 
> 
> **Note: the code is executed on macOS 10.14.1.** 

~~~
> backend@1.0.0 dev /Users/onionyst/develops/backend
> node src/index.js

dyld: lazy symbol binding failed: Symbol not found: _usdt_create_provider
  Referenced from: /Users/onionyst/develops/backend/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace

dyld: Symbol not found: _usdt_create_provider
  Referenced from: /Users/onionyst/develops/backend/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace

[1]    23424 abort      npm run dev
~~~

## Repro case

~~~javascript
var RESTify = require('restify');

var server = RESTify.createServer({
  name: 'Test Server'
})

server.listen(8081, () => {
  console.log('%s listening at %s', server.name, server.url)
})
~~~

> The program above will cause the problem. 

## Cause

> I don't know how to trace a bug like this. 
> 
> The [hexojs/hexo](https://github.com/hexojs/hexo) project also crashes on [this](https://github.com/hexojs/hexo/issues/2803). Therefore, it seems not really a RESTify bug, but rather one under **dtrace-provider** used on a macOS 10.14.1 computer using HomeBrew, where the **dtrace-provider** is used by **bunyan**, which is then used by **restify**. Using `npm install --no-optional` will mitigate the error, but will involve other issues, i.e. using node-mongo-native will cause password strategy problems. 

## Are you willing and able to fix this?

> No, I don't know how. 
> 
> I would be very delighted if you can confirm the cause of this problem, and give me a respond if you decide not to fix this for only rare situations, or to prevent it from happening in any directions.

**Comment by andrewgould** [comment]
@onionyst Do you have `binutils` installed via Homebrew? I was encountering the same problem as you (https://stackoverflow.com/questions/54014971/macos-dyld-symbol-not-found-usdt-create-provider) and managed to fix it by removing this package.

**Comment by onionyst** [comment]
@andrewgould Yes, and definitely it works! Thank you so much! 

Besides, I suppose the newest version of **binutils** has done something to overcome the conflict (i.e. the `g` prefix is removed), and by executing the following commands can have **binutils** installed again while **RESTify** works correctly. 

~~~shell
brew uninstall --force binutils
brew install binutils
~~~

**Comment by craig552uk** [comment]
For anyone else finding this bug report after encountering the same error on Apple Silicon, reinstalling node on x86 architecture resolved the issue for me.

```
$ nvm uninstall 12
$ arch -x86_64 zsh 
$ nvm install 12
```

**Comment by Thatkookooguy** [comment]
@craig552uk Just encountered this myself using `restify@8.5.1` on Apple Silicon. tried running the 3 commands you posted but I'm still getting the same error. Do you have maybe some more clues on how to solve this? :-)

**Comment by dooleyb1** [comment]
> For anyone else finding this bug report after encountering the same error on Apple Silicon, reinstalling node on x86 architecture resolved the issue for me.
> 
> ```
> $ nvm uninstall 12
> $ arch -x86_64 zsh 
> $ nvm install 12
> ```

Worked perfectly, thank you 👏

**Comment by uranium93** [comment]
@craig552uk Thanks Man worked fine. Was not for Restify but was for `@poanet/solidity-flattener`
