### ISSUE TITLE
Installation Issue on aws elastic beanstalk 

### ISSUE THREAD

**Issue by tugan** [restify/node-restify#1754]
The issue happens when we try to npm install restify to Elastic beanstalk (AWS) environment and install fails with the following message. 

we have tried 
npm cache clean --force 
delete package-lock.json 

but did not solved the problem. 

## Restify Version
7+
## Node.js Version
10.x
## Expected behaviour
npm install complete successfully 

## Actual behaviour
npm installtaion proccess stop with the following error 

npm ERR! Unexpected token  in JSON at position 2079 while parsing near '...d-my-way-0.2.4.tgz"}...'
npm ERR! A complete log of this run can be found in:

**Comment by rajatkumar** [comment]
Hi @tugan, I am unable to reproduce this at my end. Which AWS region are you on? Is it possible that this is related to https://status.npmjs.org/incidents/06vhhrnp272c?

**Comment by tugan** [comment]
Hi @rajatkumar, 
our region is eu-west-1 (Ireland). looks like possible, meanwhile, do you have any suggestion or workaround?

**Comment by tugan** [comment]
the issue is related to https://status.npmjs.org/incidents/06vhhrnp272c?
it solved
