### ISSUE TITLE
Export Router

### ISSUE THREAD

**Issue by yolibernal** [restify/node-restify#1758]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request

## Use Case

We are trying to separate the routes from the server configuration. The docs say that [`createServer`](http://restify.com/docs/server-api/#createserver) can take a `Router` instance. I did not find a way to import the [router](https://github.com/restify/node-restify/blob/master/lib/router.js), though, since it is not exported in `index.js`. (In the TypeScript definitions the Router is exported which makes it even more confusing).
Is there a way to create a Router that I missed?

## Example API

```js
const restify = require('restify')

const router = new restify.Router()
router.mount({ method: 'GET', path: '/' }, [(req, res) => res.send(200)])

const server = restify.createServer({
  name: 'myapp',
  version: '1.0.0',
  router
})
```

## Are you willing and able to implement this?

Yes

**Comment by SamuelMarks** [comment]
You might be interested in my approach here: https://github.com/SamuelMarks/restify-orm-scaffold

The idea is to have [this line in your `main`](https://github.com/SamuelMarks/restify-orm-scaffold/blob/8f60aa1/main.ts#L26):
```ts
export const all_models_and_routes: Map<string, any> = populateModelRoutes(__dirname);
```

A directory structure like:
```
$ tree --charset=ascii -d
.
|-- api
|   |-- auth
|   `-- user
`-- test
    `-- api
        |-- auth
        |-- root
        `-- user
```

With `routes` file [containing exposed functions](https://github.com/SamuelMarks/restify-orm-scaffold/blob/8f60aa1/api/user/routes.ts#L10-L22):
```ts
export const create = (app: restify.Server, namespace: string = '') =>
    app.post(namespace, has_body, mk_valid_body_mw(user_sdk.schema),
        (request: restify.Request, res: restify.Response, next: restify.Next) => {
```

Which is also packaged into its own library: https://www.npmjs.com/package/@offscale/routes-merger

**Comment by SamuelMarks** [comment]
@yolibernal Ouch
