### ISSUE TITLE
Benchmarks Restify vs Express

### ISSUE THREAD

**Issue by agurha** [restify/node-restify#176]
Hi Guys, First of all i would like to say thanks to you all for your excellent lib. 

So very recently my friend did a benchmark test for Restify vs Express as we are planning of looking into Restify. I shall say the results are impressive. 
1. restify
   [16/07/2012 07:42:16] Anatoliy Chakkaev: ~: ) /usr/local/apache2/bin/ab -n 80000 -c 500 -k http://127.0.0.1:3000/hello/world
   This is ApacheBench, Version 2.3 <$Revision: 1139530 $>
   Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
   Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 8000 requests
Completed 16000 requests
Completed 24000 requests
Completed 32000 requests
Completed 40000 requests
Completed 48000 requests
Completed 56000 requests
Completed 64000 requests
Completed 72000 requests
Completed 80000 requests
Finished 80000 requests

Server Software:        restify
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /hello/world
Document Length:        13 bytes

Concurrency Level:      500
Time taken for tests:   18.445 seconds
Complete requests:      80000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    80000
Total transferred:      42800000 bytes
HTML transferred:       1040000 bytes
Requests per second:    4337.28 [#/sec](mean)
Time per request:       115.280 [ms](mean)
Time per request:       0.231 [ms](mean, across all concurrent requests)
Transfer rate:          2266.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0  10.5      0    1201
Processing:     0  115  11.2    112     181
Waiting:        0  115  11.2    112     181
Total:          0  115  15.5    112    1351

Percentage of the requests served within a certain time (ms)
  50%    112
  66%    113
  75%    113
  80%    114
  90%    130
  95%    137
  98%    142
  99%    151
 100%   1351 (longest request)
[16/07/2012 07:42:34] Anatoliy Chakkaev: 2. express
[16/07/2012 07:42:37] Anatoliy Chakkaev: ~: ) /usr/local/apache2/bin/ab -n 80000 -c 500 -k http://127.0.0.1:3000/
This is ApacheBench, Version 2.3 <$Revision: 1139530 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 8000 requests
Completed 16000 requests
Completed 24000 requests
Completed 32000 requests
Completed 40000 requests
Completed 48000 requests
Completed 56000 requests
Completed 64000 requests
Completed 72000 requests
Completed 80000 requests
Finished 80000 requests

Server Software:        
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /
Document Length:        41 bytes

Concurrency Level:      500
Time taken for tests:   29.528 seconds
Complete requests:      80000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    80000
Total transferred:      16320000 bytes
HTML transferred:       3280000 bytes
Requests per second:    2709.27 [#/sec](mean)
Time per request:       184.551 [ms](mean)
Time per request:       0.369 [ms](mean, across all concurrent requests)
Transfer rate:          539.74 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.7      0      13
Processing:     1  184  13.6    180     209
Waiting:        1  184  13.6    180     209
Total:          1  184  13.4    180     221

Percentage of the requests served within a certain time (ms)
  50%    180
  66%    187
  75%    192
  80%    195
  90%    199
  95%    200
  98%    201
  99%    202
 100%    221 (longest request)

So for most of the part Restify outperforms Express except in the end when we see a huge peak. 

We are wondering if might be due to some leak or something. Was wondering if team is looking into making it more comparable to express ?, anytime soon.

Thanks,
A

**Comment by netpoetica** [comment]
@agurha Do you have by any chance a repo for this test? I am curious what the results would be if updated for the current versions of Restify and Express
