### ISSUE TITLE
Version 8.3.0 breaks on older version of Node.js 8

### ISSUE THREAD

**Issue by watson** [restify/node-restify#1773]
Restify v8.3.0 was just released which now uses the spread operator. Support for this wasn't added until Node.js v8.6.0, but the engine field in the package.json says that Restify supports Node.js 8.0.0+

You should probably just update the engine field to say `>=8.6.0` or something like that.

I discovered this because we at Elastic are running a compatibility test for Restify every time a new version is released against all supported versions of Node.js, to see that Elastic APM still works with Restify as expected. This morning [these tests started failing](https://travis-ci.org/elastic/apm-agent-nodejs/jobs/519013311) for Restify on Node.js v8.1.x

**Comment by watson** [comment]
Oh hang, on this issue actually comes from a sub-dependency of Restitfy: csv-parse

**Comment by watson** [comment]
Found the culprit: https://github.com/restify/node-restify/commit/3b712298c16577394d16b149be6c9a99044332b2

This commit upgraded the version of `csv` which depends on `csv-parser` which at some point started using the spread operator, so exactly when this happened is a little fuzzy. But bottom line is that Restify now requires version Node.js 8.6.0 or above.

Sorry for the confusion 😅

**Comment by DonutEspresso** [comment]
Thanks @watson for reporting this! Would you be okay with this going out as a patch release?

**Comment by DonutEspresso** [comment]
I ran through a battery of tests with the Node 8 releases. It looks like we can scope this to 8.3.0+.

**Comment by ghermeto** [comment]
fixed on #1775. Closing this issue.
