### ISSUE TITLE
Restify hangs when ending route chain without closing response

### ISSUE THREAD

**Issue by cprussin** [restify/node-restify#1774]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version

Tested on 8.3.0.

## Node.js Version

Tested on v8.15.1.

## Expected behaviour

Restify should not hang (in express this same case automatically 404s)

## Actual behaviour

Restify hangs

## Repro case

```js
const restify = require('restify');
const server = restify.createServer();
server.get('/', (req, res, next) => next()); // also could be server.get('/', () => {});
server.listen(8080, () => console.log('Server up on port 8080'));
```

## Cause

Restify does not detect cases where the middleware chain is completed and no response has been flushed.

## Are you willing and able to fix this?

Yes

**Comment by retrohacker** [comment]
Comparing this to express' behavior:

Express uses https://github.com/pillarjs/finalhandler at the end of the middleware chain. It does a check to see if headers have started being flushed yet as a heuristic.

This snippet 404s:
```js
require('express')().get('/', function(req, res, next) { next(); }).listen(8080);
```

This snippet hangs:
```js
require('express')().get('/', function(req, res, next) { res.flushHeaders(); next(); }).listen(8080);
```

It also requires calling the continuation, otherwise it hangs:

```js
require('express')().get('/', function(req, res, next) {}).listen(8080);
```

**Comment by ghermeto** [comment]
merged :)
