### ISSUE TITLE
No v7 -> v8 migration guide?

### ISSUE THREAD

**Issue by bradennapier** [restify/node-restify#1783]
Title says it all - no information or even release notes on v8 ? What changed? What do I need to do to upgrade? What should I be concerned about?  Is the documentation for v7 or v8?

**Comment by rajatkumar** [comment]
Hi @bradennapier 
As part of v7 -> v8 upgrade, restify dropped support for Node 4.x and Node 6.x and now supports NodeJS versions 8.3.0 and above.

Ideally running `npm install restify@latest --save` should upgrade restify for you and things should work as it is. If you happen to find a case that doesn't work for you, please feel to raise an issue.

Reference:
https://github.com/restify/node-restify/blob/master/CHANGELOG.md#800-2019-02-20
https://github.com/restify/node-restify/blob/master/package.json#L93

**Comment by bradennapier** [comment]
Cool , thanks.  Was just expecting to see something since the website has v6 to v7 and v5 to v6 guides.  Looks like no major breaking changes outside of Node - found the changelog, thanks!
