### ISSUE TITLE
Published version on npm includes unnecessary large log files

### ISSUE THREAD

**Issue by jbt** [restify/node-restify#1816]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version

8.5.1

## Node.js Version

N/A

## Expected behaviour

Installed files from NPM shouldn't include any extraneous files

## Actual behaviour

Currently the published version on npm includes three large log files totalling 1.7MB

isolate-0x102801e00-74163-v8.log (500526 bytes)
isolate-0x103000000-74139-v8.log (660871 bytes)
isolate-0x103000000-74561-v8.log (633352 bytes)

## Repro case

```sh
npm install restify@8.5.1
```

## Cause

There's a `*.log` in `.gitignore` that should probably also be in `.npmignore` to prevent those files from being published. Or alternatively a `"files"` entry in `package.json` to explicitly specify the files that should be included (since there are also a few much smaller unnecessary files currently included, like eslint/prettier config files)

## Are you willing and able to fix this?

I'll gladly make a PR to add `*.log` into `.npmignore` if that would help - but I'm not sure whether I should be the one to make the call between that or going with a files list in the package.json

**Comment by retrohacker** [comment]
Heh @hekike your isolates are leaking :stuck_out_tongue:

**Comment by retrohacker** [comment]
Thank you for letting us know @jbt. I'll get a PR going.
