### ISSUE TITLE
Replace bunyan with pino

### ISSUE THREAD

**Issue by ghermeto** [restify/node-restify#1838]
# Prefer Pino

## Why?
Well maintained, performance-focused, compatible API. Today we always pass a Pino instance to `createServer()`. 

## Breaking change
[bunyan_helper](https://github.com/restify/node-restify/blob/master/lib/bunyan_helper.js) has a complex implementation of `RequestCaptureStream` based on Bunyan multi-stream and RingBuffer capabilities that Pino don't have. **_I propose_** we drop`RequestCaptureStream` entirely, as it is only used if the user doesn't provide any logger themselves.  

## Are you willing and able to implement this?
Yes

**Comment by DonutEspresso** [comment]
I don't feel strongly. If folks depend on the RCS implementation we could re-publish it as its own module. Seems pretty low effort and we could ship it with the next breaking change.

**Comment by ghermeto** [comment]
👍

**Comment by ghermeto** [comment]
Done on #1841... I can publish RequestCaptureStream as its own module if needed.
