### ISSUE TITLE
Github says the latest release is 4.0.3 (should be 8.5.1)

### ISSUE THREAD

**Issue by apaatsio** [restify/node-restify#1842]
On the right column of the [Github page](https://github.com/restify/node-restify) it says the latest release is 4.0.3 (released Sep 19, 2015). Obviously, this is not correct since the latest release is 8.5.1 at the time of writing this. 4.0.3 is not even the latest 4.x release (which seems to be 4.3.4).

Also, the URL https://github.com/restify/node-restify/releases/latest redirects to the 4.0.3 release page.

![restify-latest-release](https://user-images.githubusercontent.com/195210/86517821-80ff1900-be34-11ea-8d35-fc95cff35771.png)

**Comment by ghermeto** [comment]
Thanks @apaatsio! I updated the latest release and the new release process will fix this moving forward.
