### ISSUE TITLE
Update `find-my-way` to the latest version

### ISSUE THREAD

**Issue by gmahomarf** [restify/node-restify#1900]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request

## Use Case
I ran into [an issue with `find-my-way`'s routing][fmw_issue] that has since been fixed in [version 5.2.0 of `find-my-way`][fmw_release]. This might also fix #1811, #1873 and #1874

## Example API
N/A

## Are you willing and able to implement this?
I can open a PR updating the version, but there are probably tests that need to be run and checks that need to happen. Based on `find-my-way`'s changelog, breaking changes include dropped support for Node.js < 12, and I don't know what the officially supported version for Restify is

[fmw_issue]: https://github.com/delvedor/find-my-way/issues/222
[fmw_release]: https://github.com/delvedor/find-my-way/releases/tag/v5.2.0

**Comment by rektide** [comment]
I ran into some assertion errors when running tests with newer versions of `find-my-way`. `3.0.5` passed tests, but [`4.0.0`](https://github.com/delvedor/find-my-way/releases/tag/v4.0.0) failed with four assertions.

I tentatively think this is just that `find-my-way` has changed how it outputs/prints it's route map. It's a little hard doing the visual diff. I do hope to have a PR up at some point.

We do need to upgrade node. There are issues #1921 & pr #1923 for that. I've dug through the changelog & there don't seem to be any obvious significant changes. I think it may just be this route printing. Hopefully I'll have a PR up soon.
