### ISSUE TITLE
TypeError: Cannot set property closed of #<Readable> which has only a getter

### ISSUE THREAD

**Issue by ffchristian** [restify/node-restify#1925]
- [x] Used appropriate template for the issue type
- [ ] Searched both open and closed issues for duplicates of this issue
- [ ] Title adequately and _concisely_ reflects the feature or the bug

**Restify Version**: 8.6.1
**Node.js Version**:  v18.*

## Expected behaviour
Restify should run through when using node v18

## Actual behaviour
/app/node_modules/restify/lib/request.js:848
    Request.prototype.closed = function closed() {
                             ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (/app/node_modules/restify/lib/request.js:848:30)
    at Object.<anonymous> (/app/node_modules/restify/lib/server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/node_modules/restify/lib/index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)

Node.js v18.10.0

## Repro case
npm start your app using restify latest (8.6.1) unsing nodeJs v18.*

## Cause
node_modules/restify/lib/request.js:848:30
here there is a getter function called ' Request.prototype.closed "
I think node in its version 18 uses this in another internal process and gets mixed up

## Are you willing and able to fix this?
Yes I found the solution I can make a MR so you guys can add the fix and I can keep using this wonderful framework in my projects.

I'm gonna need access to push the branch and make the MR it's a pretty simple fix you guys can evaluate it.

**Comment by hmharsh** [comment]
facing the same issue while creating the echo bot by following the steps: https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=javascript%2Cvs#start-your-bot

**Comment by hmharsh** [comment]
I update the line number 848 in `node_modules/restify/lib/request.js` from `Request.prototype.closed = function closed() {` 
to 
`Request.prototype._closed = function closed() {` 

as mentioned in https://stackoverflow.com/a/54562876

And it worked

**Comment by nyvs** [comment]
having the same problem...

**Comment by nyvs** [comment]
@ffchristian you should do a pull request, so they can fix it

**Comment by meteorlxy** [comment]
Already a PR there: https://github.com/restify/node-restify/pull/1906

**Comment by ffchristian** [comment]
I don't have access to the repo thus I cannot make the MR, but in deed there is one already which also tackles the issue

**Comment by DataKnox** [comment]
> facing the same issue while creating the echo bot by following the steps: https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=javascript%2Cvs#start-your-bot

Also why I am here. Using nvm, I installed node v16 and used that, which now works

**Comment by mmarchini** [comment]
this is fixed on restify 10

**Comment by tariromukute** [comment]
> I'm facing that issue starting the server with this command "npm start " Request.prototype.closed = function closed() { ^ TypeError: Cannot set property closed of # which has only a getter

Try upgrading restify. I got `"restify": "^11.1.0"` and it works now. Do `npm remove restify` and the `npm i restify`. I am using node 18.

**Comment by Chukarslan** [comment]
Why Jonathan... whaaaay?? :(
I loved the Python SDK but I'm forced to use JS - thanks JS devs you're the worst

**Comment by francojuliofranco14-bit** [comment]
> * [x]  Used appropriate template for the issue type[ ]  Searched both open and closed issues for duplicates of this issue[ ]  Title adequately and _concisely_ reflects the feature or the bug
> 
> **Restify Version**: 8.6.1 **Node.js Version**: v18.*
> 
> ## Expected behaviour
> Restify should run through when using node v18
> 
> ## Actual behaviour
> /app/node_modules/restify/lib/request.js:848 Request.prototype.closed = function closed() { ^
> 
> TypeError: Cannot set property closed of # which has only a getter at patch (/app/node_modules/restify/lib/request.js:848:30) at Object. (/app/node_modules/restify/lib/server.js:33:1) at Module._compile (node:internal/modules/cjs/loader:1149:14) at Module._extensions..js (node:internal/modules/cjs/loader:1203:10) at Module.load (node:internal/modules/cjs/loader:1027:32) at Module._load (node:internal/modules/cjs/loader:868:12) at Module.require (node:internal/modules/cjs/loader:1051:19) at require (node:internal/modules/cjs/helpers:103:18) at Object. (/app/node_modules/restify/lib/index.js:10:14) at Module._compile (node:internal/modules/cjs/loader:1149:14)
> 
> Node.js v18.10.0
> 
> ## Repro case
> npm start your app using restify latest (8.6.1) unsing nodeJs v18.*
> 
> ## Cause
> node_modules/restify/lib/request.js:848:30 here there is a getter function called ' Request.prototype.closed " I think node in its version 18 uses this in another internal process and gets mixed up
> 
> ## Are you willing and able to fix this?
> Yes I found the solution I can make a MR so you guys can add the fix and I can keep using this wonderful framework in my projects.
> 
> I'm gonna need access to push the branch and make the MR it's a pretty simple fix you guys can evaluate it.
