### ISSUE TITLE
Restify support for nodejs v20 is merged but not released 

### ISSUE THREAD

**Issue by abdallamourad** [restify/node-restify#1968]
node-restify support for nodejs v20 is merged but not released, is it possible to release it?

**Comment by larsdecker** [comment]
@mmarchini  Can you take a look on it?

**Comment by mmarchini** [comment]
11.2.0 released

**Comment by phil-warner** [comment]
Thanks @mmarchini ! Could you publish it to npm please?

**Comment by rohityadav225** [comment]
@mmarchini  @larsdecker can you please let us know when v11.2.0 will be available on NPM registry ?

**Comment by josephcrawfordSRH** [comment]
@mmarchini I am also interested in when 11.2.0 will be available in the NPM registry.
