### ISSUE TITLE
server after event does not fire and AuditLogger does not seem to function

### ISSUE THREAD

**Issue by agad** [restify/node-restify#201]
Using the 1.4 branch on a windows machine.  v .80 of Node.  I am trying to listen for the after event with no luck.  Not sure if its something I am doing wrong.  I wanted to be able to use my own logging to audit events.  However, I figured I'd then try to simply wire up the auditLogger and that does not seem to work either - the audit file gets created but then there is no output.  here's the code I use, copied from the docs:

``` javascript
server.on('after', restify.auditLogger({
  log: new Logger({
    name: 'audit',
    stream: process.stdout
  })
}));
```

Nothing fires if I try the below code either.

``` javascript
server.on('after', function test(req, res) {
    console.log("reached after");
});
```

**Comment by pieterjandesmedt** [comment]
I'm a bit late to the party, but this was one of the first result Google returned `restify auditlogger not working`. 

If you chain server functions, `.listen()` must come _after_ `.on()`, otherwise the auditlogger won't work even if you're calling `.next()` properly.

This didn't log anything:
```
	server
		.pre(cors.preflight)
		.use(cors.actual)
		.pre(restify.plugins.pre.userAgentConnection())
		.pre(restify.plugins.pre.dedupeSlashes())
		.use(restify.plugins.queryParser())
		.use(restify.plugins.bodyParser({ mapParams: true }))
		.use(restify.plugins.gzipResponse())
		.listen(port, function () {
			logger.info(`${api.name} listening at ${server.url}`);
		})
		.on('after', function test() {
			console.log('reached after');
		})
		.on(
			'after',
			restify.plugins.auditLogger({
				log: logger,
				event: 'after',
			}),
		);
```

This logged both to the console and to the bunyan logger I use:

```
	server
		.pre(cors.preflight)
		.use(cors.actual)
		.pre(restify.plugins.pre.userAgentConnection())
		.pre(restify.plugins.pre.dedupeSlashes())
		.use(restify.plugins.queryParser())
		.use(restify.plugins.bodyParser({ mapParams: true }))
		.use(restify.plugins.gzipResponse())
		.on('after', function test() {
			console.log('reached after');
		})
		.on(
			'after',
			restify.plugins.auditLogger({
				log: logger,
				event: 'after',
			}),
		)
		.listen(port, function () {
			logger.info(`${api.name} listening at ${server.url}`);
		});
```
