### ISSUE TITLE
Test Restify clients by mocking API responses

### ISSUE THREAD

**Issue by cjroebuck** [restify/node-restify#238]
I'm trying to test my restify Json client by mocking out the api. I've tried using sinon, node-fakeweb and now nock. Neither of these mocking solutions seem to work when I use restify's Json or http client. 

Does anyone have any idea why restifys clients are behaving differently, from what I can see they are all using node's http.request method - so the mock should work.

**Comment by avimar** [comment]
I was using node-mocks-http but I realized that it was a bit artificial around the way the POST, GET are handled and skips most of the handlers.
So, unfortunately, I went for full-on integration tests with mocha & supertest. The code seems to be shorter and works pretty decently. Just, I need to have the server spun up to actually test. Oh well, it seems to work well.
