### ISSUE TITLE
custom error handler

### ISSUE THREAD

**Issue by mongris** [restify/node-restify#270]
I can user some code like

```
  app.use(function(err, req, res, next) {
    ...
  });
```

in express to translate the error information.

How about in restify?

**Comment by slaveofcode** [comment]
I've been trying to catch all errors by using this code

    server.on('error', function (req, res, err, next) {
      // the default handler
      res.send(err)
    })

as the docs said `Restify servers emit all the events from the node http.Server and has several other events you want to listen on.`

**Comment by awesomehimanshu** [comment]
server.on('uncaughtException', function (req, res, route, err) { })

doesn't work .

C:\tfs.mercer.com\ICS.DevStack\mobile-api\controllers\blurb.controller.js:17
     throw new Error('The message');//  error("new");
     ^

Error: The message
