### ISSUE TITLE
Automatic OPTIONS responses were removed

### ISSUE THREAD

**Issue by williamkapke** [restify/node-restify#284]
A recent checkin (d1366f2f860d0c1804fe74db1774eecf482d3ebf) stopped Restify's auto handling of `OPTIONS` requests. We now have the ability to create them manually.

Although more control is good, manually adding `OPTIONS` for every endpoint is cumbersome and (if your application relies on CORS requests) can make it hard to move to Restify v2.

I propose that the auto generated `OPTIONS` responses are "on by default" and developers can override the default by specifying `server.opts(...)`. It would probably also be good to have a way to globally disable them.

**Comment by vchatterji** [comment]
If your pre-flight `OPTIONS` request specifies which headers it want to send:
`'access-control-request-headers': 'authorization, content-type'`

THEN, these headers should be allowed in a subsequent CORS request:
```
restify.CORS.ALLOW_HEADERS.push("authorization");
restify.CORS.ALLOW_HEADERS.push("content-type");
```

If the requested headers are not allowed, then the `OPTIONS` request will itself fail:
```
HTTP/1.1 405 Method Not Allowed
Allow: POST
Content-Type: application/json
Content-Length: 67
Date: Mon, 27 Jun 2016 15:30:37 GMT
Connection: keep-alive
```
The response indicates that if the client was to send a request with the headers `authorization` and `content-type`, the server would NOT allow that method (as these headers are not enabled).
