### ISSUE TITLE
Trailing Slashes in route paths

### ISSUE THREAD

**Issue by godfoder** [restify/node-restify#285]
In restify 1.4 the following statement:

``` javascript
server.get('/:apiversion/:bucket', getList);
```

used to respond to both http://localhost/v1/records and http://localhost/v1/records/

In version 2.0, this no longer works by default, and in the little bit of trouble shooting I've done so far, I can't even seem to explicitly make it happen:

``` javascript
server.get('/:apiversion/:bucket/', getList);
server.get('/:apiversion/:bucket', getList);
```

Am I missing something really obvious here, or does restify no longer support trailing slashes on paths?

**Comment by slavafomin** [comment]
Hello there!

How do I enable routing with routes having trailing slash? Right now, restify removes trailing slashes from my routes and I don't want that.

Please advise, thank you!

P/S: I'm using restify `4.0.3`.

**Comment by micahr** [comment]
@slavafomin when creating your route, you have an option of passing in your own Regexp:

```javascript
server.get(/\/foo\//, function(req, res, next) {
  // handle the route
});
```

**Comment by slavafomin** [comment]
Hello @micahr , is there a better option? Why Restify can't match routes exactly as they are stated in the configuration? This looks like a serious drawback to me. Using RegExps is overkill and makes code look ugly.

**Comment by DonutEspresso** [comment]
@slavafomin yes, this is feature we'd like to support per #692.

**Comment by maxsummers** [comment]
Are there any news?

**Comment by reothues** [comment]
`server.get('/your/action/:forgetaboutit', handler);
get 'yourserver/your/action/' now works

then you can forget about it. 
there is a null value of req.params.forgetaboutit
