### ISSUE TITLE
HTTP forward proxy support in http_client

### ISSUE THREAD

**Issue by AlainODea** [restify/node-restify#349]
If [mikeal/request](https://github.com/mikeal/request) was brought in and [http_client.rawRequest()](https://github.com/mcavage/node-restify/blob/c39e1acabac5610dd4d16ff4c0e524068e742bce/lib/clients/http_client.js#L81) was altered to use @mikeal's support for proxies it might work.

Here is code that is unlikely to work (I haven't tried it, but it may be a useful starting point):
```javascript
var proxy = opts.protocol === 'https:' ? process.env.https_proxy: process.env.http_proxy;
var r = request.defaults({'proxy': proxy});
r(opts, function onResponse(res) {
                clearTimeout(timer);
                dtrace._rstfy_probes['client-response'].fire(function () {
                        return ([ id, res.statusCode, res.headers ]);
                });
                log.trace({client_res: res}, 'Response received');

                res.log = log;

                var err;
                if (res.statusCode >= 400)
                        err = errors.codeToHttpError(res.statusCode);

                req.removeAllListeners('error');
                req.removeAllListeners('socket');
                req.emit('result', (err || null), res);
        });
```

Having HTTP proxy support would be useful for client's behind filtering web proxies like Squid and firewalls that don't allow direct access to the servers hosting the REST APIs being consumed.

**Comment by micahr** [comment]
Proxy support is built in to the http client. If your problem is not fixed by using this, please re-open.
