### ISSUE TITLE
bodyParser issue for images upload

### ISSUE THREAD

**Issue by nikravi** [restify/node-restify#383]
Hello

I was debugging lots of code these days, and I found the issue I'm facing with an image upload.
The mobile app is sending an image with "multipart-form-data" content type. The "magic number" is `ffd8ffe0` (a jpeg image). But after it passes throw the `bodyParser`, it becomes `fdfdfdfd` which is something unknown and not useful for me..
And the code that is causing this is inside the `multipartParser.js`

```
Object.keys(files).forEach(function (f) {
       if (req.params[f] && !override)
               return (false);
       var fs = require('fs');
       return fs.readFile(
           files[f].path,
           'utf8', //why utf-8? if it's binary, all is good. utf-8 would be good for txt files I guess
           function (ex, data) {
               if (ex) {
                    return (false);
               }
               console.log((new Buffer(data, 'binary')).toString('hex', 0, 4)) //the magic number
               req.params[f] = data;
               return (true);
       });
});
```

The utf-8 encoding is hard coded in the bodyParser. Can we remove it, or get dynamically assigned with the use of https://github.com/SaltwaterC/mime-magic? or based on the request content type, read the file with corresponding encoding?

Thanks..

**Comment by micahr** [comment]
This looks like it's still an issue with the multipart_parser plugin.
