### ISSUE TITLE
CORS plugin does not handle 'X-Requested-With' for preflight requests

### ISSUE THREAD

**Issue by Burstaholic** [restify/node-restify#386]
I'm experiencing the issue where an 'OPTIONS' request always receives '405 Method Not Allowed," noted in https://github.com/mcavage/node-restify/issues/284#issuecomment-13153380

I am using a workaround from the same issue thread, but it would be very helpful to have this response built-in going forward, instead of needing to re-create it in every such application.
(Workaround: https://github.com/mcavage/node-restify/issues/284#issuecomment-15336182)

I'm very new to programming in this area, so I'm unsure if this is genuinely broken in the plugin or a consequence of a design decision, but it was at the least very confusing from the perspective of someone new to dealing with REST services and HTTP headers and could use better documentation.

**Comment by micahr** [comment]
As X-Requested-With isn't in the list of allowed headers, I'm inclined to close this. If you'd like the allowed headers updated, feel free to submit a PR.
