### ISSUE TITLE
FullResponse-Plugin "overwrites" CORS-plugin

### ISSUE THREAD

**Issue by dominiklessel** [restify/node-restify#391]
Hello there!

I got the following situation: I'm using the CORS- and FullResponse-Plugin at the same time. 

The comment in the CORS-Plugin states that it won't send any CORS headers if the origin header is not set or doesn't match any whitelisted origin – that's okay.

But on the other hand the FullResponse-Plugin just sets the "Access-Control-Allow-Origin" header to "*" if it's not existing and at the same time a bunch of other Access-Control-Headers, which do not match any of my CORS settings.

Is there any good reason for that?

**Comment by micahr** [comment]
This still seems to be a bug as the `full_response.js` plugin will add Access-* headers if they aren't present, regardless of what the CORS plugin determines. 

Adding this issue to the 3.1.x milestone.

**Comment by madebyherzblut** [comment]
Any news on this one?

**Comment by gszathmari** [comment]
I am having the same issue. fullheaders override my CORS settings

**Comment by retrohacker** [comment]
CORS has found a new home and has undergone a significant rewrite. I believe the new implementation fixes this problem :tada:

If I'm missing something here, please comment and we can re-open this issue to discuss :heart: 

https://github.com/TabDigital/restify-cors-middleware/
