### ISSUE TITLE
Modifying Request in a "Pre"

### ISSUE THREAD

**Issue by ullmark** [restify/node-restify#392]
Hi,
I've read the docs and I don't think restify have any support for what I'm trying to accomplish in a "pre". Namely a way to enable POST, DELETE etc. from a browser JSONP client. X-HTTP-METHOD-OVERRIDE isn't applicable since it's only used in a POST.

I've previously in other APi frameworks solved it by supporting a *_method* query string for JSONP requests. 

Something like this; 
```javascript
var restify = require('restify'),
    jsonpOverride = require('restify-jsonpoverride');

var server = restify.createServer();
// query parser is needed, for the override and therefor must be configured as 
// a pre. **mapParams** must be set to false due to bug in query parser
server.pre(restify.queryParser( mapParams: false ));
server.pre(jsonpMethodOverride());
server.use(restify.jsonp());

// this route is executed on
// **POST**: /foo
// **GET**: /foo?_method=POST&callback=something
server.post('/foo', function(req, res, next) {
});
```
My problems are twofold; first, mapParams must be set to false if you want to use queryparser in a *pre* otherwise it crashes. Secondly, something after my plugin sets the **params** of the request to empty object.

Any ideas or thoughts?

**Comment by micahr** [comment]
If you are still interested in adding this feature, please submit it a pull request for a new plugin.
