### ISSUE TITLE
Overriding the 406 (not Acceptable) error

### ISSUE THREAD

**Issue by cyrilf** [restify/node-restify#402]
I just can't find any easy way of overriding the default 406 error (not acceptable).

In fact, I've found this documentation [Server API](http://mcavage.github.io/node-restify/#Server-API). 
But I think restify isn't emitting events for each errors. For example, I've successfully overridden the 404 (notFound) error.

Can you add "notAcceptable" as an event sent by restify or tell me how to do it ?

**Comment by matteocontrini** [comment]
Hi,
I was having the same requirement and I created a plugin like this, if anyone needs an example.

```js
function acceptJSON(req, res, next) {
	if (req.accepts('application/json')) {
		next();
		return;
	}
	else {
		var e = new MyNotAcceptableError();
		res.json(e);
		next();
	}
}
```

But can anyone explain why `res.json(e)` works and `res.send(e)` not, generating something like an infinite loop?
Thanks.

**Comment by DonutEspresso** [comment]
I'd suggest opening a new issue since it's unrelated, but to answer your question you probably have a formatter that isn't invoking its callback and so it just hangs. `res.json` will automatically set the content-type to JSON, but `res.send` will not.
