### ISSUE TITLE
server.on('after', ...) doesn't get emitted

### ISSUE THREAD

**Issue by llacroix** [restify/node-restify#416]
Here is a small sample that shows the problem. May be I got the documentation wrong. As I understand, 'after' should be always called except with errors that may require calling next... 

```
restify = require('restify')

server = restify.createServer({
    name: 'Test After'
})

server.use (req, res, next) ->
    console.log('before')
    next()

server.on 'after', (req, res) ->
    console.log('after')

server.get 'test', (req, res) ->
    res.send({ok: true})

server.listen(6060)
```

In this example, it will not call 'after' because the get('test', ...) isn't calling next. I can't talk for everyone but if I must call next on every route, it could make sense to add a new event to watch for response.  

```
server.on('response', ...)
```

**Comment by MadsRC** [comment]
@antoinegomez - You just saved me a few hours of debugging!

**Comment by jcalderonzumba** [comment]
@antoinegomez 👍 I was having problems too. Thanks. somebody in the documentation should put in CAPS that if you want to properly have server.on("after") you **MUST** call next(); after res.send();
