### ISSUE TITLE
createServer does not support https.createServer ciphers and honorCipherOrder option

### ISSUE THREAD

**Issue by paixaop** [restify/node-restify#460]
In order to control what ciphers are available createServer should support the ciphers options.

    https.createServer({
            ...
            ciphers: 'ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:RC4:HIGH:!MD5:!aNULL:!EDH',
            honorCipherOrder: true
    });

in fact the restify createServer method should support all options of https, and http createServer methods.

**Comment by micahr** [comment]
Seems that several commits were merged into master which ultimately resolved the main issue, going to go ahead and close this issue. Please re-open if it's not resolved.

**Comment by agentS** [comment]
Although having set the option `honorCipherOrder` to `true` sslyze still complains that the client's cipher order is preferred over the server's order.

    * Session Renegotiation:
        Client-initiated Renegotiations:   VULNERABLE - Server honors client-initiated renegotiations

Below you can see my source code:

    var httpsServer = restify.createServer
    ({
        ...
       honorCipherOrder: true,
       ...
   });

**Comment by micahr** [comment]
Are you passing the ciphers you want to use into the `createServer` call?

**Comment by agentS** [comment]
Yes, I am passing a string storing the value of a configuration file. I have updated my previous comment.

**Comment by agentS** [comment]
Yes, I am passing a variable holding the string stored inside a configuration file or a default value if no string is specified in the config file.

    function ApplicationSettings()
    {
        this.serverPort = 4443;
        this.certificateFile = __dirname + "/../cert/webservice.pem";
        this.keyFile = __dirname + "/../cert/webservice.key";
        this.intermediateCAFile = __dirname + "/../cert/startSSL_intermediateClassA.pem";
        this.ciphers = "EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA";
    }

    var settings = new ApplicationSettings();

    var httpsServer = restify.createServer
    ({
        key: fs.readFileSync(settings.KeyFile),
        cert: fs.readFileSync(settings.CertificateFile),
        ca: [ fs.readFileSync(settings.IntermediateCAFile) ],
        ciphers: settings.Ciphers,
        honorCipherOrder: true,
        name: "..."
    });

**Comment by agentS** [comment]
Yes, I am passing a variable holding the string stored inside a configuration file or a default value if no string is specified in the config file.
    function ApplicationSettings()
    {
        this.serverPort = 4443;
        this.certificateFile = __dirname + "/../cert/webservice.pem";
        this.keyFile = __dirname + "/../cert/webservice.key";
        this.intermediateCAFile = __dirname + "/../cert/startSSL_intermediateClassA.pem";
        this.ciphers = "EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA";
    }

    var settings = new ApplicationSettings();

    var httpsServer = restify.createServer
    ({
        key: fs.readFileSync(settings.keyFile),
        cert: fs.readFileSync(settings.certificateFile),
        ca: [ fs.readFileSync(settings.intermediateCAFile) ],
        ciphers: settings.ciphers,
        honorCipherOrder: true,
        name: "..."
    });

**Comment by agentS** [comment]
Yes, I am passing a variable holding the string stored inside a configuration file or a default value if no string is specified in the config file.

    function ApplicationSettings()
    {
        this.serverPort = 4443;
        this.certificateFile = __dirname + "/../cert/webservice.pem";
        this.keyFile = __dirname + "/../cert/webservice.key";
        this.intermediateCAFile = __dirname + "/../cert/startSSL_intermediateClassA.pem";
        this.ciphers = "EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA";
    }

    var settings = new ApplicationSettings();

    var httpsServer = restify.createServer
    ({
        key: fs.readFileSync(settings.keyFile),
        cert: fs.readFileSync(settings.certificateFile),
        ca: [ fs.readFileSync(settings.intermediateCAFile) ],
        ciphers: settings.ciphers,
        honorCipherOrder: true,
        name: "..."
    });

**Comment by micahr** [comment]
Looks like there is some evidence this isn't resolved. I'll reopen.

**Comment by agentS** [comment]
Thanks.
