### ISSUE TITLE
Error handling documentation is incomplete.

### ISSUE THREAD

**Issue by ericelliott** [restify/node-restify#466]
## Edit / resolution

The documentation about error handling is incomplete and confusing. Maybe it would help to explicitly clarify the following points in the section on error handling:

1. Handle your errors immediately, where they're generated. `next(err)` really means `res.send(err)`. It's not an alternative to `throw err`. If you need to log and shut down, pass it off to an error handling module instead of stuffing it in `next(err)` where it will be swallowed.
1. `server.on('uncaughtException'...` is how you handle any errors that were thrown in middleware / routes. It works fine for that purpose, as long as you remember the first guideline. **`'uncaughtException'` will not be triggered for `next(err)` calls.**
1. `formatters` are the way to customize error messages going out to the users. I don't think they should be used for the other tasks described in this thread. They're definitely not a viable alternative to dealing with errors in `uncaughtException`, because presumably, once you get there, you're sending the user the error you want *them* to see... not necessarily the error that was originally generated. See point 1.
1. For errors unrelated to middleware, remember to use `process.on('uncaughtException'...`

Here's the original issue, for posterity:

## Problem

Restify swallows all errors coming from route handlers. It does invoke its own error handler, but that handler never bails, regardless of whether or not an error is recoverable.

## Expected

It should be up to the application developer to determine whether or not a service restart is needed. While it should be safe to swallow 4xx errors, other types of unhandled errors could leave the application in undefined state, which could lead to all sorts of trouble.

## Reproduce

Restify v2.6.0
Node v0.10.20

```js
var restify = require('restify'),
  app = restify.createServer(),
  errorHandler = require('../error-handler.js'),

  handleError = function handleError(err) {
    console.log('Caught error!'); // never happens
    setTimeout(function () {
      process.exit(1);
    }, 3000);
  },

  middlewareError =
      function middlewareError(req, res, next) {
    throw new Error('Random middleware error.');
  };


app.get('/err', function (req, res, next) {
  // This doesn't get caught.
  next( new Error('Random unrecoverable error. ' +
    'Server is now running in undefined state!') );
});

app.get('/throwerr', function (req, res, next) {
  // This doesn't get caught.
  throw new Error('Random unrecoverable error. ' +
    'Server is now running in undefined state!');
});

// This gets caught, yay!
app.use(middlewareError);

app.get('/middleware', function (req, res, next) {
  // Placeholder to invoke middlewareError.
});

// This works for middleware. Fails for routes.
app.on('uncaughtException', handleError);

// Nope. This doesn't help.
process.on('uncaughtException', handleError);

app.listen(3000, function () {
  console.log('Listening on port 3000');
});
```

**Comment by micahr** [comment]
A little late, but: `server.on('NotFound', function(req, res, err, next){})` is the best way to handle routes that aren't matched by any existing routes.

Closing as the documentation has been updated slightly in the 1.5 years since the last update.

**Comment by Zertz** [comment]
@micahr Just to confirm, there is no way for the developer to override `next(err)` so it isn't swallowed by restify?

**Comment by DonutEspresso** [comment]
Nexting with an err doesn't get swallowed - it's just shorthand for `res.send(err).`

**Comment by Zertz** [comment]
@DonutEspresso Thanks for the quick response!

There is a library for automatically generating REST endpoints from mongoose models, with support for both express and restify. Here's an example: https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L158

I'm trying to figure out if there a way to call `next(err)` and handle it similarly to express rather than having it call `res.send(err)` immediately?

**Comment by DonutEspresso** [comment]
You can use the error events to handle errors on a per type basis:

```js
function (req, res, next) {
    return next(new NotFoundError('file not found!');
}

server.on('NotFound', function(req, res, err, next) {
   // handle your error here
});
```

It does mean you have to be very explicit about your error types. There's ongoing work right now to support a generic catch all handler over in #892 , allowing you to handle _all_ error types:

```js
server.on('restifyError', function(req, res, err next) {
    // handle all errors passed to next here, whether it's Error or NotFoundError or anything that is an instance of Error
});
```

**Comment by Zertz** [comment]
@DonutEspresso That would be awesome! For us it simply becomes a matter of reordering parameters internally and exposing a standard interface.

**Comment by DonutEspresso** [comment]
Cool - keep your eyes peeled, it's looking likely that this stuff will land in the next major release along with the breaking out of all the plugins, clients, and error modules.

**Comment by Zertz** [comment]
Do you have a rough ETA?

**Comment by micahr** [comment]
No specific timeline, but hopefully the next week or two.

**Comment by chbrown** [comment]
Is there a proper way to do this yet? The aforementioned #892 is open, but this issue is closed, so maybe there is an alternate solution?

**Comment by DonutEspresso** [comment]
Sorry all - this fell off my radar. Will try to get this merged into 5.x branch, but a proper release is probably still a bit out.

**Comment by Anaphase** [comment]
Any update on this? It would be great if Restify supported connect-style error middleware, or at least had it documented somewhere that it doesn't.

**Comment by Zertz** [comment]
@DonutEspresso Is there anything we can do to help?

**Comment by pourquoi42** [comment]
I am trying to use restify with swagger node. For some requests, I get validation errors and I have no clue how and where to catch them. I would really appreciate a way to catch all errors and handle them, instead of spending hours on trial and error.

**Comment by DonutEspresso** [comment]
@Anaphase - when you say connect style error middleware, what behavior are you expecting? 

Also, would appreciate if we could move discussion to a new issue, as this thread is pretty old and we have brand new docs site being written up right now. 

Here's a new section on errors being released with the new docs:
https://github.com/restify/node-restify/blob/5.x/docs/pages/components/server.md#errors

**Comment by Anaphase** [comment]
@DonutEspresso, by "connect style error middleware" I mean the 4-argument middleware [described here.](http://expressjs.com/en/guide/error-handling.html) Basically, if your middleware function has four arguments, it's treated as an error handler. I guess the Restify equivalent would be the `restifyError` event, with the exception that after the `restifyError` event, the error is just sent instead of processing the rest of the middleware in the chain. (Unless I'm wrong about that behavior.)

**Comment by DonutEspresso** [comment]
You can set your own custom content in the event handlers (including `restifyError` event) by doing something like this:

```js
server.on('InternalServer', function(req, res, err, callback) {
    err.body = 'Sorry, an error occurred!';
    return callback();
});
```

Alternatively, if you don't set body, then restify will just flush a serialized error out to the client.
