### ISSUE TITLE
Responsability of Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by ghost** [restify/node-restify#477]
When using both full Response and Cors:

server.use(restify.CORS());
server.use(restify.fullResponse());

It seems there is no way to add an Access-Control-Expose-Headers.

Using cors options seems non-working.
var corsOptions={
	headers : [ "lol"]
};
server.use(restify.CORS(corsOptions));

Modifying directly... same way
restify.CORS.ALLOW_HEADERS.push("lol");

And I didn't found a way for fullResponse.

So if there is a solution, it seems obscure.

**Comment by micahr** [comment]
Closing as a duplicate of #391
