### ISSUE TITLE
Getting condtionalRequest plugin work

### ISSUE THREAD

**Issue by talha-asad** [restify/node-restify#482]
I have a route that serves an item from mongoDB. I don't know how to use the conditional plugin with restify to make sure restify sends a 304 Not Modified header if the Etag matches or modified date is older than the retrieved date. How can i get this to work?

The example on the homepage of restify seems not to work, in the sense it doesn't send a 304 header and neither does it call next();

This is a pretty fundamental use case in my opinion.

**Comment by fvisticot** [comment]
Can you please provide an example to set etag and compute etag value from body response ?
