### ISSUE TITLE
Response Header Function

### ISSUE THREAD

**Issue by nalum** [restify/node-restify#484]
Just tried adding headers to the Response on a post request and found that the Restify function `res.header(key, value)` does not work but `res.header(key)` does. I worked around it by using the Node.js HTTP `response.setHeader(name, value)`.

```
nodejs@0.10.21
└─┬ restify@2.6.0
  ├── assert-plus@0.1.2
  ├── backoff@2.2.0
  ├─┬ bunyan@0.21.1
  │ └── mv@0.0.5
  ├── deep-equal@0.0.0
  ├── dtrace-provider@0.2.8
  ├── escape-regexp-component@1.0.2
  ├── formidable@1.0.14
  ├─┬ http-signature@0.10.0
  │ ├── asn1@0.1.11
  │ ├── assert-plus@0.1.2
  │ └── ctype@0.5.2
  ├── keep-alive-agent@0.0.1
  ├── lru-cache@2.3.0
  ├── mime@1.2.9
  ├── negotiator@0.2.5
  ├── node-uuid@1.4.0
  ├── once@1.1.1
  ├── qs@0.6.4
  ├── semver@1.1.4
  ├── spdy@1.8.2
  └─┬ verror@1.3.6
    └── extsprintf@1.0.2
```

**Comment by teh1** [comment]
This same thing is happening to me... And upon looking at the source code I see that if a response formatter doesn't exist for a contentType, it will default to "application/octet-stream". That is most likely also what you are experiencing. This should be further clarified somewhere, as it's not very clear.

Adding the correct "image/jpeg" (or in your case "text/html") formatter in the createServer function fixes it for me.
