### ISSUE TITLE
JsonClient Error Handling - Call a Json service, then Ctrl-X the service : Error: read ECONNRESET - throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Analogreality** [restify/node-restify#485]
I am creating a JsonClient with Restify, calling a web service, then Ctrl-X terminating the remote Json service..

The client dies hard EVEN with error handling:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)

Here's the simple program I am using:

var client = restify.createJsonClient({
  url: "http://localhost:5653",
  version: '*'
});

client.on("error", function (err) {
    console.log("ssss" + err);
});

client.get("/program/state", function (err) {
    console.log("gett");
});

The problem isn't with an error during the call, only much later.. seemingly when the client is idle..

**Comment by ygrenzinger** [comment]
Just for information to the Restify dev.

I have the same problem. The service I call trash the connection for a reason I don't really know. An ECONNRESET error is sent from NodeJS which the server crash even with server.on('uncaughtException', (req, res, route, error) => {..}).

I have added client.on('error', function (err) { ... });

But It doesn't get through.

Only the agent : false solved this problem.

I'm using Restify 4.0.3

Is it normal ?
