### ISSUE TITLE
Can I specify content types accepted by restify?

### ISSUE THREAD

**Issue by lobodpav** [restify/node-restify#488]
I've read through the DOC many times, but unable to find a way to force restify to accept certain content types only.

Example1: I want to instruct the `bodyParser` to accept `application/json` content type only.

Example2: I want to instruct any request to accept `json` content type only even when `bodyParser` is not added as a plugin.

Is there a better way then to check for content-type header within each route?

**Comment by c0b** [comment]
> You can set the acceptable (or server.acceptParser) param to tell restify to 415 all clients expecting a response type different than ones you may reply with.

Is this acceptable option still working as designed?

```js
const server = restify.createServer({
  acceptable: 'application/json',
});

// or
const server = restify.createServer({
  acceptable: [ 'application/json' ],
});

console.log(server.acceptable);
```

seems always output the 4 acceptable format, 

```json
[ 'application/json',
  'text/plain',
  'application/octet-stream',
  'application/javascript' ]
```

Then I have to use acceptParser to get wanted behavior in  Example1: I want to instruct the bodyParser to accept application/json content type only.

```js
server.use(restify.plugins.acceptParser([ 'application/json' ]));
```

then what's the purpose of `acceptable` parameter in createServer ?

**Comment by DonutEspresso** [comment]
Thanks @c0b, looks like the docs may have fallen a bit out of date. 

From what I can tell, `createServer` derives acceptable types from `options.formatters`. So `options.acceptable` isn't used at all. I don't have historical context on the accept plugin, but seems to me that defining formatters should cover pretty much most if not all use cases. I'll file an issue on the doc update.
