### ISSUE TITLE
Using PKCS12/PFX for starting TLS/SSL

### ISSUE THREAD

**Issue by rdev5** [restify/node-restify#511]
From http://mcavage.me/node-restify/#Creating-a-Server

Any chance you could expose and/or support the option to pass a PKCS12 (pfx) store as shown here: http://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

**Comment by lordbah** [comment]
I'd like to do the same. Where does getCertificate() come from?

**Comment by gimansour** [comment]
using the spdy options didn't work for me, I had to replace that with `httpsServerOptions`

my code ended up looking something like this:
```
var server = restify.createServer({
            httpsServerOptions: { 
            pfx: fs.readFileSync('key.p12'),
            passphrase: "passphrase",
             },
        });
```
