### ISSUE TITLE
Add "license" and "licenses" to package.json

### ISSUE THREAD

**Issue by garthk** [restify/node-restify#513]
Specifying your [license] in `package.json` makes it a lot easier for your users to find and comply with [GNU Affero] licenses. 

Also giving `licenses` (an array of objects with `type` and `url` keys) helps  users whose legal departments request both the license name *and the text*. See this example from [async]:

      "licenses": [{
        "type": "MIT",
        "url": "https://github.com/caolan/async/raw/master/LICENSE"
      }]

Though `licenses` isn't specified in the [npm package.json spec][license], it *is* supported by the NPM site, as you'll see if you check [async's NPM page][async]. 

[GNU Affero]: http://www.gnu.org/licenses/agpl-3.0.html
[async]: https://npmjs.org/package/async
[asyncpj]: https://github.com/caolan/async/blob/master/package.json
[license]: https://npmjs.org/doc/json.html#license

Thanks!

**Comment by DonutEspresso** [comment]
@garthk, I saw your [thread](https://github.com/npm/npm/issues/4473) over at the npm repo. Now that npm is standardizing on SPDX, I consider this issue resolved.
