### ISSUE TITLE
Use Redis with Throttle Plugin

### ISSUE THREAD

**Issue by jrnewell** [restify/node-restify#518]
It looks like the throttle plugin is designed to be modular, but the plugin assumes that the tokensTable storage object does not use callbacks.  Therefore, it is difficult to provide a wrapper around a database like redis and pass it to the plugin as is.  It seems like it would be a good idea for the TokenTable API to assume the use of callbacks even though the default in-memory storage is synchronous.

**Comment by micahr** [comment]
Thank you for the request. It does make sense to have a consistent API throughout, and the use of callbacks in synchronous code makes it easier to integrate with asynchronous code. 

We'll put this on the backlog as it isn't a high priority to rewrite the TokenTable code. If you were able to provide a pull request to assist in getting this implemented, it would help speed up the timeline for getting this added.

Thanks!

**Comment by micahr** [comment]
Closing this in favor of #381 which has a few more details. The feature request will still remain on the backlog.
