### ISSUE TITLE
ResourceNotFoundError, InvalidVersionError and BadMethodError do not go through registered handler

### ISSUE THREAD

**Issue by vickvu** [restify/node-restify#520]
If an URL does not exist, restify return the ResourceNotFoundError without going through the register handlers. For example, if  I register a CORS handler
```javascript
server.use(restify.CORS());
server.get('/hello', function (req, res, next) { 
  res.send("hello");
  next();
});
```
And the client request an non-existent URL
```
curl -v http://localhost/abc
```
The 404 response from restify will not have any of the CORS response headers.

**Comment by micahr** [comment]
This doesn't seem to be a bug in Restify. You can use the `server.on('NotFound')` event to handle any routes that haven't been found, that in combination with Soarez's solution, should give you what you are looking for.
