### ISSUE TITLE
Restify not parsing data from a PUT method resquest, so frustrating...

### ISSUE THREAD

**Issue by ezsper** [restify/node-restify#521]
I'm using the latest version (2.6.1) of Restify, and I really don't know what is happening for the Restify not parsing the data submited on PUT/POST method, it simply doesn't make sense, Restify should be assigning the data to "req.params". I've just lost plenty of time to figured this out and I just didn't, I don't know what is going on. Is this a real issue or do I completely misunderstood the documentation?

So, I execute the follow curl command:

```
curl -is -X PUT -d "phone=1-800-999-9999" http://localhost:8080/note
```

And it just returns no params whatsoever, it must be returning the phone value submited on the curl command above:

```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4
Date: Wed, 29 Jan 2014 15:14:22 GMT
Connection: keep-alive
"{}"
```

This is the full code behinded, can't be more simple than this:

```
var restify = require('restify');
var server = restify.createServer({
  name: 'App',
  version: '1.0.0'
});
server.use(restify.acceptParser(server.acceptable));
server.use(restify.bodyParser());
server.use(restify.queryParser());
function send(req, res, next) {
  res.send(JSON.stringify(req.params));
  return next();
}
var server = restify.createServer();
server.put('/note', send);
server.listen(8080, function() {
  console.log('%s listening at %s', server.name, server.url);
});
```

Someone has an answer for this behavior? It really frustrating...

**Comment by micahr** [comment]
@lazutkin Are you still experiencing an error on performing a PUT with a recent version of Restify? If so, can you provide your request parameters, as well as your server setup? 

Thanks.

**Comment by lazutkin** [comment]
@gergelyke No, we already use express. Sorry

**Comment by micahr** [comment]
Thanks for the update. Perhaps @ezsper might be still experiencing this error?

**Comment by retrohacker** [comment]
Closing this issue as stale. If you are still experiencing problems, please comment and we can revisit :heart:

**Comment by konstardiy** [comment]
For me body did not parsed on PUT request.
req.body is just a `Buffer` instance.
restify plugins setup:
```javascript
server.use(restify.plugins.acceptParser(server.acceptable));
server.use(restify.plugins.authorizationParser());
server.use(restify.plugins.queryParser());
server.use(restify.plugins.gzipResponse());
server.use(restify.plugins.bodyParser());
```
restify version - `"restify": "^8.5.1",`
