### ISSUE TITLE
req.log(...) "too few args to sprintf"

### ISSUE THREAD

**Issue by silverbucket** [restify/node-restify#542]
When I try to call `req.log()` inside a route handler, regardless of the number of parameters, I get the following message to the browser.

```javascript:
{"code":"InternalError","message":"too few args to sprintf"}
```

No further information.

**Comment by micahr** [comment]
Can you provide the message you are passing to req.log? It might be related to #646

**Comment by DonutEspresso** [comment]
'InternalError' is indicative of an uncaught exception not being handled, without more information we cannot help you. 

Also, if you're using the requestLogger, `req.log` is an instance of bunyan, which means you'll need to call `req.log.info` to actually log something at info level.
