### ISSUE TITLE
CORS error while  returning restify error to browser

### ISSUE THREAD

**Issue by arjunrp** [restify/node-restify#551]
I use angular js as my front-end to restify, both exist in different domains, ie angular js in 'my.local' and restify in 'api.my.local'
Whenever i try to return error from my restify( eg return next(new restify.InvalidArgumentError('Invalid Username'));), The browser is throwing a CORS error(XMLHttpRequest cannot load http://api.my.local/authenticate. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://my.local' is therefore not allowed access. ) .
But it is working perfectly if the error raising line is deleted from the server side restify code.
Whats happening here? Can anybody clarify it?
Thanks

**Comment by micahr** [comment]
Using `server.on('NotFound', function(){})` should allow you to handle routes that aren't found and ensure the appropriate headers are sent. Because routes that aren't found don't have the full chain of handlers that get apply to routes that are found, you would have to do this manually.

**Comment by retrohacker** [comment]
This seems to have been resolved both by @shaunc's awesome example as well as the `NotFound` event handler.

If this is still a problem, please comment. We can re-open and discuss :heart:
