### ISSUE TITLE
Strange problem with bodyParser and multipart form data

### ISSUE THREAD

**Issue by markschmid** [restify/node-restify#562]
My client app sends JSON formatted data as a POST request with content-type "multipart/form-data" (there's also more data like images, hence the multipart content-type and not application/json) to my restify powered server.
The problem: In 99% of the cases, bodyParser parses the JSON just fine and then it's available in req.params, but in the other 1% of the cases, req.params is empty.

I haven't been able to figure out why bodyParser "fails" in those cases. I have tried many times with exactly the same payload. Most of the times, it works, sometimes it doesn't.
I have tried to use bodyParser's parameters (e.g. like mapParams and rejectUnknown to get hints on errors), but to no avail. Also, I have made a diff between a complete "req" object of a request where the parsing succeeded and of a req object where it failed.
The only real difference is, unsurprisingly, that in the first case it looks like:

```
params: { message: '{"my":{"funny":"json"}}' },
context: { message: '{"my":{"funny":"json"}}' },
```

whereas in the second requests it looks like:

```
params: {},
context: {},
```

In both req objects the "files part" look the same (except for minor diffs in regards to size, timestamp and such):

```
files: 
       { message: 
          { domain: [Object],
            _events: {},
            _maxListeners: 10,
            size: 174,
            path: '/var/folders/y4/fmd05m8x2g9b43xcxsnllfmh0000gn/T/12e4bfa4e139c58f2ebbe34e5cd84e83',
            name: 'messageEntry.json',
            type: 'application/json',
            hash: null,
            lastModifiedDate: Sat Mar 15 2014 13:27:48 GMT+0100 (CET),
            _writeStream: [Object] } },
```

Maybe it's not an issue of bodyParser but myself who's making some sort of mistake. Does anyone have an idea on how to proceed hunting the issue down? Any help/hint is greatly appreciated.

**Comment by micahr** [comment]
I wonder if there could be a problem with the multiple Content-Types sent in the first example. Perhaps both are being evaluated, even though the second one if for the content, not the overall request. Likely, the resolution of `req.getContentType()` is picking the content type from inside the body boundary, when it should be picking the first content-type.

Adding this to our next minor release.

**Comment by dyerw** [comment]
@micahr is there any follow up to this? I'm observing very similar behavior hitting restify using superagent. When I don't attach a file req.params is properly populated and when I do it's empty, but the file shows up.

**Comment by micahr** [comment]
No update from my side. I'll see if I can get some time to look into it.

**Comment by dyerw** [comment]
@micahr turns out it might not be restify's fault. I was using superagent's .send method, when I attached the data using .field everything worked properly. May not be a bug.

**Comment by retrohacker** [comment]
Marking this as unconfirmed for now until a maintainer is able to reproduce it. We appreciate your simple and concise repro cases! Hopefully a community member will see these and be able to reproduce and send in a PR :smile:
