### ISSUE TITLE
Route cannot be found when a part contains the '!' character

### ISSUE THREAD

**Issue by bsander** [restify/node-restify#567]
I have an application in restify where I send URI-encoded urls as part of the path. For example:
```PUT /index/type/http%3A%2F%2Flocalhost%2F```

This fails when I try to send an url containing a hashbang (or any url with the `!` character in it for that matter).

So for example, `encodeURIComponent('http://localhost/#!/1')` results in `http%3A%2F%2Flocalhost%2F%23!%2F1`.

Then I try to send a request:
```PUT /index/type/http%3A%2F%2Flocalhost%2F%23!%2F1```

resulting in the following error message from restify:
```
{ code: 'ResourceNotFound',
  message: '/index/type/http%3A%2F%2Flocalhost%2F%23!%2F1 does not exist' }
```

For completeness, my route listens to the following pattern:
```javascript
server.put('/:index/:type/:id', middleware);
```

and the error is not emitted by any of my middleware functions, it is emitted here: https://github.com/mcavage/node-restify/blob/master/lib/router.js#L478

**Comment by micahr** [comment]
Looks like there was a change back in October, 2013, which should address your problem (https://github.com/restify/node-restify/commit/51b7245c696dd0fbf4108f478807c99a690d857a) Can you try with a newer version of Restify and see if your problem still persists?

**Comment by bsander** [comment]
Yes, this now appears to work correctly in 2.8.5.
