### ISSUE TITLE
next.ifError - strange behaviour

### ISSUE THREAD

**Issue by alekbarszczewski** [restify/node-restify#569]
`return next(new restify.ConflictError())` returns response to the client with `code = 'ConflictError'` while `next.ifError new restify.ConflictError()` causes `uncaughtException` and nothing is returned to the client.

Why this happens? Should I still use `if(err) return next(new restify...)` format to return error response to the client?

**Comment by teh1** [comment]
I second this question. An answer would be much appreciated. The docs clearly state that "alternatively you can use next.ifError(err)", which implies it has the EXACT SAME BEHAVIOR... Which it clearly does not.

**Comment by micahr** [comment]
The `ifError` function `throws` the error, while passing the error to `next` does not throw, unless it reaches the end of the chain and isn't handled.

You can see the [behavior here](https://github.com/restify/node-restify/blob/master/lib/server.js#L164).

**Comment by Burnett01** [comment]
Finally someone sorted this!
