### ISSUE TITLE
Modifying req.url in a pre middleware

### ISSUE THREAD

**Issue by alekbarszczewski** [restify/node-restify#583]
Here is the code (sorry for coffeescript):
```
prefix = '/api'
versionPattern = new RegExp "^#{prefix}/(v((?:(?:[0-9]+|x))(?:.(?:[0-9]+|x)(?:.(?:[0-9]+|x))?)?)(.*?)$)"
server.pre (req, res, next) ->
    matches = versionPattern.exec req.url
	return next() if !matches
	[path, part, version, rest] = matches
	if version
		version = version.split '.'
		version[1] ?= 'x'
		version[2] ?= 'x'
		req.headers['accept-version'] = version.join '.'
		req.url = req._url.pathname = req._url.path = req._url.href =  "#{prefix}#{rest}"
	next()
```
This middleware checks for pattern like `/api/v0.0.0/rest/of/path` and dynamically sets `accept-version` header to version extracted from path and also changes url by removing version fragment from it. It allows for passing api version in url.

So is there any other better solution for this?
Is there better method to change url in `pre`?

Currently I have to change `req.url`, `req._url.path`, `req._url.pathname` and `req._url.href`...

**Comment by micahr** [comment]
Looks like `req._url` will only be present if you call `req.getUrl`, as that is when it is set.

If you set `req.url` then called `req.getUrl` you would achieve the same effect as setting all the parts of `req._url` since the url would be parsed then stuck on `req._url`.
