### ISSUE TITLE
context of this in controllers changed to server instance

### ISSUE THREAD

**Issue by bazo** [restify/node-restify#586]
i have the following code:
server:

```
server.post('/parents', parentController.create);
```

parentController in typescript, uses oo

```
constructor(parentService) {
        this.parentService = parentService;
    }
create(req: restify.Request, res: restify.Response, next: restify.Next) {

        var parentData = req.params.parent.data;
        var parentRole = req.params.parent.role;
        var inviteId = req.params.inviteId;

        console.log(this);

        this.parentService.create(parentData, parentRole, inviteId, function (err, family) {
            if (err) {
                res.json(400, {
                    code: err.code,
                    error: err.message
                });
            } else {
                res.json(family);
            }
        });
    }
```

i would expect this to be the controller instance not the server instance. i can't think of any situation where this could be advantageous.

and it prevents correct oop and dependency injection usage.

the only workaround if i want to maintain correct di is this:

```
server.post('/parents', function(req, res, next){
parentController.create(req, res, next);
});
```

which kind of sucks. very much.

is there any specific reason for this behavior?

**Comment by KostyaTretyak** [comment]
Although the issue was created in 2014, but perhaps it is someone else interested.


If we transfer method like this
```ts
server.post('/parents', parentController.create);
```

as a result of this code transpiled to anonymous function
```javascript
server.post('/parents', function(){ /* some code*/ });
```

so `this` is not in object `parentController` context

**Comment by KostyaTretyak** [comment]
@gergelyke says:
> Also, you do not need DI, as you have the module pattern

Bun now 2016 and is [Dependency Injection for Node.js](https://www.npmjs.com/package/di)

**Comment by KostyaTretyak** [comment]
@bazo, I'm experimenting with different versions. Your code you can change quite a bit to make it work:
```ts
export SomeClass{

  constructor(parentService) {
        this.parentService = parentService;
  }

// Set arrow function to propertie "create"
  create = (req: restify.Request, res: restify.Response, next: restify.Next) => {
    // here your code
  }
}
```
