### ISSUE TITLE
Middleware design and streaming requests

### ISSUE THREAD

**Issue by rprieto** [restify/node-restify#607]
Hi,

For certain reasons, I needed to add this type of support in my app:

```
Content-Type: application/json
Content-Encoding: base64+gzip

Payload = base64( gzip( json ) )
```

Restify already supports `Content-Encoding: gzip` in requests, so I thought I would just add a middleware to handle the `base64` part. However I found it's not as easy as I thought, because `bodyParser` handles multiple things, including both the `JSON` parsing and `gzip` support.

Which made me think: is there a way, or could there be a way, for middleware to simply act on the request stream, and pass a new stream to the next one? This would mean we can have much more focussed middlewares:
- the middleware that supports `Content-Encoding: gzip` would really just be

``` js
function(req, res, next) {
  var encoding = req.headers['content-encoding'];
  if (encoding.match(/gzip/)) {
    next(req.pipe(zlib.createGunzip()));
  } else {
    next();
  }
}
```
- the middleware that supports `Content-Type: application/json` would collect data chunks before calling `JSON.parse`, but not have to worry about gzipping.
- and adding `base64` support in our app would be as trivia as

``` js
function(req, res, next) {
  var encoding = req.headers['content-encoding'];
  if (encoding.match(/^base64\+/)) {
    req.headers['content-encoding'] = encoding.replace('base64+', '');
    next(req.pipe(base64.decode()));
  } else {
    next();
  }
}
```

Of course this very wishful thinking, and I could be missing some pretty important constraints :)

**Comment by retrohacker** [comment]
Closing this as stale. There are probably some sound feature requests in these conversations though, feel free to break them out into new issues to discuss :heart:
