### ISSUE TITLE
Cannot return `Access-Control-Allow-Origin: *` with CORS plugin

### ISSUE THREAD

**Issue by longhotsummer** [restify/node-restify#608]
The [CORS](http://www.w3.org/TR/cors/#access-control-allow-origin-response-header) spec say that the `Access-Control-Allow-Origin` header can be `*` but the plugin doesn't support this.

We require this functionality in web APIs that are going to be loaded from multiple websites where the response itself is cached by the browser.

**Comment by retrohacker** [comment]
For reference, the in-flight PR can be found here: https://github.com/restify/plugins/pull/10
