### ISSUE TITLE
Clean separation of Router

### ISSUE THREAD

**Issue by bstahlhood** [restify/node-restify#610]
Any plans to possibly separate the router in the future? One of the cool things about Express 4 is that it separates the Router so you can create a cleaner separation in modules for resources and their routes.

**Comment by lgomez** [comment]
Did this happen? I'm trying to figure out how to separate my routers into separate files. Thank you!

**Comment by micahr** [comment]
No, the router hasn't been split out. We are working on [Restify-Conductor](https://github.com/restify/conductor) which will help address the desire to have resources defined separate from the routes they represent.
