### ISSUE TITLE
Array param overwrites all req.params

### ISSUE THREAD

**Issue by dweinstein** [restify/node-restify#621]
If both queryParser and jsonBodyParser (bodyParser) are employed and the user sends an empty array `[]` as the body of a POST, currently that will clobber the current content of `req.params` (potentially some query string parameters) due to this line:
https://github.com/mcavage/node-restify/blob/master/lib/plugins/json_body_parser.js#L43

I'm not sure if this is expected behavior or not... shouldn't the query parameters not get clobbered? Does the HTTP specification specify what should happen in this case?

**Comment by DonutEspresso** [comment]
You can use `req.query` to access query params, leaving `req.params` as a bucket for POST params or URL params. If you're using queryParser, it will get merged with `req.params` by default, but you can turn that off:

```js
server.use(restify.jsonBodyParser({ mapParams: true }));
```
