### ISSUE TITLE
Multiple File Upload

### ISSUE THREAD

**Issue by Nalum** [restify/node-restify#627]
Uploading multiple files seems to be working fine but instead of getting a list of the files uploaded I only get that last file that was uploaded. Note I'm uploading through one file input not multiple file inputs. I would guess multiple inputs would work fine but I don't want to use multiple inputs for this app.

Here is a `console.log` of `req.files`

```
{
    "files[]": {
        "size": 5593,
        "path": "/tmp/app-files/5291c6d4cece951749845fa5881ebb12",
        "name": "file-4.csv",
        "type": "text/csv",
        "mtime": "2014-06-15T13:45:55.808Z"
    }
}
```

**Comment by retrohacker** [comment]
Fixed in https://github.com/restify/node-restify/pull/689
