### ISSUE TITLE
Support RegExp for route.render

### ISSUE THREAD

**Issue by germanz** [restify/node-restify#632]
It is very useful being able to name the routes, however I have discovered that the **server.router.render** method fails if the path of the route is specified using a regular expression. For example:

```
// configuring named routes
var server = restify.createServer();

// Register route
server.get({
  name: 'foo', 
  path: new RegExp('/test/([a-zA-Z0-9]+)?$')
 }, doSomething);

// somewhere in another route
server.router.render('foo');
```

Will trigger the following error:

```
Object '/test/([a-zA-Z0-9]+)?$' has no method 'replace'
```

Because the "render" method assumes path is always a string. Have a look at:
https://github.com/mcavage/node-restify/blob/v2.8.1/lib/router.js#L187

```
...
var _url = route.spec.path.replace(/\/:([^/]+)/g, pathItem);
...
```

**Comment by retrohacker** [comment]
Marking this as a feature request, as @rprieto points out, this behaviour needs to be well defined before a PR can be created.

**Comment by retrohacker** [comment]
If there is still interest in this, please comment and we can discuss.
