### ISSUE TITLE
res.send can't send boolean false

### ISSUE THREAD

**Issue by lightma** [restify/node-restify#636]
e.g:

res.send(200, true);  //this will write true to response body
# res.send(200, false);  //this has no body in response

I just checked the source and found that
response.js, line 204:
if (body) {
        var ret = this.format(body, _cb);
        ...
Against "res.send(200, false)", body is false, so there is no data to write back.

**Comment by p-somers** [comment]
This seems to have regressed. If I pass "true", it's fine, but "false" results in "null". It seems to be due to a simple "falsy" check when writing to the response:
https://github.com/restify/node-restify/blob/23c80b82d22bce3a29b194e61f802992ff121333/lib/response.js#L852
