### ISSUE TITLE
httpclient.close() isn't really safe

### ISSUE THREAD

**Issue by davepacheco** [restify/node-restify#642]
HttpClient.close() reaches into the Node agent and calls end() on all of the sockets in use by the agent.  It doesn't check that the socket's remote address matches the server that the client was created with.  More importantly, though, the Node documentation says not to touch these sockets, and the problem with doing this is that if you call client.close() and then try to make another request (with a different client or even outside restify, AFAICT), the Node agent may decide to use one of the sockets that has started closing, and it will immediately get a "socket hang up" error.

I don't think there's a great way to implement close() given the current agent API, but what restify's doing right now makes it possible to run into bugs like node-manta#194.  If the point of close() is basically for command-line programs to wrap things up, then it should probably be a global function (i.e., not per-agent), since it's closing everything, and it probably needs to be provided by the agent implementation.

**Comment by micahr** [comment]
Definitely can cause some unexpected behavior. Thanks for reporting it Dave. We should probably just remove the close method from the Http Client as a user could call the method expecting it to act only on their client instance, not across all sockets for the agent.

**Comment by hekike** [comment]
Moved: https://github.com/restify/clients/issues/164
