### ISSUE TITLE
Custom Error statusCode are not being converted to HTTP codes

### ISSUE THREAD

**Issue by hongkongkiwi** [restify/node-restify#645]
Custom errors don't seem to have their status codes respected when throwing them.

I'm creating an error with the following

``` javascript
AccountAlreadyExists = function (message) {
  restify.RestError.call(this, {
    restCode: 'AccountAlreadyExists',
    statusCode: 409,
    message: message,
    description: "The specified account already exists.",
    constructorOpt: AccountAlreadyExists
  });
  this.name = 'AccountAlreadyExists';
};
util.inherits(AccountAlreadyExists, restify.RestError);
```

Then I'm calling the error using the following inside a restify route:
`return next(new AccountAlreadyExists("Account already exists"));`

In theory this should pass an error with an HTTP status code of 409 (right?) however no matter what I pass it always returns 500 for the status code.

**Comment by DonutEspresso** [comment]
I'm unable to repro this, I'm getting the expected 409 using the exact code above. What version of restify are you on?

**Comment by micahr** [comment]
@hongkongkiwi - Can you confirm whether you are still seeing this error or not?

**Comment by DonutEspresso** [comment]
It's also worth nothing that errors is now it's own module, with a built in method for creating dynamic constructors. So you no longer have to create manual constructors as in the OP.

**Comment by retrohacker** [comment]
Closing as stale due to inactivity. If you are still having this problem, please comment and we can re-open this issue to discuss :heart:
