### ISSUE TITLE
incorrect `MethodNotAllowedError` on route with no versions when `Accept-Version` header used

### ISSUE THREAD

**Issue by trentm** [restify/node-restify#652]
Update: this ticket is now only about #2 below. Updating ticket accordingly.

@mcavage For consideration. Take this server (modified to add the '/ping' route from the restify docs example for Accept-Version handling:

```
var restify = require('./');

var server = restify.createServer({});

function sendV1(req, res, next) {
  res.send('hello: ' + req.params.name + ' (this is V1)');
  return next();
}

function sendV2(req, res, next) {
  log.debug('req.version', req.getVersion())
  res.send({hello: req.params.name, v: 2});
  return next();
}

var PATH = '/hello/:name';
server.get({path: PATH, version: '1.1.3'}, sendV1);
server.get({path: PATH, version: '2.0.0'}, sendV2);

// **I added this route. It has no `version` set.**
server.get({path: '/ping'}, function (req, res, next) {
  res.send({ping: 'pong'});
  next();
});

server.listen(8000);
```

Some requests:

```
$ curl localhost:8000/ping       # fine
{"ping":"pong"}

$ curl localhost:8000/ping -H 'Accept-Version: *'        # fine
{"ping":"pong"}

$ curl localhost:8000/ping -H 'Accept-Version: ~1' -i       # hrm
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: application/json
Content-Length: 63
Date: Wed, 30 Jul 2014 07:13:33 GMT
Connection: keep-alive

{"code":"MethodNotAllowedError","message":"GET is not allowed"}
```
1. That last request (i.e. any request that specifies a Accept-Version other than `*`) means that currently if I want my clients to starting using Accept-Version, then I need to add relevant version(s) values to _all_ my routes. I wonder if it would be nice to allow "no versions specified on a route" to mean "this route works for all Accept-Version". Thoughts?
2. Is the `MethodNotAllowedError` here a bug? Should it not be `InvalidVersionError`?

**Comment by karthikiyengar** [comment]
Please let me know if anything else is needed here.
