### ISSUE TITLE
req.query: two natures; function & object?

### ISSUE THREAD

**Issue by epappas** [restify/node-restify#658]
Hi,

I run into an issue where req.query sometimes acts as a function, while I'm in server.pre(...) server.on('after' ... ); or in a custom middleware in server.use(...); :
```
req.query = function getQuery() {
    if (this._query !== undefined)
        return (this._query);

    this._query = this.getUrl().query || {};
    return (this._query);
}
```
and most of the times acts as an object, containing the query parameters, while I am in a route's middleware.

I debug this issue and realised that this behaviour is only happening when I have not assigned a route at the root path (/) of my server.

In that case, all three middlewares are triggering with having req.query as a function.

in order to work around with this I am doing:
```
(typeof req.query === 'function' ? req.query() : req.query )
```
But is this the willing behaviour, or is it just a bug?

My server's middlewares are;
```
server.use(restify.acceptParser(server.acceptable));
server.use(restify.dateParser());
server.use(restify.queryParser());
server.use(restify.bodyParser());
server.use(restify.requestLogger({}));
server.use(restify.gzipResponse());
server.use(....);

server.pre(...);
server.on('after', ......);

// routing is following...
```

Cheers,
Evangelos.

EDIT: I forgot to mention; restify's version is 2.8.1, Node's v0.10.28

**Comment by DonutEspresso** [comment]
If it hasn't been fixed already, this should be fixed in the next release. `req.query` will always return a string if you're not using the queryParser, and if you are, it will always return an object.

Ref:
https://github.com/restify/node-restify/commit/ecec8ddfd9adf9bfb22041ee75c6feabe9102600
