### ISSUE TITLE
Feature Request for Exponential Backoff and Retry

### ISSUE THREAD

**Issue by yunong** [restify/node-restify#663]
Currently restify does fixed interval retries based on the connectTimeout. However, if the time it takes to establish the connection is longer than the connectTimeout, then having exponential intervals on the retries would be more preferable.

**Comment by retrohacker** [comment]
Prior art: https://github.com/retrohacker/concurrent-request

**Comment by retrohacker** [comment]
Documentation explaining prior art: https://github.com/retrohacker/knowledge/blob/master/rest/client.adoc

**Comment by hekike** [comment]
Closing this as it's already implemented in the client.
