### ISSUE TITLE
Chrome postman app returns value successfully for a 'POST', but restify returns 'CERT_HAS_EXPIRED' for the same POST request

### ISSUE THREAD

**Issue by NidhiArien** [restify/node-restify#666]
I am using Restify to make rest calls to a third party entity. I am using the following code:

// Require 'restify' 
 var client = restify.createJsonClient({
        url: request.url,
        rejectUnauthorized:true
    });
     client.post(request.path, request.object, callback);

I get the response as CERT_HAS_EXPIRED. I use the same url to make POST call in postman app of chrome and I post the data successfully. What additional parameters do i need to include while making a rest call via restify in order to prevent the problem. We have notofied the third party entity to update their certificates. I am curious, how does it work with Postman and not Restify? 

Any help would be appreciated.

**Comment by micahr** [comment]
This appears to be CA issue. If the site you are accessing has an expired certificate or somewhere in the CA chain there is an expired certificate, your client may not have that update and will throw this error. The easiest solution is to set `rejectUnauthorized: false` in your client configuration, but if that doesn't work, you'll have to set up an Agent with the specific CA you need added.
