### ISSUE TITLE
Error Logging

### ISSUE THREAD

**Issue by 58bits** [restify/node-restify#667]
At the moment I'm using
```
if (err)
    log.error(err);    
    return next(err);
```

In Restify 2.1 we can use `next.ifError(err);`

How can I create a general handler that will log all errors before they are sent in the response?, i.e. whenever it's handed to 'next()'? 

Will it show up in...

`server.on('uncaughtException', function (req, res, route, err)` ?

In which case can I then just ...

```
log.error(err);
res.send(err);
```
Or do I need to write my own handler?

**Comment by DonutEspresso** [comment]
You'd have to write your own handler at the moment, though maybe we could expose some hooks before rendering out the response. Worth some further investigation.

**Comment by DonutEspresso** [comment]
Closing, we have since added support to attach a listener for any errors passed to next().
