### ISSUE TITLE
restify.bodyParser modifys req.body for GET requests

### ISSUE THREAD

**Issue by wburningham** [restify/node-restify#684]
If you use the `restify.bodyParser` middleware and then make a GET request to a route I would expect `req.body` to be undefined or and empty object. Instead `req.body === 'null'`

It looks like when you use the `restify.bodyParser` you always call the body_reader which does the following:

        req.body = new Buffer(0);
        return (function (chunk) {
                req.body = Buffer.concat([req.body, chunk]);
        });

Thus making `req.body` a string with the contents of null.

Shouldn't the `body_reader` only be invoked right before the switch statement in `body_parser.js`?

**Comment by DonutEspresso** [comment]
The code has changed a bit since initial filing, and a quick demo I put together doesn't seem to be exhibiting the behavior noted here. Please reopen if you still find this to be an issue.
