### ISSUE TITLE
Default "uncaughtException" handler can crash with asynchronous response writes

### ISSUE THREAD

**Issue by rprieto** [restify/node-restify#685]
It seems I can crash the server if an exception happens after the headers were set, but before the response was written:

```js
var server = restify.createServer({});
server.use(restify.gzipResponse());
server.get('/hello', function(req, res) {
  res.send(200, 'ok');
  throw new Error('foooooooo');
});
```

or

```js
var server = restify.createServer({});
server.get('/hello', function(req, res) {
  res.writeHead(200, {foo: 'bar'});
  setTimeout((function() { res.end('ok'); }), 100);
  throw new Error('foooooooo');
});
```

Node [tries to send headers with the first body packet](https://github.com/joyent/node/blob/master/lib/_http_outgoing.js#L121), so in both these examples we might be in a state where:

- `res._header` is already set
- but `res._headerSent` is still false, because no data has been written yet

Restify's default `uncaughtException` handler checks `res._headerSent`, and otherwise sends an `InternalError`. So in the cases above, `res.send(new InternalError)` will try to set headers again, which [throws an exception](https://github.com/joyent/node/blob/master/lib/_http_outgoing.js#L325). Since we're already [inside the error handler of the request domain](https://github.com/mcavage/node-restify/blob/master/lib/server.js#L770), the original exception just bubbles up and crashes the server :boom: .

I found that this change fixes the problem:

```js
 if (this.listeners('uncaughtException').length > 1 || res._header) { ... }
```

Happy to submit a PR if this makes sense, otherwise would love to understand the proper way of fixing this.

**Comment by DonutEspresso** [comment]
Apologies for the delayed reply. Seems this has been addressed:

https://github.com/restify/node-restify/blob/master/lib/index.js#L145
