### ISSUE TITLE
Support strict routing

### ISSUE THREAD

**Issue by Dante-Edge** [restify/node-restify#692]
Like the strict options in express. "/foo" and "/foo/" can be treated different by route.

**Comment by DonutEspresso** [comment]
Fixed, will be released with 5.x before end of the month.

**Comment by maxsummers** [comment]
End of what month? )

**Comment by DonutEspresso** [comment]
Hello - we've been testing the 5.x beta on the beta tag over last couple of months (`npm i restify@beta`). We intend to formalize the release soon. Feel free to check out the beta, the API is pretty much finalized.
