### ISSUE TITLE
Support for multiple HTTP response header values

### ISSUE THREAD

**Issue by thizzle** [restify/node-restify#693]
If I have multiple HTTP response headers, only the most recent one is output as part of the response.

This has been discussed at length in the node project itself (see https://github.com/joyent/node/issues/2750)

Node's ServerResponse will correctly accumulate header values, and consolidate them into a comma-separated list for output, which is also acceptable.

I'm happy to send a PR if you agree with this change.

Thanks

**Comment by DonutEspresso** [comment]
Looks like this has already been merged, so I will close this. Let me know if that's not the case.
