### ISSUE TITLE
Example has bug for the Create HttpClient

### ISSUE THREAD

**Issue by CowPanda** [restify/node-restify#701]
Hi,for this example has a bug see here :[http://mcavage.me/node-restify/#installation](http://mcavage.me/node-restify/#installation) . code like this: 

   client = restify.createClient({
    url: 'http://127.0.0.1'
  });
  
  client.get('/str/mcavage', function(err, req) {
    assert.ifError(err); // connection error
  
    req.on('result', function(err, res) {
      assert.ifError(err); // HTTP status code >= 400
  
      res.body = '';
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        res.body += chunk;
      });
  
      res.on('end', function() {
        console.log(body);  //* console.log(body) ->console.log(res.body)
      });
    });
  });     

##### `body` is undefined; change the code like this? : `console.log(res.body) `

**Comment by DonutEspresso** [comment]
Looks like this has been merged in already.
