### ISSUE TITLE
Throttling problem

### ISSUE THREAD

**Issue by mdi** [restify/node-restify#706]
I'm seeing an issue when using the throttling plugin where once a request is made with an "override" username, any future requests (regardless of username) are allowed through and not sent back with a 429.

For example:

```
var server = restify.createServer({
  version: require('../package.json').version,
  acceptable: ['application/json']
});

server.use(restify.authorizationParser());
server.pre(restify.CORS());
server.pre(restify.pre.userAgentConnection());
server.use(restify.fullResponse());
server.use(restify.acceptParser(server.acceptable));
server.use(restify.bodyParser({mapParams: false}));
server.use(restify.queryParser());

server.use(restify.throttle({
  burst: 1,
  rate: 1,
  username: true,
  overrides: {
    'foo@foo.foo': {burst: 0, rate: 0}
  }
}));
```

If I hit the API with too many requests with a user `bar@bar.bar` *first*, I get the expected 429 errors. But as soon as I hit the API with user `foo@foo.foo` which allows all requests, and then hit the API again with `bar@bar.bar`, all of those requests are allowed through *without* a 429.

**Comment by micahr** [comment]
This issue looks to have been fixed in https://github.com/restify/node-restify/commit/f399a33080ec77667f4655f4bff8747e394a209c The problem was that `rate` and `burst` were globals for the entire middleware, rather than set per request. Your issue should be gone with a newer (3.0 or greater) version of Restify.

**Comment by mdi** [comment]
I still see the same issue with `v3.0.3`.

**Comment by micahr** [comment]
Thanks for the response. I'll reopen the issue and take a look.
