### ISSUE TITLE
How to get on('UnsupportedMediaType'... to emit

### ISSUE THREAD

**Issue by Todd-Werelius** [restify/node-restify#710]
I have some routes that I can only process if the content-type is json, if the content-type is not json I want to handle it in the server.on('UnsupportedMediaType'... event 

I can't quite figure out how to do this

I can check for the json content-type and take some action based on that 

```javascript
return function(req,res,next){
    if ("POST" !== req.method && "PUT" !== req.method) {
      return next();
    }

    if (req.is('json')) {
      return next();
    }
    next(new errors.UnsupportedMediaTypeError("Some Message"));
  };
```

That ends up sending a json response back to the client 
```json
{
    "code": "UnsupportedMediaTypeError",
    "message": "Some Message"
}
```

It also ends up being reported via the sever.on('after'... with the error object set, but as stated I would prefer to handle it via proper event

I tried to emit the event myself, which worked, but it took forever to show up

**Comment by DonutEspresso** [comment]
The server itself inherits from EventEmitter, so you can simply call `server.emit('UnsupportedMediaType')` or `this.emit('UnsupportedMediaType')`.
