### ISSUE TITLE
SSLv3 with HttpClient

### ISSUE THREAD

**Issue by mchicote** [restify/node-restify#712]
Hi
How can I make a HttpClient use SSLv3? 
I'm adding the following line before I create the client but does not seem to work:

``` javascript
https.globalAgent.options.secureProtocol = 'SSLv3_method';
```

Ideas? Thanks

**Comment by micahr** [comment]
When creating your client, you can set the `agent` property, with a secureProtocol of SSLv3_method. You can see an example of setting up an agent here: https://github.com/restify/node-restify/blob/master/lib/clients/http_client.js#L438-L456.
