### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by sarices** [restify/node-restify#716]
> dtrace-provider@0.2.8 install /zsnet/one/jb/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/zsnet/one/jb/node_modules/restify/node_modules/dtrace-provider/build'
make: Warning: File `DTraceProviderStub.target.mk' has modification time 1.3 s in the future
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: warning:  Clock skew detected.  Your build may be incomplete.
make: Leaving directory `/zsnet/one/jb/node_modules/restify/node_modules/dtrace-provider/build'
npm WARN optional dep failed, continuing mv@2.0.3
npm ERR! Linux 2.6.32-358.18.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "restify" "--save"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! path ../node-uuid/bin/uuid
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../node-uuid/bin/uuid'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by throrin19** [comment]
i've send this issue directly to dtrace : https://github.com/chrisa/node-dtrace-provider/issues/58

**Comment by DonutEspresso** [comment]
dtrace-provider has been updated, should no longer be an issue.
