### ISSUE TITLE
bodyParser and post array support

### ISSUE THREAD

**Issue by alexmipego** [restify/node-restify#718]
Apparently there is an issue with restify where if you use the bodyParser to automatically parse the JSON body of a POST then the params object will only contain the body of the POST and lose the other params (especially the url parts). While on another issue I saw an argument that this was somehow part of the HTTP specs, it makes no sense a framework like restify to lose the routing parameters.

A simple app to test the issue is here: https://gist.github.com/alexmipego/71d03c632b76c96dfc2c
Just send a post with a JSON array and you lose the url parameters.

I believe the bodyParser should only parse the body and replace the req.body with the resulting object and not even touch the req.params variable.

Alternatively, the recommendation and examples could be fixed so that the default way of accessing url/routing arguments is req.context instead of req.params.

**Comment by DonutEspresso** [comment]
Thanks @scippio, `mapParams: false` should get you the desired behavior.
