### ISSUE TITLE
Version.join() issue when using socketio 

### ISSUE THREAD

**Issue by fredericfok** [restify/node-restify#724]
Restify Server file performs a join(), raising an error: 

node_modules/restify/lib/server.js:557
    str += sprintf(LINE_FMT, 'Version', this.versions.join());
                                                      ^
TypeError: Object 1.0.0 has no method 'join'
    at Server.toString (.../node_modules/restify/lib/server.js:557:55)
    at Number (<anonymous>)
    at Server.listen.Server.attach (.../node_modules/socket.io/lib/index.js:203:7)
    at new Server (.../node_modules/socket.io/lib/index.js:51:17)
    at Function.Server (.../node_modules/socket.io/lib/index.js:39:41)

This only happens when I use socketio: 
 scope.io = socketio.listen(scope.server);

    scope.io.sockets.on('connection', function (socket) {
        socket.emit('hello', { hello: 'world' });
        socket.on('msg', function (data) {
                console.log(data);
        });
        
        socket.on('disconnect', function(){
            console.log('user disconnected');
        }); 
    });

 To walk around, I have passed an array in the createServer function and it works just fine...: 
	scope.server = restify.createServer({ 
		name: "localhost", 
		version: ["0.0.1"]
	});

I did not deep dive in the restify server code, but I believe at some point, the version attribute (String) is being parsed, leading the join() function to crash as it expects an array

**Comment by micahr** [comment]
This was fixed with #840, thank you for reporting the issue.
