### ISSUE TITLE
Response does not return when incorrect Content-Type is passed

### ISSUE THREAD

**Issue by Xiot** [restify/node-restify#730]
I was having an issue the other day when sending a POST to one of my handlers.
I could see that the handler was being executed, however the request never returned.

It turned out that the tool that I was using was sending the Content-Type of `application/x-www-formurlencoded` but the content of the message was JSON.  When I switched the Content-Type to `application/json` everything worked fine.

I haven't dug deep enough yet to determine whether or not req.body was just not returning or exploding however.  I just read threw #466 which gives some guidance on how to set up error handlers, but I was surprised to see it just hang.  Is there a default `uncaughtException` that should have caught the error?

**Comment by micahr** [comment]
`uncaughtException` is certainly a last resort. If you aren't able to catch your exception in a middleware or other handler, then `server.on('uncaughException')` should give you a chance to clean up and send an error. 

Closing this issue as it was not in Restify.
