### ISSUE TITLE
signRequest doc change maybe

### ISSUE THREAD

**Issue by cmawhorter** [restify/node-restify#737]
signRequest is a sync callback that passes an http.ClientRequest (writable stream).  

Unless I'm mistaken, this means that the body is not exposed unless you create the client and request in the same scope like so: 

``` javascript
function makeRequest(data) {
  var client = restify.createJsonClient({
    url: 'http://localhost:3000',
    signRequest: function(req) {
      var body = JSON.stringify(data);
      req.setHeader('authorization', someSigner(headers + body));
    }
  });

  client.post('/foo', data, function(err, req, res, obj) {
    assert.ifError(err);
    console.log('%d -> %j', res.statusCode, res.headers);
    console.log('%j', obj);
  });
};

makeRequest({ hello: 'world' });
```

Might be noteworthy in the docs.

**Comment by retrohacker** [comment]
Hey @cmawhorter,

Thank you for taking the time to open this issue, sorry it took so long for you to get a response.

I've tagged this as a documentation improvement and will look to see if it is still relevant in the upcoming 5.x release. :heart:
