### ISSUE TITLE
Request bodies ignored by restify clients on DELETE requests

### ISSUE THREAD

**Issue by jmhnilbog** [restify/node-restify#742]
The HTTP spec allows for DELETE request bodies, and the restify server works with DELETE request bodies, but the restify clients' `del` method doesn't allow a payload as an argument.

**Comment by CristyTarantino** [comment]
Any news on this?

**Comment by retrohacker** [comment]
Thank you for taking the time to open this issue. I'm flagging it as a feature request and asking for help from the community, I have an upcoming PR that creates a `FEATURES_REQUEST.md` document and this will move there :heart:

**Comment by hekike** [comment]
Moved: https://github.com/restify/clients/issues/165
