### ISSUE TITLE
Npm install fails on Ubuntu when node is install via a package manager

### ISSUE THREAD

**Issue by BossLevel** [restify/node-restify#745]

**Comment by BossLevel** [comment]
Apologies - hit Enter before completing the description!

Ubuntu has a known issue with a non-nodejs package named "node" and requires the use of nodejs-legacy:

http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

"npm install" manages to load all dependencies for every other node module I'm using with the exception of restify suggesting that you've not taken this into account.

**Comment by BossLevel** [comment]
Illustrative example

├─┬ bcrypt@0.8.1
│ ├── bindings@1.0.0
│ └── nan@1.5.0
├── bluebird@2.9.3
├─┬ chai@1.10.0
│ ├── assertion-error@1.0.0
│ └─┬ deep-eql@0.1.3
│   └── type-detect@0.1.1
├── faker@2.1.2
├─┬ mocha@2.1.0
│ ├── commander@2.3.0
│ ├─┬ debug@2.0.0
│ │ └── ms@0.6.2
│ ├── diff@1.0.8
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ └─┬ mkdirp@0.5.0
│   └── minimist@0.0.8
├─┬ passport@0.2.1
│ ├── passport-strategy@1.0.0
│ └── pause@0.0.1
├─┬ passport-facebook-token@0.4.0
│ ├─┬ passport-oauth@0.1.15
│ │ ├── oauth@0.9.12
│ │ └─┬ passport@0.1.18
│ │   └── pause@0.0.1
│ └── pkginfo@0.2.3
├─┬ passport-http@0.2.2
│ ├─┬ passport@0.1.18
│ │ └── pause@0.0.1
│ └── pkginfo@0.2.3
├── path@0.11.14
├─┬ request@2.51.0
│ ├── aws-sign2@0.5.0
│ ├─┬ bl@0.9.4
│ │ └─┬ readable-stream@1.0.33
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├── caseless@0.8.0
│ ├─┬ combined-stream@0.0.7
│ │ └── delayed-stream@0.0.5
│ ├── forever-agent@0.5.2
│ ├─┬ form-data@0.2.0
│ │ ├── async@0.9.0
│ │ └─┬ mime-types@2.0.8
│ │   └── mime-db@1.6.0
│ ├─┬ hawk@1.1.1
│ │ ├── boom@0.4.2
│ │ ├── cryptiles@0.2.2
│ │ ├── hoek@0.9.1
│ │ └── sntp@0.2.4
│ ├─┬ http-signature@0.10.1
│ │ ├── asn1@0.1.11
│ │ ├── assert-plus@0.1.5
│ │ └── ctype@0.5.3
│ ├── json-stringify-safe@5.0.0
│ ├── mime-types@1.0.2
│ ├── node-uuid@1.4.2
│ ├── oauth-sign@0.5.0
│ ├── qs@2.3.3
│ ├── stringstream@0.0.4
│ ├─┬ tough-cookie@0.12.1
│ │ └── punycode@1.3.2
│ └── tunnel-agent@0.4.0
├─┬ restify@2.8.2
│ ├── UNMET DEPENDENCY assert-plus ^0.1.5
│ ├── UNMET DEPENDENCY backoff ^2.3.0
│ ├── UNMET DEPENDENCY bunyan ^0.23.1
│ ├── UNMET DEPENDENCY csv ^0.4.0
│ ├── UNMET DEPENDENCY deep-equal ^0.2.1
│ ├── UNMET DEPENDENCY escape-regexp-component ^1.0.2
│ ├── UNMET DEPENDENCY formidable ^1.0.14
│ ├── UNMET DEPENDENCY http-signature ^0.10.0
│ ├── UNMET DEPENDENCY keep-alive-agent ^0.0.1
│ ├── UNMET DEPENDENCY lru-cache ^2.5.0
│ ├── UNMET DEPENDENCY mime ^1.2.11
│ ├── UNMET DEPENDENCY negotiator ^0.4.5
│ ├── UNMET DEPENDENCY node-uuid ^1.4.1
│ ├── UNMET DEPENDENCY once ^1.3.0
│ ├── UNMET DEPENDENCY qs ^1.0.0
│ ├── UNMET DEPENDENCY semver ^2.3.0
│ ├── UNMET DEPENDENCY spdy ^1.26.5
│ ├── UNMET DEPENDENCY tunnel-agent ^0.4.0
│ └── UNMET DEPENDENCY verror ^1.4.0
├─┬ supertest@0.13.0
│ ├── methods@1.0.0
│ └─┬ superagent@0.18.0
│   ├── component-emitter@1.1.2
│   ├── cookiejar@1.3.2
│   ├── debug@0.7.4
│   ├── extend@1.2.1
│   ├─┬ form-data@0.1.2
│   │ ├── async@0.2.10
│   │ ├─┬ combined-stream@0.0.7
│   │ │ └── delayed-stream@0.0.5
│   │ └── mime@1.2.11
│   ├── formidable@1.0.14
│   ├── methods@0.0.1
│   ├── mime@1.2.5
│   ├── qs@0.6.6
│   ├─┬ readable-stream@1.0.27-1
│   │ ├── core-util-is@1.0.1
│   │ ├── inherits@2.0.1
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.31
│   └── reduce-component@1.0.1
└─┬ supertest-as-promised@1.0.0
  ├── bluebird@1.2.4
  └── methods@1.1.1

**Comment by yunong** [comment]
Could you please add the npm logs?

**Comment by BossLevel** [comment]
Sorry for the late response - had a bit of a meltdown with that machine subsequently (nothing to do with restify :) !) - will attempt to get them to you in the next day or 2 but I'm afraid that I can't promise anything - sorry.

**Comment by micahr** [comment]
Any update on the NPM logs? If you are able to still reproduce this issue, it would be good to try removing the node_modules folder and trying to `npm install` again with `--loglevel verbose`
