### ISSUE TITLE
req.id() Not returns a unique hash

### ISSUE THREAD

**Issue by CodersBrothers** [restify/node-restify#749]
If you do 2 parallel requests at same millisecond this return the same hash

**Comment by pfmooney** [comment]
Could you provide more detail about the environment where you're encountering this issue?

**Comment by micahr** [comment]
This might be fixed in (https://github.com/restify/node-restify/commit/0640a0ba4854dc44834b9f34c0f7a48dfadcd7a5) which is using uuid.v4 instead of v1.

@CodersBrothers can you confirm if you are still seeing the issue?

**Comment by retrohacker** [comment]
Closing as stale
