### ISSUE TITLE
Options to keep the Content-Type based on the file extension, while serving Static files

### ISSUE THREAD

**Issue by RaghavendhraK** [restify/node-restify#754]
Hi,
I need to show the raml files in the browser. But since the raml files got the extension .raml, whenever I view this from the browser, it downloads the raml files as the Content-Type is 'application/octet-stream', and doesn't show it in the browser.
So, while serving static content, if the option is provided for the developer to keep the Content-Type, based on the file extension, it could have been useful.

Thanks,
Raghu

**Comment by DonutEspresso** [comment]
restify uses [node-mime](https://github.com/broofa/node-mime) to do lookup based on the file extension, but it looks like 'raml' is not a supported type. We could probably allow serveStatic plugin to take a mapping of extensions to content-type, and use that as a pass through to `mime.define()`:

```js
server.get(/.*/, restify.serveStatic({
  mimeTypes: {
    'application/my-custom-type': ['raml']
}));
```

**Comment by RaghavendhraK** [comment]
Yup, Thanks for the reply. :-)

**Comment by retrohacker** [comment]
Closing this as stale. There is a potential feature here, but looks like the best path forward is to open a PR against node-mime if there is a standard mime-type for `.raml` files.

**Comment by retrohacker** [comment]
Please comment if there is something I'm missing here and we can re-open and discuss :heart:
