### ISSUE TITLE
Accept header being ignored

### ISSUE THREAD

**Issue by kevinpeno** [restify/node-restify#769]
I noticed something affected by #563 and #564 today. While those changes do decide the default content-type based on the server's q-level, it completely ignores the client's accept header in the ordering.

Currently the changes above cause the content-type to be the servers favorite choice. The server is also validating that it *can* respond with what's in the accept header, but the two are disconnected from what I can tell (validated in `restify.acceptParser` and acted on in `Response.format`). This forces the routes to do content negotiation in order to supply the client's preferred output.

What I believe the server should do is to send the client its highest choice even if it's not the server's favorite choice.

Example 1: Client wants an SVG, the server has support for SVG and json on GET /image/:id
Client's Accept: `image/xml+svg`
Server's formatters: `application/json, image/xml+svg`
Result: `application/json`
Expected: `image/xml+svg`

The second example is not directly related to the problem above, but the code in the response module forces `application/octet-stream` if a formatter isn't defined. This shouldn't happen because no formatter should return 406, but also `*/*` should resolve to server's favorite choice.

Example 2: Client accepts anything 
Client: `*/*`
Server: `application/json, image/xml+svg, application/octet-stream; q=0.2`
Result: `application/octet-stream`
Expected: `application/json`

I'm not sure the best way to manage this in the system, but if you'd provide some insight I'd be happy to supply the PR. Thanks!

**Comment by yunong** [comment]
@kevinpeno For example 1, we should definitely be honouring the client accept headers. That should be fixed in the response.js file. If you could send a PR that includes a test that'd be great.

For example 2, I would imagine application/octet-stream is the default for the server -- I'm not sure whether @mcavage intended that or whether we should be using the server's favourite. @mcavage care to weigh in on ex 2?

**Comment by kevinpeno** [comment]
@yunong thanks for the response. I think I mixed up my errors locally and accidentally thought there was an issue causing Example 1 when Example 2 was actually causing it.

For Example 2, it appears as though the resulting Content-Type will actually be the highest q-value. However, formatters that don't have a q-value specified are not considered (even though they should default to 1). See PR #771

**Comment by micahr** [comment]
Closing, as the initial bug has been fixed in #771
