### ISSUE TITLE
JSON client ignores `accept` option

### ISSUE THREAD

**Issue by chrisallenlane** [restify/node-restify#773]
The [documentation](http://mcavage.me/node-restify/#jsonclient) states that the JSON client can be initialized with an `accept` option that will set the value of the `accept` header. As far as I can tell, it is being ignored.

Here is my test case:
### server

``` javascript
var restify = require('restify');

// initialize server
var server = restify.createServer({
  name    : 'restify-debug',
  version : '0.0.1',
});

server.get('/', function (req, res, next) {
  console.log(req.headers);
  res.send(200);
  return next();
});

// start the server
server.listen(1337, function () {
  console.log('%s listening at %s', server.name, server.url);
});
```
### client

``` javascript
var restify = require('restify');

// initialize the JSON client
var client = restify.createJsonClient({
  url    : 'http://localhost:1337',
  accept : 'application/vnd.chrisallenlane.restify.v1.0.0+json',
});

client.get('/', process.exit);
```

The value of the `accept` header being logged to my console is `"application/json"`.

Contrast that with curl:

``` sh
curl http://localhost:1337 -H 'accept: foo'
```

The value of the `accept` header being logged to my console is `"foo"`, which is what I'd expect. That indicates to me that the problem is with the client, and not the server.

I'll note that I tried setting the header value "manually" by initializing the JSON client with a `headers` property, but `headers.accept` was being ignored as well.

This is occurring with `restify` version `2.8.5`.

**Comment by retrohacker** [comment]
Hey @chrisallenlane,

Thank you for opening this issue, and thank you for providing a detailed repro case. I've flagged this as a bug, and labeled it as help wanted. Also, for now, I have it as unconfirmed until a maintainer runs the repro case. I'm unsure the maintainers will be able to tackle this in the near future, but we may see a good samaritan come along and send in a PR for this.

**Comment by retrohacker** [comment]
Migrated to clients repo
