### ISSUE TITLE
disable multipart from bodyParser

### ISSUE THREAD

**Issue by symsel** [restify/node-restify#780]
I want to use Multer/Busboy for my multipart logic and so I want to disable bodyParser's multipart. 
I want to use bodyParser for all other content-types like application/json, etc. How to do that?

**Comment by wotek** [comment]
That's not possible right now. I'd suggest creating you own bodyParser that reuses  code from original one for most of the content-types and plug in your code for multipart.

**Comment by micahr** [comment]
@wotek's recommendation is a good one. If you are wanting part of a plugin, it makes sense to re-implement the parts you want in your own plugin. Feel free to reuse parts of bodyParser in your own, and add it as a plugin to your Restify instance.
