### ISSUE TITLE
Migrate website to restify.com

### ISSUE THREAD

**Issue by claylo** [restify/node-restify#788]
Hey maintainers,

I emailed @mcavage about the URL restify.com, which I own and would like to donate to this project. Please contact him for the email, or ping me so we can arrange an ownership transfer.

Not kidding.

-Clay

**Comment by mcavage** [comment]
Hey Clay-

Sorry I didn't respond to your email (I'm frankly terrible at it). I'll figure out with @yunong where it goes; I don't have a GoDaddy account.

Thank you so much for this very gracious offer, by the way. It's extremely nice of you :).

m

**Comment by claylo** [comment]
You're welcome! I've been in contact with @yunong already today, and we're getting it taken care of. It'll take a few months to actually transfer ownership, unfortunately. But in the meantime, you'll find that restify.com -> restifyjs.com :smile:

**Comment by micahr** [comment]
Documentation is now on restify.com. Thanks @claylo!
