### ISSUE TITLE
bodyParser should use `mapParams: false` by default

### ISSUE THREAD

**Issue by robey** [restify/node-restify#789]
I think the bodyParser plugin should use `mapParams: false` by default.

I realize this would be a breaking change. My reasoning is this: There may be times when the path of a `PUT` contains valuable info (the id of the object to write, for example) and the json body contains some fields with the same name. In other cases, like one I just ran into, a client may send a meaningless json body like `true` which will overwrite any path params.

For people who want the option to merge body and path params, the option is there, but for people who don't want it, the default behavior is fairly surprising, and therefore violates the "principle of least astonishment". :)

**Comment by DonutEspresso** [comment]
If this change is made, queryParser should do the same to maintain consistency.

**Comment by DonutEspresso** [comment]
In 5.x, with the new restify-plugins module, this is the new default behavior.

**Comment by heycalmdown** [comment]
It can be corrupted by that the body is "string" itself.
The "string" assigned into req.params, and the original params gone.

Thanks @DonutEspresso, @robey

**Comment by DonutEspresso** [comment]
Hi @heycalmdown, are you talking about existing 4.x behavior, or the new restify-plugins module? If it's the latter, would you mind opening up a new issue in that repo? I think some sample code would help a lot to set context for the issue you are seeing. Thanks!

**Comment by heycalmdown** [comment]
no I was saying about 4.x. Just intended to add an edge case. Thanks :)

**Comment by retrohacker** [comment]
Hey @heycalmdown :smile:

It looks like this has been fixed in the 5.x release. I'm closing this as resolved for now :heart: if I'm missing a nuance here, please comment and I would be happy to re-open and discuss!
