### ISSUE TITLE
server.router.render queryString from multilevel object

### ISSUE THREAD

**Issue by 11bucks** [restify/node-restify#799]
I need `server.router.render` to render `queryString` like this `?sort[a]=1&sort[b]=-1&page=1` from this object

```
var query = {
    sort: {
        a: 1,
        b: -1
    },
    page: 1
};
server.router.render('foo', {}, query);
```

I have already made a fix. I'll try to create pull request (first in my life :) )

**Comment by 11bucks** [comment]
Hm, is that all from me to create a pull request? Just commit to my fork?

**Comment by 11bucks** [comment]
Btw, that's my first node project. Maybe there is better way to do it without `node-jquery-param` lib but it does it job pretty well in this case.

**Comment by 11bucks** [comment]
`node-jquery-param` was not so good. It wasn't able to stringify objects like
```
var query = {
    query: {
        created: {
            $gte: '2015-05-11T18:00:03.338Z'
        }
    }
};
```

So I've found `qs` lib which does it perfectly: `?query%5Bcreated%5D%5B%24gte%5D=2015-05-11T18%3A00%3A03.338Z`

And it was already in `packages.js`, so no new packages now :)

**Comment by yunong** [comment]
Hi, thanks for the work. Can you please send a PR? Could you please include a unit test for this as well? Please prefix the test case with 'GH-799'. Thanks

**Comment by retrohacker** [comment]
Hey @11bucks!

It was super cool to see you working on your first open source contribution! It looks like the changes you made never found their way into a PR. I'm going to close this as stale for right now due to its age, but if you are wanting to still be involved let us know and I can help you put together a PR. :heart:
