### ISSUE TITLE
bodyParser IE9 support

### ISSUE THREAD

**Issue by donniev** [restify/node-restify#801]
IE 9 requests do not set the content-type and the body-parser leaves req.body as undefined. In version 2.60 that was not true. I am not sure when behavior changed but as of 2.85 it definitely has and still leaves it undefined in 3

**Comment by yunong** [comment]
Can you give me an example request?

**Comment by micahr** [comment]
Looks like there is no default body parser when a content-type isn't sent by the client. We should `application/x-www-form-urlencoded` as the default to catch these type of cases.

**Comment by ddxtreme** [comment]
Any one found a workaround for this? Im tryng to make CORS requests form ie9 and i cant parse the body of the post request. thanks

**Comment by donniev** [comment]
This is in 4.0 milestone but does not seem to have been assigned or addressed in 4.0. Do we have an estimate of when this will be addressed?

**Comment by ddxtreme** [comment]
a workaround for anyone interested until this doesn't get fixed into native plugin

```
function ieParser(req, res, next) {
  if (req.method === 'GET' || req.method === 'HEAD') {
    next();
    return;
  }
  if(req.body == undefined) {
    var buffer = []

    req.on('data', function onRequestData(chunk) {
      buffer.push(chunk)
    });

    req.once('end', function() {
      var concated = Buffer.concat(buffer);
      req.body = JSON.parse(concated.toString('utf8'));
      next()
    });
  } else {
    next();
    return;
  }
}

module.exports = ieParser;
```

And use this as a middleware of your app, after processing the restify.bodyParser().
I am forcing JSON encoding, so change to your needs;

**Comment by micahr** [comment]
@donniev I don't have an exact timeline for when this will be addressed. It is obviously affecting several people, so we will do our best to get it fixed as soon as possible.
