### ISSUE TITLE
Errors thrown from the controller are not logged in AuditLogger

### ISSUE THREAD

**Issue by Achrome** [restify/node-restify#817]
Hi,

I'm trying to prototype a Restify API with ES6 syntax using Babel.

Wanted to debug, so I enabled auditLogger like this

```javascript
server.on('after', Restify.auditLogger({
  log: global.LOG //global.LOG is an instance of Bunyan here
});
```

And in my users controller I have this code

```javascript
'use strict';

import User from '../models/user';
import Co from 'co';

let UsersController = {};

UsersController.create = (req, res, next) => {
  let user =  new User({
    email: req.params.email,
    password: req.params.password
  });

  Co(function* () {
    yield user.save();
  }).then(() => {
    res.send(201)
  }, (err) => {
    res.send(422, err);
  });

  return next();
};

export default UsersController;
```

This works well in sending the appropriate response, but audit logger still logs the response as 200 OK for some reason.

For example,
```shell
$ curl -v -X POST http://localhost:3131/users/create -d email=foo -d password=bar
```
creates the user and gives me a `201 Created` response.
If I run this again to force an error, I get `422 Unprocessable Entity`.

However, checking the bunyan logger shows me the following.

```
11:55:31.583Z  INFO Salve API: handled: 200 (req_id=3f9f47ef-28ff-456f-bc81-7aef8b510861, audit=true, remoteAddress=127.0.0.1, remotePort=49145, latency=21, _audit=true, req.version=*)
    POST /users/create HTTP/1.1
    user-agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
    host: localhost:3131
    accept: */*
    content-length: 22
    content-type: application/x-www-form-urlencoded
    --
    HTTP/1.1 200 OK
```

Since I am getting the correct responses on curl, but logging incorrect responses, it leads me to believe that the audit logger might not be working as expected.

Will investigate further and update here.

**Comment by DonutEspresso** [comment]
Could you post what the transpiled JS looks like?

**Comment by Achrome** [comment]
@DonutEspresso Sure.

Here's the relevant part.

```javascript
Object.defineProperty(exports, '__esModule', {
  value: true
});
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
var _restify = require('restify');
var _restify2 = _interopRequireDefault(_restify);
var middleware = {
  inject: function inject(server) {
    server.on('after', _restify2['default'].auditLogger({
      log: global.LOG
    }));
  }
};

exports['default'] = middleware;
module.exports = exports['default'];
```

I've pruned the irrelevant part (rest of the middleware) from it, but this is how it looks.

Regardless, I'm not sure if Babel is related to this issue. Let me set up a skeleton Restify app without ES6 and I should be able to comment better.

**Comment by Achrome** [comment]
So, I figured out that it was happening due to `next()` not being called properly.

Changing the following

```javascript
Co(function* () {
    yield user.save();
  }).then(() => {
    res.send(201)
  }, (err) => {
    res.send(422, err);
  });

  return next();
```

to

```javascript
Co(function* () {
    return yield user.save();
  }).then((user) => {
    res.send(201);
  }, (err) => {
    res.send(422, err);
  }).then(next);
```

started working.

Closing this issue now.
