### ISSUE TITLE
Passing errors via next() without triggering .send() feature or implementation detail?

### ISSUE THREAD

**Issue by bittrance** [restify/node-restify#821]
I have an API that takes multiple "operations" in one HTTP POST. Some of these operations may fail. This should affect the status code (setting custom 4xx or 5xx codes meaning "partial" success). These errors are still real errors and should be properly logged et cetera so it is important that they get passed to .on('after').

This results in code looking something like this:

    return function(req, res, next) {
        var promise_per_operation = handler(req, res, next)
        var promise = Promise.settle(promise_per_operation)
        promise.done(function(results) {
            var errobjs = []
            var replies = results.map(function(pi) {
                if (pi.isRejected()) {
                    err = pi.reason()
                    errobjs.push(err)
                    return err.body
                } else {
                    return pi.value()
                }
            })

            if(errobjs.length == 0) {
                res.send(200, replies)
                next()
            } else {
                var multi = new errors.MultiError(errobjs)
                res.send(multi.statusCode, replies)
                next(errobjs)
            }
        })
    }

This works because _run() does nothing with arrays and simply passes it on to .on('after') handler. Is this intentional, or is it liable to change in future development?

Alternatively, should _run() check if headers are already sent before proceeding to sending errors to the client? (I.e. should I submit a pull request to this effect?)

**Comment by DonutEspresso** [comment]
You should handle this yourself by constructing a custom payload with the info you want you pass on, and give it whatever status code you think is most relevant. There's no need to call next with the errors. If you want to to stop processing the request, you can call next with a second param of false.

```
res.send(500, myErrorContext);
next(null, false);
```

**Comment by micahr** [comment]
The comment from @DonutEspresso should resolve your issue.
