### ISSUE TITLE
uncaughtException logs not dumped by default

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#829]
Currently, uncaughtExceptions are not logged by default, which can cause somewhat confusing behavior for those new to restify. Should consider logging these out to console by default.

**Comment by micahr** [comment]
:+1:

**Comment by DonutEspresso** [comment]
How that domains are off by default, this should be less of an issue. We should update docs to reflect that in enabling domains you should also make sure to add an uncaughtException handler.
