### ISSUE TITLE
Consider hiding or removing server.rm()

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#834]
Not sure what the use case was for this method, seems like you could shoot yourself in the foot with this. Consider removing, or making it private, at least.

**Comment by micahr** [comment]
For reference, you are talking about this method https://github.com/restify/node-restify/blob/master/lib/server.js#L516-L524

Which has the following code:

    Server.prototype.rm = function rm(route) {
        var r = this.router.unmount(route);

        if (r && this.routes[r]) {
            delete this.routes[r];
        }

        return (r);
    };

I'm sure this can be useful for dynamically removing routes based on backend data changes. Why shouldn't this be exposed to userland?

**Comment by dun4n** [comment]
Pretty useful in case of feature flipping.

**Comment by retrohacker** [comment]
It seems a case has been made for this feature being useful, and there hasn't been a counter-argument.

I'm going to close this for now, if I'm missing a nuance let me know and we can re-open to discuss :heart:
