### ISSUE TITLE
require('restify') slow: takes about 800 ms

### ISSUE THREAD

**Issue by greglearns** [restify/node-restify#837]
Requiring restify takes about 800ms on my 2015 Mac Macbook Pro. I realize that this is probably due to Node.js having a slow require method, but still, was surprised. While debugging a restart the server continually (half the time with an automated script, and half the time manually), and so I notice the almost 1 second delay.

```
var now = new Date
var restify = require('restify')
console.log('duration', new Date - now);
# 721 ms (ranges up to 900ms)
```
(Thank you for Restify, by the way. Love it!)

**Comment by jokesterfr** [comment]
I got ~500ms with restify, and ~102ms with expressjs (comparison may be irrelevant, due to its "component" design). 

Linux 4.0.1-040001-generic, Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz, running on SSD

**Comment by rosskukulinski** [comment]
@greglearns which version of node are your running?

**Comment by greglearns** [comment]
Ok, it looks like it is probably related to Docker and/or Boot2docker.

Directly on my Mac, running Node 0.10.33, it is about 170ms.

Running Restify 3.0.3 in a container running on my mac in Boot2docker, with the container running ubuntu 15.04, using Node 0.10.38 (and also 0.10.25) it is about 800ms.

**Comment by yunong** [comment]
@rosskukulinski thanks for looking into this. Closing this issue.

**Comment by rosskukulinski** [comment]
@greglearns that makes sense -- there is a perf hit w/ boot2docker due to the virtualization layer - especially with filesystem access.  FWIW, we're running dockerized restify apps in production on CoreOS/Ubuntu where Docker is supported without a VM. We haven't seen any performance issues since moving to Docker.

**Comment by greglearns** [comment]
Thank you Ross, that is good to know
