### ISSUE TITLE
Router should use DFAs instead of an array for route lookups

### ISSUE THREAD

**Issue by yunong** [restify/node-restify#850]
From when we were discussing this on HN, the router can actually use a DFA based approach such that url lookups are constant time `n` where `n` is the length of the url. http://www.colm.net/open-source/ragel/

Otherwise the current approach for routes with regexes means that we need to make an O(n) pass through all of the routes.

**Comment by yunong** [comment]
Here's a good thread about how we might do this: https://news.ycombinator.com/item?id=8631370

**Comment by DonutEspresso** [comment]
:+1:
