### ISSUE TITLE
Error w/ dtrace build when installing in a directory with a '(' in the path on OSX

### ISSUE THREAD

**Issue by andyburke** [restify/node-restify#857]
```
  LD_LIBRARY_PATH=/Users/aburke/Dropbox (Personal)/...
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `LD_LIBRARY_PATH=/Users/aburke/Dropbox (Personal)/...
make: *** [.] Error 2
```

**Comment by micahr** [comment]
Can you provide a little more context as to what you were doing when you received this error?

**Comment by andyburke** [comment]
Just npm installing the package. This is trying to build the dtrace stuff. Likely a path needs to be wrapped in quotes somewhere in a makefile.

**Comment by micahr** [comment]
Please open an issue with the Dtrace-Provider module: https://github.com/chrisa/node-dtrace-provider so they can fix the install issues.
