### ISSUE TITLE
restify-client socket not closing

### ISSUE THREAD

**Issue by jareddlc** [restify/node-restify#858]
I was trying to test my restify server using mocha and restify-client, However, I noticed that when i was done with a test and tried closing server, it would not close and it would the test would fail due to test timeouts. In order for the restify server to close correctly, I would have to keep an list of sockets opened, and when I call closed, iterate over the list of sockets and close them. Alternatively, I could set the socket timeout upon connection.

**Comment by yunong** [comment]
@jareddlc Can you give an example of where this was failing for you?

**Comment by jareddlc** [comment]
Hey @yunong here a simple test case: https://gist.github.com/jareddlc/6fccc11ec325161d4b1a

**Comment by yunong** [comment]
@micahr Mind taking a look at this?

**Comment by micahr** [comment]
The Restify `server.close` method is a proxy for the Node net [`server.close`](https://nodejs.org/api/net.html#net_server_close_callback) function. The behavior that is exposed is that the callback doesn't get called until all connections to the server have been closed. If you call `client.close()` in your callback to `client.get` (right before `done`). You will see that your test finishes almost immediately. 

In that case, I recommend creating your json client in the `before`, and tearing it down in the `after`. Similar to how the Restify [tests](https://github.com/restify/node-restify/blob/master/test/client.test.js#L205) are written. 

Let me know if that works for you.

**Comment by rosskukulinski** [comment]
The server not shutting down because connections are still open makes complete sense.  It's the client behavior that threw us off.

@micahr I feel like that's rather odd behavior for an HTTP client -- I would expect that once a request is done it would properly cleanup the connection.  Nowhere in the [Client docs](http://mcavage.me/node-restify/#client-api) does it mention that you should call ```close()``` (nor mention the close function at all!)

I can understand that sometimes you _do_ want to keep the socket open, but I wouldn't expect that to be the default.

We're going to continue to use the restify server for our microservices, but are switching to [request](https://github.com/request/request) for tests.  If you're happy with the behavior of restify-client, by all means keep it.  I would, however, recommend updating the documentation for restify-client to describe this behavior.

**Comment by yunong** [comment]
@rosskukulinski Thanks for the feedback. 

Yes, the default behaviour for the clients is to keep the connection open until ```close()``` is invoked. This quite handy in a lot of use cases, where you're making many requests to the same endpoint, and do not want to deal with the overhead of creating new connections each time.

I do agree that the docs need to be better -- we're in the process of updating them and this is a good data point. 

Out of curiosity, are there any features that request provides that you feel is lacking in restify-clients? It'd be good to for the core team to understand the specifics of why you're switching (which is totally okay) just so we can improve our framework. Feel free to email me if you'd prefer a private channel. yjxiao at google's mail product dot com.

**Comment by yunong** [comment]
Added #859

**Comment by micahr** [comment]
The client implementations have been neglected for a while, and aren't very robust, especially when it comes to proxying and other cases that aren't exercised by the test suite. We are looking to improve all our clients, as well as their documentation.

In this case, we create a default Agent, who sets a keepAlive for the socket. This means that after your request is completed, we will keep the socket open a little longer, in case another request is made. If you set `agent: false` in your client options, there won't be any keepAlives (off is the default) and you will get a clean exit, without calling `client.close()`.

Thank you for the feedback, we'll be sure to use it as we set our goals for the next few releases. Additionally, if there are further features you'd like for a client, please add them in an issue so we can be sure to track and prioritize them.

**Comment by micahr** [comment]
Closing this issue, as the central problem was resolved. Yunong added #859 to track the updating of the documentation for clients.
