### ISSUE TITLE
Update client docs to refer to client.close()

### ISSUE THREAD

**Issue by yunong** [restify/node-restify#859]
From #858, it's clear that the client docs need some work. We should for one, at least document the fact that connections remain open until explicitly closed by the client.

**Comment by micahr** [comment]
Here is an initial list of tasks for client docs
- []  client.close()
- [] Proxying vs Tunneling
- [] Agents
- [] Full list of options and what they do

**Comment by retrohacker** [comment]
Sorry @micahr, could you clarify what you mean by `Agents`? Is this referring to the HTTP header `User-Agent`?
