### ISSUE TITLE
Global Variable

### ISSUE THREAD

**Issue by AaronTrazona** [restify/node-restify#861]
is there way to create global variable without using .use handler? just like express
app.locals..

**Comment by DonutEspresso** [comment]
You could just create a `server.locals` object on your instance of the server. It's basically what express is doing.

**Comment by lmaccherone** [comment]
If you do this, how does it show up in the req parameter of a handler

**Comment by DonutEspresso** [comment]
Handlers are implicitly bound to the server object using `this`, so you _could_ do `this.locals` but I'd highly recommend against it, as it can be rather brittle. Since you really just want a namespace where you can dump things, it technically doesn't have to live on the server object at all.
