### ISSUE TITLE
Chinese character code issue

### ISSUE THREAD

**Issue by hellfire** [restify/node-restify#863]
I write some API for a project, and I get some data with json schema. The data is well when it transfer from db to client. But It has chinese character code issue when the data present by restify framework. So I want to ask wether you handle this situation.

for some reason, I can't show the picture to you , because the data is internal.

**Comment by micahr** [comment]
If you aren't able to provide a picture of what is happening, perhaps you can provide a contrived example with scrubbed data?

When you say the data is presented by the restify framework, do you mean to a browser, or when the data is accessed within restify?

**Comment by yunong** [comment]
@hellfire Closing this request. Feel free to re-open when you can give us something we can repro.
