### ISSUE TITLE
Reflect API for online documentation

### ISSUE THREAD

**Issue by ChicagoDave** [restify/node-restify#870]
Provide mechanism to report/auto-document entire API with as much information as possible.

**Comment by micahr** [comment]
@ChicagoDave Are you looking for something that will document your routes and the methods they accept? If so, that is an application detail and I suggest using a third party documentation tool. 

Here is a great [rundown](http://blog.fusioncharts.com/2013/12/jsdoc-vs-yuidoc-vs-doxx-vs-docco-choosing-a-javascript-documentation-generator/) of 4 options for documenting your API, it may be a little out of date, but at least it will give you a good idea of the options out there.

**Comment by retrohacker** [comment]
Closing this issue as stale. If this is still a feature you would like to see in restify, comment and we can re-open to disucss :heart:
