### ISSUE TITLE
Doesn't work with serve-static

### ISSUE THREAD

**Issue by halt-hammerzeit** [restify/node-restify#873]
```js
import serve_static from 'serve-static'
application.use(serve_static(path.join(__dirname, '..', 'build')))
console.log(fs.existsSync(path.join(__dirname, '..', 'build', '1.txt'))) // outputs "true"
```

http://127.0.0.1:3000/1.txt
```
{"code":"ResourceNotFound","message":"/1.txt does not exist"}
```

**Comment by DonutEspresso** [comment]
We don't own serve-static, and it looks like that was built with express in mind. I'd check with them to see what their take is on supporting restify. 

That said, you can achieve the same thing using restify's built-in static plugin:

```js
server.get(/\/?.*/, restify.serveStatic({
  directory: '../build'
}));
```

**Comment by halt-hammerzeit** [comment]
@DonutEspresso Well, I know that, and I used that before, but then I found the issue where the author said he thinks this should be removed from the framework because it's no part of it.
So why not delegate it then to such a module?

Anyway, that weekend I moved my project from restify back to express again, because I like to use my serve-static as a middleware: `app.use(static())`
Also I was getting `ResourceNotFoundError` just because I didn't have any gets or posts and only had `use`s, so this was also the reason.

**Comment by DonutEspresso** [comment]
Yeah, restify handles serving static assets a little differently, since it treats it like routing. I tried serve static and found you can do it this way:

```js
application.pre(serve_static(path.join(__dirname, '..', 'build')))
```

Which causes restify to run this middleware prior to routing. So if the files you ask for exist, they will get served. However, because serve_static doesn't call next on a successful file serve, you'll never get audit logs if you're using the restify.auditLogger() plugin.

**Comment by halt-hammerzeit** [comment]
@DonutEspresso oh, I see, I guess that can be useful for other users googling for "restify serve static files".

"However, because serve_static doesn't call next on a successful file serve, you'll never get audit logs if you're using the restify.auditLogger() plugin"

As for the next call, one can always determine if `next()` was called by instrumenting it, something like this
```

for (let method of ['get', 'post', 'put', 'delete', 'head'])
{
	const method_function = web[method]
	web[method] = function(path, handler)
	{
		const simpler_handler = handler
		handler = (request, response, next) =>
		{
			let next_explicitly_called = false
			self_detecting_next = () =>
			{
				next_explicitly_called = true
				next.apply(this, arguments)
			}

			simpler_handler(request, response, self_detecting_next)

			if (!next_explicitly_called) {
				self_detecting_next()
			}
		}

		method_function.apply(this, arguments)
	}
}
```

And if `next()` wasn't called then it calls it manually.
Something like that.
It's some food for thought for anyone looking for this on the internets.
This code is what I wrote to call `next()` manually even if it wasn't called by the interceptor.

**Comment by DonutEspresso** [comment]
Yep, calling `next()` is only half the problem, though. Since you're serving static assets before routing, you'll eventually get a 404 from restify. The audit logs would be misleading in these scenarios.

**Comment by halt-hammerzeit** [comment]
Yeah, I experienced that ResourceNotFound response.
Ok.
