### ISSUE TITLE
next.ifError never sends a response when Promises are involved

### ISSUE THREAD

**Issue by fangel** [restify/node-restify#874]
Hi,

I have found a very odd behaviour of next.ifError when it is being called after a asynchronous operation that involves the use of Promise's. It simply never sends the response back to the client (response.send is never triggered). The behaviour seems to be identical when using the built-in Promise implementation of Node 0.12 and [then](https://github.com/then)'s implementation of [promise](https://github.com/then/promise).  
If you compare it to the normal `if (err) { return next(err) }`, then this will send the response like normal

Let's jump straight into a minimal server that demonstrates this behaviour:

```javascript
var restify = require("restify")
  , bunyan = require("bunyan")

var log = bunyan.createLogger({
  name: 'logger',
  level: 'trace'
})

var server = restify.createServer({log: log})

// Simple function that returns a promise that will get rejected after 100ms
function slowThingBasedOnPromise() {
  log.trace("slow thing started")

  return new Promise(function(resolve, reject) {
    setTimeout(function() {
      reject(new restify.errors.NotFoundError("Some HttpError"))
      log.trace("slow thing finished")
    }, 100)
  })
}

// Lets convert that Promise-based function into one that takes a (err, res)
// style callback, by mapping then -> done(null, res), and catch -> done(err)
var slowThingThenCatch = function(done) {
  slowThingBasedOnPromise()
    .then(function(res) {
      log.trace("then called")
      done(null, res)
    })
    .catch(function(err) {
      log.trace("catch called")
      done(err)
    })
}

// One route where we use ifError
server.get("/thencatch", function thenCatchDemo(req, res, next) {
  slowThingThenCatch(function(err, data) {
    log.trace("data received from the then/catch function")
    next.ifError(err)
    
    res.send(data)
    next()
  })
})
// And an identical one where we use if(err) return next(err)
server.get("/thencatch_manual", function thenCatchManualDemo(req, res, next) {
  slowThingThenCatch(function(err, data) {
    log.trace("data received from the then/catch function")
    if (err) {
      return next(err)
    }
    
    res.send(data)
    next()
  })
})

server.listen(1234)
````

So this has a slow function based on a Promise, that always rejects the promise (indicating a failure).
Then this is converted into a Node.js style function that takes a callback instead.

The server then has two routes, which both calls this Node.js-style function that wrappes slow slow-resolving Promise. One then tries to handle the inevitable error with `next.ifError` while the second uses the more cumbersome `if (err) return next(err)`.
If you call the first route, the response is never sent. If you look at the trace-log, then it simply stops execution without sending a response. The trace-log is the following:

````
[2015-08-03T10:59:44.112Z] TRACE: logger/86270 on note101540.tv2.local: running thenCatchDemo
[2015-08-03T10:59:44.114Z] TRACE: logger/86270 on note101540.tv2.local: slow thing started
[2015-08-03T10:59:44.218Z] TRACE: logger/86270 on note101540.tv2.local: slow thing finished
[2015-08-03T10:59:44.219Z] TRACE: logger/86270 on note101540.tv2.local: catch called
[2015-08-03T10:59:44.219Z] TRACE: logger/86270 on note101540.tv2.local: data received from the then/catch function
````

While if you use the second route that has the manual error-handling, then the response is sent through just fine. The trace-log is the following:

 ````
[2015-08-03T10:59:06.449Z] TRACE: logger/85769 on note101540.tv2.local: running thenCatchManualDemo
[2015-08-03T10:59:06.451Z] TRACE: logger/85769 on note101540.tv2.local: slow thing started
[2015-08-03T10:59:06.558Z] TRACE: logger/85769 on note101540.tv2.local: slow thing finished
[2015-08-03T10:59:06.559Z] TRACE: logger/85769 on note101540.tv2.local: catch called
[2015-08-03T10:59:06.559Z] TRACE: logger/85769 on note101540.tv2.local: data received from the then/catch function
[2015-08-03T10:59:06.560Z] TRACE: logger/85769 on note101540.tv2.local: next(err=NotFoundError) (errName=NotFound) [snip]
[2015-08-03T10:59:06.560Z] TRACE: logger/85769 on note101540.tv2.local: response::send entered (code=200, headers={}) [snip]
[2015-08-03T10:59:06.566Z] TRACE: logger/85769 on note101540.tv2.local: response sent [snip]
    HTTP/1.1 404 Not Found
 ````

I haven't investigate what causes this behaviour yet, but I might try and spend some more time trying to find the cause of this difference.

Kind regards
Morten

**Comment by DonutEspresso** [comment]
Your example doesn't work, because you've wrapped `next` inside of a promise. When restify throws, your promise is actually catching it (instead of restify's domain). Yes, `catch()` actually just returns another Promise, so you don't get the expected behavior.

You can test this by simply adding another catch clause to your example:

```js
var slowThingThenCatch = function(done) {
  slowThingBasedOnPromise()
    .then(function(res) {
      log.trace("then called")
      done(null, res)
    })
    .catch(function(err) {
      log.trace("catch called")
      done(err)
    })
    .catch(function(err) {
      log.trace("catch yet again") 
    })
}
````

Run your example, and you'll see the chained `catch()` get invoked. Unfortunately, by using Promises you have to be Promises all the way down. Due to the way `next.ifError()` is currently implemented, you'll have to do the manual check as you already have done above.

**Comment by fangel** [comment]
Fair point. I knew that `.catch()` returned a new promise, but just hadn't made the connection to the fact that `done()` which called `next()` was inside of the promise, so that any errors thrown in `next` would be caught by the promise and not the domain that `next.ifError` uses. So yes - everything works as intended. Sorry about that...

On a related note, if you use the promise-library from then, and use their [`Promise.nodeify`](https://github.com/then/promise/blob/master/src/node-extensions.js#L37-L57) function to turn a Promise-returning function into a `(err, result)`-style callback function, then neither the Promise nor Restify's domain catches the error from `next.ifError` and instead the exception thrown in `next.ifError` will be uncaught. So `Promise.nodeify` must do some sort of magic to let any exceptions escape the promise, which is then also able to escape the domain that Restify uses to implement `next.ifError`.

**Comment by DonutEspresso** [comment]
I don't know what Promise.nodeify is doing, but certainly it is mucking with domains. Here's a really simple sample code using your example:

```js
var domain = require('domain');
d = domain.create();

d.on('error', function(err) {
    console.log('domain caught err');
});

d.run(function() {
    // domain will catch this
    throw new Error();

    var fn = Promise.nodeify(slowThingThenCatch);

    fn(function(err, data) {
       log.trace("data received from the then/catch function")
       // domain will not catch this
       throw new Error('foo');
    });
});
```

I'd go over to whatever Promise
