### ISSUE TITLE
Consider removing `next.ifError`, or changing it's underlying implementation

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#875]
We've gone back and forth on this a bit, but it may be worth considering removing this API due to it causing a lot of confusion. Certainly, it is partially a documentation problem. 

Because it also currently relies on throwing in the domain, it doesn't work with Promise or Observable chains.

**Comment by karthikiyengar** [comment]
The API is pretty confusing to me. It simply seems to be throwing the exception. What if I want to send the error back as JSON? Do I implement that in uncaughtException?

**Comment by DonutEspresso** [comment]
@karthikiyengar You can use `res.send(err)`  to send the error back in JSON.

**Comment by retrohacker** [comment]
`next.ifError` is deprecated in the 5.x release: https://github.com/restify/node-restify/blob/5.x/lib/deprecationWarnings.js#L4-L17
