### ISSUE TITLE
requests with content-type: application/octet-stream don't have a body property

### ISSUE THREAD

**Issue by iansmills** [restify/node-restify#880]
I'm having issues posting binary data from a c++ app to our restify api when the content-type is application/octet-stream. 

I was looking through the body_parser code to try and find out why this is happening, and I came across this in the body_reader.js file:

``` javascript
function readBody(req, res, next) {
        if ((req.getContentLength() === 0 && !req.isChunked()) ||
            req.contentType() === 'multipart/form-data' ||
            req.contentType() === 'application/octet-stream') {
            next();
            return;
        }
```

It looks like this is preventing the request body being set when the content type is application/octet-stream.

If I'm correct about that, why is this being done? How should I be getting binary data from the c++ app instead? And is there anything wrong with just removing application/octet-stream from the if statement there?

Thanks,
Ian

**Comment by micahr** [comment]
The body_reader plugin should be considered an 80% use case for reading the body of an HTTP request. It is not meant to cover 100% of all uses case, and therefore, it has to limit it's use cases to the most common. Since binary data is likely to be very application specific, it's best if you as the application developer handle it in your own middleware, that way you ensure you cover all of your use cases. 

If you are looking for where to get started with a custom binary body data reading middleware, I'd start with something like the following:

```javascript
function readBinaryBodyData(req, res, next) {
    if ( req.contentType() !== 'application/octet-stream' ) {
        next();
        return;
    }

    // These functions will be specific to your application
    req.on('data', handleData);
    // Don't forget to call next in your done handler
    req.on('done', handleDone);
    // If you handle errors, you should also call next
    req.on('error', handleError);
    // If you don't handle the error, then just send it to next
    req.on('error', next);
}
```

**Comment by ddxtreme** [comment]
Hi,

You can use a custom parser for your needs. 

```
function my_parser(req, res, next) {
  if(req.body == undefined) {
    var buffer = []
    req.on('data', function onRequestData(chunk) {
      buffer.push(chunk)
    });

    req.once('end', function() {
      var concated = Buffer.concat(buffer);
      req.body = concated.toString('utf8'); // change it to meet your needs (gzip, json, etc)
      next()
    });
  } else {
    next();
    return;
  }
}
module.exports = my_parser;
```

After creating this module you can use it on the server middleware after bodyParser()

```
var my_parser = require('./utils/my_parser')
server.use(my_parser)
```
