### ISSUE TITLE
Make OMA DM 2.0 SUPPORT

### ISSUE THREAD

**Issue by lupu60** [restify/node-restify#881]
http://openmobilealliance.org/about-oma/work-program/device-management/

**Comment by micahr** [comment]
Can you elaborate on what supporting OMA DM 2.0 entails and what would be needed to implement it?

**Comment by lupu60** [comment]
In the first step will be nice for the content-type header to have custom value.
The OMA protocol needs some  special value for the  ![content-type](http://prntscr.com/88qrya)
The full doc of OMA DM protocol : http://technical.openmobilealliance.org/Technical/technical-information/release-program/current-releases/oma-device-management-v2-0

To solve this problem for a demo, i added the following lines in /restify/lib/formatters/index.js
```javascript
// Copyright 2012 Mark Cavage, Inc.  All rights reserved.
'use strict';
///--- Exports
module.exports = {
    'application/javascript; q=0.1': require('./jsonp'),
    'application/json; q=0.4': require('./json'),
    =>>>>>>    'application/vnd.oma.dm.initiation+json; q=0.4': require('./json'),
    =>>>>>>    'application/vnd.oma.dm.request+json; q=0.4': require('./json'),
    'text/plain; q=0.3': require('./text'),
    'application/octet-stream; q=0.2': require('./binary')
};
```
In this demo i used restify for a node server and i developed a java client, if you have time read the doc for better understanding.

And for the future to support  OMD commands : 
*HGET
*HPUT
*HPOST
*DELETE 
*EXEC
*GET
*SHOW
*CONT 
*END 
*DEFAULT 
*SUB
*UNSUB

Or  better to start a new NPM package dedicated OMA DM.

Have a nice day!

**Comment by micahr** [comment]
Thanks for adding all that information. Based on the spec and the necessary implementation details, it seems outside the scope of what Restify is best at providing and I don't think it should be included in the module. 

That being said, you could still implement this protocol inside of a Restify application. You can add your own formatters when creating a restify server. Using the following example:

```javascript
var Restify = require('restify');

var server = new Restify({
    formatters: {
        'application/vnd.oma.dm.initiation+json; q=0.4': require('./json'),
        'application/vnd.oma.dm.request+json; q=0.4': require('./json')
    }
});
```

As for the custom methods, you'd have to implement that through query parameters or the post body as HTTP doesn't support those methods.

**Comment by lupu60** [comment]
Thanks !
