### ISSUE TITLE
Route name is stripped of hyphens

### ISSUE THREAD

**Issue by sean3z** [restify/node-restify#882]
I understand the route names are typically used internally solely for the `router.render()` method but, this doesn't seem like expected behavior nor does it allow for a given route name to be useful in any other cases.

Is there any way to get around this?

```js
app.get({
  name: 'my-awesome-route',
  path: '/my-awesome-route'
}, ...)
```

Will provide the following `req.route` object

```js
route: { 
  name: 'myawesomeroute',
  path: '/my-awesome-route',
  method: 'GET',
  versions: [] 
}
```

**edit**: It looks like this is happening for several other characters as well

**Comment by yunong** [comment]
@sean3z this seems like a bug, do you have the cycles to submit a PR?

**Comment by sean3z** [comment]
@yunong sure thing ^^ :)

**Comment by sean3z** [comment]
Fixed in https://github.com/restify/node-restify/commit/30ff6cc9013d4d0168ade28082289ef8f49239e7
