### ISSUE TITLE
async formatter implies that res.send() can also be async

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#885]
Formatters have async signatures now (use cb), but all formatters shipping today are sync. If there's truly an async formatter, `res.send` needs to accept an optional callback as part of it's signature. 

Otherwise, restify will proceed down the handler chain even before the formatter has returned the contents.

**Comment by yunong** [comment]
I think you'd just have to call res.send and or next() in the callback?

**Comment by DonutEspresso** [comment]
But consumers can call res.send directly:

```
function(req, res, next) {
    res.send('hello world');
    next();
}
```

An async formatter would call next before send() has actually completed.

**Comment by retrohacker** [comment]
Closing this in favor of #1347
