### ISSUE TITLE
Formatters documentation outdated wrt v4

### ISSUE THREAD

**Issue by ikr** [restify/node-restify#886]
http://restify.com/#content-negotiation prescribes to _return_ a formatter's result directly, while actually starting from v4.0.0 the result should be returned via the callback.

https://github.com/restify/node-restify/commit/d8d76f1bb6cb9427cfde76d5537d27499f5e24d3

**Comment by ikr** [comment]
Ah, looks like simply the restify.com content is outdated. Here https://github.com/restify/node-restify/blob/master/docs/index.restdown#L415 it's already correct.

**Comment by micahr** [comment]
Good catch @ikr. We'll update the docs with the new API.

**Comment by micahr** [comment]
The docs have been updated with the `cb` signature. Thanks again for pointing this out.
