### ISSUE TITLE
Integration with Connect server

### ISSUE THREAD

**Issue by ggoodman** [restify/node-restify#89]
The object created by restify.createServer() cannot be used as middleware in a connect-based server.

The reason that this would be useful would be to mount a restify server at a specific path for an existing server:

``` javascript
// Mount the restify server from ./servers/api.js at the path "/path/to/api"
app.use("/path/to/api", require("./servers/api"));
```

This approach would allow an application to benefit from connect/express specific advantages for serving templated html pages at the root while leveraging restify's REST api competencies at that specific path.

Note that I have tried the following:

``` javascript
// ./servers/api.js

server = restify.createServer()

// Define routes, etc..

// Export the HttpServer created by Restify for connect to mount as per above
module.exports = server.server
```

This approach causes connect's /lib/patch.js to spew errors that headers have already been sent (by Restify)

**Comment by cadesalaberry** [comment]
Some pretty nice versioning techniques could be done with this feature. For reference, I found a nice article explaining how to do it with `express`.

http://j-query.blogspot.ca/2013/01/versioned-apis-with-express.html

**Comment by DonutEspresso** [comment]
@cadesalaberry restify already supports [route versioning](http://restify.com/#versioned-routes).
