### ISSUE TITLE
Please release 4.0.1

### ISSUE THREAD

**Issue by KenanSulayman** [restify/node-restify#898]
Hey,

given #897, we're currently working on deploying nodejs 4.0.0 and would like to have the optional dtrace-provider to correctly build in the release that we roll out in production.

That is, please release 4.0.1 with *dtrace-provider 0.6.0*.

Thanks! :-)

**Comment by micahr** [comment]
4.0.1 is out.

**Comment by KenanSulayman** [comment]
:+1: :beers:

**Comment by micahr** [comment]
Spoke too soon, 4.0.2 is out now :)

**Comment by KenanSulayman** [comment]
Great, thanks for the notice! :-)
