### ISSUE TITLE
restify now requires git to install from npm

### ISSUE THREAD

**Issue by dsandor** [restify/node-restify#899]
Somewhere around this commit d3e72d8e5b0600933265feb380e7acc4364681a0 (from v4.0.0 to v4.0.1) a requirement was introduced that requires consumers to have the git executable installed in order to install `restify`.  Pinning my dependency to restify@4.0.0 does not have this requirement.  Git installed on my build machine is not an option.

**Comment by micahr** [comment]
When installing a clean version of Restify 4.0.1 I get the following for dependencies:

```
restify@4.0.1 node_modules/restify
├── assert-plus@0.1.5
├── escape-regexp-component@1.0.2
├── tunnel-agent@0.4.1
├── keep-alive-agent@0.0.1
├── negotiator@0.5.3
├── lru-cache@2.6.5
├── mime@1.3.4
├── formidable@1.0.17
├── node-uuid@1.4.3
├── once@1.3.2 (wrappy@1.0.1)
├── semver@5.0.1
├── qs@5.0.0
├── vasync@1.6.3
├── backoff@2.4.1 (precond@0.2.3)
├── spdy@1.32.4
├── verror@1.6.0 (extsprintf@1.2.0)
├── http-signature@0.11.0 (asn1@0.1.11, ctype@0.5.3)
├── csv@0.4.6 (csv-generate@0.0.6, stream-transform@0.1.0, csv-stringify@0.0.8, csv-parse@1.0.0)
├── bunyan@1.5.1 (safe-json-stringify@1.0.3, mv@2.1.1)
├── restify-errors@3.0.0 (lodash@3.10.1)
├── restify-clients@1.1.0 (restify-errors@3.0.0, lodash@3.10.1)
└── dtrace-provider@0.6.0 (nan@2.0.9)
```

I don't see Git as a requirement in that list.

**Comment by dsandor** [comment]
Thanks @micahr.  I get these errors during an `npm i restify@4.0.1` but not during an `npm i restify@4.0.0`:

```
npm verb about to build C:\temp\nmtest\node_modules\restify
npm verb unlock done using C:\Users\dsandor\AppData\Roaming\npm-cache\_locks\restify-3547e112d5344f75.lock for C:\temp\nmtest\node_modules\restify
npm verb stack Error: not found: git
npm verb stack     at F (C:\NodeJS\0.12.7-x64\node_modules\npm\node_modules\which\which.js:72:28)
npm verb stack     at E (C:\NodeJS\0.12.7-x64\node_modules\npm\node_modules\which\which.js:75:29)
npm verb stack     at C:\NodeJS\0.12.7-x64\node_modules\npm\node_modules\which\which.js:83:16
npm verb stack     at FSReqWrap.oncomplete (fs.js:95:15)
npm verb cwd C:\temp\nmtest
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\NodeJS\\0.12.7-x64\\\\node.exe" "C:\\NodeJS\\0.12.7-x64\\node_modules\\npm\\bin\\npm-cli.js" "i" "--verbose" "restify@4.0.1"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
npm verb exit [ 1, true ]
npm verb unbuild node_modules\restify\node_modules\restify-clients
```

**Comment by dsandor** [comment]
I tried the same thing on OS X and I get no mention of git in the silly level log.  Seems like a its related to some Windows dependency.  Also, I never said it was a module dependency but rather it is a build chain dependency that somehow crept in.

**Comment by micahr** [comment]
Can you try on your windows machine with 4.0.2? We had previously included restify-clients in 4.0.1, but it broke semver, so we unpublished and put out 4.0.2 with a smaller set of non API breaking changes.

**Comment by dsandor** [comment]
4.0.2 does in fact work properly.

**Comment by micahr** [comment]
That's great to hear, thanks for reporting the issue. When 5.0 lands we'll
be sure to not include the git URLs in the package.json.
