### ISSUE TITLE
"request" object used as a context when processing a request

### ISSUE THREAD

**Issue by dun4n** [restify/node-restify#900]
People used to use the "request" object as a context but IMHO this object should be stateless, according to the semantic used.
Is this the good way to do it?

I was thinking about to use the domain created on server._run call as a context. Unfortunately, it seems impossible in case of route chaining since a new domain is created for each route.

Btw, sorry for my english, it's not my best skill.

**Comment by micahr** [comment]
Using an object on request should work for most needs.

**Comment by dun4n** [comment]
Of course, but this way you modify the "request" object, so you do not use the original one when you chain route.

A use case could be that the last route may need the original request to perform things like a cache request.

WDYT?

**Comment by micahr** [comment]
`req` is passed to all middleware / handlers and is "stateless" from the sense that it is different for every request. It is common practice to attach request specific state to the `req` object so that you can easily manage the state. If you were to create a new domain for every request, you would be effectively duplicating the built capability with `req`.

**Comment by dun4n** [comment]
Agree but I'm not talking about the middleware but the fact that new domain is created when chaining a route within a route, e.g. `next('other_route')`.
In this case, not creating a new domain will allow to properly use the domain context instead of extending the request object which, IMO, should be immutable.

**Comment by micahr** [comment]
The domains are purely there for error handling. It allows Restify to catch
the error at the appropriate level and either allow the developer to handle
it, or pass it on to the client, or further up the stack if it's a chained
route. For this reason, we don't want to remove the use of domains, until
there is a better way to handle errors in Node.

**Comment by dun4n** [comment]
I didn't told there is a need to remove the use of domains but it's not useful to create a new domain when chaining route: we could just use the existing one (created when running the first route). This way, the domain could be used as a context for a request.
No offense but it's just my point of view :smiley:

**Comment by micahr** [comment]
If you don't create a new domain for each "link" in the request chain, then you wouldn't be able to catch errors before they have lost the context of the location in the request chain. This is why it's necessary to create a new domain for each chained request.

**Comment by dun4n** [comment]
Sorry, I don't understand. What do you mean by "the context of the location in the request chain"? Is it the route name?

**Comment by micahr** [comment]
Yes, route name and other details about the route being run when the error occurs.

**Comment by dun4n** [comment]
Ok I see, but the context could be referenced by the domain when starting the processing of the chained route? Sorry if I missed something.

**Comment by micahr** [comment]
That would involve pushing context on to a domain object, then popping it off in the proper order. This adds more complexity to a solution that is currently easy to reason about and makes it more difficult to manage where an error occurred should one arise.

**Comment by dun4n** [comment]
Thanks for your time and consideration!

**Comment by micahr** [comment]
No problem.
