### ISSUE TITLE
v4.0.1 removes "createStringClient"

### ISSUE THREAD

**Issue by robey** [restify/node-restify#902]
I had to pin restify at 4.0.0 because the new version (v4.0.1) removes "createStringClient". I haven't really investigated yet, but I suspect the intention was to move that API into a new module.

**Comment by micahr** [comment]
Thanks for reporting the issue. We've unpublished 4.0.1 due to that issue. 4.0.2 has been released and it doesn't include the API changes which were breaking. We apologize for the trouble.
