### ISSUE TITLE
Investigate alternative to using domains

### ISSUE THREAD

**Issue by fabiancook** [restify/node-restify#904]
In version 4 of NodeJS domains have been deprecated, to avoid technical debt an alternative should investigated

Just kicking of the conversation

**Comment by DonutEspresso** [comment]
Thanks for filing the issue, here are other relevant links:
https://github.com/nodejs/node/issues/66
https://github.com/nodejs/node/commit/6a29356451e4f2a204c6319aa85923176dee92c1

Honestly, not much we can do at the moment until there's a viable alternative (at which time full deprecation will kick in).

**Comment by retrohacker** [comment]
Closing as it appears v5 has full deprecated domains in restify.
