### ISSUE TITLE
Distribute restify API across files?

### ISSUE THREAD

**Issue by SamuelMarks** [restify/node-restify#907]
Should we call `createServer` in many files, import them all into a main module, then merge the instances together?

Or do we export the `app` from the main module, then `require` them in all submodules; add routes, then ensure they're all required from the main module?

Xor something else entirely?!

PS: Please recommend a solution that caters to testing (I use `supertest`)

**Comment by micahr** [comment]
You should only call `createServer` once, and either export that server object, adding routes in other files or you can require your routes into the same file you are creating the server object in. The latter option gives you one place to that is creating routes, so if you have issues with your routes, you only have to look in one location.

I don't think there is a specific solution that caters more or less to testing. But if you find one, please feel free to share it.

**Comment by SamuelMarks** [comment]
Hmm, I thought maybe passing along the `Server` object would be the best way to proceed:

### app.ts
```
/// <reference path='typings/node/node.d.ts' />
/// <reference path='typings/restify/restify.d.ts' />

'use strict';

import restify = require('restify')
import auth_routes = require('./api/auth/routes');

var app = restify.createServer();
auth_routes.login(app);

var config = {
    appRoot: __dirname // required config
};

if (require.main === module) {
    app.listen(process.env.PORT || 3000, function () {
        console.log('%s listening at %s', app.name, app.url);
    });
}

module.exports = app; // for testing
```

### /api/auth/routes.ts
```
/// <reference path='../../typings/restify/restify.d.ts' />

'use strict';

import restify = require('restify')

export function login(app: restify.Server): void {
  app.get('/login', function(req: restify.Request, res: restify.Response, next){
    res.send('/login ' + req.params.name);
    next();
  });
};
```

My solution almost works, for some reason that route isn't being registered with the app. Any clues?
