### ISSUE TITLE
Router need to detect route conflict

### ISSUE THREAD

**Issue by leitsubomi** [restify/node-restify#909]
If developer accidentally specify a route path and version conflict with existing the registered route, the server always run the callback registered first.  Need to detect route path and version collision and throw error.

**Comment by micahr** [comment]
:+1:

**Comment by leitsubomi** [comment]
I spent sometime to add a helper function as following to detect a duplicate route
/**
 * Check if a identical version, path and method route already exists
 * if so server throws error
 * @private
 * @function checkDuplicate
 * @throws {Error} If a duplication is detect, server throws
 * @param  {String} method new route's method
 * @param {String} routePath new route's routePath regex pattern
 * @param {Array} versions new route's version if any
 * @param  {Array} routes  existing routes for a certain method
 * @returns {boolean} return true if there is no duplication else throw
 */
function checkDuplicate(method, routePath, versions, routes) {
    var dupVersion;
    var dupMethod;
    var dupPath;
    var routeInfo;
    var duplicate = Object.keys(routes).filter(function (rname){
        var exist = false;
        exist = routes[rname].method === method && routes[rname].path.toString() === routePath.toString();
        if (!exist) {
            return false;
        } else {
            dupMethod = routes[rname].method;
            dupPath = routes[rname].path.toString();
            //check if there is version available
            if (typeof versions === undefined) {
                return true;
            } else if (typeof versions !== undefined && typeof routes[rname].versions === undefined) {
                //if existing route doesn't have version, it's not a conflict
                return false;
            }
            //check if there is version match
            dupVersion = versions.filter(function (v) {
                if (routes[rname].versions) {
                for (var i =0 ; i < routes[rname].versions.length; i+=1) {
                    if (routes[rname].versions[i] === v) {
                        return true;
                    }
                }
                return false;
            }
            });
        }
        //dupVersion is the conflicting version number
        if (dupVersion.length && dupVersion[0]) {
            return true;
        }
        return false;
    });
    if (duplicate.length && duplicate[0]) {
        if (dupVersion) {
            routeInfo = dupMethod + ' ' + dupPath + ' ' + dupVersion[0];
        } else {
            routeInfo = dupMethod + ' ' + dupPath;
        }
        throw new Error('Route already exists' + routeInfo);
    }

    return true;
}

It turns out not only path, version, method determine route's uniqueness.  There is undocumented parameters like content-type, name also determines the finding algorithm.  Need to spend more time to read router.js code where determines the route.  Therefore, will schedule time to revisit this later.

**Comment by leitsubomi** [comment]
sample unit test for this would be 
test('use + get duplicate path', function (t) {
    SERVER.use(function (req, res, next) {
        next();
    });
    SERVER.get({
        url: '/foo/something',
        version: '1.1.1'
    }, function tester(req, res, next) {
        res.send(200, {
            testdata: 1
        });
        next();
    });
    assert.throws(
        SERVER.get({
            url: '/foo/something',
            version: '1.1.1'
        }, function tester(req, res, next) {
            res.contentType = 'json';
            res.send(200, {
                testdata: 2
            });
            next();
        }),
    Error);
});
