### ISSUE TITLE
Built-in way to return HTTP 406 as part of content negotiation?

### ISSUE THREAD

**Issue by honzajavorek** [restify/node-restify#911]
Let's say I am about to implement API, which contains an URL, which:

- answers with media type `A` if requested with no `Accept`
- answers with media type `A` if requested with `Accept: A`
- answers with HTTP 406 if requested with `Accept: B`

Does Restify has any built-in content negotiation mechanism to handle such scenario? Also, what if I need to use completely different rules and media types on other URLs? The way `formatters` are implemented it seems that they are API-wide. It seems I cannot specify different formatters and rules for separate routes. Is this correct?

**Comment by honzajavorek** [comment]
I guess I found answer (sort of) here: http://stackoverflow.com/questions/15762034/handling-accept-headers-in-node-js-restify It's a shame the catch-all formatter is not mentioned in the docs.

**Comment by micahr** [comment]
Glad you found the answer to your question :smile:

We'll update the docs with more information on formatters.
