### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by micahr** [restify/node-restify#912]
We should adopt a template similar to what Node is using for their [documentation](https://nodejs.org/api/index.html) as it is clean, concise, and easy to read. 

I propose we move from Restdown to Markdown, break out individual files of documentation (instead of all one file), and use a new template. Also, streamlining the method in which documentation is generated will make it easier for everyone to contribute.

**Comment by o5** [comment]
I just attach a few links, if you're going to use Markdown.

http://ricostacruz.com/flatdoc/
http://documentup.com/jeromegn/documentup

**Comment by retrohacker** [comment]
GitHub pages supports jekyll by default, and I've had great success using that for will.blankenship.io, it would give us the flexibility of full HTML/CSS/JS while still being able to parse markdown for content. Plus, then updates to our docs would be near-instant and we wouldn't need any extra CI/CD infra as GitHub will do the rebuild for us.

My only complaint so far is that it doens't support ASM-GAS highlighting, though I suspect that wouldn't be an issue here :wink:

**Comment by retrohacker** [comment]
Shipped a new website.
