### ISSUE TITLE
OPTIONS response should contain Allow header with list of allowed methods

### ISSUE THREAD

**Issue by honzajavorek** [restify/node-restify#915]
Hello,

https://tools.ietf.org/html/rfc7231#section-4.3.7 says

> A server generating a successful response to OPTIONS SHOULD send any
> header fields that might indicate optional features implemented by
> the server and applicable to the target resource (e.g., Allow),
> including potential extensions not defined by this specification.

Is there any preferred way how to easily implement `Allow` header in a response to `OPTIONS`?

**Comment by micahr** [comment]
You would have to set a route handler for options, then just set a header on the response:

```javascript
var server = restify.createServer({});

server.opts('/', function(req, res, next) {
    res.setHeader('allow', 'all');
    res.send(200);
    return next();
}
```

**Comment by honzajavorek** [comment]
Thanks. I learned there is something like `req.methods`, which allows me to list all the available methods or add/remove some.
