### ISSUE TITLE
Why do Twilio requests fail?

### ISSUE THREAD

**Issue by robwilkerson** [restify/node-restify#920]
First, my apologies for dropping a help request here. It's not the best forum for them and, depending on the project, not the appropriate forum. Unfortunately, I can't seem to find any help (or any dialog) anywhere else I've tried so I've landed here.

I'm trying to create an endpoint that will respond to SMS messages via Twilio. When I send a SMS message to my Twilio phone number, they send a POST request to my endpoint. The endpoint just returns a specifically formatted response. Unfortunately, my endpoint is never receiving the Twilio POST request and, for the life of me, I can't seem to find the right answer.

The only thing I've been able to find that _might_ be the answer is that the Twilio request is sent with the `Content-Type: application/x-www-form-urlencoded` request header. Although the Restify docs say the `bodyParser` handles that type, I do notice that my `server.acceptable` array does not include it.  To my eye, that looks like it could be an issue, but maybe I'm just not familiar enough with the underlying details.

In every other way that I can tell, the Twilio request looks pretty normal, but at this point, even within `server.pre()`, dumping `req.body` simply returns `undefined`.

I'm sure it's a me problem, but I'm at a complete loss. Any push in the right direction would be much appreciated.

**Comment by micahr** [comment]
Do you mind posting the code (or an example of it) to a gist or this issue so we can try to help debug?

**Comment by robwilkerson** [comment]
Thanks, @micahr. See if this helps: https://gist.github.com/robwilkerson/a6bef1ab80f47d6efd97

**Comment by micahr** [comment]
Looks like you are using versions for your routes, which requires that twilio passes that appropriate version back to your server on the POST or else it won't find a route that matches. If you remove the `version: [semVer] ` config from your route, you should get properly routed.

Additionally, req.body won't be populated until after the bodyParser is run, so your `pre` function won't have access to it as the bodyParser hasn't run yet. Try making that `pre` function another `use` method, after the body parser.

**Comment by robwilkerson** [comment]
Well that's just embarrassingly simple. I can't believe I never saw that. One last question (I hope). Twilio now reports that it:

> was unable to process the application/octet-stream Content-Type header in the response

I think I'm setting the header to `text/xml`. Is the syntax off? I've also tried using `res.setHeader() and setting the content-type to `application/xml` with the same result.

Thanks again for your help with this. The number of hours I've spent dancing around this is humbling to say the least.

**Comment by robwilkerson** [comment]
Huh. Changing `res.send(twiml.toString())` to `res.end(twiml.toString())` checked the last box to a Twilio integration that finally works. I thought `send()` handled `end()`, but I'm too tired to worry about it now.

I really appreciate your help getting over that last hurdle.

**Comment by micahr** [comment]
If you call `next(false)` after using `res.send(twiml.toString())` it will flush the response with the header you set.

`send` isn't quite the same syntax as `end`. 

It is also a best practice to call `next` even after calling `res.send` so your audit logger or other post processing middlewares can run.
