### ISSUE TITLE
allow passing of qs options

### ISSUE THREAD

**Issue by objelke** [restify/node-restify#925]
Problem:

qs limits the number of array elements in a URL query to 20 - above that, it will be converted to object properties, see: https://github.com/hapijs/qs.
Highly undesirable for some cases.

> qs will also limit specifying indices in an array to a maximum index of 20. Any array members with an index of greater than 20 will instead be converted to an object with the index as the key.
> This limit can be overridden by passing an arrayLimit option:

if the options which can be passed here:

server.use(restify.queryParser({...}));

would allow for a qs section or some argument pass-through mechanism, qs could be configured by the restify user. Even a specific: arrayLimit option would work.

If this request is found useful, absolutely willing to make a pull request - not sure of the standard process here. It's such a minor thing that the whole pull request/review cycle may be a bit overkill?

(note: I am aware that it's not hard to replace the restify queryParser - so it's not that there is no solution. But would consider configuration options for the built-in parser the superior solution)

**Comment by micahr** [comment]
Thank you for the suggestion. It wouldn't be too hard to pass config through to the `qs` module.

**Comment by trentm** [comment]
This is fixed by #1209 in the 4.x branch and published as restify@4.2.0.
For restify versions after 4.x the plugins are now unbundled to restify-plugins. I have yet to do the PR to add this functionality there.

**Comment by retrohacker** [comment]
Unmarking this as a blocker for the 5.x release. We will be changing the way we handle releases moving forward so this PR can be opened against either 5.x before the release, or master after, and will still be shipped to npm in a timely manner :heart:
