### ISSUE TITLE
Add link to github project page on docs

### ISSUE THREAD

**Issue by ricardograca** [restify/node-restify#926]
There was already an open issue (#88) about this that was closed and apparently resolved. However, there is currently no link in the docs to the repo any more.

**Comment by yunong** [comment]
@micahr @DonutEspresso Would you guys mind adding a "fork me on github" banner to the current site? Thanks!

**Comment by micahr** [comment]
Closed by #933. [Restify.com](http://restify.com) has been updated.

**Comment by yunong** [comment]
WOOT

**Comment by ricardograca** [comment]
Great work! Love the new logo on the left :) The only problem now is that the "fork me" banner covers the scrollbar:

![captura de ecra de 2015-10-11 12 49 19](https://cloud.githubusercontent.com/assets/1457035/10416675/1b812bba-7017-11e5-9c50-67152a583311.png)

Another issue I don't understand is why http://mcavage.me/node-restify/ and http://restify.com don't show the same thing. The top result on Google when searching for "Restify" is always the first link, so I wasn't even aware that restify.com existed.
