### ISSUE TITLE
Tell your points of strength

### ISSUE THREAD

**Issue by marcolino** [restify/node-restify#927]
In the README you say: "this framework is similar to `express`"... I feel you should clearly point out what are the main differences with `express`, and for which use cases this is better then the others... :-)

**Comment by yunong** [comment]
@marcolino This is true. Do you think you have some cycles to help us craft the message?

**Comment by marcolino** [comment]
@yunong I think I'll keep my cycles to work on some more clearly headed project, sorry... :-)

**Comment by tvjg** [comment]
I believe this is already [covered at the top here](http://restify.com/) @marcolino . Probably should be in the README too.

**Comment by marcolino** [comment]
Sorry, didn't see *API guide*... Yes, two lines in the README would be very useful...
