### ISSUE TITLE
be able to access both the raw request body as well as the eventually parsed body

### ISSUE THREAD

**Issue by hyun007** [restify/node-restify#928]
would love to have a req.rawBody available in the request object

**Comment by DonutEspresso** [comment]
`req.rawBody` should be available. Which post types are you seeing this missing for? I see it's missing for JSON - we'll fix that for 5.x.

**Comment by DonutEspresso** [comment]
In the meantime, you should be able to access it via `req._body`, but it may be subject to change.

**Comment by DonutEspresso** [comment]
Closing in favor of issue in plugins repo.
