### ISSUE TITLE
How to scale socket.io on restify?

### ISSUE THREAD

**Issue by louisgv** [restify/node-restify#930]
I am trying to scale socket.io running on restify. I was able to set it up to run great on one nodejs instance. Now when I scale my app to four instances, the app ecosystem broke (i.e., events were not synched correctly between clients).

I'm looking for examples on how to set up sticky sessions with restify. Or, how is it being done nowadays?

The update on sticky session was a year ago: [Socket 1.0 Update / Scalability](http://socket.io/blog/introducing-socket-io-1-0/#scalability). 

I found these two blogs on setting this up but they both used Express and were also written more than a year ago: 
- [Article 1](http://www.ibm.com/developerworks/cloud/library/cl-bluemix-node-redis-app/index.html_) 
- [Article 2](http://blog.pivotal.io/pivotal-cloud-foundry/products/scaling-real-time-apps-on-cloud-foundry-using-node-js-and-redis)

As I am making a headless API, I think Express should not be used. Is it the recommended way of thinking or I should just use Express?

**`package.json:`**

```
  "dependencies": {
    "hiredis": "^0.4.1",
    "pouchdb": "^4.0.3",
    "pouchdb-upsert": "^1.1.3",
    "redis": "^2.0.1",
    "restify": "^4.0.0",
    "socket.io": "^1.3.7"
  }
```

Any help would be appreciated!

**Comment by yunong** [comment]
This doesn't really look like it's an issue with restify. You should be able to test out sticky sessions with socket.io without restify. Can you try that first? If that's working then I can tell you whether the issues resides with restify.

**Comment by louisgv** [comment]
@yunong Thanks for the quick reply, and sorry for the late reply...

I have been reading into the issue and just realized that I had left off an important detail: I wanted to scale socket.io on cloud foundry, and they already have sticky session enabled, the only requirement is to setup a cookie named 'jsessionid'

The only way I can see to set a cookie with restify is by using [restify-cookies](https://www.npmjs.com/package/restify-cookies) package, however I don't see any example of setting the cookie for socket.io using this package...

So the question comes down to is there a way to setup a global cookies that's similar to Express which looks like this?
```
/**
* Use cookieParser and session middleware together.
* By default Express/Connect app creates a cookie by name 'connect.sid'. But to scale Socket.io app,
* make sure to use cookie name 'jsessionid' (instead of connect.sid) use Cloud Foundry's 'Sticky Session' feature.
* W/o this, Socket.io won't work when you have more than 1 instance.
* If you are NOT running on Cloud Foundry, having cookie name 'jsessionid' doesn't hurt - it's just a cookie name.
*/
app.use(cookieParser);
app.use(express.session({store:sessionStore, key:'jsessionid', secret:'your secret here'}));
```

**Comment by kmudrick** [comment]
@louisgv Not sure if this is helpful, but the 'cookie-session' module (https://github.com/expressjs/cookie-session) is actually compatible with restify too - maybe you can use that.

**Comment by retrohacker** [comment]
Closing this issue as stale due to inactivity.

If the cookie-session plugin didn't help, please comment and we can re-open this issue to discuss :heart:
