### ISSUE TITLE
Update to latest node-spdy

### ISSUE THREAD

**Issue by indutny** [restify/node-restify#931]
Hello!

What do you think about upgrading node-spdy to 2.x?

Cheers!

**Comment by yunong** [comment]
We'd definitely want to. Feel free to file an issue.

**Comment by andytzeng** [comment]
node-spdy has released to 3.2.0. Is there any plan to upgrade to latest version of spdy?

**Comment by DonutEspresso** [comment]
We'd love to - feel free to try it out and file a PR.
