### ISSUE TITLE
How can i return RESTful  error with a JSON object 

### ISSUE THREAD

**Issue by pangguoming** [restify/node-restify#934]
Hello, i use the following statement to return a RESTful Error,
return next(new restify.InvalidArgumentError(util.inspect(errors)));
but i find In "message" , it is a string ,but i want it is a JSON array 
{
  "code": "InvalidArgument",
  "message": "[ { param: 'start', msg: 'start is required', value: undefined },\n  { param: 'end', msg: 'end is required', value: undefined } ]"
}

how can i do it?

**Comment by DonutEspresso** [comment]
I'm not sure what you're trying to do with `util.inspect(errors)`, but InvalidArgumentError is an Error constructor, which takes a string as an argument. It's getting coerced into a string. You can attach your own `body` property to an error, which would be used when "rendering" an Error object:

```
var stringifiedErrs = JSON.stringify(errors);
var resError = new restify.InvalidArgumentError();
resError.body = stringifiedErrs;
return next(resError);
```

**Comment by pangguoming** [comment]
Thanks a lot
