### ISSUE TITLE
Pass `name` option into createServer() does not work

### ISSUE THREAD

**Issue by o5** [restify/node-restify#936]
From [docs](https://github.com/restify/node-restify/blob/5.x/docs/index.restdown#L147): 
```
By default, this will be set in the `Server` response header, default is restify
```

Created the server with options:
```js
var server = restify.createServer({
    name: 'My Server',
});
```

Expected the `Server: My Server` response header, but none given.
```
curl -is http://localhost:8080/hello/test
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 12
Date: Thu, 22 Oct 2015 14:48:47 GMT
Connection: keep-alive

"hello test"%
```

Node.js v4.2.1
Restify v4.0.3

**Comment by micahr** [comment]
Looks like the docs are a bit misleading. You need to use the full_response plugin in order to get that: https://github.com/restify/node-restify/blob/master/lib/plugins/full_response.js#L75-L77

**Comment by o5** [comment]
Thanks! This is the trick :)

```js
server.use(restify.fullResponse());
```
