### ISSUE TITLE
Custom errors in plugins

### ISSUE THREAD

**Issue by matteocontrini** [restify/node-restify#948]
In the case an API has a custom format for error responses, plugins cannot be used/adapted.
For example, the `accept` or `throttle` plugins hardcode the error prototype that should be used when returning an error. And if the values of that property (the 'restCode' for example) don't comply with the API standard, the plugin cannot be used.

An idea would simply be to add an optional parameter/property in the options object, for the plugin.

Anyone with me?

**Comment by DonutEspresso** [comment]
Yes, I think this would be really nice to have. The plugins should definitely call next with the error instead of sending out a response directly. That would give the user a chance to handle it via the server events:

```js
server.on('NotAcceptable', function(req, res, err, cb) { ... });
```
