### ISSUE TITLE
Authorization header with CORS?

### ISSUE THREAD

**Issue by nparsons08** [restify/node-restify#950]
How does one go about using an Authorization header with CORS? It doesn't seem to work for various reasons... one of which is that the Authorization header is not exposed by Restify. Thoughts?

**Comment by SamuelMarks** [comment]
Maybe use a plugin? - https://github.com/TabDigital/restify-cors-middleware

**Comment by WarFox** [comment]
I had to do this

```
restify.CORS.ALLOW_HEADERS.push('authorization');
restify.CORS()
```

Don't know why authorization is not added in `ALLOW_HEADERS` in [CORS plugin](https://github.com/restify/node-restify/blob/5.x/lib/plugins/cors.js#L10). To me it seems logical to add it into `ALLOW_HEADERS`.

There is a comment in [router.js](https://github.com/restify/node-restify/blob/5.x/lib/router.js#L548) that says, 
> user will need to defined their own .opts handler to
> do that (_that being authentication_)

Also see #664, there is more discussion.

**Comment by Qwerios** [comment]
I added a working code sample to #664 which might be of interest for you

**Comment by leonibr** [comment]
Even if you configure it will always use the constant 'ALLOW_HEADERS';

`restify.CORS({
    headers: ['x-request-id', 'authorization']
})
`
The current alternative is to override the constant like @WarFox  did.

**Comment by retrohacker** [comment]
https://github.com/TabDigital/restify-cors-middleware is now supported

Deprecated CORS example has been removed from the repo
