### ISSUE TITLE
Support arbitrary extra attributes on RestError?

### ISSUE THREAD

**Issue by SamuelMarks** [restify/node-restify#954]
Depending on my tier—e.g.: `prod`, `dev`, `test`—different information is exposed in the output.

For example, with `dev` I might want to expose the full stack-trace. To make things cleaner, I'm using `next.ifError` around the place, and am inheriting from `RestError` as per the suggestion in your docs.

Finally when I implement to an RFC, there are certain restriction on the output. For example, with RFC6749 the error output needs to have `error`, `error_description` and `error_uri`. ttps://tools.ietf.org/html/rfc6749#appendix-A.7

So one wouldn't need other attributes (except `statusCode` and [maybe] `error_code`).

Can you please support arbitrary attributes on `RestError`, or at least a superset of the current one?

PS: Yes I will be open-sourcing this project!

**Comment by DonutEspresso** [comment]
When restify renders an error out, it uses the error object's `body` property. Feel free to append to that property as needed. 

Alternatively, the newly broken out [restify-errors](https://github.com/restify/errors#makeconstructorname--defaults) module allows you to create custom constructors that allow you to specify arbitrary properties on the prototype.

**Comment by SamuelMarks** [comment]
Perfect, overwriting the `body` did the trick.
