### ISSUE TITLE
matchedVersion() returns range instead of version on every call but the first

### ISSUE THREAD

**Issue by doodlemeat** [restify/node-restify#959]
When calling req.matchedVersion() the second time, it returns the range. It should always return the version.
	server.get({
		"path": "/test",
		"versions": ["0.1.0", "0.1.1"]
	}, function(req, res, next) {

		// requested version (Unaltered Accept-Version header)
		req.version(); 

		// the matched version (This should only return a version, not a range)
		// problem is that this function returns the range on the second call to this route because of caching
		req.matchedVersion();
		
		next();
	})

**Comment by DonutEspresso** [comment]
Here's the code for `matchedVersion()`:

```js
Request.prototype.matchedVersion = function matchedVersion() {
     if (this._matchedVersion !== undefined) {
        return (this._matchedVersion);
     } else {
        return (this.version());
     }
 };
```

If `matchedVersion()` is returning the same thing, it's because the router couldn't find a version match. What's the version specified by the request?

**Comment by doodlemeat** [comment]
The thing is, matchedVersion ONLY works the first time I do a request to that endpoint.

**Comment by doodlemeat** [comment]
BUMP!

	var restify = require("restify");

	var server = restify.createServer();

	server.get({
		"path": "/test",
		"version": "0.5.0"
	}, function(req, res, next) {
		res.send(200, {
			"req.version()": req.version(),

			// First response gives correct version
			// All responses after gives the same as req.version()
			"req.matchedVersion()": req.matchedVersion()
		});
	});

	server.listen(8080);

I think this should be considered a bug.

**Comment by micahr** [comment]
This could be a bug in your example code, but you don't call `next` in your handler.

**Comment by doodlemeat** [comment]
Calling next() is not the problem. calling next() is optional. And by calling next after the response already has isnt going to change what the actual response is. This is all the code that is needed.

**Comment by DonutEspresso** [comment]
Looks like the problem was with caching in the router. It was returning early and never getting a chance to set the matchedVersion on the request object.

**Comment by tvjg** [comment]
Sorry to bump a closed issue, but is there any chance of a backport to 4.x branch? I am willing to assist if desired.

**Comment by DonutEspresso** [comment]
Hi, at this point we're not working on 4.x anymore given the imminent (this month) release of 5.x, but we're happy to take PRs if that's something you're interested in.

**Comment by tvjg** [comment]
Thanks @DonutEspresso , I've opened PR #1098 .
