### ISSUE TITLE
Best practice for accessing logger from a module

### ISSUE THREAD

**Issue by ajwagnerilluminate** [restify/node-restify#967]
I have looked for the answer to this for a while and just have not come up with a solution.  I understand that I have access to the builtin logger from `req.log.xxxxx(...)`, but what about a module that I have required into my controller?  For example:

in my controller file, someController.js
```javascript
    var myModule = require('myModule');

    SomeController.listUsers = function listUsers(req, res, next){
        req.log.info('Some log message'); // <---- this works just fine
        //... 
    }
```

In myModule.js:
```javascript
    module.exports = {
        getUsers: function () {
            // ...
            // I would like to be able to log from here, but don't have access to the req object.
        }
    }
```

I don't really like the idea of passing the log object to the module's method, as that seems sloppy to me.  If that's the only solution, then I'll live with it.

**Comment by DonutEspresso** [comment]
If you want request scoped logs, this is unfortunately the only way to do it.

**Comment by DonutEspresso** [comment]
Before closing this out - an alternative is to have the module create its own logger. The downside is that logs created by that module are then no longer request scoped (which may or may not be a deal breaker depending on what the module is doing).
