### ISSUE TITLE
'hapijs/qs' module recently EOL'd, what's the plan?

### ISSUE THREAD

**Issue by notmatt** [restify/node-restify#968]
Today I root-caused a problem I was having to qs, and when I went to open the requisite issue on it, discovered [it is going EOL](https://github.com/hapijs/qs/issues/140#issuecomment-164850132). As restify is a consumer, and I didn't see it mentioned or anyone participating on the qs issue, I thought I should bring it up here, as alternative(s) will eventually be required.

As an aside for the curious, the issue was down to this un-[expected, documented, specified] behaviour:
```javascript
qs.stringify({ foo: null }) // => 'foo='
qs.stringify({ foo: [] })   // => ''
```

**Comment by DonutEspresso** [comment]
Thanks for the heads up! We'll definitely want to migrate to an alternative. AFAICT, qs usage is contained within the plugins only, which reduces scope a bit.

**Comment by hstonge** [comment]
Ownership has been transfered: https://github.com/ljharb/qs

**Comment by DonutEspresso** [comment]
Cool. Going to mark this as closed for now.
