### ISSUE TITLE
Handling an InternalServerError or an uncaughtExcpetion properly

### ISSUE THREAD

**Issue by TravelingTechGuy** [restify/node-restify#979]
I'm trying to use my own event handlers, using the documented `.on` command, with the proper event name (see [restify error handling documentation](http://restify.com/#error-handling)). Here's a sample Mocha test:

```javascript
  it('should handle 500 for internal server error', done => {
    let msg = 'myError';
    server.on('InternalError', (req, res, err, cb) => {
      console.log(1);
      res.send(500, msg);
      cb();
    });
    server.on('InternalServerError', (req, res, err, cb) => {
      console.log(2);
      res.send(500, msg);
      cb();
    });
    server.on('uncaughtException', (req, res, route, err) => {
      console.log(3);
      res.send(500, msg);
    });
    
    client.get('/broken', (err, req, res, obj) => {
      console.log(err);
      should.exist(err);
      err.statusCode.should.equal(500);
      err.body.message.includes(msg).should.equal(true);
      done();
    });
  });
```

The route I've added earlier is:

```javascript
  server.get('/broken', (req, res, next) => {
    process.nextTick(function() {
      next(new Error('oh no!'));
    });
  });
```

**Results:**

1. Neither 1, 2 or 3 are printed - meaning none of the handlers were called
2. Instead of seeing `'myerror'` in the error body, I see `'oh no!'`
3. Test fails to find expected string (duh :))

What's the proper way to ensure that a server error hits my handler first? Is my route correct in simulating the error?

**Things I've tried:**
- Using a restify error in the route:

```javascript
  server.get('/broken', (req, res, next) => {
    var err = new restify.errors.InternalServerError('oh no!');
    return next(err);
  });
```

- Trying to simulate an uncaught exception:

```javascript
  server.get('/broken', (req, res) => {
    res.send(200, 1/0);  //division by zero
  });
```

In both cases, none of the handlers fired.

**Comment by micahr** [comment]
I think the issue is that you are passing an error to `next` which allows your next handler to gracefully handle the error. If instead you `threw` the Error, you would get it in the uncaught exception handler or the handler for the individual error.

```
server.get('/error', (req, res, next) => {
    throw new Error('broken');
});

server.on('uncaughtException', (req, res, route, err) => {
   console.log(err); // Logs the error
});
```

**Comment by DonutEspresso** [comment]
There are two things here:

1) `uncaughtException` event is fire only on uncaught exceptions (unexpected errors) in your code, or an explicit throw (per @micahr's example above) that will trigger that event. In your example, division by zero actually just returns you `Infinity`, so it's not an exception. 

2) To trigger the other standard events, you'd pass that error type to `next()`, as you are already doing:

```js
server.on('GatewayTimeoutError', function(err, req, res, cb) {
  // boom! this event has been fired.
});

server.on('/', function(req, res, next) {
  next(new restify.errors.GatewayTimeoutError('too slow'));
});
```

I think the problem you're running into is that InternalServerErrors are currently "special" in that the event name is actually `InternalServer`, so you'd want `server.on('InternalServer', ...);`. It's not consistent with the other errors, and something def worth fixing. Please see the [docs on error handling](http://restify.com/#error-handling) to see how to send alter the response for specific errors as you are trying to do.

**Comment by TravelingTechGuy** [comment]
Thanks @micahr and @DonutEspresso for the pointers. Here's where I am now:
1. Handling `InternalServer` works - and I see an issue was opened to correct that.
1. Throwing an exception, rather than passing to `next()` always yields an `uncaughtException`
1. Due to the above, I now have an issue with handling other errors. So my main goal was to provide default error handlers for the 5 basic HTTP errors, in my module. I want to handle 403 (Forbidden). 
I have a `server.on('FobiddenError', (req, res, err, cb) => {...});` handler, but if I try:

```javscript
  server.get('/forbidden', (req, res, next) => {
    let err = new errors.ForbiddenError('Forbidden!!!');
    return next(err);
  });
```

And if I just try `throw new errors.ForbiddenError('Forbidden!!!');` it gets caught by the `uncaughtException` handler.

So what's the best way to trigger default HTTP errors and handle them (btw, no problem with triggering 404 - just call a route that does not exist).

**Comment by DonutEspresso** [comment]
Apologies - I think I remembered incorrectly, had to do some quick testing to verify. It turns out all the error events do not have 'error' in them. So for forbidden, it would be: `server.on('Forbidden', ...)` and you would pass that error via next.

**Comment by TravelingTechGuy** [comment]
Thanks @DonutEspresso - this worked (i.e. looking for "Forbidden", instead of "ForbiddenError"). If that's the case, than "InternalServer" - without the "Error" - is consistent (if unsavory). So you can close the other issue.
