### ISSUE TITLE
Cannot pass to null to res.send (includes possible solution)

### ISSUE THREAD

**Issue by felixmc** [restify/node-restify#982]
When I pass `null` to `res.send`, I get a `Cannot read property 'constructor' of null` error.

Browsing though the source code, I found the issue in file `/lib/response.js` starting on line `275`:  
```javascript
    if (code === undefined) {
        this.statusCode = 200;
    } else if (code.constructor.name === 'Number') {
        this.statusCode = code;

        if (body instanceof Error) {
            body.statusCode = this.statusCode;
        }
    } else {
        headers = body;
        body = code;
        code = null;
    }
```

Seems like the conditionals do not account for a null value for the code parameter of the `send` method and assume that if the parameter is not `undefined`, it must have a `constructor` property, as it uses that to check if the parameter is a number.

Perhaps a better way of checking if the code parameter is a number is by using `typeof code === 'number'` as it seems more explicit and can handle `null` values and perhaps other edge cases. This technique is already being used on line `191` of `/lib/upgrade.js` to essentially check for the same thing.

Is there any reason why `code.constructor.name` makes more sense in this situation?

**Comment by DonutEspresso** [comment]
We've gotten reports of this before but were unable to reproduce it. In fact, we have a test that was added recently for it, which is currently passing. 

https://github.com/restify/node-restify/blob/5.x/test/response.test.js#L410

Is there a snippet you can provide that reproduces this scenario?
