### ISSUE TITLE
Response formatter blows up when headers turn into arrays

### ISSUE THREAD

**Issue by jocull** [restify/node-restify#986]
https://github.com/restify/node-restify/blob/20f8fa8f0084bfc2e5ff3f981aa24edde32f6758/lib/response.js#L118

I ran into a strange scenario today that I can't understand.

    // Setting the default content-type, assuming we will override it in another middleware
    res.setHeader('content-type', 'text/plain')
    // At this point: this.getHeader('Content-Type') == "text/plain"

    // ... some time later, in another middleware
    res.json(200, { ok: true })
    // At this point: this.getHeader('Content-Type') == ["text/plain", "application/json"]

This is incredibly strange. I don't understand why I would end up with an array of content types. At any rate, the formatter doesn't know how to deal with this as its expecting strings. Yet another fun day with dynamic languages!

**Comment by DonutEspresso** [comment]
This looks related to #779, looks like we need to create a blacklist of headers that should not allow for multiple comma separated values.

**Comment by DonutEspresso** [comment]
reference: https://www.ietf.org/rfc/rfc2045.txt

**Comment by jocull** [comment]
Using `res.headers["content-type"] = "text/plain"` instead of `res.setHeader("content-type", "text/plain")` avoid this. I'm guessing because it overwrites instead of appends.

**Comment by jocull** [comment]
I'm not sure if it would be more effective to whitelist or blacklist -- depends on how many headers allow for multiple values.

**Comment by jocull** [comment]
Attached code to resolve this. Sorry about the commit noise, I had some issues with my branching.
