### ISSUE TITLE
CSV default escape character

### ISSUE THREAD

**Issue by edorivai** [restify/node-restify#989]
I'm using the `bodyParser` middleware, and ran into the following error when receiving a `text/csv` request:

```
[Error: Invalid closing quote at line 735; found "\"" instead of delimiter ","]
```

I'm stringifying my document using [csv-stringify](http://csv.adaltas.com/stringify/) and found that the violating line contained double-double quotes as a means of escaping: `"My name is ""John"""`. I haven't specified this style of escaping, so I'm assuming this is the default way of escaping CSV.

In `field_text_body_parser.js` I found that the default escaping character is set to a backslash: `\`. It also hints at how to set the escaping character; by setting the `x-content-escape` header.

So using this header the CSV body parser works fine. Has this default escaping character been set intentionally?

Also, I couldn't find any of this in the documentation. Actually, the documentation doesn't even indicate that `bodyParser` parses `text/csv` at all:

> application/json, application/x-www-form-urlencoded and multipart/form-data are currently supported.

**Comment by DonutEspresso** [comment]
Yes, it looks like the documentation is out of date. The plugin should support those three in addition to `text/tsv`, `text/tab-separated-values`, and `text/csv`.
