### ISSUE TITLE
Reverse routing URLs

### ISSUE THREAD

**Issue by jocull** [restify/node-restify#990]
I don't know if this exists or not, but I am not able to find it.

I am trying to follow the JSON API spec here, and it has "links" sections where you attach the routes to related resources.
http://jsonapi.org/

I don't know the best way to handle this with Restify right now. I could of course save my route strings and regex them to death, but I would rather not. This is what I am hoping to do (pseudo code)

```
router.reverseRoute("/my/route/:param1/:param2", {
  param1: "hey",
  param2: "you"
});

// Would return "/my/route/hey/you"
```

**Comment by DonutEspresso** [comment]
This isn't supported. Looks like there are some options on that website:
http://jsonapi.org/implementations/#server-libraries-node-js

**Comment by jocull** [comment]
It seems like you can use `Router.render` with a route name and passed in
params to generate URLs. That might be just as good if I save the generated
route names or name them myself.
