### ISSUE TITLE
serveStatic should have caching?

### ISSUE THREAD

**Issue by avimar** [restify/node-restify#993]
I would have hoped that serveStatic would check the file modify time and reply with 304 not modified, but it doesn't seem to do this.
How hard might this be?

**Comment by avimar** [comment]
The issue seems to be that res.header('Last-Modified') is set AFTER conditional_request is already run.

I monkey patched libs/plugins/static.js and made it an option, but I didn't write any tests for a PR...

    function serveFileFromStats(file, err, stats, isGzip, req, res, next) {
        if (err) {
            next(new ResourceNotFoundError(err,
                req.path()));
            return;
        } else if (!stats.isFile()) {
            next(new ResourceNotFoundError('%s does not exist', req.path()));
            return;
        }

        if (res.handledGzip && isGzip) {
            res.handledGzip();
        }

        var maxAge = opts.maxAge === undefined ? 3600 : opts.maxAge;
        res.cache({maxAge: maxAge});
        res.set('Content-Length', stats.size);
        res.set('Content-Type', mime.lookup(file));
        res.set('Last-Modified', stats.mtime);
        if (opts.charSet) {
            var type = res.getHeader('Content-Type') +
                '; charset=' + opts.charSet;
            res.setHeader('Content-Type', type);
        }

        if (opts.etag) {
            res.set('ETag', opts.etag(stats, opts));
        }
       
        var ctime = req.header('if-modified-since');
        if (opts.checkIfModified && Date.parse(stats.mtime) <= Date.parse(ctime) && (req.method=='GET' || req.method=='HEAD')) {
            res.send(304);
            next(false);
        } else {
            var fstream = fs.createReadStream(file + (isGzip ? '.gz' : ''));
            fstream.once('open', function (fd) {
                res.writeHead(200);
                fstream.pipe(res);
                });
            fstream.once('end', function () {
                next(false);
            });
        }
    }

**Comment by retrohacker** [comment]
https://github.com/restify/plugins/pull/23 for reference

**Comment by retrohacker** [comment]
Closing this as stale for now as the PR is no longer open and the plugins have migrated. This is still an exciting feature and we would be happy to reopen this and help get a PR merged into the main repo if anyone is interested in carrying it over the finish line :heart:

**Comment by avimar** [comment]
@retrohacker Sorry, but I'm not willing to put in the time to *figure out* how to test this (the static file tests look rather cryptic). The original changeset is here... I hope someone can help merge this feature.

https://github.com/restify/plugins/pull/23/files

**Comment by retrohacker** [comment]
Thanks for following up @avimar :heart:
