### ISSUE TITLE
Invalid JSON delivered by POST-Method in req object

### ISSUE THREAD

**Issue by Injac** [restify/node-restify#995]
It seems that restify is tampering with the JSON request-body (or the request body in general, using POST). I am not sure if this is because of any of the plugins that I am using:

```
var server = restify.createServer();
  server.use(restify.acceptParser(server.acceptable));
  server.use(restify.dateParser());
  server.use(restify.queryParser());
  server.use(restify.bodyParser());
  server.use(restify.authorizationParser());
 server.pre(restify.pre.sanitizePath());
```
The json delivered by the request should look something like this:

`{ "id":"SOMEID","value":"SomeValue"}`

Instead, restify delivers the JSON like this in the req.body object, removing the double-quotes from the first key-value pair:

`{id:SOMEID, "value":"SomeValue"}`

I have decided to "correct" the faulty JSON out put by replacing the faulty sections with the correct syntax, by hand.

**Comment by DonutEspresso** [comment]
That's definitely unexpected - any chance you can provide a code snippet demonstrating the behavior?

**Comment by Injac** [comment]
Sure, here is the code:
``
server.post('/unregisterdevice', function(req, res, next) {

    var url = 'mongodb://localhost:27017/managment';
    MongoClient.connect(url, function(err, db) {

        assert.equal(null, err);

        //console.log("Connected correctly to server.");
        if (!req.body || req.body === '')
            throw new Error('Invalid content One.');
        console.log(req.body);
        var bodyData = JSON.stringify(req.body);
        bodyData.replace("deviceId", "\"deviceId\"");
        console.log(bodyData);

        bodyData = bodyData.replace("'", "\"");

        try {

            JSON.parse(bodyData);
        } catch (e) {
            console.log(bodyData);
            throw new Error('Invalid JSON.' + bodyData);
        }


        var collection = db.collection('devices');
        //Get the admin user
        collection.deleteOne(
            JSON.parse(bodyData), function(err, records) {
                if (!err) {
                    res.send(bodyData);
                    db.close();
                    next();
                } else {
                    throw new Error(err);
                }
            });
    });

});
``
This is just some piece of testing code, to get into restify. I have sent the request to the server using Postman.

This is the content I am sending:
``
{ 
    "deviceId":"a3e6af54-0445-4c87-b9d1-81fa1b800a74"
}
``
The first line is what I receive, and the second what it looks like after the replacement (console output):
``
{ deviceId: 'a3e6af54-0445-4c87-b9d1-81fa1b800a74' }
{"deviceId":"a3e6af54-0445-4c87-b9d1-81fa1b800a74"}
``
Content-Type is application/json

**Comment by Khez** [comment]
@Injac I believe you are not having an actual issue..

The first `console.log` is showing you have a valid object. The missing quotes that you describe, are just syntactic sugar and are part of the way `console.log` displays an object.

Try this code:
```
console.log({
 deviceId: 'a3e6af54-0445-4c87-b9d1-81fa1b800a74',
 deviceId2: "a3e6af54-0445-4c87-b9d1-81fa1b800a74",
 "deviceid3": "object keys only require quotes when special characters are involved",
 " : * - etc": "Special Key Quotes"
});
```
It will show you the behaviour I'm describing.

Your second `console.log` is done on a a string, meaning it will be shown verbatim no pretty-print.

My question to you is why you believe restify is giving you an invalid JSON in your handler.
Does your code actually hit the `throw new Error('Invalid JSON.' + bodyData);` ?

**Comment by Injac** [comment]
@Khez 

First of all, thank you for the detailed explanations :) I did not know about this behaviour of JS/node.js built-in console.log function.

I am expecting that JSON.parse(bodyData); does the job right. I came to this conclusion, because the body-value delivered, does actually not pass the (I suppose there is one) internal validation of JSON.parse(), if I don't replace the values.

**Comment by DonutEspresso** [comment]
The bodyParser plugin will automatically parse the JSON for you into a JS object, so there's no need to parse it again yourself. 

If you need the original unparsed value, you can use `req.rawBody`, which should you return you the actual JSON string.

**Comment by Injac** [comment]
@DonutEspresso, @Khez 

Ok. I think I can handle now this thing on my own. Thank you very much for your help. You can close this issue now.

**Comment by DonutEspresso** [comment]
Cool, glad we could figure it out.
