### ISSUE TITLE
Cannot read property '_restify_next' of undefined

### ISSUE THREAD

**Issue by barenko** [restify/node-restify#996]
I created a server like that:
```javascript
		let server = restify.createServer()

		server.pre((req, res, next) => {
			return next()
		})

		server.del('/item/:id', this.deleteItem.bind(this))
		server.on('uncaughtException', this.uncaughtException.bind(this))
```

Running on: node v4.2.2 with "restify": "^4.0.3"

And when I ran the follow command:
`curl -X DELETE http://127.0.0.1:3000/item/`

I got the error:

```
TypeError: Cannot read property '_restify_next' of undefined
    at Domain.onError (/projects/frank/node_modules/restify/lib/server.js:952:16)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:65:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:104:16)
    at process._fatalException (node.js:220:33)
```

*NOTE*: this issue does not happens when I change `server.pre()` to `server.use()`.

**Comment by barenko** [comment]
The problem occurred because I was throwing a restify.InvalidArgumentError

```javascript
	deleteItem(req, res, next){
		throw restify.InvalidArgumentError('Invalid id')
		res.send(200)
		next()
	}
```

**Comment by barenko** [comment]
Wow, I made a bad mistake: I forgotten to use `new` to instantiate the InvalidArgumentError. But with this error I found a strange restify behavior...

**Comment by DonutEspresso** [comment]
Yup, that's javascript for you :)  The problem is because the domain attempts to use the error you've thrown, but because it wasn't actually an error object it doesn't know what to do with it. Glad you figured it out!
